// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by tool/generate_bindings.dart

import 'package:ffigen_js/ffigen_js.dart' as jsgen;

import 'package:skia/geometry/web.dart' as geometry;

int sizeOf<T extends jsgen.NativeType>() {
  return switch (T) {
    const (geometry.Cubic2) => 64,
    const (geometry.Vector2) => 16,
    const (geometry.Intersection) => 32,
    const (geometry.Aabb2) => 32,
    const (geometry.Quadratic2) => 48,
    _ => jsgen.sizeOf<T>(),
  };
}