import 'package:flutter/widgets.dart';

class AugmentedTextStyle extends TextStyle {
  AugmentedTextStyle(TextStyle style)
    : this._(
        color: style.color,
        background: style.background,
        backgroundColor: style.backgroundColor,
        debugLabel: style.debugLabel,
        decoration: style.decoration,
        decorationColor: style.decorationColor,
        decorationStyle: style.decorationStyle,
        decorationThickness: style.decorationThickness,
        fontFamily: style.fontFamily,
        fontFamilyFallback: style.fontFamilyFallback,
        fontFeatures: style.fontFeatures,
        fontSize: style.fontSize,
        fontStyle: style.fontStyle,
        fontVariations: style.fontVariations,
        fontWeight: style.fontWeight,
        foreground: style.foreground,
        height: style.height,
        leadingDistribution: style.leadingDistribution,
        letterSpacing: style.letterSpacing,
        locale: style.locale,
        overflow: style.overflow,
        shadows: style.shadows,
        textBaseline: style.textBaseline,
        wordSpacing: style.wordSpacing,
      );

  const AugmentedTextStyle._({
    super.inherit = true,
    super.color,
    super.background,
    super.backgroundColor,
    super.debugLabel,
    super.decoration,
    super.decorationColor,
    super.decorationStyle,
    super.decorationThickness,
    super.fontFamily,
    super.fontFamilyFallback,
    super.fontFeatures,
    super.fontSize,
    super.fontStyle,
    super.fontVariations,
    super.fontWeight,
    super.foreground,
    super.height,
    super.leadingDistribution,
    super.letterSpacing,
    super.locale,
    super.overflow,
    super.shadows,
    super.textBaseline,
    super.wordSpacing,
    super.package,
  }) : super();
}
