name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  image: ^4.8.0
  dawn:
    path: ../

flutter:
  uses-material-design: true
