name: scene
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  shared:
  geometry:
  kernel:
  program:
  state:
  skia:
  color:

dev_dependencies:
  test: ^1.31.2