// ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:wgpu/src/asset.dart')
library;

import 'dart:ffi' as ffi;

/// All backends (the default when zero-initialized).
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_All;

/// Vulkan backend.
/// Supported on Windows, Linux/Android, and macOS/iOS via Vulkan Portability.
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_Vulkan;

/// OpenGL / OpenGL ES backend.
/// Supported on Linux/Android, the web via WebGL, and Windows/macOS via ANGLE.
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_GL;

/// Metal backend.
/// Supported on macOS and iOS.
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_Metal;

/// Direct3D 12 backend.
/// Supported on Windows 10 and later.
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_DX12;

/// Browser WebGPU backend.
/// Supported when targeting the web through WebAssembly.
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_BrowserWebGPU;

/// Primary (first-tier) backends: Vulkan, Metal, DX12, and BrowserWebGPU.
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_Primary;

/// Secondary (second-tier) backends: GL.
@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_Secondary;

@ffi.Native<WGPUInstanceBackend>()
external final int WGPUInstanceBackend_Force32;

/// No flags set.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_Empty;

/// Generate debug information in shaders and objects.
///
/// When using @ref WGPUInstanceFlag_WithEnv, takes value from the
/// @c WGPU_DEBUG environment variable.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_Debug;

/// Enable validation in the backend API, if possible:
///
/// - On the DX12 backend, this calls @c ID3D12Debug::EnableDebugLayer.
/// - On the Vulkan backend, this enables the Vulkan Validation Layers.
/// - On the GLES backend (Windows), this enables debug output.
/// - On the GLES backend (non-Windows), this calls @c eglDebugMessageControlKHR.
///
/// When using @ref WGPUInstanceFlag_WithEnv, takes value from the
/// @c WGPU_VALIDATION environment variable.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_Validation;

/// Don't pass labels to the backend API (wgpu-hal).
///
/// When using @ref WGPUInstanceFlag_WithEnv, takes value from the
/// @c WGPU_DISCARD_HAL_LABELS environment variable.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_DiscardHalLabels;

/// Whether wgpu should expose adapters that run on top of non-compliant
/// adapters.
///
/// Turning this on might mean that some of the functionality provided by the
/// wgpu adapter/device is not working or broken. This mainly applies to a
/// Vulkan driver's compliance version. If the major compliance version is 0,
/// then the driver is ignored unless this flag is set.
///
/// When using @ref WGPUInstanceFlag_WithEnv, takes value from the
/// @c WGPU_ALLOW_UNDERLYING_NONCOMPLIANT_ADAPTER environment variable.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_AllowUnderlyingNoncompliantAdapter;

/// Enable GPU-based validation. Implies @ref WGPUInstanceFlag_Validation.
/// Currently only changes behavior on the DX12 and Vulkan backends.
///
/// - D3D12: Called "GPU-based validation" (GBV).
/// - Vulkan: Called "GPU-Assisted Validation" via VK_LAYER_KHRONOS_validation.
///
/// When using @ref WGPUInstanceFlag_WithEnv, takes value from the
/// @c WGPU_GPU_BASED_VALIDATION environment variable.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_GPUBasedValidation;

/// Validate indirect buffer content prior to issuing indirect draws/dispatches.
///
/// This validation will transform indirect calls into no-ops if they are not
/// valid. For example, @c dispatch_workgroups_indirect arguments must be less
/// than the @c max_compute_workgroups_per_dimension device limit.
///
/// When using @ref WGPUInstanceFlag_WithEnv, takes value from the
/// @c WGPU_VALIDATION_INDIRECT_CALL environment variable.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_ValidationIndirectCall;

/// Enable automatic timestamp normalization. When enabled,
/// @c wgpuCommandEncoderResolveQuerySet will automatically normalize timestamps
/// to nanoseconds instead of returning raw timestamp values.
///
/// This introduces a compute shader into the resolution of query sets. When
/// enabled, the timestamp period returned by @ref wgpuQueueGetTimestampPeriod
/// will always be @c 1.0.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_AutomaticTimestampNormalization;

/// Use the default flags for the current build configuration.
/// In debug builds, this typically enables @ref WGPUInstanceFlag_Debug and
/// @ref WGPUInstanceFlag_Validation.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_Default;

/// Convenience alias that enables @ref WGPUInstanceFlag_Debug and
/// @ref WGPUInstanceFlag_Validation.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_Debugging;

/// Convenience alias that enables @ref WGPUInstanceFlag_Debug,
/// @ref WGPUInstanceFlag_Validation, and
/// @ref WGPUInstanceFlag_GPUBasedValidation.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_AdvancedDebugging;

/// Modify the flags based on environment variables. Flags with environment
/// variable support (e.g. @c WGPU_DEBUG, @c WGPU_VALIDATION) will be read
/// from the process environment and applied on top of the explicitly set flags.
@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_WithEnv;

@ffi.Native<WGPUInstanceFlag>()
external final int WGPUInstanceFlag_Force32;

@ffi.Native<ffi.Void Function(WGPUInstance, ffi.Pointer<WGPUGlobalReport>)>()
external void wgpuGenerateReport(
  WGPUInstance instance,
  ffi.Pointer<WGPUGlobalReport> report,
);

@ffi.Native<
  ffi.Size Function(WGPUInstance, ffi.Pointer<WGPUInstanceEnumerateAdapterOptions>, ffi.Pointer<WGPUAdapter>)
>()
external int wgpuInstanceEnumerateAdapters(
  WGPUInstance instance,
  ffi.Pointer<WGPUInstanceEnumerateAdapterOptions> options,
  ffi.Pointer<WGPUAdapter> adapters,
);

@ffi.Native<WGPUSubmissionIndex Function(WGPUQueue, ffi.Size, ffi.Pointer<WGPUCommandBuffer>)>()
external int wgpuQueueSubmitForIndex(
  WGPUQueue queue,
  int commandCount,
  ffi.Pointer<WGPUCommandBuffer> commands,
);

@ffi.Native<ffi.Float Function(WGPUQueue)>()
external double wgpuQueueGetTimestampPeriod(
  WGPUQueue queue,
);

@ffi.Native<WGPUBool Function(WGPUDevice, WGPUBool, ffi.Pointer<WGPUSubmissionIndex>)>()
external int wgpuDevicePoll(
  WGPUDevice device,
  int wait,
  ffi.Pointer<WGPUSubmissionIndex> submissionIndex,
);

@ffi.Native<WGPUShaderModule Function(WGPUDevice, ffi.Pointer<WGPUShaderModuleDescriptorSpirV>)>()
external WGPUShaderModule wgpuDeviceCreateShaderModuleSpirV(
  WGPUDevice device,
  ffi.Pointer<WGPUShaderModuleDescriptorSpirV> descriptor,
);

@ffi.Native<ffi.Void Function(WGPULogCallback, ffi.Pointer<ffi.Void>)>()
external void wgpuSetLogCallback(
  WGPULogCallback callback,
  ffi.Pointer<ffi.Void> userdata,
);

@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>(symbol: 'wgpuSetLogLevel')
external void _wgpuSetLogLevel(
  int level,
);

void wgpuSetLogLevel(
  WGPULogLevel level,
) => _wgpuSetLogLevel(
  level.value,
);

@ffi.Native<ffi.Uint32 Function()>()
external int wgpuGetVersion();

/// Returns the backend-native `id<MTLDevice>` as an opaque pointer.
///
/// The returned pointer is borrowed and remains valid only while `device` is alive.
/// Ownership is retained by wgpu-native; callers must not release or destroy it.
/// Returns NULL when the active backend is not Metal or when the handle is unavailable.
@ffi.Native<ffi.Pointer<ffi.Void> Function(WGPUDevice)>()
external ffi.Pointer<ffi.Void> wgpuDeviceGetNativeMetalDevice(
  WGPUDevice device,
);

/// Returns the backend-native `id<MTLCommandQueue>` as an opaque pointer.
///
/// The returned pointer is borrowed and remains valid only while `queue` is alive.
/// Ownership is retained by wgpu-native; callers must not release or destroy it.
/// Returns NULL when the active backend is not Metal or when the handle is unavailable.
@ffi.Native<ffi.Pointer<ffi.Void> Function(WGPUQueue)>()
external ffi.Pointer<ffi.Void> wgpuQueueGetNativeMetalCommandQueue(
  WGPUQueue queue,
);

/// Returns the backend-native `id<MTLTexture>` as an opaque pointer.
///
/// The returned pointer is borrowed and remains valid only while `texture` is alive.
/// Ownership is retained by wgpu-native; callers must not release or destroy it.
/// Returns NULL when the active backend is not Metal or when the handle is unavailable.
@ffi.Native<ffi.Pointer<ffi.Void> Function(WGPUTexture)>()
external ffi.Pointer<ffi.Void> wgpuTextureGetNativeMetalTexture(
  WGPUTexture texture,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder, ffi.Uint32, ffi.Uint32, ffi.Pointer<ffi.Void>)>()
external void wgpuRenderPassEncoderSetImmediates(
  WGPURenderPassEncoder encoder,
  int offset,
  int sizeBytes,
  ffi.Pointer<ffi.Void> data,
);

@ffi.Native<ffi.Void Function(WGPUComputePassEncoder, ffi.Uint32, ffi.Uint32, ffi.Pointer<ffi.Void>)>()
external void wgpuComputePassEncoderSetImmediates(
  WGPUComputePassEncoder encoder,
  int offset,
  int sizeBytes,
  ffi.Pointer<ffi.Void> data,
);

@ffi.Native<ffi.Void Function(WGPURenderBundleEncoder, ffi.Uint32, ffi.Uint32, ffi.Pointer<ffi.Void>)>()
external void wgpuRenderBundleEncoderSetImmediates(
  WGPURenderBundleEncoder encoder,
  int offset,
  int sizeBytes,
  ffi.Pointer<ffi.Void> data,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder, WGPUBuffer, ffi.Uint64, ffi.Uint32)>()
external void wgpuRenderPassEncoderMultiDrawIndirect(
  WGPURenderPassEncoder encoder,
  WGPUBuffer buffer,
  int offset,
  int count,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder, WGPUBuffer, ffi.Uint64, ffi.Uint32)>()
external void wgpuRenderPassEncoderMultiDrawIndexedIndirect(
  WGPURenderPassEncoder encoder,
  WGPUBuffer buffer,
  int offset,
  int count,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder, WGPUBuffer, ffi.Uint64, WGPUBuffer, ffi.Uint64, ffi.Uint32)>()
external void wgpuRenderPassEncoderMultiDrawIndirectCount(
  WGPURenderPassEncoder encoder,
  WGPUBuffer buffer,
  int offset,
  WGPUBuffer count_buffer,
  int count_buffer_offset,
  int max_count,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder, WGPUBuffer, ffi.Uint64, WGPUBuffer, ffi.Uint64, ffi.Uint32)>()
external void wgpuRenderPassEncoderMultiDrawIndexedIndirectCount(
  WGPURenderPassEncoder encoder,
  WGPUBuffer buffer,
  int offset,
  WGPUBuffer count_buffer,
  int count_buffer_offset,
  int max_count,
);

@ffi.Native<ffi.Void Function(WGPUComputePassEncoder, WGPUQuerySet, ffi.Uint32)>()
external void wgpuComputePassEncoderBeginPipelineStatisticsQuery(
  WGPUComputePassEncoder computePassEncoder,
  WGPUQuerySet querySet,
  int queryIndex,
);

@ffi.Native<ffi.Void Function(WGPUComputePassEncoder)>()
external void wgpuComputePassEncoderEndPipelineStatisticsQuery(
  WGPUComputePassEncoder computePassEncoder,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder, WGPUQuerySet, ffi.Uint32)>()
external void wgpuRenderPassEncoderBeginPipelineStatisticsQuery(
  WGPURenderPassEncoder renderPassEncoder,
  WGPUQuerySet querySet,
  int queryIndex,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder)>()
external void wgpuRenderPassEncoderEndPipelineStatisticsQuery(
  WGPURenderPassEncoder renderPassEncoder,
);

@ffi.Native<ffi.Void Function(WGPUComputePassEncoder, WGPUQuerySet, ffi.Uint32)>()
external void wgpuComputePassEncoderWriteTimestamp(
  WGPUComputePassEncoder computePassEncoder,
  WGPUQuerySet querySet,
  int queryIndex,
);

@ffi.Native<ffi.Void Function(WGPURenderPassEncoder, WGPUQuerySet, ffi.Uint32)>()
external void wgpuRenderPassEncoderWriteTimestamp(
  WGPURenderPassEncoder renderPassEncoder,
  WGPUQuerySet querySet,
  int queryIndex,
);

@ffi.Native<WGPUBool Function(WGPUDevice)>()
external int wgpuDeviceStartGraphicsDebuggerCapture(
  WGPUDevice device,
);

@ffi.Native<ffi.Void Function(WGPUDevice)>()
external void wgpuDeviceStopGraphicsDebuggerCapture(
  WGPUDevice device,
);

enum WGPUNativeSType {
  /// Identifies @ref WGPUDeviceExtras.
  WGPUSType_DeviceExtras(196609),

  /// Identifies @ref WGPUNativeLimits.
  WGPUSType_NativeLimits(196610),

  /// Identifies @ref WGPUPipelineLayoutExtras.
  WGPUSType_PipelineLayoutExtras(196611),

  /// Identifies @ref WGPUShaderSourceGLSL.
  WGPUSType_ShaderSourceGLSL(196612),

  /// Identifies @ref WGPUInstanceExtras.
  WGPUSType_InstanceExtras(196614),

  /// Identifies @ref WGPUBindGroupEntryExtras.
  WGPUSType_BindGroupEntryExtras(196615),

  /// Identifies @ref WGPUBindGroupLayoutEntryExtras.
  WGPUSType_BindGroupLayoutEntryExtras(196616),

  /// Identifies @ref WGPUQuerySetDescriptorExtras.
  WGPUSType_QuerySetDescriptorExtras(196617),

  /// Identifies @ref WGPUSurfaceConfigurationExtras.
  WGPUSType_SurfaceConfigurationExtras(196618),

  /// Identifies @ref WGPUSurfaceSourceSwapChainPanel.
  WGPUSType_SurfaceSourceSwapChainPanel(196619),

  /// Identifies @ref WGPUPrimitiveStateExtras.
  WGPUSType_PrimitiveStateExtras(196620),
  WGPUNativeSType_Force32(2147483647);

  final int value;
  const WGPUNativeSType(this.value);

  static WGPUNativeSType fromValue(int value) => switch (value) {
    196609 => WGPUSType_DeviceExtras,
    196610 => WGPUSType_NativeLimits,
    196611 => WGPUSType_PipelineLayoutExtras,
    196612 => WGPUSType_ShaderSourceGLSL,
    196614 => WGPUSType_InstanceExtras,
    196615 => WGPUSType_BindGroupEntryExtras,
    196616 => WGPUSType_BindGroupLayoutEntryExtras,
    196617 => WGPUSType_QuerySetDescriptorExtras,
    196618 => WGPUSType_SurfaceConfigurationExtras,
    196619 => WGPUSType_SurfaceSourceSwapChainPanel,
    196620 => WGPUSType_PrimitiveStateExtras,
    2147483647 => WGPUNativeSType_Force32,
    _ => throw ArgumentError('Unknown value for WGPUNativeSType: $value'),
  };
}

/// Additional surface-get-current-texture status codes defined by wgpu-native.
///
/// These extend the standard @c WGPUSurfaceGetCurrentTextureStatus values.
enum WGPUNativeSurfaceGetCurrentTextureStatus {
  /// The surface texture was not acquired because the window is occluded
  /// (e.g. minimized or fully covered by another window).
  ///
  /// No texture is returned and the @c texture field of
  /// @c WGPUSurfaceTexture will be NULL. The surface and swapchain remain
  /// valid -- there is no need to reconfigure or recreate the surface.
  ///
  /// Applications should skip rendering for the current frame and try
  /// again once the window is no longer occluded. If you are using a
  /// windowing library such as winit, listen for the window's "occluded"
  /// event and request a new redraw when the window becomes visible again.
  ///
  /// When does this occur?
  ///
  /// Currently this status is only produced by the Metal backend on macOS.
  /// When a window is not visible (checked via the @c NSWindow
  /// @c occlusionState property), acquiring the next drawable would block
  /// for up to one second waiting for vsync. wgpu-native returns
  /// @c Occluded instead to avoid that hang.
  ///
  /// Other backends (Vulkan, DX12, GL) do not currently report this
  /// status; an occluded window on those backends may produce
  /// @c WGPUSurfaceGetCurrentTextureStatus_Timeout or simply succeed
  /// normally.
  WGPUSurfaceGetCurrentTextureStatus_Occluded(196609),
  WGPUNativeSurfaceGetCurrentTextureStatus_Force32(2147483647);

  final int value;
  const WGPUNativeSurfaceGetCurrentTextureStatus(this.value);

  static WGPUNativeSurfaceGetCurrentTextureStatus fromValue(int value) => switch (value) {
    196609 => WGPUSurfaceGetCurrentTextureStatus_Occluded,
    2147483647 => WGPUNativeSurfaceGetCurrentTextureStatus_Force32,
    _ => throw ArgumentError('Unknown value for WGPUNativeSurfaceGetCurrentTextureStatus: $value'),
  };
}

/// Native-only device features.
///
/// These extend the standard @c WGPUFeatureName values and can be passed to
/// @c WGPUDeviceDescriptor::requiredFeatures to request additional
/// capabilities when creating a device.
enum WGPUNativeFeature {
  /// Allows the use of immediate data: small, fast blocks of memory
  /// that can be updated inside a render pass, compute pass, or render
  /// bundle encoder.
  ///
  /// Enables @ref wgpuRenderPassEncoderSetImmediates,
  /// @ref wgpuComputePassEncoderSetImmediates,
  /// @ref wgpuRenderBundleEncoderSetImmediates,
  /// non-zero @c immediateDataSize in @ref WGPUPipelineLayoutExtras,
  /// and non-zero @c maxImmediateSize in @ref WGPUNativeLimits.
  ///
  /// A block of immediate data can be declared in WGSL with
  /// @c var<immediate>:
  /// @code
  /// struct Immediates { example: f32, }
  /// var<immediate> c: Immediates;
  /// @endcode
  ///
  /// In GLSL, this corresponds to @c layout(immediates) @c uniform @c Name @c {..}.
  ///
  /// Supported platforms:
  /// - DX12
  /// - Vulkan
  /// - Metal
  /// - OpenGL (emulated with uniforms)
  /// - WebGPU
  ///
  /// This is a web and native feature.
  WGPUNativeFeature_Immediates(196609),

  /// Enables device-specific texture format features.
  ///
  /// By default only texture format properties as defined by the WebGPU
  /// specification are allowed. Enabling this feature flag extends the
  /// features of each format to the ones supported by the current device.
  /// Note that without this flag, read/write storage access is not allowed
  /// at all.
  ///
  /// This extension does not enable additional formats.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  /// - Metal
  ///
  /// This is a native only feature.
  WGPUNativeFeature_TextureAdapterSpecificFormatFeatures(196610),

  /// Allows the use of a buffer containing the actual number of draw calls.
  ///
  /// Enables @ref wgpuRenderPassEncoderMultiDrawIndirectCount and
  /// @ref wgpuRenderPassEncoderMultiDrawIndexedIndirectCount.
  ///
  /// This feature being present also implies that all calls to
  /// @ref wgpuRenderPassEncoderMultiDrawIndirect and
  /// @ref wgpuRenderPassEncoderMultiDrawIndexedIndirect are not being
  /// emulated with a series of @c draw_indirect calls.
  ///
  /// Supported platforms:
  /// - DX12
  /// - Vulkan 1.2+ (or VK_KHR_draw_indirect_count)
  ///
  /// This is a native only feature.
  WGPUNativeFeature_MultiDrawIndirectCount(196612),

  /// Enables bindings of writable storage buffers and textures visible
  /// to vertex shaders.
  ///
  /// Note: some (tiled-based) platforms do not support vertex shaders
  /// with any side-effects.
  ///
  /// Supported platforms:
  /// - All
  ///
  /// This is a native only feature.
  WGPUNativeFeature_VertexWritableStorage(196613),

  /// Allows the user to create uniform arrays of textures in shaders:
  ///
  /// - WGSL: @c var @c textures: @c binding_array<texture_2d<f32>, @c 10>
  /// - GLSL: @c uniform @c texture2D @c textures[10]
  ///
  /// If @ref WGPUNativeFeature_StorageResourceBindingArray is supported
  /// as well as this, the user may also create uniform arrays of storage
  /// textures.
  ///
  /// This capability allows them to exist and to be indexed by dynamically
  /// uniform values.
  ///
  /// Supported platforms:
  /// - DX12
  /// - Metal (with MSL 2.0+ on macOS 10.13+)
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_TextureBindingArray(196614),

  /// Allows shaders to index sampled texture and storage buffer resource
  /// arrays with dynamically non-uniform values:
  ///
  /// e.g. @c texture_array[vertex_data]
  ///
  /// In order to use this capability, the corresponding GLSL extension must
  /// be enabled:
  ///
  /// @c \#extension @c GL_EXT_nonuniform_qualifier @c : @c require
  ///
  /// and then used either as @c nonuniformEXT qualifier in variable
  /// declaration or as @c nonuniformEXT constructor.
  ///
  /// WGSL and HLSL do not need any extension.
  ///
  /// Supported platforms:
  /// - DX12
  /// - Metal (with MSL 2.0+ on macOS 10.13+)
  /// - Vulkan 1.2+ (or VK_EXT_descriptor_indexing)
  ///
  /// This is a native only feature.
  WGPUNativeFeature_SampledTextureAndStorageBufferArrayNonUniformIndexing(196615),

  /// Enables use of Pipeline Statistics Queries. These queries report the
  /// count of various operations performed between the start and stop call.
  ///
  /// Use @ref wgpuRenderPassEncoderBeginPipelineStatisticsQuery /
  /// @ref wgpuRenderPassEncoderEndPipelineStatisticsQuery (or the compute
  /// pass equivalents) to start and stop a query.
  ///
  /// They must be resolved using @c wgpuCommandEncoderResolveQuerySet into
  /// a buffer. See @ref WGPUPipelineStatisticName for the list of available
  /// statistics.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  ///
  /// This is a native only feature.
  WGPUNativeFeature_PipelineStatisticsQuery(196616),

  /// Allows the user to create uniform arrays of storage buffers or
  /// textures in shaders, if @ref WGPUNativeFeature_BufferBindingArray
  /// or @ref WGPUNativeFeature_TextureBindingArray (respectively)
  /// is also supported.
  ///
  /// This capability allows them to exist and to be indexed by dynamically
  /// uniform values.
  ///
  /// Supported platforms:
  /// - Metal (with MSL 2.2+ on macOS 10.13+)
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_StorageResourceBindingArray(196617),

  /// Allows the user to create bind groups containing arrays with fewer
  /// bindings than the @c WGPUBindGroupLayout requires.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  ///
  /// This is a native only feature.
  WGPUNativeFeature_PartiallyBoundBindingArray(196618),

  /// Enables normalized 16-bit texture formats:
  /// @ref WGPUNativeTextureFormat_R16Unorm, @ref WGPUNativeTextureFormat_R16Snorm,
  /// @ref WGPUNativeTextureFormat_Rg16Unorm, @ref WGPUNativeTextureFormat_Rg16Snorm,
  /// @ref WGPUNativeTextureFormat_Rgba16Unorm, @ref WGPUNativeTextureFormat_Rgba16Snorm.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  /// - Metal
  ///
  /// This is a native only feature.
  WGPUNativeFeature_TextureFormat16bitNorm(196619),

  /// Enables ASTC HDR family of compressed textures.
  ///
  /// Compressed textures sacrifice some quality in exchange for
  /// significantly reduced bandwidth usage.
  ///
  /// Support for this feature guarantees availability of
  /// @c COPY_SRC | @c COPY_DST | @c TEXTURE_BINDING for ASTC formats
  /// with the HDR channel type.
  /// @ref WGPUNativeFeature_TextureAdapterSpecificFormatFeatures may
  /// enable additional usages.
  ///
  /// Supported platforms:
  /// - Metal
  /// - Vulkan
  /// - OpenGL
  ///
  /// This is a native only feature.
  WGPUNativeFeature_TextureCompressionAstcHdr(196620),

  /// Removes the WebGPU restriction that @c MAP_READ and @c MAP_WRITE
  /// buffer usages must be paired exclusively with @c COPY_DST and
  /// @c COPY_SRC respectively.
  ///
  /// This is only beneficial on systems that share memory between CPU and
  /// GPU. If enabled on a system that doesn't, this can severely hinder
  /// performance. Only use if you understand the consequences.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  /// - Metal
  ///
  /// This is a native only feature.
  WGPUNativeFeature_MappablePrimaryBuffers(196622),

  /// Allows the user to create arrays of buffers in shaders:
  ///
  /// - WGSL: @c var<uniform> @c buffer_array: @c array<MyBuffer, @c 10>
  /// - GLSL: @c uniform @c myBuffer @c { @c ... @c } @c buffer_array[10]
  ///
  /// This capability allows them to exist and to be indexed by dynamically
  /// uniform values.
  ///
  /// If @ref WGPUNativeFeature_StorageResourceBindingArray is supported as
  /// well as this, the user may also create arrays of storage buffers.
  ///
  /// Supported platforms:
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_BufferBindingArray(196623),

  /// Allows shaders to index uniform buffer and storage texture resource
  /// arrays with dynamically non-uniform values.
  ///
  /// This is a native only feature.
  WGPUNativeFeature_UniformBufferAndStorageTextureArrayNonUniformIndexing(196624),

  /// Allows the user to set @ref WGPUPolygonMode_Line in
  /// @ref WGPUPrimitiveStateExtras::polygonMode.
  ///
  /// This allows drawing polygons/triangles as lines (wireframe) instead
  /// of filled.
  ///
  /// Supported platforms:
  /// - DX12
  /// - Vulkan
  /// - Metal
  ///
  /// This is a native only feature.
  WGPUNativeFeature_PolygonModeLine(196627),

  /// Allows the user to set @ref WGPUPolygonMode_Point in
  /// @ref WGPUPrimitiveStateExtras::polygonMode.
  ///
  /// This allows only drawing the vertices of polygons/triangles instead
  /// of filled.
  ///
  /// Supported platforms:
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_PolygonModePoint(196628),

  /// Allows the user to enable overestimation conservative rasterization
  /// via @ref WGPUPrimitiveStateExtras::conservative.
  ///
  /// Processing of degenerate triangles/lines is hardware specific.
  /// Only triangles are supported.
  ///
  /// Supported platforms:
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_ConservativeRasterization(196629),

  /// Enables creating shader modules from pre-compiled SPIR-V binary via
  /// @ref wgpuDeviceCreateShaderModuleSpirV.
  ///
  /// Shader code isn't parsed or interpreted in any way. It is the caller's
  /// responsibility to ensure the code is correct.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  /// - Metal
  /// - WebGPU
  ///
  /// This is a native only feature.
  WGPUNativeFeature_SpirvShaderPassthrough(196631),

  /// Enables using 64-bit types for vertex attributes.
  ///
  /// Requires @ref WGPUNativeFeature_ShaderF64.
  ///
  /// This is a native only feature.
  WGPUNativeFeature_VertexAttribute64bit(196633),

  /// Allows for creation of textures of format
  /// @ref WGPUNativeTextureFormat_NV12.
  ///
  /// Supported platforms:
  /// - DX12
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_TextureFormatNv12(196634),

  /// Allows for the creation of ray-tracing queries within shaders.
  ///
  /// @b EXPERIMENTAL: Features enabled by this may have major bugs and are
  /// expected to be subject to breaking changes.
  ///
  /// Supported platforms:
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_RayQuery(196636),

  /// Enables 64-bit floating point types in SPIR-V shaders.
  ///
  /// Note: even when supported by GPU hardware, 64-bit floating point
  /// operations are frequently between 16 and 64 @e times slower than
  /// equivalent operations on 32-bit floats.
  ///
  /// Supported platforms:
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_ShaderF64(196637),

  /// Allows shaders to use i16. Not currently supported in naga, only
  /// available through SPIR-V passthrough.
  ///
  /// Supported platforms:
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_ShaderI16(196638),

  /// Allows shaders to use the @c early_depth_test attribute.
  ///
  /// The attribute is applied to the fragment shader entry point and can be
  /// used in two ways:
  ///
  /// 1. Force early depth/stencil tests:
  /// - WGSL: @c \@early_depth_test(force)
  /// - GLSL: @c layout(early_fragment_tests) @c in;
  ///
  /// 2. Provide a conservative depth specifier that allows an additional
  /// early depth test under certain conditions:
  /// - WGSL: @c \@early_depth_test(greater_equal/less_equal/unchanged)
  /// - GLSL: @c layout(depth_<greater/less/unchanged>) @c out @c float @c gl_FragDepth;
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - GLES 3.1+
  ///
  /// This is a native only feature.
  WGPUNativeFeature_ShaderEarlyDepthTest(196640),

  /// Allows compute and fragment shaders to use the subgroup operation
  /// built-ins and perform subgroup operations (except barriers).
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  /// - Metal
  ///
  /// This is a native only feature.
  WGPUNativeFeature_Subgroup(196641),

  /// Allows vertex shaders to use the subgroup operation built-ins and
  /// perform subgroup operations (except barriers).
  ///
  /// Supported platforms:
  /// - Vulkan
  ///
  /// This is a native only feature.
  WGPUNativeFeature_SubgroupVertex(196642),

  /// Allows compute shaders to use the subgroup barrier.
  ///
  /// Requires @ref WGPUNativeFeature_Subgroup. Without it, enables nothing.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - Metal
  ///
  /// This is a native only feature.
  WGPUNativeFeature_SubgroupBarrier(196643),

  /// Allows for timestamp queries directly on command encoders.
  ///
  /// Implies @c WGPUFeatureName_TimestampQuery is supported.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  /// - Metal
  /// - OpenGL (with GL_ARB_timer_query)
  ///
  /// This is a native only feature.
  WGPUNativeFeature_TimestampQueryInsideEncoders(196644),

  /// Allows for timestamp queries inside render and compute passes.
  ///
  /// Implies @c WGPUFeatureName_TimestampQuery and
  /// @ref WGPUNativeFeature_TimestampQueryInsideEncoders are supported.
  ///
  /// Enables @ref wgpuRenderPassEncoderWriteTimestamp and
  /// @ref wgpuComputePassEncoderWriteTimestamp.
  ///
  /// This is generally not available on tile-based rasterization GPUs.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12
  /// - Metal (AMD & Intel, not Apple GPUs)
  /// - OpenGL (with GL_ARB_timer_query)
  ///
  /// This is a native only feature.
  WGPUNativeFeature_TimestampQueryInsidePasses(196645),

  /// Allows shaders to use i64 and u64.
  ///
  /// Supported platforms:
  /// - Vulkan
  /// - DX12 (DXC only)
  /// - Metal (with MSL 2.3+)
  ///
  /// This is a native only feature.
  WGPUNativeFeature_ShaderInt64(196646),
  WGPUNativeFeature_Force32(2147483647);

  final int value;
  const WGPUNativeFeature(this.value);

  static WGPUNativeFeature fromValue(int value) => switch (value) {
    196609 => WGPUNativeFeature_Immediates,
    196610 => WGPUNativeFeature_TextureAdapterSpecificFormatFeatures,
    196612 => WGPUNativeFeature_MultiDrawIndirectCount,
    196613 => WGPUNativeFeature_VertexWritableStorage,
    196614 => WGPUNativeFeature_TextureBindingArray,
    196615 => WGPUNativeFeature_SampledTextureAndStorageBufferArrayNonUniformIndexing,
    196616 => WGPUNativeFeature_PipelineStatisticsQuery,
    196617 => WGPUNativeFeature_StorageResourceBindingArray,
    196618 => WGPUNativeFeature_PartiallyBoundBindingArray,
    196619 => WGPUNativeFeature_TextureFormat16bitNorm,
    196620 => WGPUNativeFeature_TextureCompressionAstcHdr,
    196622 => WGPUNativeFeature_MappablePrimaryBuffers,
    196623 => WGPUNativeFeature_BufferBindingArray,
    196624 => WGPUNativeFeature_UniformBufferAndStorageTextureArrayNonUniformIndexing,
    196627 => WGPUNativeFeature_PolygonModeLine,
    196628 => WGPUNativeFeature_PolygonModePoint,
    196629 => WGPUNativeFeature_ConservativeRasterization,
    196631 => WGPUNativeFeature_SpirvShaderPassthrough,
    196633 => WGPUNativeFeature_VertexAttribute64bit,
    196634 => WGPUNativeFeature_TextureFormatNv12,
    196636 => WGPUNativeFeature_RayQuery,
    196637 => WGPUNativeFeature_ShaderF64,
    196638 => WGPUNativeFeature_ShaderI16,
    196640 => WGPUNativeFeature_ShaderEarlyDepthTest,
    196641 => WGPUNativeFeature_Subgroup,
    196642 => WGPUNativeFeature_SubgroupVertex,
    196643 => WGPUNativeFeature_SubgroupBarrier,
    196644 => WGPUNativeFeature_TimestampQueryInsideEncoders,
    196645 => WGPUNativeFeature_TimestampQueryInsidePasses,
    196646 => WGPUNativeFeature_ShaderInt64,
    2147483647 => WGPUNativeFeature_Force32,
    _ => throw ArgumentError('Unknown value for WGPUNativeFeature: $value'),
  };
}

enum WGPULogLevel {
  WGPULogLevel_Off(0),

  /// Only error messages.
  WGPULogLevel_Error(1),

  /// Errors and warnings.
  WGPULogLevel_Warn(2),

  /// Errors, warnings, and informational messages.
  WGPULogLevel_Info(3),

  /// Errors, warnings, informational, and debug messages.
  WGPULogLevel_Debug(4),

  /// All messages, including very verbose trace-level output.
  WGPULogLevel_Trace(5),
  WGPULogLevel_Force32(2147483647);

  final int value;
  const WGPULogLevel(this.value);

  static WGPULogLevel fromValue(int value) => switch (value) {
    0 => WGPULogLevel_Off,
    1 => WGPULogLevel_Error,
    2 => WGPULogLevel_Warn,
    3 => WGPULogLevel_Info,
    4 => WGPULogLevel_Debug,
    5 => WGPULogLevel_Trace,
    2147483647 => WGPULogLevel_Force32,
    _ => throw ArgumentError('Unknown value for WGPULogLevel: $value'),
  };
}

typedef WGPUFlags = ffi.Uint64;
typedef DartWGPUFlags = int;

/// Bitflags selecting which graphics backends the @ref WGPUInstance should
/// enable.
///
/// Pass in the @c backends field of @ref WGPUInstanceExtras.
typedef WGPUInstanceBackend = WGPUFlags;

/// Bitflags controlling instance debugging and validation behavior.
///
/// These are not part of the WebGPU standard.
///
/// Pass in the @c flags field of @ref WGPUInstanceExtras.
typedef WGPUInstanceFlag = WGPUFlags;

enum WGPUDx12Compiler {
  WGPUDx12Compiler_Undefined(0),

  /// Use the FXC (D3DCompile) shader compiler.
  ///
  /// The FXC compiler is old, slow, and unmaintained. However, it doesn't
  /// require any additional DLLs to be shipped with the application.
  WGPUDx12Compiler_Fxc(1),

  /// Use the DXC (DirectX Shader Compiler).
  ///
  /// The DXC compiler is new, fast, and maintained. However, it requires
  /// @c dxcompiler.dll to be available. The path to this DLL can be
  /// specified via @ref WGPUInstanceExtras::dxcPath.
  ///
  /// Minimum supported version: v1.8.2502.
  /// Requires WDDM 2.1 (Windows 10 version 1607).
  WGPUDx12Compiler_Dxc(2),
  WGPUDx12Compiler_Force32(2147483647);

  final int value;
  const WGPUDx12Compiler(this.value);

  static WGPUDx12Compiler fromValue(int value) => switch (value) {
    0 => WGPUDx12Compiler_Undefined,
    1 => WGPUDx12Compiler_Fxc,
    2 => WGPUDx12Compiler_Dxc,
    2147483647 => WGPUDx12Compiler_Force32,
    _ => throw ArgumentError('Unknown value for WGPUDx12Compiler: $value'),
  };
}

enum WGPUGles3MinorVersion {
  WGPUGles3MinorVersion_Automatic(0),

  /// Request an ES 3.0 context.
  WGPUGles3MinorVersion_Version0(1),

  /// Request an ES 3.1 context.
  WGPUGles3MinorVersion_Version1(2),

  /// Request an ES 3.2 context.
  WGPUGles3MinorVersion_Version2(3),
  WGPUGles3MinorVersion_Force32(2147483647);

  final int value;
  const WGPUGles3MinorVersion(this.value);

  static WGPUGles3MinorVersion fromValue(int value) => switch (value) {
    0 => WGPUGles3MinorVersion_Automatic,
    1 => WGPUGles3MinorVersion_Version0,
    2 => WGPUGles3MinorVersion_Version1,
    3 => WGPUGles3MinorVersion_Version2,
    2147483647 => WGPUGles3MinorVersion_Force32,
    _ => throw ArgumentError('Unknown value for WGPUGles3MinorVersion: $value'),
  };
}

enum WGPUPipelineStatisticName {
  WGPUPipelineStatisticName_VertexShaderInvocations(0),

  /// Number of times the clipper is invoked. This is also the number of
  /// triangles output by the vertex shader.
  WGPUPipelineStatisticName_ClipperInvocations(1),

  /// Number of primitives that are not culled by the clipper. This is the
  /// number of triangles that are actually on screen and will be rasterized
  /// and rendered.
  WGPUPipelineStatisticName_ClipperPrimitivesOut(2),

  /// Number of times the fragment shader is invoked. Accounts for fragment
  /// shaders running in 2x2 blocks in order to get derivatives.
  WGPUPipelineStatisticName_FragmentShaderInvocations(3),

  /// Number of times a compute shader is invoked. This will be equivalent
  /// to the dispatch count times the workgroup size.
  WGPUPipelineStatisticName_ComputeShaderInvocations(4),
  WGPUPipelineStatisticName_Force32(2147483647);

  final int value;
  const WGPUPipelineStatisticName(this.value);

  static WGPUPipelineStatisticName fromValue(int value) => switch (value) {
    0 => WGPUPipelineStatisticName_VertexShaderInvocations,
    1 => WGPUPipelineStatisticName_ClipperInvocations,
    2 => WGPUPipelineStatisticName_ClipperPrimitivesOut,
    3 => WGPUPipelineStatisticName_FragmentShaderInvocations,
    4 => WGPUPipelineStatisticName_ComputeShaderInvocations,
    2147483647 => WGPUPipelineStatisticName_Force32,
    _ => throw ArgumentError('Unknown value for WGPUPipelineStatisticName: $value'),
  };
}

enum WGPUNativeQueryType {
  WGPUNativeQueryType_PipelineStatistics(196608),
  WGPUNativeQueryType_Force32(2147483647);

  final int value;
  const WGPUNativeQueryType(this.value);

  static WGPUNativeQueryType fromValue(int value) => switch (value) {
    196608 => WGPUNativeQueryType_PipelineStatistics,
    2147483647 => WGPUNativeQueryType_Force32,
    _ => throw ArgumentError('Unknown value for WGPUNativeQueryType: $value'),
  };
}

enum WGPUDxcMaxShaderModel {
  WGPUDxcMaxShaderModel_V6_0(0),

  /// Shader Model 6.1
  WGPUDxcMaxShaderModel_V6_1(1),

  /// Shader Model 6.2
  WGPUDxcMaxShaderModel_V6_2(2),

  /// Shader Model 6.3
  WGPUDxcMaxShaderModel_V6_3(3),

  /// Shader Model 6.4
  WGPUDxcMaxShaderModel_V6_4(4),

  /// Shader Model 6.5
  WGPUDxcMaxShaderModel_V6_5(5),

  /// Shader Model 6.6
  WGPUDxcMaxShaderModel_V6_6(6),

  /// Shader Model 6.7
  WGPUDxcMaxShaderModel_V6_7(7),
  WGPUDxcMaxShaderModel_Force32(2147483647);

  final int value;
  const WGPUDxcMaxShaderModel(this.value);

  static WGPUDxcMaxShaderModel fromValue(int value) => switch (value) {
    0 => WGPUDxcMaxShaderModel_V6_0,
    1 => WGPUDxcMaxShaderModel_V6_1,
    2 => WGPUDxcMaxShaderModel_V6_2,
    3 => WGPUDxcMaxShaderModel_V6_3,
    4 => WGPUDxcMaxShaderModel_V6_4,
    5 => WGPUDxcMaxShaderModel_V6_5,
    6 => WGPUDxcMaxShaderModel_V6_6,
    7 => WGPUDxcMaxShaderModel_V6_7,
    2147483647 => WGPUDxcMaxShaderModel_Force32,
    _ => throw ArgumentError('Unknown value for WGPUDxcMaxShaderModel: $value'),
  };
}

enum WGPUGLFenceBehaviour {
  WGPUGLFenceBehaviour_Normal(0),

  /// Fences are short-circuited to always report completion immediately.
  ///
  /// This solves a specific issue that arose due to a bug in wgpu-core that
  /// made many WebGL programs work when they shouldn't have. If you have
  /// code that calls @ref wgpuDevicePoll with @c wait=true on WebGL, you
  /// may need to enable this option for "wait" to behave how you expect.
  ///
  /// When this is set, @c wgpuQueueOnCompletedWorkDone callbacks will fire
  /// the next time the device is polled, not when work is actually done on
  /// the GPU.
  WGPUGLFenceBehaviour_AutoFinish(1),
  WGPUGLFenceBehaviour_Force32(2147483647);

  final int value;
  const WGPUGLFenceBehaviour(this.value);

  static WGPUGLFenceBehaviour fromValue(int value) => switch (value) {
    0 => WGPUGLFenceBehaviour_Normal,
    1 => WGPUGLFenceBehaviour_AutoFinish,
    2147483647 => WGPUGLFenceBehaviour_Force32,
    _ => throw ArgumentError('Unknown value for WGPUGLFenceBehaviour: $value'),
  };
}

enum WGPUDx12SwapchainKind {
  WGPUDx12SwapchainKind_Undefined(0),

  /// Use a DXGI swapchain created directly from the window's HWND.
  ///
  /// This does not support transparency but has better support from
  /// developer tooling such as RenderDoc.
  WGPUDx12SwapchainKind_DxgiFromHwnd(1),

  /// Use a DXGI swapchain created from a DirectComposition visual made
  /// automatically from the window's HWND.
  ///
  /// This creates a single @c IDCompositionVisual over the entire window.
  /// Supports transparency. If you want to manage the composition tree
  /// yourself, create your own device and composition and pass the relevant
  /// visual via the surface target.
  WGPUDx12SwapchainKind_DxgiFromVisual(2),
  WGPUDx12SwapchainKind_Force32(2147483647);

  final int value;
  const WGPUDx12SwapchainKind(this.value);

  static WGPUDx12SwapchainKind fromValue(int value) => switch (value) {
    0 => WGPUDx12SwapchainKind_Undefined,
    1 => WGPUDx12SwapchainKind_DxgiFromHwnd,
    2 => WGPUDx12SwapchainKind_DxgiFromVisual,
    2147483647 => WGPUDx12SwapchainKind_Force32,
    _ => throw ArgumentError('Unknown value for WGPUDx12SwapchainKind: $value'),
  };
}

/// Discriminant for @ref WGPUNativeDisplayHandle.
///
/// Identifies which platform's display connection is stored in the tagged union.
/// Use @ref WGPUNativeDisplayHandleType_None (the default when zero-initialized) when
/// no display handle is needed. Platforms with no display connection data (Windows,
/// macOS, iOS, Android) should use @ref WGPUNativeDisplayHandleType_None.
enum WGPUNativeDisplayHandleType {
  /// No display handle provided.
  WGPUNativeDisplayHandleType_None(0),

  /// X11 display connection via Xlib. See @ref WGPUXlibDisplayHandle.
  WGPUNativeDisplayHandleType_Xlib(1),

  /// X11 display connection via XCB. See @ref WGPUXcbDisplayHandle.
  WGPUNativeDisplayHandleType_Xcb(2),

  /// Wayland display connection. See @ref WGPUWaylandDisplayHandle.
  WGPUNativeDisplayHandleType_Wayland(3),
  WGPUNativeDisplayHandleType_Force32(2147483647);

  final int value;
  const WGPUNativeDisplayHandleType(this.value);

  static WGPUNativeDisplayHandleType fromValue(int value) => switch (value) {
    0 => WGPUNativeDisplayHandleType_None,
    1 => WGPUNativeDisplayHandleType_Xlib,
    2 => WGPUNativeDisplayHandleType_Xcb,
    3 => WGPUNativeDisplayHandleType_Wayland,
    2147483647 => WGPUNativeDisplayHandleType_Force32,
    _ => throw ArgumentError('Unknown value for WGPUNativeDisplayHandleType: $value'),
  };
}

/// Xlib display connection data for @ref WGPUNativeDisplayHandle.
final class WGPUXlibDisplayHandle extends ffi.Struct {
  /// Pointer to the X11 @c Display (i.e. @c Display*). Must not be NULL.
  external ffi.Pointer<ffi.Void> display;

  /// X11 screen number.
  @ffi.Int()
  external int screen;
}

/// XCB display connection data for @ref WGPUNativeDisplayHandle.
final class WGPUXcbDisplayHandle extends ffi.Struct {
  /// Pointer to the XCB connection (i.e. @c xcb_connection_t*). Must not be NULL.
  external ffi.Pointer<ffi.Void> connection;

  /// X11 screen number.
  @ffi.Int()
  external int screen;
}

/// Wayland display connection data for @ref WGPUNativeDisplayHandle.
final class WGPUWaylandDisplayHandle extends ffi.Struct {
  /// Pointer to the Wayland display (i.e. @c wl_display*). Must not be NULL.
  external ffi.Pointer<ffi.Void> display;
}

final class UnnamedUnion extends ffi.Union {
  external WGPUXlibDisplayHandle xlib;

  external WGPUXcbDisplayHandle xcb;

  external WGPUWaylandDisplayHandle wayland;
}

/// Platform display connection, passed as a field of @ref WGPUInstanceExtras.
///
/// This is a tagged union. Set @c type to indicate which variant is active, then
/// populate the corresponding field in @c data. Zero-initialization yields
/// @ref WGPUNativeDisplayHandleType_None, meaning no display handle is provided.
///
/// Currently required by the GLES backend when presenting on Wayland. Other
/// backends ignore this field. If the instance is created with a display handle,
/// all surfaces created from it must use the same display connection.
final class WGPUNativeDisplayHandle extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  WGPUNativeDisplayHandleType get type => WGPUNativeDisplayHandleType.fromValue(typeAsInt);

  external UnnamedUnion data;
}

enum WGPUSType {
  WGPUSType_ShaderSourceSPIRV(1),
  WGPUSType_ShaderSourceWGSL(2),
  WGPUSType_RenderPassMaxDrawCount(3),
  WGPUSType_SurfaceSourceMetalLayer(4),
  WGPUSType_SurfaceSourceWindowsHWND(5),
  WGPUSType_SurfaceSourceXlibWindow(6),
  WGPUSType_SurfaceSourceWaylandSurface(7),
  WGPUSType_SurfaceSourceAndroidNativeWindow(8),
  WGPUSType_SurfaceSourceXCBWindow(9),
  WGPUSType_SurfaceColorManagement(10),
  WGPUSType_RequestAdapterWebXROptions(11),
  WGPUSType_TextureComponentSwizzleDescriptor(12),
  WGPUSType_ExternalTextureBindingLayout(13),
  WGPUSType_ExternalTextureBindingEntry(14),
  WGPUSType_CompatibilityModeLimits(15),
  WGPUSType_TextureBindingViewDimension(16),
  WGPUSType_Force32(2147483647);

  final int value;
  const WGPUSType(this.value);

  static WGPUSType fromValue(int value) => switch (value) {
    1 => WGPUSType_ShaderSourceSPIRV,
    2 => WGPUSType_ShaderSourceWGSL,
    3 => WGPUSType_RenderPassMaxDrawCount,
    4 => WGPUSType_SurfaceSourceMetalLayer,
    5 => WGPUSType_SurfaceSourceWindowsHWND,
    6 => WGPUSType_SurfaceSourceXlibWindow,
    7 => WGPUSType_SurfaceSourceWaylandSurface,
    8 => WGPUSType_SurfaceSourceAndroidNativeWindow,
    9 => WGPUSType_SurfaceSourceXCBWindow,
    10 => WGPUSType_SurfaceColorManagement,
    11 => WGPUSType_RequestAdapterWebXROptions,
    12 => WGPUSType_TextureComponentSwizzleDescriptor,
    13 => WGPUSType_ExternalTextureBindingLayout,
    14 => WGPUSType_ExternalTextureBindingEntry,
    15 => WGPUSType_CompatibilityModeLimits,
    16 => WGPUSType_TextureBindingViewDimension,
    2147483647 => WGPUSType_Force32,
    _ => throw ArgumentError('Unknown value for WGPUSType: $value'),
  };
}

/// @} */
/// /**
/// \defgroup ChainedStructures Chained Structures
/// \brief Structures used to extend descriptors.
///
/// @{
final class WGPUChainedStruct extends ffi.Struct {
  external ffi.Pointer<WGPUChainedStruct> next;

  @ffi.UnsignedInt()
  external int sTypeAsInt;

  WGPUSType get sType => WGPUSType.fromValue(sTypeAsInt);
}

/// Nullable value defining a pointer+length view into a UTF-8 encoded string.
///
/// Values passed into the API may use the special length value @ref WGPU_STRLEN
/// to indicate a null-terminated string.
/// Non-null values passed out of the API (for example as callback arguments)
/// always provide an explicit length and **may or may not be null-terminated**.
///
/// Some inputs to the API accept null values. Those which do not accept null
/// values "default" to the empty string when null values are passed.
///
/// Values are encoded as follows:
/// - `{NULL, WGPU_STRLEN}`: the null value.
/// - `{non_null_pointer, WGPU_STRLEN}`: a null-terminated string view.
/// - `{any, 0}`: the empty string.
/// - `{NULL, non_zero_length}`: not allowed (null dereference).
/// - `{non_null_pointer, non_zero_length}`: an explictly-sized string view with
/// size `non_zero_length` (in bytes).
///
/// For info on how this is used in various places, see \ref Strings.
final class WGPUStringView extends ffi.Struct {
  external ffi.Pointer<ffi.Char> data;

  @ffi.Size()
  external int length;
}

final class WGPUInstanceExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// Which backends to enable.
  /// Zero (@ref WGPUInstanceBackend_All) enables all backends.
  @WGPUInstanceBackend()
  external int backends;

  /// Flags controlling debug/validation behavior.
  /// See @ref WGPUInstanceFlag for available flags.
  @WGPUInstanceFlag()
  external int flags;

  /// Which DX12 shader compiler to use.
  /// See @ref WGPUDx12Compiler. Ignored on non-DX12 backends.
  @ffi.UnsignedInt()
  external int dx12ShaderCompilerAsInt;

  WGPUDx12Compiler get dx12ShaderCompiler => WGPUDx12Compiler.fromValue(dx12ShaderCompilerAsInt);

  /// Which OpenGL ES 3 minor version to request.
  /// See @ref WGPUGles3MinorVersion. Ignored on non-GL backends.
  @ffi.UnsignedInt()
  external int gles3MinorVersionAsInt;

  WGPUGles3MinorVersion get gles3MinorVersion => WGPUGles3MinorVersion.fromValue(gles3MinorVersionAsInt);

  /// Controls OpenGL fence synchronization behavior.
  /// See @ref WGPUGLFenceBehaviour. Ignored on non-GL backends.
  @ffi.UnsignedInt()
  external int glFenceBehaviourAsInt;

  WGPUGLFenceBehaviour get glFenceBehaviour => WGPUGLFenceBehaviour.fromValue(glFenceBehaviourAsInt);

  /// File system path to @c dxcompiler.dll for dynamic DXC loading.
  /// Only used when @c dx12ShaderCompiler is @ref WGPUDx12Compiler_Dxc.
  /// An empty/undefined string view means the DLL will be searched for
  /// on the system PATH.
  external WGPUStringView dxcPath;

  /// Maximum HLSL shader model version that DXC should target.
  /// See @ref WGPUDxcMaxShaderModel. Only used with the DXC compiler.
  @ffi.UnsignedInt()
  external int dxcMaxShaderModelAsInt;

  WGPUDxcMaxShaderModel get dxcMaxShaderModel => WGPUDxcMaxShaderModel.fromValue(dxcMaxShaderModelAsInt);

  /// Which DX12 presentation system (swapchain kind) to use.
  /// See @ref WGPUDx12SwapchainKind. Ignored on non-DX12 backends.
  @ffi.UnsignedInt()
  external int dx12PresentationSystemAsInt;

  WGPUDx12SwapchainKind get dx12PresentationSystem => WGPUDx12SwapchainKind.fromValue(dx12PresentationSystemAsInt);

  external ffi.Pointer<ffi.Uint8> budgetForDeviceCreation;

  external ffi.Pointer<ffi.Uint8> budgetForDeviceLoss;

  /// Platform display connection to associate with this instance.
  /// Zero-initialized yields @ref WGPUNativeDisplayHandleType_None (no handle).
  external WGPUNativeDisplayHandle displayHandle;
}

final class WGPUDeviceExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// File system path for API trace output.
  ///
  /// When set to a non-empty path, wgpu will record all API calls to
  /// the given directory, which can later be replayed for debugging.
  /// An empty/undefined string view disables tracing.
  external WGPUStringView tracePath;
}

final class WGPUNativeLimits extends ffi.Struct {
  /// This struct chain is used as mutable in some places and immutable in others.
  external WGPUChainedStruct chain;

  /// Amount of storage available for immediate data, in bytes.
  ///
  /// Defaults to 0. A non-zero value requires
  /// @ref WGPUNativeFeature_Immediates. Expected maximum sizes vary by
  /// backend:
  /// - Vulkan: 128-256 bytes
  /// - DX12: 128 bytes
  /// - Metal: 4096 bytes
  /// - OpenGL: ~256 bytes (emulated with uniforms)
  @ffi.Uint32()
  external int maxImmediateSize;

  /// Maximum number of live non-sampler bindings.
  ///
  /// Default is 1,000,000. Only meaningful on D3D12.
  ///
  /// @b Warning: On integrated GPUs, large values can cause significant
  /// system RAM consumption.
  @ffi.Uint32()
  external int maxNonSamplerBindings;

  /// Maximum number of individual resources within binding arrays per
  /// shader stage.
  @ffi.Uint32()
  external int maxBindingArrayElementsPerShaderStage;
}

final class WGPUPipelineLayoutExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// The number of bytes of immediate data allocated for use in shaders
  /// attached to this pipeline.
  ///
  /// The @c var<immediate> declarations in the shader must be equal or
  /// smaller than this size. If this value is non-zero,
  /// @ref WGPUNativeFeature_Immediates must be enabled.
  @ffi.Uint32()
  external int immediateDataSize;
}

/// Identifier for a particular call to @ref wgpuQueueSubmitForIndex.
///
/// Can be passed to @ref wgpuDevicePoll to block until a particular
/// submission has finished execution.
///
/// This type is unique to wgpu-native; there is no analogue in the
/// WebGPU specification.
typedef WGPUSubmissionIndex = ffi.Uint64;
typedef DartWGPUSubmissionIndex = int;

final class WGPUShaderDefine extends ffi.Struct {
  external WGPUStringView name;

  /// The value of the preprocessor macro (e.g. @c "1").
  external WGPUStringView value;
}

/// For reserved non-standard bitflag values, see @ref BitflagRegistry.
typedef WGPUShaderStage = WGPUFlags;

final class WGPUShaderSourceGLSL extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// The shader stage this GLSL source targets.
  @WGPUShaderStage()
  external int stage;

  /// GLSL source code.
  external WGPUStringView code;

  /// Number of entries in @c defines.
  @ffi.Uint32()
  external int defineCount;

  external ffi.Pointer<WGPUShaderDefine> defines;
}

final class WGPUShaderModuleDescriptorSpirV extends ffi.Struct {
  external WGPUStringView label;

  /// Number of 32-bit words in @c source.
  @ffi.Uint32()
  external int sourceSize;

  external ffi.Pointer<ffi.Uint32> source;
}

final class WGPURegistryReport extends ffi.Struct {
  @ffi.Size()
  external int numAllocated;

  @ffi.Size()
  external int numKeptFromUser;

  @ffi.Size()
  external int numReleasedFromUser;

  @ffi.Size()
  external int elementSize;
}

final class WGPUHubReport extends ffi.Struct {
  external WGPURegistryReport adapters;

  external WGPURegistryReport devices;

  external WGPURegistryReport queues;

  external WGPURegistryReport pipelineLayouts;

  external WGPURegistryReport shaderModules;

  external WGPURegistryReport bindGroupLayouts;

  external WGPURegistryReport bindGroups;

  external WGPURegistryReport commandBuffers;

  external WGPURegistryReport renderBundles;

  external WGPURegistryReport renderPipelines;

  external WGPURegistryReport computePipelines;

  external WGPURegistryReport pipelineCaches;

  external WGPURegistryReport querySets;

  external WGPURegistryReport buffers;

  external WGPURegistryReport textures;

  external WGPURegistryReport textureViews;

  external WGPURegistryReport samplers;
}

final class WGPUGlobalReport extends ffi.Struct {
  external WGPURegistryReport surfaces;

  /// Statistics for all other resource types, grouped by backend hub.
  external WGPUHubReport hub;
}

final class WGPUInstanceEnumerateAdapterOptions extends ffi.Struct {
  external ffi.Pointer<WGPUChainedStruct> nextInChain;

  @WGPUInstanceBackend()
  external int backends;
}

final class WGPUBufferImpl extends ffi.Opaque {}

typedef WGPUBuffer = ffi.Pointer<WGPUBufferImpl>;

final class WGPUSamplerImpl extends ffi.Opaque {}

typedef WGPUSampler = ffi.Pointer<WGPUSamplerImpl>;

final class WGPUTextureViewImpl extends ffi.Opaque {}

typedef WGPUTextureView = ffi.Pointer<WGPUTextureViewImpl>;

final class WGPUBindGroupEntryExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  external ffi.Pointer<WGPUBuffer> buffers;

  @ffi.Size()
  external int bufferCount;

  external ffi.Pointer<WGPUSampler> samplers;

  @ffi.Size()
  external int samplerCount;

  external ffi.Pointer<WGPUTextureView> textureViews;

  @ffi.Size()
  external int textureViewCount;
}

final class WGPUBindGroupLayoutEntryExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// Number of resources in this binding array slot. Corresponds to the
  /// array size in the shader (e.g. @c binding_array<T, @c N>).
  @ffi.Uint32()
  external int count;
}

final class WGPUQuerySetDescriptorExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  external ffi.Pointer<ffi.UnsignedInt> pipelineStatistics;

  @ffi.Size()
  external int pipelineStatisticCount;
}

final class WGPUSurfaceConfigurationExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// Desired maximum number of frames in flight (i.e. the number of monitor
  /// refreshes between @c wgpuSurfaceGetCurrentTexture and presentation).
  ///
  /// - 1: Minimize latency (CPU and GPU cannot run in parallel).
  /// - 2: Balance between latency and throughput (the default).
  /// - 3+: Maximize throughput.
  @ffi.Uint32()
  external int desiredMaximumFrameLatency;
}

/// Chained in @ref WGPUSurfaceDescriptor to make a @ref WGPUSurface wrapping a WinUI [`SwapChainPanel`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.swapchainpanel).
final class WGPUSurfaceSourceSwapChainPanel extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// A pointer to the [`ISwapChainPanelNative`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/microsoft.ui.xaml.media.dxinterop/nn-microsoft-ui-xaml-media-dxinterop-iswapchainpanelnative)
  /// interface of the SwapChainPanel that will be wrapped by the @ref WGPUSurface.
  external ffi.Pointer<ffi.Void> panelNative;
}

enum WGPUPolygonMode {
  WGPUPolygonMode_Fill(0),

  /// Polygons are drawn as line segments (wireframe).
  /// Requires @ref WGPUNativeFeature_PolygonModeLine.
  WGPUPolygonMode_Line(1),

  /// Polygons are drawn as points (vertices only).
  /// Requires @ref WGPUNativeFeature_PolygonModePoint.
  WGPUPolygonMode_Point(2);

  final int value;
  const WGPUPolygonMode(this.value);

  static WGPUPolygonMode fromValue(int value) => switch (value) {
    0 => WGPUPolygonMode_Fill,
    1 => WGPUPolygonMode_Line,
    2 => WGPUPolygonMode_Point,
    _ => throw ArgumentError('Unknown value for WGPUPolygonMode: $value'),
  };
}

typedef WGPUBool = ffi.Uint32;
typedef DartWGPUBool = int;

final class WGPUPrimitiveStateExtras extends ffi.Struct {
  external WGPUChainedStruct chain;

  /// Controls the way each polygon is rasterized.
  /// See @ref WGPUPolygonMode. Defaults to @ref WGPUPolygonMode_Fill.
  @ffi.UnsignedInt()
  external int polygonModeAsInt;

  WGPUPolygonMode get polygonMode => WGPUPolygonMode.fromValue(polygonModeAsInt);

  /// If set to true, the primitives are rendered with conservative
  /// overestimation. Only valid when @c polygonMode is
  /// @ref WGPUPolygonMode_Fill.
  /// Requires @ref WGPUNativeFeature_ConservativeRasterization.
  @WGPUBool()
  external int conservative;
}

typedef WGPULogCallbackFunction =
    ffi.Void Function(ffi.UnsignedInt level, WGPUStringView message, ffi.Pointer<ffi.Void> userdata);
typedef DartWGPULogCallbackFunction =
    void Function(WGPULogLevel level, WGPUStringView message, ffi.Pointer<ffi.Void> userdata);
typedef WGPULogCallback = ffi.Pointer<ffi.NativeFunction<WGPULogCallbackFunction>>;

enum WGPUNativeTextureFormat {
  WGPUNativeTextureFormat_R16Unorm(196609),

  /// Red channel only. 16-bit signed integer per channel.
  /// [-32767, 32767] converted to/from float [-1, 1] in shader.
  /// Requires @ref WGPUNativeFeature_TextureFormat16bitNorm.
  WGPUNativeTextureFormat_R16Snorm(196610),

  /// Red and green channels. 16-bit unsigned integer per channel.
  /// [0, 65535] converted to/from float [0, 1] in shader.
  /// Requires @ref WGPUNativeFeature_TextureFormat16bitNorm.
  WGPUNativeTextureFormat_Rg16Unorm(196611),

  /// Red and green channels. 16-bit signed integer per channel.
  /// [-32767, 32767] converted to/from float [-1, 1] in shader.
  /// Requires @ref WGPUNativeFeature_TextureFormat16bitNorm.
  WGPUNativeTextureFormat_Rg16Snorm(196612),

  /// Red, green, blue, and alpha channels. 16-bit unsigned integer per channel.
  /// [0, 65535] converted to/from float [0, 1] in shader.
  /// Requires @ref WGPUNativeFeature_TextureFormat16bitNorm.
  WGPUNativeTextureFormat_Rgba16Unorm(196613),

  /// Red, green, blue, and alpha channels. 16-bit signed integer per channel.
  /// [-32767, 32767] converted to/from float [-1, 1] in shader.
  /// Requires @ref WGPUNativeFeature_TextureFormat16bitNorm.
  WGPUNativeTextureFormat_Rgba16Snorm(196614),

  /// YUV 4:2:0 chroma subsampled format (NV12).
  /// Plane 0 contains R8Unorm luminance (Y), Plane 1 contains Rg8Unorm
  /// chrominance (UV) at half width and half height.
  /// Requires @ref WGPUNativeFeature_TextureFormatNv12.
  WGPUNativeTextureFormat_NV12(196615),

  /// YUV 4:2:0 with 10 bits used from 16-bit channels (P010).
  /// Plane 0 contains R16Unorm luminance (Y), Plane 1 contains Rg16Unorm
  /// chrominance (UV) at half width and half height.
  WGPUNativeTextureFormat_P010(196616);

  final int value;
  const WGPUNativeTextureFormat(this.value);

  static WGPUNativeTextureFormat fromValue(int value) => switch (value) {
    196609 => WGPUNativeTextureFormat_R16Unorm,
    196610 => WGPUNativeTextureFormat_R16Snorm,
    196611 => WGPUNativeTextureFormat_Rg16Unorm,
    196612 => WGPUNativeTextureFormat_Rg16Snorm,
    196613 => WGPUNativeTextureFormat_Rgba16Unorm,
    196614 => WGPUNativeTextureFormat_Rgba16Snorm,
    196615 => WGPUNativeTextureFormat_NV12,
    196616 => WGPUNativeTextureFormat_P010,
    _ => throw ArgumentError('Unknown value for WGPUNativeTextureFormat: $value'),
  };
}

final class WGPUInstanceImpl extends ffi.Opaque {}

typedef WGPUInstance = ffi.Pointer<WGPUInstanceImpl>;

final class WGPUAdapterImpl extends ffi.Opaque {}

/// \defgroup Objects Objects
/// \brief Opaque, non-dispatchable handles to WebGPU objects.
///
/// @{
typedef WGPUAdapter = ffi.Pointer<WGPUAdapterImpl>;

final class WGPUQueueImpl extends ffi.Opaque {}

typedef WGPUQueue = ffi.Pointer<WGPUQueueImpl>;

final class WGPUCommandBufferImpl extends ffi.Opaque {}

typedef WGPUCommandBuffer = ffi.Pointer<WGPUCommandBufferImpl>;

final class WGPUDeviceImpl extends ffi.Opaque {}

/// TODO
///
/// Releasing the last ref to a `WGPUDevice` also calls @ref wgpuDeviceDestroy.
/// For more info, see @ref DeviceRelease.
typedef WGPUDevice = ffi.Pointer<WGPUDeviceImpl>;

final class WGPUShaderModuleImpl extends ffi.Opaque {}

typedef WGPUShaderModule = ffi.Pointer<WGPUShaderModuleImpl>;

final class WGPUTextureImpl extends ffi.Opaque {}

typedef WGPUTexture = ffi.Pointer<WGPUTextureImpl>;

final class WGPURenderPassEncoderImpl extends ffi.Opaque {}

typedef WGPURenderPassEncoder = ffi.Pointer<WGPURenderPassEncoderImpl>;

final class WGPUComputePassEncoderImpl extends ffi.Opaque {}

typedef WGPUComputePassEncoder = ffi.Pointer<WGPUComputePassEncoderImpl>;

final class WGPURenderBundleEncoderImpl extends ffi.Opaque {}

typedef WGPURenderBundleEncoder = ffi.Pointer<WGPURenderBundleEncoderImpl>;

final class WGPUQuerySetImpl extends ffi.Opaque {}

typedef WGPUQuerySet = ffi.Pointer<WGPUQuerySetImpl>;
