name: mouse_cursor
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
    
  bindings:
  state:
  native:
  ui:

  vector_graphics: ^1.2.3

