name: renderer
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  shared:
  geometry:
  kernel:
  program:
  scene:
  color:
  skia:

  listen: ^1.0.1
