name: motif
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - app
  - schema
  - server
  - editor

  - core/geometry
  - core/kernel
  - core/program
  - core/scene
  - core/renderer

  - packages/native
  - packages/genie
  - packages/log
  - packages/mouse_cursor
  - packages/bindings
  - packages/state
  - packages/tool
  - packages/ui
  - packages/color
  - packages/css
  
  - vendor/stack_assets

dev_dependencies:
  flutter_lints: ^6.0.0