name: motif
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - app

  - design
  - vector

  - packages/blueprint
  - packages/canvas
  - packages/color
  - packages/commander
  - packages/css
  - packages/genie
  - packages/geometry
  - packages/ink_stroke_modeler
  - packages/node
  - packages/shared
  - packages/skia
  - packages/text
  - packages/tool
  - packages/tree
  - packages/ui
  - packages/vc
  - packages/vgc
  - packages/vgc_renderer
  - packages/wgpu
  - packages/wgslgen

dev_dependencies:
  flutter_lints: ^6.0.0
  wgslgen:
