// ignore_for_file: unused_import, unused_local_variable
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:jsgen`.
// ignore_for_file: type=lint
import 'dart:typed_data';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';
import 'package:ffigen_js/ffigen_js.dart';
export 'package:ffigen_js/ffigen_js.dart';

extension type GeneratedBindings(NativeLibrary _) implements JSObject {
  static GeneratedBindings get instance => NativeLibrary.instance as GeneratedBindings;

  static void initBindings(String moduleName) {
    var lib = globalContext.getProperty(moduleName.toJS);
    if (lib == null) {
      throw Exception("Failed to find JS module ${moduleName}");
    }
    NativeLibrary.instance = lib as NativeLibrary;
  }

  external int _cubic_intersect(
    Pointer<Cubic2> a,
    Pointer<Cubic2> b,
    Pointer<Intersection> out_hits,
  );
  external int _cubic_circle_intersect(
    Pointer<Cubic2> a,
    Pointer<Circle2> b,
    Pointer<Intersection> out_hits,
  );
  external int _cubic_self_intersect(
    Pointer<Cubic2> a,
    Pointer<Intersection> out_hit,
  );
  external void _cubic_bbox_tight(
    Pointer<Cubic2> a,
    Pointer<Aabb2> out_bbox,
  );
  external double _cubic_arc_length(
    Pointer<Cubic2> a,
  );
  external int _cubic_pos_tan_at_distance(
    Pointer<Cubic2> a,
    double distance,
    Pointer<Vector2> out_pos,
    Pointer<Vector2> out_tan,
  );
  external int _cubic_find_inflections(
    Pointer<Cubic2> a,
    Pointer<Float64> out,
  );
  external int _cubic_to_quads(
    Pointer<Cubic2> a,
    double tolerance,
    Pointer<Quadratic2> out_quads,
    Pointer<Float64> out_t,
    bool chop_at_inflections,
  );
  external int _cull_noisy_points(
    Pointer<InputPoint> points,
    int count,
    double spatial_tolerance,
  );
  external void _stroke_to_spline(
    Pointer<CubicSpline2> CubicSpline2_out,
    Pointer<InputPoint> points,
    int count,
    double spatial_tolerance,
    double velocity_threshold,
  );
}

int cubic_intersect(
  Pointer<Cubic2> a,
  Pointer<Cubic2> b,
  Pointer<Intersection> out_hits,
) {
  final result = GeneratedBindings.instance._cubic_intersect(a.cast(), b.cast(), out_hits.cast());
  return result;
}

int cubic_circle_intersect(
  Pointer<Cubic2> a,
  Pointer<Circle2> b,
  Pointer<Intersection> out_hits,
) {
  final result = GeneratedBindings.instance._cubic_circle_intersect(a.cast(), b.cast(), out_hits.cast());
  return result;
}

int cubic_self_intersect(
  Pointer<Cubic2> a,
  Pointer<Intersection> out_hit,
) {
  final result = GeneratedBindings.instance._cubic_self_intersect(a.cast(), out_hit.cast());
  return result;
}

void cubic_bbox_tight(
  Pointer<Cubic2> a,
  Pointer<Aabb2> out_bbox,
) {
  final result = GeneratedBindings.instance._cubic_bbox_tight(a.cast(), out_bbox.cast());
  return result;
}

double cubic_arc_length(
  Pointer<Cubic2> a,
) {
  final result = GeneratedBindings.instance._cubic_arc_length(a.cast());
  return result;
}

int cubic_pos_tan_at_distance(
  Pointer<Cubic2> a,
  double distance,
  Pointer<Vector2> out_pos,
  Pointer<Vector2> out_tan,
) {
  final result = GeneratedBindings.instance._cubic_pos_tan_at_distance(
    a.cast(),
    distance,
    out_pos.cast(),
    out_tan.cast(),
  );
  return result;
}

int cubic_find_inflections(
  Pointer<Cubic2> a,
  Pointer<Float64> out,
) {
  final result = GeneratedBindings.instance._cubic_find_inflections(a.cast(), out);
  return result;
}

int cubic_to_quads(
  Pointer<Cubic2> a,
  double tolerance,
  Pointer<Quadratic2> out_quads,
  Pointer<Float64> out_t,
  bool chop_at_inflections,
) {
  final result = GeneratedBindings.instance._cubic_to_quads(
    a.cast(),
    tolerance,
    out_quads.cast(),
    out_t,
    chop_at_inflections,
  );
  return result;
}

int cull_noisy_points(
  Pointer<InputPoint> points,
  int count,
  double spatial_tolerance,
) {
  final result = GeneratedBindings.instance._cull_noisy_points(points.cast(), count, spatial_tolerance);
  return result;
}

CubicSpline2 stroke_to_spline(
  Pointer<InputPoint> points,
  int count,
  double spatial_tolerance,
  double velocity_threshold,
) {
  final CubicSpline2_out = CubicSpline2.stackAlloc();
  final result = GeneratedBindings.instance._stroke_to_spline(
    CubicSpline2_out.cast(),
    points.cast(),
    count,
    spatial_tolerance,
    velocity_threshold,
  );
  return CubicSpline2_out.toDart();
}

extension Cubic2Ext on Pointer<Cubic2> {
  Cubic2 toDart() {
    return Cubic2(this);
  }
  Cubic2 get ref => toDart();
  Cubic2 operator [](int index) => Pointer<Cubic2>(this.address + sizeOf * index).toDart();
  operator []=(int index, Cubic2 value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 64;
}

final class Cubic2 extends Struct {
  Pointer<Cubic2> get address => super.address.cast();
  Vector2 get p0 {
    final addr = Pointer<Cubic2>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set p0(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Cubic2>(this.address.addr + 0), val.address.toJS, '*');
  }

  Vector2 get p1 {
    final addr = Pointer<Cubic2>(this.address.addr + 16);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set p1(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Cubic2>(this.address.addr + 16), val.address.toJS, '*');
  }

  Vector2 get p2 {
    final addr = Pointer<Cubic2>(this.address.addr + 32);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set p2(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Cubic2>(this.address.addr + 32), val.address.toJS, '*');
  }

  Vector2 get p3 {
    final addr = Pointer<Cubic2>(this.address.addr + 48);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set p3(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Cubic2>(this.address.addr + 48), val.address.toJS, '*');
  }

  Cubic2(super.address);

  static Pointer<Cubic2> stackAlloc() {
    return Pointer<Cubic2>(NativeLibrary.instance.stackAlloc<Cubic2>(64));
  }
}

extension Vector2Ext on Pointer<Vector2> {
  Vector2 toDart() {
    return Vector2(this);
  }
  Vector2 get ref => toDart();
  Vector2 operator [](int index) => Pointer<Vector2>(this.address + sizeOf * index).toDart();
  operator []=(int index, Vector2 value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 16;
}

final class Vector2 extends Struct {
  Pointer<Vector2> get address => super.address.cast();
  double get x {
    final addr = Pointer<Vector2>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, 'double').toDartDouble;
    return value;
  }

  set x(double val) {
    NativeLibrary.instance.setValue(Pointer<Vector2>(this.address.addr + 0), val.toJS, 'double');
  }

  double get y {
    final addr = Pointer<Vector2>(this.address.addr + 8);
    final value = NativeLibrary.instance.getValue(addr, 'double').toDartDouble;
    return value;
  }

  set y(double val) {
    NativeLibrary.instance.setValue(Pointer<Vector2>(this.address.addr + 8), val.toJS, 'double');
  }

  Vector2(super.address);

  static Pointer<Vector2> stackAlloc() {
    return Pointer<Vector2>(NativeLibrary.instance.stackAlloc<Vector2>(16));
  }
}

extension IntersectionExt on Pointer<Intersection> {
  Intersection toDart() {
    return Intersection(this);
  }
  Intersection get ref => toDart();
  Intersection operator [](int index) => Pointer<Intersection>(this.address + sizeOf * index).toDart();
  operator []=(int index, Intersection value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 32;
}

final class Intersection extends Struct {
  Pointer<Intersection> get address => super.address.cast();
  Vector2 get pt {
    final addr = Pointer<Intersection>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set pt(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Intersection>(this.address.addr + 0), val.address.toJS, '*');
  }

  double get tA {
    final addr = Pointer<Intersection>(this.address.addr + 16);
    final value = NativeLibrary.instance.getValue(addr, 'double').toDartDouble;
    return value;
  }

  set tA(double val) {
    NativeLibrary.instance.setValue(Pointer<Intersection>(this.address.addr + 16), val.toJS, 'double');
  }

  double get tB {
    final addr = Pointer<Intersection>(this.address.addr + 24);
    final value = NativeLibrary.instance.getValue(addr, 'double').toDartDouble;
    return value;
  }

  set tB(double val) {
    NativeLibrary.instance.setValue(Pointer<Intersection>(this.address.addr + 24), val.toJS, 'double');
  }

  Intersection(super.address);

  static Pointer<Intersection> stackAlloc() {
    return Pointer<Intersection>(NativeLibrary.instance.stackAlloc<Intersection>(32));
  }
}

extension Circle2Ext on Pointer<Circle2> {
  Circle2 toDart() {
    return Circle2(this);
  }
  Circle2 get ref => toDart();
  Circle2 operator [](int index) => Pointer<Circle2>(this.address + sizeOf * index).toDart();
  operator []=(int index, Circle2 value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 24;
}

final class Circle2 extends Struct {
  Pointer<Circle2> get address => super.address.cast();
  Vector2 get center {
    final addr = Pointer<Circle2>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set center(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Circle2>(this.address.addr + 0), val.address.toJS, '*');
  }

  double get radius {
    final addr = Pointer<Circle2>(this.address.addr + 16);
    final value = NativeLibrary.instance.getValue(addr, 'double').toDartDouble;
    return value;
  }

  set radius(double val) {
    NativeLibrary.instance.setValue(Pointer<Circle2>(this.address.addr + 16), val.toJS, 'double');
  }

  Circle2(super.address);

  static Pointer<Circle2> stackAlloc() {
    return Pointer<Circle2>(NativeLibrary.instance.stackAlloc<Circle2>(24));
  }
}

extension Aabb2Ext on Pointer<Aabb2> {
  Aabb2 toDart() {
    return Aabb2(this);
  }
  Aabb2 get ref => toDart();
  Aabb2 operator [](int index) => Pointer<Aabb2>(this.address + sizeOf * index).toDart();
  operator []=(int index, Aabb2 value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 32;
}

final class Aabb2 extends Struct {
  Pointer<Aabb2> get address => super.address.cast();
  Vector2 get min {
    final addr = Pointer<Aabb2>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set min(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Aabb2>(this.address.addr + 0), val.address.toJS, '*');
  }

  Vector2 get max {
    final addr = Pointer<Aabb2>(this.address.addr + 16);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set max(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Aabb2>(this.address.addr + 16), val.address.toJS, '*');
  }

  Aabb2(super.address);

  static Pointer<Aabb2> stackAlloc() {
    return Pointer<Aabb2>(NativeLibrary.instance.stackAlloc<Aabb2>(32));
  }
}

extension Quadratic2Ext on Pointer<Quadratic2> {
  Quadratic2 toDart() {
    return Quadratic2(this);
  }
  Quadratic2 get ref => toDart();
  Quadratic2 operator [](int index) => Pointer<Quadratic2>(this.address + sizeOf * index).toDart();
  operator []=(int index, Quadratic2 value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 48;
}

final class Quadratic2 extends Struct {
  Pointer<Quadratic2> get address => super.address.cast();
  Vector2 get p0 {
    final addr = Pointer<Quadratic2>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set p0(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Quadratic2>(this.address.addr + 0), val.address.toJS, '*');
  }

  Vector2 get p1 {
    final addr = Pointer<Quadratic2>(this.address.addr + 16);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set p1(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Quadratic2>(this.address.addr + 16), val.address.toJS, '*');
  }

  Vector2 get p2 {
    final addr = Pointer<Quadratic2>(this.address.addr + 32);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set p2(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<Quadratic2>(this.address.addr + 32), val.address.toJS, '*');
  }

  Quadratic2(super.address);

  static Pointer<Quadratic2> stackAlloc() {
    return Pointer<Quadratic2>(NativeLibrary.instance.stackAlloc<Quadratic2>(48));
  }
}

extension InputPointExt on Pointer<InputPoint> {
  InputPoint toDart() {
    return InputPoint(this);
  }
  InputPoint get ref => toDart();
  InputPoint operator [](int index) => Pointer<InputPoint>(this.address + sizeOf * index).toDart();
  operator []=(int index, InputPoint value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 32;
}

final class InputPoint extends Struct {
  Pointer<InputPoint> get address => super.address.cast();
  Vector2 get position {
    final addr = Pointer<InputPoint>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Vector2(Pointer<Vector2>(addr));
  }

  set position(Vector2 val) {
    NativeLibrary.instance.setValue(Pointer<InputPoint>(this.address.addr + 0), val.address.toJS, '*');
  }

  double get timestamp_ms {
    final addr = Pointer<InputPoint>(this.address.addr + 16);
    final value = NativeLibrary.instance.getValue(addr, 'double').toDartDouble;
    return value;
  }

  set timestamp_ms(double val) {
    NativeLibrary.instance.setValue(Pointer<InputPoint>(this.address.addr + 16), val.toJS, 'double');
  }

  double get pressure {
    final addr = Pointer<InputPoint>(this.address.addr + 24);
    final value = NativeLibrary.instance.getValue(addr, 'double').toDartDouble;
    return value;
  }

  set pressure(double val) {
    NativeLibrary.instance.setValue(Pointer<InputPoint>(this.address.addr + 24), val.toJS, 'double');
  }

  InputPoint(super.address);

  static Pointer<InputPoint> stackAlloc() {
    return Pointer<InputPoint>(NativeLibrary.instance.stackAlloc<InputPoint>(32));
  }
}

extension CubicSpline2Ext on Pointer<CubicSpline2> {
  CubicSpline2 toDart() {
    return CubicSpline2(this);
  }
  CubicSpline2 get ref => toDart();
  CubicSpline2 operator [](int index) => Pointer<CubicSpline2>(this.address + sizeOf * index).toDart();
  operator []=(int index, CubicSpline2 value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, '*');
  int get sizeOf => 8;
}

final class CubicSpline2 extends Struct {
  Pointer<CubicSpline2> get address => super.address.cast();
  Pointer<Cubic2> get cubics {
    final addr = Pointer<CubicSpline2>(this.address.addr + 0);
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<Cubic2>(value.toDartInt);
  }

  set cubics(Pointer<Cubic2> val) {
    NativeLibrary.instance.setValue(Pointer<CubicSpline2>(this.address.addr + 0), val.toJS, '*');
  }

  int get count {
    final addr = Pointer<CubicSpline2>(this.address.addr + 4);
    final value = NativeLibrary.instance.getValue(addr, 'i32').toDartInt;
    return value;
  }

  set count(int val) {
    NativeLibrary.instance.setValue(Pointer<CubicSpline2>(this.address.addr + 4), val.toJS, 'i32');
  }

  CubicSpline2(super.address);

  static Pointer<CubicSpline2> stackAlloc() {
    return Pointer<CubicSpline2>(NativeLibrary.instance.stackAlloc<CubicSpline2>(8));
  }
}

extension StructAllocator on Struct {
  static T create<T>() {
    switch (T) {
      case Cubic2:
        final ptr = Cubic2.stackAlloc();
        return ptr.toDart() as T;
      case Vector2:
        final ptr = Vector2.stackAlloc();
        return ptr.toDart() as T;
      case Intersection:
        final ptr = Intersection.stackAlloc();
        return ptr.toDart() as T;
      case Circle2:
        final ptr = Circle2.stackAlloc();
        return ptr.toDart() as T;
      case Aabb2:
        final ptr = Aabb2.stackAlloc();
        return ptr.toDart() as T;
      case Quadratic2:
        final ptr = Quadratic2.stackAlloc();
        return ptr.toDart() as T;
      case InputPoint:
        final ptr = InputPoint.stackAlloc();
        return ptr.toDart() as T;
      case CubicSpline2:
        final ptr = CubicSpline2.stackAlloc();
        return ptr.toDart() as T;
    }
    throw Exception("Unsupported type $T");
  }
}
