// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by wgslgen

import 'dart:typed_data';
import 'package:wgpu/wgpu.dart' as wgpu;
import 'package:wgpu/wgsl.dart' as wgsl;

@wgsl.Overrides()
extension type const Overrides._(() _) {
  const Overrides(): this._(());

  List<wgpu.ConstantEntry> get entries => const [];
}

@wgsl.Struct('Cubic2')
extension type const Cubic2._((wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3) _) {
  static const Cubic2 zero = Cubic2._((
    .zero,
    .zero,
    .zero,
    .zero,
  ));

  wgsl.Vec2f get p0 => _.$1;
  wgsl.Vec2f get p1 => _.$2;
  wgsl.Vec2f get p2 => _.$3;
  wgsl.Vec2f get p3 => _.$4;

  @pragma('vm:prefer-inline')
  Cubic2({wgsl.Vec2f p0 = .zero, wgsl.Vec2f p1 = .zero, wgsl.Vec2f p2 = .zero, wgsl.Vec2f p3 = .zero}): this._((
    p0,
    p1,
    p2,
    p3,
  ));

  @pragma('vm:prefer-inline')
  Cubic2.read(ByteData data, int offset): this._((
    wgsl.Vec2f.read(data, offset + 0),
    wgsl.Vec2f.read(data, offset + 8),
    wgsl.Vec2f.read(data, offset + 16),
    wgsl.Vec2f.read(data, offset + 24),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    _.$2.write(data, offset + 8);
    _.$3.write(data, offset + 16);
    _.$4.write(data, offset + 24);
  }
}

@wgsl.Struct('Quadratic2')
extension type const Quadratic2._((wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2) _) {
  static const Quadratic2 zero = Quadratic2._((
    .zero,
    .zero,
    .zero,
  ));

  wgsl.Vec2f get p0 => _.$1;
  wgsl.Vec2f get p1 => _.$2;
  wgsl.Vec2f get p2 => _.$3;

  @pragma('vm:prefer-inline')
  Quadratic2({wgsl.Vec2f p0 = .zero, wgsl.Vec2f p1 = .zero, wgsl.Vec2f p2 = .zero}): this._((
    p0,
    p1,
    p2,
  ));

  @pragma('vm:prefer-inline')
  Quadratic2.read(ByteData data, int offset): this._((
    wgsl.Vec2f.read(data, offset + 0),
    wgsl.Vec2f.read(data, offset + 8),
    wgsl.Vec2f.read(data, offset + 16),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    _.$2.write(data, offset + 8);
    _.$3.write(data, offset + 16);
  }
}

@wgsl.Struct('CubicToQuadsUniforms')
extension type const CubicToQuadsUniforms._((double tolerance, int maxQuadratics, wgsl.Mat4x4f transform) _) {
  static const CubicToQuadsUniforms zero = CubicToQuadsUniforms._((
    0.0,
    0,
    .identity,
  ));

  double get tolerance => _.$1;
  int get maxQuadratics => _.$2;
  wgsl.Mat4x4f get transform => _.$3;

  @pragma('vm:prefer-inline')
  CubicToQuadsUniforms({double tolerance = 0.0, int maxQuadratics = 0, wgsl.Mat4x4f transform = .identity}): this._((
    tolerance,
    maxQuadratics,
    transform,
  ));

  @pragma('vm:prefer-inline')
  CubicToQuadsUniforms.read(ByteData data, int offset): this._((
    wgsl.F32.read(data, offset + 0),
    wgsl.U32.read(data, offset + 4),
    wgsl.Mat4x4f.read(data, offset + 16),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.F32(_.$1).write(data, offset + 0);
    wgsl.U32(_.$2).write(data, offset + 4);
    _.$3.write(data, offset + 16);
  }
}

@wgsl.Struct('ChoppedCubic2')
extension type const ChoppedCubic2._((Cubic2 left, Cubic2 right) _) {
  static const ChoppedCubic2 zero = ChoppedCubic2._((
    .zero,
    .zero,
  ));

  Cubic2 get left => _.$1;
  Cubic2 get right => _.$2;

  @pragma('vm:prefer-inline')
  ChoppedCubic2({Cubic2 left = .zero, Cubic2 right = .zero}): this._((
    left,
    right,
  ));

  @pragma('vm:prefer-inline')
  ChoppedCubic2.read(ByteData data, int offset): this._((
    Cubic2.read(data, offset + 0),
    Cubic2.read(data, offset + 32),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    _.$2.write(data, offset + 32);
  }
}

@wgsl.Struct('Cubic2ChopAtInflectionsResult')
extension type const Cubic2ChopAtInflectionsResult._(((Cubic2, Cubic2, Cubic2) cubics, (double, double, double) t0, (double, double, double) t1, int count) _) {
  static const Cubic2ChopAtInflectionsResult zero = Cubic2ChopAtInflectionsResult._((
    (.zero, .zero, .zero),
    (0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0),
    0,
  ));

  (Cubic2, Cubic2, Cubic2) get cubics => _.$1;
  (double, double, double) get t0 => _.$2;
  (double, double, double) get t1 => _.$3;
  int get count => _.$4;

  @pragma('vm:prefer-inline')
  Cubic2ChopAtInflectionsResult({(Cubic2, Cubic2, Cubic2) cubics = (.zero, .zero, .zero), (double, double, double) t0 = (0.0, 0.0, 0.0), (double, double, double) t1 = (0.0, 0.0, 0.0), int count = 0}): this._((
    cubics,
    t0,
    t1,
    count,
  ));

  @pragma('vm:prefer-inline')
  Cubic2ChopAtInflectionsResult.read(ByteData data, int offset): this._((
    (
      Cubic2.read(data, offset + 0 + 0 * 32),
      Cubic2.read(data, offset + 0 + 1 * 32),
      Cubic2.read(data, offset + 0 + 2 * 32),
    ),
    (
      wgsl.F32.read(data, offset + 96 + 0 * 4),
      wgsl.F32.read(data, offset + 96 + 1 * 4),
      wgsl.F32.read(data, offset + 96 + 2 * 4),
    ),
    (
      wgsl.F32.read(data, offset + 108 + 0 * 4),
      wgsl.F32.read(data, offset + 108 + 1 * 4),
      wgsl.F32.read(data, offset + 108 + 2 * 4),
    ),
    wgsl.U32.read(data, offset + 120),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.$1.write(data, offset + 0 + 0 * 32);
    _.$1.$2.write(data, offset + 0 + 1 * 32);
    _.$1.$3.write(data, offset + 0 + 2 * 32);
    wgsl.F32(_.$2.$1).write(data, offset + 96 + 0 * 4);
    wgsl.F32(_.$2.$2).write(data, offset + 96 + 1 * 4);
    wgsl.F32(_.$2.$3).write(data, offset + 96 + 2 * 4);
    wgsl.F32(_.$3.$1).write(data, offset + 108 + 0 * 4);
    wgsl.F32(_.$3.$2).write(data, offset + 108 + 1 * 4);
    wgsl.F32(_.$3.$3).write(data, offset + 108 + 2 * 4);
    wgsl.U32(_.$4).write(data, offset + 120);
  }
}

@wgsl.Struct('StackItem')
extension type const StackItem._((Cubic2 cubic, double t0, double t1) _) {
  static const StackItem zero = StackItem._((
    .zero,
    0.0,
    0.0,
  ));

  Cubic2 get cubic => _.$1;
  double get t0 => _.$2;
  double get t1 => _.$3;

  @pragma('vm:prefer-inline')
  StackItem({Cubic2 cubic = .zero, double t0 = 0.0, double t1 = 0.0}): this._((
    cubic,
    t0,
    t1,
  ));

  @pragma('vm:prefer-inline')
  StackItem.read(ByteData data, int offset): this._((
    Cubic2.read(data, offset + 0),
    wgsl.F32.read(data, offset + 32),
    wgsl.F32.read(data, offset + 36),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    wgsl.F32(_.$2).write(data, offset + 32);
    wgsl.F32(_.$3).write(data, offset + 36);
  }
}

@wgsl.Struct('QuadBinningUniforms')
extension type const QuadBinningUniforms._((wgsl.Vec2f screenSize, double tileSize, int maxPerTile, int tilesWidth, int tilesHeight, double strokeWidth) _) {
  static const QuadBinningUniforms zero = QuadBinningUniforms._((
    .zero,
    0.0,
    0,
    0,
    0,
    0.0,
  ));

  wgsl.Vec2f get screenSize => _.$1;
  double get tileSize => _.$2;
  int get maxPerTile => _.$3;
  int get tilesWidth => _.$4;
  int get tilesHeight => _.$5;
  double get strokeWidth => _.$6;

  @pragma('vm:prefer-inline')
  QuadBinningUniforms({wgsl.Vec2f screenSize = .zero, double tileSize = 0.0, int maxPerTile = 0, int tilesWidth = 0, int tilesHeight = 0, double strokeWidth = 0.0}): this._((
    screenSize,
    tileSize,
    maxPerTile,
    tilesWidth,
    tilesHeight,
    strokeWidth,
  ));

  @pragma('vm:prefer-inline')
  QuadBinningUniforms.read(ByteData data, int offset): this._((
    wgsl.Vec2f.read(data, offset + 0),
    wgsl.F32.read(data, offset + 8),
    wgsl.U32.read(data, offset + 12),
    wgsl.U32.read(data, offset + 16),
    wgsl.U32.read(data, offset + 20),
    wgsl.F32.read(data, offset + 24),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    wgsl.F32(_.$2).write(data, offset + 8);
    wgsl.U32(_.$3).write(data, offset + 12);
    wgsl.U32(_.$4).write(data, offset + 16);
    wgsl.U32(_.$5).write(data, offset + 20);
    wgsl.F32(_.$6).write(data, offset + 24);
  }
}

@wgsl.Struct('QuadRendererUniforms')
extension type const QuadRendererUniforms._((wgsl.Vec2f screenSize, double tileSize, int maxPerTile, int tilesWidth) _) {
  static const QuadRendererUniforms zero = QuadRendererUniforms._((
    .zero,
    0.0,
    0,
    0,
  ));

  wgsl.Vec2f get screenSize => _.$1;
  double get tileSize => _.$2;
  int get maxPerTile => _.$3;
  int get tilesWidth => _.$4;

  @pragma('vm:prefer-inline')
  QuadRendererUniforms({wgsl.Vec2f screenSize = .zero, double tileSize = 0.0, int maxPerTile = 0, int tilesWidth = 0}): this._((
    screenSize,
    tileSize,
    maxPerTile,
    tilesWidth,
  ));

  @pragma('vm:prefer-inline')
  QuadRendererUniforms.read(ByteData data, int offset): this._((
    wgsl.Vec2f.read(data, offset + 0),
    wgsl.F32.read(data, offset + 8),
    wgsl.U32.read(data, offset + 12),
    wgsl.U32.read(data, offset + 16),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    wgsl.F32(_.$2).write(data, offset + 8);
    wgsl.U32(_.$3).write(data, offset + 12);
    wgsl.U32(_.$4).write(data, offset + 16);
  }
}

@wgsl.Struct('CardanoResult')
extension type const CardanoResult._((double t, double distSq) _) {
  static const CardanoResult zero = CardanoResult._((
    0.0,
    0.0,
  ));

  double get t => _.$1;
  double get distSq => _.$2;

  @pragma('vm:prefer-inline')
  CardanoResult({double t = 0.0, double distSq = 0.0}): this._((
    t,
    distSq,
  ));

  @pragma('vm:prefer-inline')
  CardanoResult.read(ByteData data, int offset): this._((
    wgsl.F32.read(data, offset + 0),
    wgsl.F32.read(data, offset + 4),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.F32(_.$1).write(data, offset + 0);
    wgsl.F32(_.$2).write(data, offset + 4);
  }
}

@wgsl.UniformBufferView('u_cubic_to_quads')
extension type CubicToQuadsUniformsBufferView(ByteData data) {
  static const int sizeInBytes = 80;

  CubicToQuadsUniformsBufferView.create(): this(ByteData(sizeInBytes));

  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static wgpu.BufferDescriptor descriptor({
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(cubic_renderer.wgsl) cubictoquadsuniforms buffer',
    size: sizeInBytes,
    usage: usage ?? .of([.uniform, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(wgpu.Device device, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void write(CubicToQuadsUniforms value) {
    value.write(data, 0);
  }

  CubicToQuadsUniforms read() {
    return CubicToQuadsUniforms.read(data, 0);
  }

  double get tolerance {
    return wgsl.F32.read(data, 0);
  }

  set tolerance(double value) {
    wgsl.F32(value).write(data, 0);
  }

  int get maxQuadratics {
    return wgsl.U32.read(data, 4);
  }

  set maxQuadratics(int value) {
    wgsl.U32(value).write(data, 4);
  }

  wgsl.Mat4x4f get transform {
    return wgsl.Mat4x4f.read(data, 16);
  }

  set transform(wgsl.Mat4x4f value) {
    value.write(data, 16);
  }


  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.UniformBuffer('u_cubic_to_quads')
class CubicToQuadsUniformsBuffer {
  CubicToQuadsUniformsBuffer(wgpu.Device device, {String? label, wgpu.BufferUsage? usage}):
    buffer = CubicToQuadsUniformsBufferView.createBuffer(device, label: label, usage: usage),
    _view = CubicToQuadsUniformsBufferView(ByteData(CubicToQuadsUniformsBufferView.sizeInBytes));

  final wgpu.Buffer buffer;
  final CubicToQuadsUniformsBufferView _view;

  static const int sizeInBytes = CubicToQuadsUniformsBufferView.sizeInBytes;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void write(CubicToQuadsUniforms value) => _view.write(value);
  double get tolerance => _view.tolerance;
  set tolerance(double value) => _view.tolerance = value;
  int get maxQuadratics => _view.maxQuadratics;
  set maxQuadratics(int value) => _view.maxQuadratics = value;
  wgsl.Mat4x4f get transform => _view.transform;
  set transform(wgsl.Mat4x4f value) => _view.transform = value;
  void clear() => _view.clear();
}

@wgsl.UniformBufferView('u_quad_binning')
extension type QuadBinningUniformsBufferView(ByteData data) {
  static const int sizeInBytes = 32;

  QuadBinningUniformsBufferView.create(): this(ByteData(sizeInBytes));

  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static wgpu.BufferDescriptor descriptor({
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(cubic_renderer.wgsl) quadbinninguniforms buffer',
    size: sizeInBytes,
    usage: usage ?? .of([.uniform, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(wgpu.Device device, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void write(QuadBinningUniforms value) {
    value.write(data, 0);
  }

  QuadBinningUniforms read() {
    return QuadBinningUniforms.read(data, 0);
  }

  wgsl.Vec2f get screenSize {
    return wgsl.Vec2f.read(data, 0);
  }

  set screenSize(wgsl.Vec2f value) {
    value.write(data, 0);
  }

  double get tileSize {
    return wgsl.F32.read(data, 8);
  }

  set tileSize(double value) {
    wgsl.F32(value).write(data, 8);
  }

  int get maxPerTile {
    return wgsl.U32.read(data, 12);
  }

  set maxPerTile(int value) {
    wgsl.U32(value).write(data, 12);
  }

  int get tilesWidth {
    return wgsl.U32.read(data, 16);
  }

  set tilesWidth(int value) {
    wgsl.U32(value).write(data, 16);
  }

  int get tilesHeight {
    return wgsl.U32.read(data, 20);
  }

  set tilesHeight(int value) {
    wgsl.U32(value).write(data, 20);
  }

  double get strokeWidth {
    return wgsl.F32.read(data, 24);
  }

  set strokeWidth(double value) {
    wgsl.F32(value).write(data, 24);
  }


  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.UniformBuffer('u_quad_binning')
class QuadBinningUniformsBuffer {
  QuadBinningUniformsBuffer(wgpu.Device device, {String? label, wgpu.BufferUsage? usage}):
    buffer = QuadBinningUniformsBufferView.createBuffer(device, label: label, usage: usage),
    _view = QuadBinningUniformsBufferView(ByteData(QuadBinningUniformsBufferView.sizeInBytes));

  final wgpu.Buffer buffer;
  final QuadBinningUniformsBufferView _view;

  static const int sizeInBytes = QuadBinningUniformsBufferView.sizeInBytes;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void write(QuadBinningUniforms value) => _view.write(value);
  wgsl.Vec2f get screenSize => _view.screenSize;
  set screenSize(wgsl.Vec2f value) => _view.screenSize = value;
  double get tileSize => _view.tileSize;
  set tileSize(double value) => _view.tileSize = value;
  int get maxPerTile => _view.maxPerTile;
  set maxPerTile(int value) => _view.maxPerTile = value;
  int get tilesWidth => _view.tilesWidth;
  set tilesWidth(int value) => _view.tilesWidth = value;
  int get tilesHeight => _view.tilesHeight;
  set tilesHeight(int value) => _view.tilesHeight = value;
  double get strokeWidth => _view.strokeWidth;
  set strokeWidth(double value) => _view.strokeWidth = value;
  void clear() => _view.clear();
}

@wgsl.UniformBufferView('u_quad_renderer')
extension type QuadRendererUniformsBufferView(ByteData data) {
  static const int sizeInBytes = 24;

  QuadRendererUniformsBufferView.create(): this(ByteData(sizeInBytes));

  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static wgpu.BufferDescriptor descriptor({
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(cubic_renderer.wgsl) quadrendereruniforms buffer',
    size: sizeInBytes,
    usage: usage ?? .of([.uniform, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(wgpu.Device device, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void write(QuadRendererUniforms value) {
    value.write(data, 0);
  }

  QuadRendererUniforms read() {
    return QuadRendererUniforms.read(data, 0);
  }

  wgsl.Vec2f get screenSize {
    return wgsl.Vec2f.read(data, 0);
  }

  set screenSize(wgsl.Vec2f value) {
    value.write(data, 0);
  }

  double get tileSize {
    return wgsl.F32.read(data, 8);
  }

  set tileSize(double value) {
    wgsl.F32(value).write(data, 8);
  }

  int get maxPerTile {
    return wgsl.U32.read(data, 12);
  }

  set maxPerTile(int value) {
    wgsl.U32(value).write(data, 12);
  }

  int get tilesWidth {
    return wgsl.U32.read(data, 16);
  }

  set tilesWidth(int value) {
    wgsl.U32(value).write(data, 16);
  }


  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.UniformBuffer('u_quad_renderer')
class QuadRendererUniformsBuffer {
  QuadRendererUniformsBuffer(wgpu.Device device, {String? label, wgpu.BufferUsage? usage}):
    buffer = QuadRendererUniformsBufferView.createBuffer(device, label: label, usage: usage),
    _view = QuadRendererUniformsBufferView(ByteData(QuadRendererUniformsBufferView.sizeInBytes));

  final wgpu.Buffer buffer;
  final QuadRendererUniformsBufferView _view;

  static const int sizeInBytes = QuadRendererUniformsBufferView.sizeInBytes;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void write(QuadRendererUniforms value) => _view.write(value);
  wgsl.Vec2f get screenSize => _view.screenSize;
  set screenSize(wgsl.Vec2f value) => _view.screenSize = value;
  double get tileSize => _view.tileSize;
  set tileSize(double value) => _view.tileSize = value;
  int get maxPerTile => _view.maxPerTile;
  set maxPerTile(int value) => _view.maxPerTile = value;
  int get tilesWidth => _view.tilesWidth;
  set tilesWidth(int value) => _view.tilesWidth = value;
  void clear() => _view.clear();
}

@wgsl.StorageBufferView(['in_cubics'])
extension type Cubic2ArrayBufferView(ByteData data) {
  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static const int stride = 32;
  int get length => data.lengthInBytes ~/ stride;

  Cubic2ArrayBufferView.create(int length): this(ByteData(length * stride));

  static wgpu.BufferDescriptor descriptor(
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(in_cubics) incubics buffer',
    size: length * stride,
    usage: usage ?? .of([.storage, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(
    wgpu.Device device,
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(length, label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void operator []=(int index, Cubic2 value) {
    value.write(data, index * stride);
  }

  Cubic2 operator [](int index) {
    return Cubic2.read(data, index * stride);
  }

  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.StorageBuffer(['in_cubics'])
class Cubic2ArrayBuffer {
  Cubic2ArrayBuffer(wgpu.Device device, this.length, {String? label, wgpu.BufferUsage? usage}):
    buffer = Cubic2ArrayBufferView.createBuffer(device, length, label: label, usage: usage),
    _view = Cubic2ArrayBufferView(ByteData(length * Cubic2ArrayBufferView.stride));

  final int length;
  final wgpu.Buffer buffer;
  final Cubic2ArrayBufferView _view;

  static const int stride = Cubic2ArrayBufferView.stride;
  int get sizeInBytes => length * stride;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void operator []=(int index, Cubic2 value) => _view[index] = value;
  Cubic2 operator [](int index) => _view[index];
  void clear() => _view.clear();
}

@wgsl.StorageBufferView(['out_quadratics, in_quadratics, in_renderer_quadratics'])
extension type Quadratic2ArrayBufferView(ByteData data) {
  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static const int stride = 24;
  int get length => data.lengthInBytes ~/ stride;

  Quadratic2ArrayBufferView.create(int length): this(ByteData(length * stride));

  static wgpu.BufferDescriptor descriptor(
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(out_quadratics, in_quadratics, in_renderer_quadratics) outquadratics buffer',
    size: length * stride,
    usage: usage ?? .of([.storage, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(
    wgpu.Device device,
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(length, label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void operator []=(int index, Quadratic2 value) {
    value.write(data, index * stride);
  }

  Quadratic2 operator [](int index) {
    return Quadratic2.read(data, index * stride);
  }

  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.StorageBuffer(['out_quadratics, in_quadratics, in_renderer_quadratics'])
class Quadratic2ArrayBuffer {
  Quadratic2ArrayBuffer(wgpu.Device device, this.length, {String? label, wgpu.BufferUsage? usage}):
    buffer = Quadratic2ArrayBufferView.createBuffer(device, length, label: label, usage: usage),
    _view = Quadratic2ArrayBufferView(ByteData(length * Quadratic2ArrayBufferView.stride));

  final int length;
  final wgpu.Buffer buffer;
  final Quadratic2ArrayBufferView _view;

  static const int stride = Quadratic2ArrayBufferView.stride;
  int get sizeInBytes => length * stride;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void operator []=(int index, Quadratic2 value) => _view[index] = value;
  Quadratic2 operator [](int index) => _view[index];
  void clear() => _view.clear();
}

@wgsl.StorageBufferView(['out_counter, in_quad_counts'])
extension type U32BufferView(ByteData data) {
  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static const int sizeInBytes = 4;

  U32BufferView.create(): this(ByteData(sizeInBytes));

  static wgpu.BufferDescriptor descriptor({
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(out_counter, in_quad_counts) outcounter buffer',
    size: sizeInBytes,
    usage: usage ?? .of([.storage, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(wgpu.Device device, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void write(int value) {
    wgsl.U32(value).write(data, 0);
  }

  int read() {
    return wgsl.U32.read(data, 0);
  }

  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.StorageBuffer(['out_counter, in_quad_counts'])
class U32Buffer {
  U32Buffer(wgpu.Device device, {String? label, wgpu.BufferUsage? usage}):
    buffer = U32BufferView.createBuffer(device, label: label, usage: usage),
    _view = U32BufferView(ByteData(U32BufferView.sizeInBytes));

  final wgpu.Buffer buffer;
  final U32BufferView _view;

  static const int sizeInBytes = U32BufferView.sizeInBytes;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void write(int value) => _view.write(value);
  int read() => _view.read();
  void clear() => _view.clear();
}

@wgsl.StorageBufferView(['out_tile_counts, out_tile_indices, in_tile_counts, in_tile_indices'])
extension type U32ArrayBufferView(ByteData data) {
  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static const int stride = 4;
  int get length => data.lengthInBytes ~/ stride;

  U32ArrayBufferView.create(int length): this(ByteData(length * stride));

  static wgpu.BufferDescriptor descriptor(
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(out_tile_counts, out_tile_indices, in_tile_counts, in_tile_indices) outtilecounts buffer',
    size: length * stride,
    usage: usage ?? .of([.storage, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(
    wgpu.Device device,
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(length, label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void operator []=(int index, int value) {
    wgsl.U32(value).write(data, index * stride);
  }

  int operator [](int index) {
    return wgsl.U32.read(data, index * stride);
  }

  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.StorageBuffer(['out_tile_counts, out_tile_indices, in_tile_counts, in_tile_indices'])
class U32ArrayBuffer {
  U32ArrayBuffer(wgpu.Device device, this.length, {String? label, wgpu.BufferUsage? usage}):
    buffer = U32ArrayBufferView.createBuffer(device, length, label: label, usage: usage),
    _view = U32ArrayBufferView(ByteData(length * U32ArrayBufferView.stride));

  final int length;
  final wgpu.Buffer buffer;
  final U32ArrayBufferView _view;

  static const int stride = U32ArrayBufferView.stride;
  int get sizeInBytes => length * stride;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void operator []=(int index, int value) => _view[index] = value;
  int operator [](int index) => _view[index];
  void clear() => _view.clear();
}

@wgsl.BindGroupLayoutDescriptor(0)
wgpu.BindGroupLayoutDescriptor get bindGroup0LayoutDescriptor => .new(
  label: '(cubic_renderer.wgsl) bind group 0 layout',
  entries: [
    .new(
      binding: 0,
      visibility: .compute,
      buffer: .new(
        type: .uniform,
        minBindingSize: 80,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 1,
      visibility: .compute,
      buffer: .new(
        type: .readOnlyStorage,
        minBindingSize: 32,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 2,
      visibility: .compute,
      buffer: .new(
        type: .storage,
        minBindingSize: 24,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 3,
      visibility: .compute,
      buffer: .new(
        type: .storage,
        minBindingSize: 4,
        hasDynamicOffset: false,
      ),
    ),
  ],
);

@wgsl.BindGroupLayout(0)
wgpu.BindGroupLayout createBindGroup0Layout(wgpu.Device device) => device.createBindGroupLayout(bindGroup0LayoutDescriptor);

@wgsl.BindGroup(0)
wgpu.BindGroup createBindGroup0Raw(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required wgpu.BufferView uCubicToQuads,
  required wgpu.BufferView inCubics,
  required wgpu.BufferView outQuadratics,
  required wgpu.BufferView outCounter,
  String? label,
}) => device.createBindGroup(.new(
  label: label ?? '(cubic_renderer.wgsl) bind group 0',
  layout: layout,
  entries: [
    .new(
      binding: 0,
      buffer: uCubicToQuads.buffer,
      offset: uCubicToQuads.offset,
      size: uCubicToQuads.size,
    ),
    .new(
      binding: 1,
      buffer: inCubics.buffer,
      offset: inCubics.offset,
      size: inCubics.size,
    ),
    .new(
      binding: 2,
      buffer: outQuadratics.buffer,
      offset: outQuadratics.offset,
      size: outQuadratics.size,
    ),
    .new(
      binding: 3,
      buffer: outCounter.buffer,
      offset: outCounter.offset,
      size: outCounter.size,
    ),
  ],
));

@wgsl.BindGroup(0)
wgpu.BindGroup createBindGroup0(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required CubicToQuadsUniformsBuffer uCubicToQuads,
  required Cubic2ArrayBuffer inCubics,
  required Quadratic2ArrayBuffer outQuadratics,
  required U32Buffer outCounter,
}) => createBindGroup0Raw(
  device,
  layout,
  uCubicToQuads: uCubicToQuads.bufferView,
  inCubics: inCubics.bufferView,
  outQuadratics: outQuadratics.bufferView,
  outCounter: outCounter.bufferView,
);

@wgsl.BindGroupLayoutDescriptor(1)
wgpu.BindGroupLayoutDescriptor get bindGroup1LayoutDescriptor => .new(
  label: '(cubic_renderer.wgsl) bind group 1 layout',
  entries: [
    .new(
      binding: 0,
      visibility: .compute,
      buffer: .new(
        type: .uniform,
        minBindingSize: 32,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 1,
      visibility: .compute,
      buffer: .new(
        type: .readOnlyStorage,
        minBindingSize: 24,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 2,
      visibility: .compute,
      buffer: .new(
        type: .readOnlyStorage,
        minBindingSize: 4,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 3,
      visibility: .compute,
      buffer: .new(
        type: .storage,
        minBindingSize: 4,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 4,
      visibility: .compute,
      buffer: .new(
        type: .storage,
        minBindingSize: 4,
        hasDynamicOffset: false,
      ),
    ),
  ],
);

@wgsl.BindGroupLayout(1)
wgpu.BindGroupLayout createBindGroup1Layout(wgpu.Device device) => device.createBindGroupLayout(bindGroup1LayoutDescriptor);

@wgsl.BindGroup(1)
wgpu.BindGroup createBindGroup1Raw(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required wgpu.BufferView uQuadBinning,
  required wgpu.BufferView inQuadratics,
  required wgpu.BufferView inQuadCounts,
  required wgpu.BufferView outTileCounts,
  required wgpu.BufferView outTileIndices,
  String? label,
}) => device.createBindGroup(.new(
  label: label ?? '(cubic_renderer.wgsl) bind group 1',
  layout: layout,
  entries: [
    .new(
      binding: 0,
      buffer: uQuadBinning.buffer,
      offset: uQuadBinning.offset,
      size: uQuadBinning.size,
    ),
    .new(
      binding: 1,
      buffer: inQuadratics.buffer,
      offset: inQuadratics.offset,
      size: inQuadratics.size,
    ),
    .new(
      binding: 2,
      buffer: inQuadCounts.buffer,
      offset: inQuadCounts.offset,
      size: inQuadCounts.size,
    ),
    .new(
      binding: 3,
      buffer: outTileCounts.buffer,
      offset: outTileCounts.offset,
      size: outTileCounts.size,
    ),
    .new(
      binding: 4,
      buffer: outTileIndices.buffer,
      offset: outTileIndices.offset,
      size: outTileIndices.size,
    ),
  ],
));

@wgsl.BindGroup(1)
wgpu.BindGroup createBindGroup1(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required QuadBinningUniformsBuffer uQuadBinning,
  required Quadratic2ArrayBuffer inQuadratics,
  required U32Buffer inQuadCounts,
  required U32ArrayBuffer outTileCounts,
  required U32ArrayBuffer outTileIndices,
}) => createBindGroup1Raw(
  device,
  layout,
  uQuadBinning: uQuadBinning.bufferView,
  inQuadratics: inQuadratics.bufferView,
  inQuadCounts: inQuadCounts.bufferView,
  outTileCounts: outTileCounts.bufferView,
  outTileIndices: outTileIndices.bufferView,
);

@wgsl.BindGroupLayoutDescriptor(2)
wgpu.BindGroupLayoutDescriptor get bindGroup2LayoutDescriptor => .new(
  label: '(cubic_renderer.wgsl) bind group 2 layout',
  entries: [
    .new(
      binding: 0,
      visibility: .fragment,
      buffer: .new(
        type: .uniform,
        minBindingSize: 24,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 1,
      visibility: .fragment,
      buffer: .new(
        type: .readOnlyStorage,
        minBindingSize: 24,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 2,
      visibility: .fragment,
      buffer: .new(
        type: .readOnlyStorage,
        minBindingSize: 4,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 3,
      visibility: .fragment,
      buffer: .new(
        type: .readOnlyStorage,
        minBindingSize: 4,
        hasDynamicOffset: false,
      ),
    ),
  ],
);

@wgsl.BindGroupLayout(2)
wgpu.BindGroupLayout createBindGroup2Layout(wgpu.Device device) => device.createBindGroupLayout(bindGroup2LayoutDescriptor);

@wgsl.BindGroup(2)
wgpu.BindGroup createBindGroup2Raw(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required wgpu.BufferView uQuadRenderer,
  required wgpu.BufferView inRendererQuadratics,
  required wgpu.BufferView inTileCounts,
  required wgpu.BufferView inTileIndices,
  String? label,
}) => device.createBindGroup(.new(
  label: label ?? '(cubic_renderer.wgsl) bind group 2',
  layout: layout,
  entries: [
    .new(
      binding: 0,
      buffer: uQuadRenderer.buffer,
      offset: uQuadRenderer.offset,
      size: uQuadRenderer.size,
    ),
    .new(
      binding: 1,
      buffer: inRendererQuadratics.buffer,
      offset: inRendererQuadratics.offset,
      size: inRendererQuadratics.size,
    ),
    .new(
      binding: 2,
      buffer: inTileCounts.buffer,
      offset: inTileCounts.offset,
      size: inTileCounts.size,
    ),
    .new(
      binding: 3,
      buffer: inTileIndices.buffer,
      offset: inTileIndices.offset,
      size: inTileIndices.size,
    ),
  ],
));

@wgsl.BindGroup(2)
wgpu.BindGroup createBindGroup2(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required QuadRendererUniformsBuffer uQuadRenderer,
  required Quadratic2ArrayBuffer inRendererQuadratics,
  required U32ArrayBuffer inTileCounts,
  required U32ArrayBuffer inTileIndices,
}) => createBindGroup2Raw(
  device,
  layout,
  uQuadRenderer: uQuadRenderer.bufferView,
  inRendererQuadratics: inRendererQuadratics.bufferView,
  inTileCounts: inTileCounts.bufferView,
  inTileIndices: inTileIndices.bufferView,
);

@wgsl.ComputeState('cs_cubic_to_quads')
wgpu.ComputeState createCsCubicToQuadsComputeState(
  wgpu.ShaderModule module, {
  Overrides? overrides,
}) => wgpu.ComputeState(
  module: module,
  entryPoint: 'cs_cubic_to_quads',
  constants: overrides?.entries ?? const [],
);

@wgsl.ComputeState('cs_quad_binning')
wgpu.ComputeState createCsQuadBinningComputeState(
  wgpu.ShaderModule module, {
  Overrides? overrides,
}) => wgpu.ComputeState(
  module: module,
  entryPoint: 'cs_quad_binning',
  constants: overrides?.entries ?? const [],
);

@wgsl.VertexState('vs_quad_renderer')
wgpu.VertexState createVsQuadRendererVertexState(
  wgpu.ShaderModule module, {
  Overrides? overrides,
  List<wgpu.VertexBufferLayout>? vertexBuffers,
}) => wgpu.VertexState(
  module: module,
  entryPoint: 'vs_quad_renderer',
  constants: overrides?.entries ?? const [],
  buffers: vertexBuffers ?? const [],
);

@wgsl.FragmentState('fs_quad_renderer')
wgpu.FragmentState createFsQuadRendererFragmentState(
  wgpu.ShaderModule module,
  List<wgpu.ColorTargetState> targets, {
  Overrides? overrides,
}) => wgpu.FragmentState(
  module: module,
  entryPoint: 'fs_quad_renderer',
  constants: overrides?.entries ?? const [],
  targets: targets,
);

@wgsl.PipelineLayout('cubic_renderer.wgsl (CsCubicToQuads)')
wgpu.PipelineLayout createCsCubicToQuadsPipelineLayout(
 wgpu.Device device, {
  wgpu.BindGroupLayout? group0,
}) => device.createPipelineLayout(.new(
  label: '(CsCubicToQuads) CsCubicToQuads pipeline layout',
  bindGroupLayouts: [
    group0 ?? device.createBindGroupLayout(bindGroup0LayoutDescriptor),
  ],
));

@wgsl.ComputePipeline('cs_cubic_to_quads')
wgpu.ComputePipeline createCsCubicToQuadsPipeline(
  wgpu.Device device,
  wgpu.ShaderModule module, {
  wgpu.PipelineLayout? layout,
  Overrides? overrides,
}) => device.createComputePipeline(.new(
  label: '(cubic_renderer.wgsl) cs_cubic_to_quads compute pipeline',
  layout: layout ?? createCsCubicToQuadsPipelineLayout(device),
  compute: createCsCubicToQuadsComputeState(module, overrides: overrides),
));

@wgsl.PipelineLayout('cubic_renderer.wgsl (CsQuadBinning)')
wgpu.PipelineLayout createCsQuadBinningPipelineLayout(
 wgpu.Device device, {
  wgpu.BindGroupLayout? group1,
}) => device.createPipelineLayout(.new(
  label: '(CsQuadBinning) CsQuadBinning pipeline layout',
  bindGroupLayouts: [
    _emptyLayout ??= device.createBindGroupLayout(.new(label: 'empty')),
    group1 ?? device.createBindGroupLayout(bindGroup1LayoutDescriptor),
  ],
));

wgpu.BindGroupLayout? _emptyLayout;

@wgsl.ComputePipeline('cs_quad_binning')
wgpu.ComputePipeline createCsQuadBinningPipeline(
  wgpu.Device device,
  wgpu.ShaderModule module, {
  wgpu.PipelineLayout? layout,
  Overrides? overrides,
}) => device.createComputePipeline(.new(
  label: '(cubic_renderer.wgsl) cs_quad_binning compute pipeline',
  layout: layout ?? createCsQuadBinningPipelineLayout(device),
  compute: createCsQuadBinningComputeState(module, overrides: overrides),
));

@wgsl.PipelineLayout('cubic_renderer.wgsl (VsQuadRenderer - FsQuadRenderer)')
wgpu.PipelineLayout createVsQuadRendererFsQuadRendererPipelineLayout(
 wgpu.Device device, {
  wgpu.BindGroupLayout? group2,
}) => device.createPipelineLayout(.new(
  label: '(VsQuadRenderer - FsQuadRenderer) VsQuadRendererFsQuadRenderer pipeline layout',
  bindGroupLayouts: [
    _emptyLayout ??= device.createBindGroupLayout(.new(label: 'empty')),
    _emptyLayout ??= device.createBindGroupLayout(.new(label: 'empty')),
    group2 ?? device.createBindGroupLayout(bindGroup2LayoutDescriptor),
  ],
));

@wgsl.RenderPipeline('vs_quad_renderer', 'fs_quad_renderer')
wgpu.RenderPipeline createVsQuadRendererFsQuadRendererRenderPipeline(
  wgpu.Device device,
  wgpu.ShaderModule module,
  List<wgpu.ColorTargetState> targets, {
  wgpu.PipelineLayout? layout,
  Overrides? overrides,
  wgpu.PrimitiveState primitive = const wgpu.PrimitiveState(),
  wgpu.MultisampleState multisample = const wgpu.MultisampleState(),
  wgpu.DepthStencilState? depthStencil,
  List<wgpu.VertexBufferLayout>? vertexBuffers,
}) => device.createRenderPipeline(.new(
  label: '(cubic_renderer.wgsl) vs_quad_renderer-fs_quad_renderer render pipeline',
  layout: layout ?? createVsQuadRendererFsQuadRendererPipelineLayout(device),
  vertex: createVsQuadRendererVertexState(module, overrides: overrides, vertexBuffers: vertexBuffers),
  fragment: createFsQuadRendererFragmentState(module, targets, overrides: overrides),
  primitive: primitive,
  multisample: multisample,
  depthStencil: depthStencil,
));

@wgsl.ShaderSource('cubic_renderer.wgsl')
const String _shaderSource = r'''
struct Cubic2 {
  p0: vec2f,
  p1: vec2f,
  p2: vec2f,
  p3: vec2f,
};

struct Quadratic2 {
  p0: vec2f,
  p1: vec2f,
  p2: vec2f,
};

const PI = 3.141592653589;
const TWO_PI = 2.0 * PI;

// #region cubic_to_quads

struct CubicToQuadsUniforms {
  tolerance: f32,
  max_quadratics: u32,
  _pad1: u32,
  _pad2: u32,
  transform: mat4x4f,
}

@group(0) @binding(0) var<uniform> u_cubic_to_quads: CubicToQuadsUniforms;
@group(0) @binding(1) var<storage, read> in_cubics: array<Cubic2>;
@group(0) @binding(2) var<storage, read_write> out_quadratics: array<Quadratic2>;
@group(0) @binding(3) var<storage, read_write> out_counter: atomic<u32>;


fn vec2f_cross(a: vec2f, b: vec2f) -> f32 { return a.x * b.y - a.y * b.x; }

fn cubic2_eval_pos_tan(c: Cubic2, t: f32) -> vec4f {
  let mt = 1.0 - t;
  let mt2 = mt * mt;
  let t2 = t * t;

  let p = c.p0 * (mt2 * mt) + c.p1 * (3.0 * mt2 * t) + c.p2 * (3.0 * mt * t2) + c.p3 * (t2 * t);
  let d = (c.p1 - c.p0) * (3.0 * mt2) + (c.p2 - c.p1) * (6.0 * mt * t) + (c.p3 - c.p2) * (3.0 * t2);

  return vec4f(p, d);
}

struct ChoppedCubic2 {
  left: Cubic2,
  right: Cubic2,
};

fn cubic2_chop_at(c: Cubic2, t: f32) -> ChoppedCubic2 {
  let p01 = mix(c.p0, c.p1, t);
  let p12 = mix(c.p1, c.p2, t);
  let p23 = mix(c.p2, c.p3, t);

  let p012 = mix(p01, p12, t);
  let p123 = mix(p12, p23, t);

  let p0123 = mix(p012, p123, t);

  var out: ChoppedCubic2;
  out.left = Cubic2(c.p0, p01, p012, p0123);
  out.right = Cubic2(p0123, p123, p23, c.p3);
  return out;
}

fn cubic2_chop_at_half(c: Cubic2) -> ChoppedCubic2 { return cubic2_chop_at(c, 0.5); }

fn cubic2_find_inflections(c: Cubic2, out_t: ptr<function, vec2f>) -> u32 {
  let A = c.p1 - c.p0;
  let B = c.p2 - 2.0 * c.p1 + c.p0;
  let C = c.p3 - 3.0 * c.p2 + 3.0 * c.p1 - c.p0;

  let a = vec2f_cross(B, C);
  let b = vec2f_cross(A, C);
  let c_coeff = vec2f_cross(A, B);

  var roots_found = 0u;
  var roots = vec2f(-1.0, -1.0);

  if (abs(a) < 1.0e-5) {
    if (abs(b) > 1.0e-5) {
      let t = -c_coeff / b;
      if (t > 1.0e-4 && t < 1.0 - 1.0e-4) {
        roots[0] = t;
        roots_found = 1u;
      }
    }
  }
  else {
    let disc = b * b - 4.0 * a * c_coeff;
    if (disc >= 0.0) {
      let sqrt_disc = sqrt(disc);
      let t1 = (-b + sqrt_disc) / (2.0 * a);
      let t2 = (-b - sqrt_disc) / (2.0 * a);

      if (t1 > 1.0e-4 && t1 < 1.0 - 1.0e-4) {
        roots[roots_found] = t1;
        roots_found = roots_found + 1u;
      }

      if (t2 > 1.0e-4 && t2 < 1.0 - 1.0e-4) {
        roots[roots_found] = t2;
        roots_found = roots_found + 1u;
      }
    }
  }

  if (roots_found == 2u && roots[0] > roots[1]) {
    let temp = roots[0];
    roots[0] = roots[1];
    roots[1] = temp;
  }

  *out_t = roots;
  return roots_found;
}

struct Cubic2ChopAtInflectionsResult {
  cubics: array<Cubic2, 3>,
  t0: array<f32, 3>,
  t1: array<f32, 3>,
  count: u32,
}

fn cubic2_chop_at_inflections(c: Cubic2) -> Cubic2ChopAtInflectionsResult {
  var out: Cubic2ChopAtInflectionsResult;
  
  var inflection_ts: vec2f;
  let inflection_count = cubic2_find_inflections(c, &inflection_ts);

  if (inflection_count == 0u) {
    out.cubics[0] = c;
    out.t0[0] = 0.0;
    out.t1[0] = 1.0;
    out.count = 1u;
  }
  else if (inflection_count == 1u) {
    let t1 = inflection_ts[0];
    let chopped = cubic2_chop_at(c, t1);

    out.cubics[0] = chopped.left;
    out.t0[0] = 0.0;
    out.t1[0] = t1;

    out.cubics[1] = chopped.right;
    out.t0[1] = t1;
    out.t1[1] = 1.0;

    out.count = 2u;
  }
  else if (inflection_count == 2u) {
    let t1 = inflection_ts[0];
    let t2 = inflection_ts[1];
    
    let chopped1 = cubic2_chop_at(c, t1);
    out.cubics[0] = chopped1.left;
    out.t0[0] = 0.0;
    out.t1[0] = t1;

    let local_t2 = (t2 - t1) / (1.0 - t1);
    let chopped2 = cubic2_chop_at(chopped1.right, local_t2);
    out.cubics[1] = chopped2.left;
    out.t0[1] = t1;
    out.t1[1] = t2;

    out.cubics[2] = chopped2.right;
    out.t0[2] = t2;
    out.t1[2] = 1.0;

    out.count = 3u;
  }

  return out;
}

struct StackItem {
  cubic: Cubic2,
  t0: f32,
  t1: f32,
};

@compute @workgroup_size(64)
fn cs_cubic_to_quads(@builtin(global_invocation_id) id: vec3u) {
  let index = id.x;
  if (index >= arrayLength(&in_cubics)) { return; }

  let tolerance = u_cubic_to_quads.tolerance;
  let max_quadratics = u_cubic_to_quads.max_quadratics;
  let transform = u_cubic_to_quads.transform;

  var initial_cubic = in_cubics[index];
  initial_cubic.p0 = (transform * vec4f(initial_cubic.p0, 0.0, 1.0)).xy;
  initial_cubic.p1 = (transform * vec4f(initial_cubic.p1, 0.0, 1.0)).xy;
  initial_cubic.p2 = (transform * vec4f(initial_cubic.p2, 0.0, 1.0)).xy;
  initial_cubic.p3 = (transform * vec4f(initial_cubic.p3, 0.0, 1.0)).xy;

  var stack: array<StackItem, 16>;
  var stack_ptr = 0u;

  let chopped_res = cubic2_chop_at_inflections(initial_cubic);
  for (var i = chopped_res.count; i > 0u; i--) {
    let idx = i - 1u;
    stack[stack_ptr] = StackItem(chopped_res.cubics[idx], chopped_res.t0[idx], chopped_res.t1[idx]);
    stack_ptr++;
  }

  while (stack_ptr > 0u) {
    stack_ptr--;
    let item = stack[stack_ptr];
    let c = item.cubic;

    let eval0 = cubic2_eval_pos_tan(c, 0.0);
    let eval1 = cubic2_eval_pos_tan(c, 1.0);
    let tan0 = eval0.zw;
    let tan1 = eval1.zw;

    var q1: vec2f;
    let det = vec2f_cross(tan0, tan1);
    if (abs(det) < 1.0e-5) {
      q1 = mix(c.p0, c.p3, 0.5);
    }
    else {
      let d = c.p3 - c.p0;
      let t = vec2f_cross(d, tan1) / det;
      q1 = c.p0 + tan0 * t;
    }

    let quad_mid = (c.p0 + q1 * 2.0 + c.p3) * 0.25;
    let cubic_mid = cubic2_eval_pos_tan(c, 0.5).xy;

    let err = length(quad_mid - cubic_mid);
    if (err <= tolerance) {
      let out_idx = atomicAdd(&out_counter, 1u);
      if (out_idx < max_quadratics) {
        let quad: Quadratic2 = Quadratic2(c.p0, q1, c.p3);
        out_quadratics[out_idx] = quad;
      }
    }
    else {
      if (stack_ptr + 2u <= 16u) {
        let chopped = cubic2_chop_at_half(c);
        let t_mid = (item.t0 + item.t1) * 0.5;

        stack[stack_ptr] = StackItem(chopped.right, t_mid, item.t1);
        stack_ptr++;
        stack[stack_ptr] = StackItem(chopped.left, item.t0, t_mid);
        stack_ptr++;
      }
      else {
        // fallback
        let out_idx = atomicAdd(&out_counter, 1u);
        if (out_idx < max_quadratics) {
          let quad: Quadratic2 = Quadratic2(c.p0, q1, c.p3);
          out_quadratics[out_idx] = quad;
        }
      }
    }
  }
}

// #endregion

// #region quad_binning

struct QuadBinningUniforms {
  screen_size: vec2f,
  tile_size: f32,
  max_per_tile: u32,
  tiles_width: u32,
  tiles_height: u32,
  stroke_width: f32,
};

@group(1) @binding(0) var<uniform> u_quad_binning: QuadBinningUniforms;
@group(1) @binding(1) var<storage, read> in_quadratics: array<Quadratic2>;
@group(1) @binding(2) var<storage, read> in_quad_counts: u32;
@group(1) @binding(3) var<storage, read_write> out_tile_counts: array<atomic<u32>>;
@group(1) @binding(4) var<storage, read_write> out_tile_indices: array<u32>;

@compute @workgroup_size(64)
fn cs_quad_binning(@builtin(global_invocation_id) id: vec3u) {
  let quad_id = id.x;
  if (quad_id >= in_quad_counts) { return; }

  let quad = in_quadratics[quad_id];

  let screen_size = u_quad_binning.screen_size;
  let tile_size = u_quad_binning.tile_size;
  let max_per_tile = u_quad_binning.max_per_tile;
  let tiles_width = u_quad_binning.tiles_width;
  let tiles_height = u_quad_binning.tiles_height;
  let stroke_width = u_quad_binning.stroke_width;

  var min_p = min(quad.p0, min(quad.p1, quad.p2));
  var max_p = max(quad.p0, max(quad.p1, quad.p2));
  
  min_p = min_p - vec2f(stroke_width);
  max_p = max_p + vec2f(stroke_width);

  let min_tile_x = u32(clamp(floor(min_p.x / tile_size), 0.0, f32(tiles_width - 1)));
  let max_tile_x = u32(clamp(floor(max_p.x / tile_size), 0.0, f32(tiles_width - 1)));
  let min_tile_y = u32(clamp(floor(min_p.y / tile_size), 0.0, f32(tiles_height - 1)));
  let max_tile_y = u32(clamp(floor(max_p.y / tile_size), 0.0, f32(tiles_height - 1)));

  for (var y = min_tile_y; y <= max_tile_y; y++) {
    for (var x = min_tile_x; x <= max_tile_x; x++) {
      let tile_index = y * tiles_width + x;
      let slot = atomicAdd(&out_tile_counts[tile_index], 1u);
      if (slot < max_per_tile) {
        let address = tile_index * max_per_tile + slot;
        out_tile_indices[address] = quad_id;
      }
    }
  }
}

// #endregion

// #region quad_renderer

struct QuadRendererUniforms {
  screen_size: vec2f,
  tile_size: f32,
  max_per_tile: u32,
  tiles_width: u32,
};

@group(2) @binding(0) var<uniform> u_quad_renderer: QuadRendererUniforms;
@group(2) @binding(1) var<storage, read> in_renderer_quadratics: array<Quadratic2>;
@group(2) @binding(2) var<storage, read> in_tile_counts: array<u32>;
@group(2) @binding(3) var<storage, read> in_tile_indices: array<u32>;


struct VertexOutput {
  @builtin(position) position: vec4f,
};

@vertex
fn vs_quad_renderer(@builtin(vertex_index) index: u32) -> VertexOutput {
  let pos = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );

  var output: VertexOutput;
  output.position = vec4f(pos[index], 0.0, 1.0);
  return output;
}


fn bezier_pt(t: f32, p0: vec2f, p1: vec2f, p2: vec2f) -> vec2f {
  let mt = 1.0 - t;
  return mt * mt * p0 + 2.0 * mt * t * p1 + t * t * p2;
}

fn cbrt(x: f32) -> f32 {
  return sign(x) * pow(abs(x), 1.0 / 3.0);
}

struct CardanoResult {
  t: f32,
  dist_sq: f32,
}

fn solve_cardano(q: vec2f, p0: vec2f, p1: vec2f, p2: vec2f) -> CardanoResult {
  let A = p1 - p0;
  let B = p2 - 2.0 * p1 + p0;
  let C = p0 - q;

  let a = dot(B, B);
  let b = 3.0 * dot(A, B);
  let c = 2.0 * dot(A, A) + dot(C, B);
  let d = dot(A, C);

  if (abs(a) < 1.0e-6) {
    let line_dir = p2 - p0;
    let line_len_sq = dot(line_dir, line_dir);
    if (line_len_sq < 1.0e-6) {
      let dist_sq = dot(p0 - q, p0 - q);
      return CardanoResult(0.0, dist_sq);
    }
    else {
      let t = clamp(dot(q - p0, line_dir) / line_len_sq, 0.0, 1.0);
      let pt = p0 + t * line_dir;
      let dist_sq = dot(pt - q, pt - q);
      return CardanoResult(t, dist_sq);
    }
  }

  let nb = b / a;
  let nc = c / a;
  let nd = d / a;

  let p = nc - (nb * nb) / 3.0;
  let q_coeff = nd - (nb * nc) / 3.0 + (2.0 * nb * nb * nb) / 27.0;
  let disc = (q_coeff * q_coeff) / 4.0 + (p * p * p) / 27.0;

  var t_candidates = vec3f(-1.0, -1.0, -1.0);
  var t_count = 0u;

  if (disc > 0.0) {
    let root = sqrt(disc);
    let u_val = cbrt(-q_coeff / 2.0 + root);
    let v_val = cbrt(-q_coeff / 2.0 - root);
    t_candidates[0] = u_val + v_val - nb / 3.0;
    t_count = 1u;
  }
  else {
    let r = 2.0 * sqrt(-p / 3.0);
    let k = clamp(-q_coeff / (2.0 * sqrt(-p * p * p / 27.0)), -1.0, 1.0);

    let acos_k = acos(k);
    let boff = nb / 3.0;

    t_candidates[0] = r * cos(acos_k / 3.0) - boff;
    t_candidates[1] = r * cos((acos_k + TWO_PI) / 3.0) - boff;
    t_candidates[2] = r * cos((acos_k - TWO_PI) / 3.0) - boff;
    t_count = 3u;
  }

  var best_t = 0.0;
  var min_dist_sq = 1.0e20;

  for (var i = 0u; i < t_count; i++) {
    let clamped_t = clamp(t_candidates[i], 0.0, 1.0);
    let pt = bezier_pt(clamped_t, p0, p1, p2);

    let dist_sq = dot(pt - q, pt - q);
    if (dist_sq < min_dist_sq) {
      min_dist_sq = dist_sq;
      best_t = clamped_t;
    }
  }

  let d0 = dot(p0 - q, p0 - q);
  if (d0 < min_dist_sq) { min_dist_sq = d0; best_t = 0.0; }

  let d2 = dot(p2 - q, p2 - q);
  if (d2 < min_dist_sq) { min_dist_sq = d2; best_t = 1.0; }

  return CardanoResult(best_t, min_dist_sq);
}

@fragment
fn fs_quad_renderer(in: VertexOutput) -> @location(0) vec4f {
  let frag_world = in.position.xy;

  let screen_size = u_quad_renderer.screen_size;
  let tile_size = u_quad_renderer.tile_size;
  let max_per_tile = u_quad_renderer.max_per_tile;
  let tiles_width = u_quad_renderer.tiles_width;

  let tile_x = u32(frag_world.x / tile_size);
  let tile_y = u32(frag_world.y / tile_size);
  let tile_index = tile_y * tiles_width + tile_x;

  let count = min(in_tile_counts[tile_index], max_per_tile);
  if (count == 0u) { discard; }

  var min_sdf = 1.0e20;
  for (var i = 0u; i < count; i++) {
    let address = tile_index * max_per_tile + i;
    let quad_id = in_tile_indices[address];
    let quad = in_renderer_quadratics[quad_id];

    let result = solve_cardano(frag_world, quad.p0, quad.p1, quad.p2);
    let t = result.t;
    let dist = sqrt(result.dist_sq);

    let sdf = dist;
    min_sdf = min(min_sdf, sdf);
  }

  let coverage = 1.0 - smoothstep(-0.5, 0.5, min_sdf);
  if (coverage <= 0.0) { discard; }

  return vec4f(1.0, 1.0, 1.0, coverage);
}

// #endregion

''';

@wgsl.ShaderModule('cubic_renderer.wgsl')
wgpu.ShaderModule createShaderModule(wgpu.Device device) => device.createShaderModule(.new(
  label: '(cubic_renderer.wgsl) module',
  next: const wgpu.ShaderSourceWGSL(code: _shaderSource),
));