syntax = "proto3";

package motif;

import "core/program/program.proto";

message SceneInfo {
  string id         = 1;
  string title      = 2;
  int64  updated_at = 3;
  bool   managed    = 4;
}

message Client {
  string id = 1;
}

message ListScenesResponse {
  repeated SceneInfo scenes = 1;
}

message CreateSceneRequest {
  optional Program program = 1;
  optional string  title   = 2;
}

message CreateSceneResponse {
  SceneInfo info    = 1;
  Program   program = 2;
}

message GetSceneRequest {
  string id = 1;
}

message GetSceneResponse {
  SceneInfo info    = 1;
  Program   program = 2;
}

message ClientPresence {
  Client          client           = 1;
  optional Vec2   pointer_position = 2;
  optional string pointer_type     = 3;
}

message ClientDelta {
  ProgramDelta delta  = 1;
  Client       client = 2;
}

message SceneInfoUpdate {
  SceneInfo info = 1;
}

message Snapshot {
  Program                 program = 1;
  repeated ClientPresence clients = 2;
}

message ClientEvent {
  oneof event {
    ClientPresence presence = 1;
    ClientDelta    delta    = 2;
  }
}

message ServerEvent {
  oneof event {
    Snapshot        snapshot   = 1;
    ClientPresence  presence   = 2;
    ClientDelta     delta      = 3;
    Client          left       = 4;
    SceneInfoUpdate scene_info = 5;
  }
}