name: app
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  stack_ffi:
  stack_window_manager:

  editor:

  skia:
  shared:
  ui:

  metal_capture_util:
    path: ../../metal_capture_util
