name: program
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  shared:
  geometry:
  kernel:
  asset:
  color:
  blueprint:
  schema:
  skia:

dev_dependencies:
  test: ^1.31.2