// ignore_for_file: avoid_print

import 'types.dart';

part 'generator/bindings/bind_group_layout_generator.dart';
part 'generator/bindings/bind_group_generator.dart';
part 'generator/functions/compute_state_generator.dart';
part 'generator/functions/fragment_state_generator.dart';
part 'generator/functions/vertex_buffer_generator.dart';
part 'generator/functions/vertex_buffer_layout_generator.dart';
part 'generator/functions/vertex_state_generator.dart';

part 'generator/pipelines/compute_pipeline_generator.dart';
part 'generator/pipelines/pipeline_bindings_generator.dart';
part 'generator/pipelines/pipeline_layout_generator.dart';
part 'generator/pipelines/render_pipeline_generator.dart';

part 'generator/misc/overrides_generator.dart';
part 'generator/misc/shader_module_generator.dart';

part 'generator/array_generator.dart';
part 'generator/storage_generator.dart';
part 'generator/struct_generator.dart';
part 'generator/uniform_generator.dart';

part 'templates/buffer_view_templates.dart';
part 'templates/meta_templates.dart';

part 'utils/array_utils.dart';
part 'utils/function_utils.dart';
part 'utils/member_utils.dart';
part 'utils/override_utils.dart';
part 'utils/string_utils.dart';
part 'utils/struct_utils.dart';
part 'utils/type_utils.dart';
part 'utils/variable_utils.dart';

String _module = '';

List<String> generate(String name, String source, WgslReflectionInfo info) {
  _module = name;

  final lines = <String>[];

  lines.addAll([
    '// GENERATED CODE - DO NOT MODIFY BY HAND',
    '//',
    '// Generated by wgslgen',
    '',
    'import \'dart:typed_data\';',
    'import \'package:wgpu/wgpu.dart\' as wgpu;',
    'import \'package:wgpu/wgsl.dart\' as wgsl;',
    'import \'package:wgpu/wgsl_meta.dart\' as meta;',
    '',
  ]);

  lines.addAll(generateOverrides(info.overrides));
  lines.add('');

  // Stores bindings by group and binding number.
  final groups = <int, Map<int, VariableInfo>>{};
  void _addBinding(VariableInfo info) {
    groups[info.group] ??= {};
    final group = groups[info.group]!;
    if (group.containsKey(info.binding)) {
      throw Exception('Duplicate binding: @group(${info.group}), @binding(${info.binding})');
    }

    group[info.binding] = info;
  }

  var needsReadbackHelper = false;

  // Parse for array types and generate their typedefs
  final _arrayTypes = <String, ArrayInfo>{};
  void _checkArrayTypes(TypeInfo type) {
    if (type.isArray) {
      _arrayTypes[type.dartName] = type.asArray;
    }
    if (type.isStruct) {
      for (final member in type.asStruct.members) {
        _checkArrayTypes(member.type);
      }
    }
  }

  for (final s in info.structs) _checkArrayTypes(s);
  for (final s in [...info.storages, ...info.uniforms]) {
    if (s.resourceType == .storage) needsReadbackHelper = true;
    _checkArrayTypes(s.type);
  }

  if (needsReadbackHelper) {
    lines.addAll(_readbackHelper());
    lines.add('');
  }

  for (final array in _arrayTypes.values) {
    lines.addAll(generateArray(array));
    lines.add('');
  }

  for (final struct in info.structs) {
    if (struct.isVertexIOStruct) {
      print('skipping struct ${struct.name}: potentially vertex input or output struct.');
      continue;
    }

    lines.addAll(generateStruct(struct));
    lines.add('');
  }

  final _uniqueUniforms = <String, List<VariableInfo>>{};
  for (final uniform in info.uniforms) {
    _addBinding(uniform);
    _uniqueUniforms[uniform.type.dartName] ??= [];
    _uniqueUniforms[uniform.type.dartName]!.add(uniform);
  }

  for (final uniform in _uniqueUniforms.keys) {
    final variables = _uniqueUniforms[uniform]!;
    final variableNames = variables.map((v) => v.name).toList();
    lines.addAll(generateUniform(variables.first, variables: variableNames));
    lines.add('');
  }

  final _uniqueStorages = <String, List<VariableInfo>>{};
  for (final storage in info.storages) {
    _addBinding(storage);
    if (storage.resourceType != .storage) continue;
    _uniqueStorages[storage.type.dartName] ??= [];
    _uniqueStorages[storage.type.dartName]!.add(storage);
  }

  for (final storage in _uniqueStorages.keys) {
    final variables = _uniqueStorages[storage]!;
    final variableNames = variables.map((v) => v.name).toList();
    lines.addAll(generateStorage(variables.first, variables: variableNames));
    lines.add('');
  }

  for (final sampler in info.samplers) _addBinding(sampler);
  for (final texture in info.textures) _addBinding(texture);

  for (final group in groups.entries) {
    final groupId = group.key;
    final bindings = group.value;

    lines.addAll(generateBindGroupLayout(groupId, info.entry, bindings));
    lines.add('');
    lines.addAll(generateBindGroup(groupId, bindings));
    lines.add('');
  }

  for (final vertexEntry in info.entry.vertex) {
    final vertexBuffer = generateVertexBuffer(vertexEntry);
    if (vertexBuffer != null) {
      lines.addAll(generateVertexBufferLayout(vertexEntry)!);
      lines.add('');
      lines.addAll(vertexBuffer);
      lines.add('');
    }
  }

  for (final computeEntry in info.entry.compute) {
    lines.addAll(generateComputeState(computeEntry));
    lines.add('');
  }

  for (final vertexEntry in info.entry.vertex) {
    lines.addAll(generateVertexState(vertexEntry));
    lines.add('');
  }

  for (final fragmentEntry in info.entry.fragment) {
    lines.addAll(generateFragmentState(fragmentEntry));
    lines.add('');
  }

  final pipelineCount = info.entry.compute.length + info.entry.vertex.length * info.entry.fragment.length;
  final isOnlyPipeline = pipelineCount == 1;

  for (final computeEntry in info.entry.compute) {
    lines.addAll(generateComputePipeline(computeEntry, groups, isOnlyPipeline));
    lines.add('');
  }

  for (final vertexEntry in info.entry.vertex) {
    for (final fragmentEntry in info.entry.fragment) {
      lines.addAll(generateRenderPipeline(vertexEntry, fragmentEntry, groups, isOnlyPipeline));
      lines.add('');
    }
  }

  lines.addAll(generateShaderModule(name, source));

  return lines;
}
