name: app
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  bindings:
  state:
  native:
  skia:
  schema:

  program:
  scene:
  editor:
  ui:
  
  sync:
  sync_server:

  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.6