#!/usr/bin/env dart
// ignore_for_file: avoid_print

import 'dart:io';

import 'package:skia/src/config.dart' as config;
import 'package:ffigen/ffigen.dart' as ffigen;
import 'package:ffigen_js/src/jsgen/jsgen.dart' as ffigen_js;

void main() {
  final packages = config.packages;
  final root = Platform.script.resolve('../');
  final sizesTable = <(String, String), int>{};

  for (final package in packages) {
    final srcDir = root.resolve('../$package/src');
    final outFile = root.resolve('lib/$package.dart');
    final outFfiFile = root.resolve('lib/$package/native.dart');
    final outJsFile = root.resolve('lib/$package/web.dart');

    final dir = Directory.fromUri(srcDir);
    if (!dir.existsSync()) {
      print('src dir not found for package $package: $srcDir');
      continue;
    }

    final headers = dir.listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('.h')).toList();
    if (headers.isEmpty) {
      print('no header files found for package $package in $srcDir');
      continue;
    }

    final generator = ffigen.FfiGenerator(
      output: .new(
        dartFile: outFfiFile,
        style: ffigen.NativeExternalBindings(assetId: 'package:skia/src/asset.dart'),
      ),
      headers: .new(
        entryPoints: headers.map((f) => f.uri).toList(),
      ),
      functions: .includeAll,
      globals: .includeAll,
      enums: .includeAll,
      structs: .includeAll,
      unions: .includeAll,
    );

    generator.generate();

    ffigen_js.JSGen().run(
      .new(
        entryPoints: headers.map((f) => f.uri).toList(),
        output: outJsFile,
        functionDecl: .includeAll,
        // globals: .includeAll,
        // enumClassDecl: .includeAll,
        // structDecl: .includeAll,
        // unionDecl: .includeAll,
        preamble: '// ignore_for_file: unused_import, unused_local_variable',
      ),
    );

    final sizes = _fixJsgenOutput(outJsFile);
    for (final entry in sizes.entries) {
      sizesTable[(package, entry.key)] = entry.value;
    }

    final outFileContent = [
      '// GENERATED CODE - DO NOT MODIFY BY HAND',
      '//',
      '// Generated by tool/generate_bindings.dart',
      '',
      'export \'$package/native.dart\' if (dart.library.js_interop) \'$package/web.dart\';',
    ];

    File.fromUri(outFile).writeAsStringSync(outFileContent.join('\n'));
    print('generated bindings for package $package at $outFfiFile');
  }

  // Generate sizes table
  final sizesOutFile = root.resolve('lib/src/utils/wasm_sizes.dart');
  final sizesOutContent = [
    '// GENERATED CODE - DO NOT MODIFY BY HAND',
    '//',
    '// Generated by tool/generate_bindings.dart',
    '',
    'import \'package:ffigen_js/ffigen_js.dart\' as jsgen;',
    '',
  ];

  final packagesSet = sizesTable.keys.map((k) => k.$1).toSet();

  for (final package in packagesSet) {
    sizesOutContent.add('import \'package:skia/$package/web.dart\' as $package;');
  }

  sizesOutContent.add('');
  sizesOutContent.add('int sizeOf<T extends jsgen.NativeType>() {');
  sizesOutContent.add('  return switch (T) {');

  for (final entry in sizesTable.entries) {
    final package = entry.key.$1;
    final type = entry.key.$2;
    final size = entry.value;
    sizesOutContent.add('    const ($package.$type) => $size,');
  }

  sizesOutContent.add('    _ => jsgen.sizeOf<T>(),');
  sizesOutContent.add('  };');
  sizesOutContent.add('}');

  File.fromUri(sizesOutFile).writeAsStringSync(sizesOutContent.join('\n'));
  print('generated sizes table at $sizesOutFile');
}

Map<String, int> _fixJsgenOutput(Uri file) {
  final f = File.fromUri(file);
  if (!f.existsSync()) {
    print('jsgen output not found: $file');
    return {};
  }

  final src = f.readAsStringSync();

  final sizePattern = RegExp(
    r'NativeLibrary\.instance\.stackAlloc<(\w+)>\((\d+)\)',
  );
  final sizes = <String, int>{};
  for (final m in sizePattern.allMatches(src)) {
    sizes[m.group(1)!] = int.parse(m.group(2)!);
  }

  final pattern = RegExp(
    r'extension\s+(\w+)Ext\s+on\s+Pointer<\1>\s*\{\s*'
    r'\1\s+toDart\(\)\s*\{[^}]*\}\s*'
    r'\}',
    multiLine: true,
  );

  final patched = src.replaceAllMapped(pattern, (m) {
    final original = m.group(0)!;
    final name = m.group(1)!;

    final additions = [
      '  $name get ref => toDart();',
      '  $name operator [](int index) => Pointer<$name>(this.address + sizeOf * index).toDart();',
      '  operator []=(int index, $name value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, \'*\');',
      '  int get sizeOf => ${sizes[name] ?? 'throw UnimplementedError()'};',
      '',
    ];

    final additionsStr = additions.join('\n');
    final closingBrace = original.lastIndexOf('}');
    return original.substring(0, closingBrace) + additionsStr + original.substring(closingBrace);
  });

  f.writeAsStringSync(patched);
  print('patched jsgen output: $file');
  return sizes;
}
