#!/usr/bin/env dart

// ignore_for_file: avoid_print

import 'dart:io';

import 'package:ffigen/ffigen.dart' as ffigen;
import 'package:ffigen_js/src/jsgen/jsgen.dart' as ffigen_js;

void main() {
  final root = Platform.script.resolve('../');
  final sizesTable = <String, int>{};

  final srcDir = root.resolve('src');
  final outFile = root.resolve('lib/src/gen/skia_bindings.g.dart');
  final outFfiFile = root.resolve('lib/src/gen/skia_bindings_native.g.dart');
  final outJsFile = root.resolve('lib/src/gen/skia_bindings_web.g.dart');
  final outSizesFile = root.resolve('lib/src/gen/skia_bindings_sizes.g.dart');

  final dir = Directory.fromUri(srcDir);

  final headers = dir.listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('.h')).toList();
  headers.removeWhere((f) => f.path.endsWith('exports.h'));

  if (headers.isEmpty) {
    print('no header files found in $srcDir');
    return;
  }

  final generator = ffigen.FfiGenerator(
    output: .new(
      dartFile: outFfiFile,
      style: ffigen.NativeExternalBindings(assetId: 'package:skia/src/asset.dart'),
      preamble: '// ignore_for_file: unused_import, unused_local_variable, unused_element, unused_field',
    ),
    headers: .new(
      entryPoints: headers.map((f) => f.uri).toList(),
    ),
    typedefs: .includeAll,
    functions: .new(
      include: (decl) => true,
      includeSymbolAddress: (decl) => decl.originalName.endsWith('_destroy'),
    ),
    globals: .includeAll,
    enums: .includeAll,
    structs: .includeAll,
    unions: .includeAll,
  );

  generator.generate();

  final emsdk = root.resolve('build/skia/third_party/externals/emsdk/');
  final clangInclude = Directory.fromUri(emsdk.resolve('upstream/lib/clang'))
      .listSync()
      .whereType<Directory>()
      .single
      .uri
      .resolve('include')
      .toFilePath();

  final sysroot = emsdk.resolve('upstream/emscripten/cache/sysroot').toFilePath();

  ffigen_js.JSGen().run(
    .new(
      entryPoints: headers.map((f) => f.uri).toList(),
      compilerOpts: [
        '--target=wasm32-unknown-emscripten',
        '--sysroot=$sysroot',
        '-isystem',
        clangInclude,
      ],
      output: outJsFile,
      functionDecl: .new(
        shouldInclude: (d) => d.usr.contains('motif'),
        shouldIncludeSymbolPointer: (d) {
          print(d.originalName);
          return true;
        },
      ),
      // globals: .includeAll,
      // enumClassDecl: .includeAll,
      // structDecl: .includeAll,
      // unionDecl: .includeAll,
      typedefs: .includeAll,
      language: .c,
      preamble: '// ignore_for_file: unused_import, unused_local_variable, unnecessary_cast',
    ),
  );

  final sizes = _fixJsgenOutput(outJsFile);
  sizesTable.addAll(sizes);

  final outFileContent = [
    '// GENERATED CODE - DO NOT MODIFY BY HAND',
    '//',
    '// Generated by tool/generate_bindings.dart',
    '',
    'export \'skia_bindings_native.g.dart\' if (dart.library.js_interop) \'skia_bindings_web.g.dart\';',
  ];

  File.fromUri(outFile).writeAsStringSync(outFileContent.join('\n'));
  print('generated bindings at $outFfiFile and $outJsFile');

  // Generate sizes table
  final sizesOutContent = [
    '// GENERATED CODE - DO NOT MODIFY BY HAND',
    '//',
    '// Generated by tool/generate_bindings.dart',
    '',
    '// ignore_for_file: unused_import, unused_local_variable',
    '',
    'import \'package:ffigen_js/ffigen_js.dart\' as jsgen;',
    '',
    'import \'skia_bindings_web.g.dart\';',
  ];

  sizesOutContent.add('');
  sizesOutContent.add('int sizeOf<T extends jsgen.NativeType>() {');
  sizesOutContent.add('  return switch (T) {');

  for (final entry in sizesTable.entries) {
    final type = entry.key;
    final size = entry.value;
    sizesOutContent.add('    const ($type) => $size,');
  }

  sizesOutContent.add('    _ => jsgen.sizeOf<T>(),');
  sizesOutContent.add('  };');
  sizesOutContent.add('}');

  File.fromUri(outSizesFile).writeAsStringSync(sizesOutContent.join('\n'));
  print('generated sizes table at $outSizesFile');
}

Map<String, int> _fixJsgenOutput(Uri file) {
  final f = File.fromUri(file);
  if (!f.existsSync()) {
    print('jsgen output not found: $file');
    return {};
  }

  final src = f.readAsStringSync();

  final sizePattern = RegExp(
    r'NativeLibrary\.instance\.stackAlloc<(\w+)>\((\d+)\)',
  );
  final sizes = <String, int>{};
  for (final m in sizePattern.allMatches(src)) {
    sizes[m.group(1)!] = int.parse(m.group(2)!);
  }

  final pattern = RegExp(
    r'extension\s+(\w+)Ext\s+on\s+Pointer<\1>\s*\{\s*'
    r'\1\s+toDart\(\)\s*\{[^}]*\}\s*'
    r'\}',
    multiLine: true,
  );

  var patched = src;
  patched = patched.replaceAllMapped(pattern, (m) {
    final original = m.group(0)!;
    final name = m.group(1)!;

    final additions = [
      '  $name get ref => toDart();',
      '  $name operator [](int index) => Pointer<$name>(this.address + sizeOf * index).toDart();',
      '  operator []=(int index, $name value) => NativeLibrary.instance.setValue(this[index].address, value.address.toJS, \'*\');',
      '  int get sizeOf => ${sizes[name] ?? 'throw UnimplementedError()'};',
      '',
    ];

    final additionsStr = additions.join('\n');
    final closingBrace = original.lastIndexOf('}');
    return original.substring(0, closingBrace) + additionsStr + original.substring(closingBrace);
  });

  // Remove `export 'package:ffigen_js/ffigen_js.dart';`
  patched = patched.replaceAll("export 'package:ffigen_js/ffigen_js.dart';", '');

  // Add symbol table for functions ending with _destroy
  final functions = <String>[];
  final destroyPattern = RegExp(r'void _(\w+_destroy)\(');
  for (final m in destroyPattern.allMatches(src)) {
    functions.add(m.group(1)!);
  }

  print(functions);

  final symbolTable = [
    'final addresses = _SymbolAddresses();',
    '',
    'class _SymbolAddresses {',
    '  _SymbolAddresses();',
    '',
  ];

  for (final fn in functions) {
    symbolTable.add('  late final void Function(Pointer) $fn = (ptr) => GeneratedBindings.instance._$fn(ptr.cast());');
  }
  symbolTable.add('}');

  patched = '$patched\n${symbolTable.join('\n')}';

  f.writeAsStringSync(patched);
  print('patched jsgen output: $file');
  return sizes;
}
