name: editor
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  state:
  mouse_cursor:

  blueprint:
  geometry:
  kernel:
  program:
  scene:
  renderer:

  color:
  ui:
  schema:
  ink_stroke_modeler:

  equatable: ^2.1.0
  web_socket_channel: ^3.0.3
  flutter_boring_avatars: ^2.1.0
  uuid: ^4.6.0
  http: ^1.6.0
