name: editor
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  state:
  mouse_cursor:

  shared:
  blueprint:
  geometry:
  kernel:
  program:
  scene:
  renderer:

  color:
  ui:
  schema:
  ink_stroke_modeler:

  skia:
  skia_flutter:
  sync:
  sync_server:

  flutter_boring_avatars: ^2.1.0
  file_picker: ^13.1.0
  pretty_qr_code: ^3.6.0

flutter:
  assets:
    - assets/builtin/
    - assets/builtin/fonts/