part 'node_generator.dart';
part 'socket_generator.dart';

enum SocketType {
  constant,
  dynamic,
}

class SocketDescription {
  const SocketDescription({
    required this.name,
    required this.type,
    required this.defaultValue,
    this.color,
    this.isList = false,
  });

  final String name;
  final String type;
  final String? color;
  final String defaultValue;
  final bool isList;

  String get baseClassName => '${name}Socket';
  String get inputClassName => '${name}InputSocket';
  String get outputClassName => '${name}OutputSocket';

  String get constantInputClassName => '${name}ConstantInputSocket';
  String get dynamicInputClassName => '${name}DynamicInputSocket';
  String get constantOutputClassName => '${name}ConstantOutputSocket';
  String get dynamicOutputClassName => '${name}DynamicOutputSocket';

  String resolveInputName(SocketType s) => switch (s) {
    .constant => constantInputClassName,
    .dynamic => dynamicInputClassName,
  };

  String resolveOutputName(SocketType s) => switch (s) {
    .constant => constantOutputClassName,
    .dynamic => dynamicOutputClassName,
  };
}

abstract class VariableDescription {
  const VariableDescription({required this.name, required this.type, this.socketType = .constant});

  final String name;
  final SocketDescription type;
  final SocketType socketType;

  String get baseClassName => type.baseClassName;
  String get ioClassName;
}

class InputVariableDescription extends VariableDescription {
  const InputVariableDescription({required super.name, required super.type, super.socketType});

  // dart format off
  @override String get ioClassName => type.resolveInputName(socketType);
  // dart format on
}

class OutputVariableDescription extends VariableDescription {
  const OutputVariableDescription({required super.name, required super.type, super.socketType});

  // dart format off
  @override String get ioClassName => type.resolveOutputName(socketType);
  // dart format on
}

class NodeDescription {
  const NodeDescription({
    required this.name,
    this.inputs = const [],
    this.outputs = const [],
    this.color,
  });

  final String name;
  final List<InputVariableDescription> inputs;
  final List<OutputVariableDescription> outputs;
  final String? color;

  String get baseClassName => '${name}Node';
}

List<String> generateBlueprint({
  List<NodeDescription> nodes = const [],
  List<SocketDescription> sockets = const [],
  List<String> prelude = const [],
}) {
  final code = <String>[
    '// GENERATED CODE - DO NOT MODIFY BY HAND',
    '//',
    '// Generated by blueprint/generator.dart',
    '',
    '// ignore_for_file: unused_import',
    '',
    'import \'package:blueprint/blueprint.dart\' as bp;',
    ...prelude,
    '',
    '// dart format off',
    '',
  ];

  final _sockets = <String, SocketDescription>{};
  for (final socket in sockets) {
    _sockets[socket.name] = socket;
  }

  for (final node in nodes) {
    code.addAll(generateNode(node));
    code.add('');

    for (final variable in [...node.inputs, ...node.outputs]) {
      _sockets[variable.type.name] = variable.type;
    }
  }

  for (final socket in _sockets.values) {
    code.addAll(generateSocket(socket));
    code.add('');
  }

  code.add('// dart format on');
  code.add('');

  return code;
}
