// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by blueprint/generator.dart

// ignore_for_file: unused_import

import 'package:blueprint/blueprint.dart' as bp;
import 'package:vc/vc.dart';
import 'package:geometry/geometry.dart';
import 'package:ui/ui.dart';

// dart format off

abstract class PrimitiveVertexNodeBase extends bp.Node {
  PrimitiveVertexNodeBase(): super(
    name: 'PrimitiveVertex',
    inputs: const [],
    outputs: [
      GeometryConstantOutputSocket(name: 'vertex'),
    ],
  );

  late final o = (
    vertex: outputs[0] as GeometryConstantOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.primitive;
}

abstract class ConnectVerticesNodeBase extends bp.Node {
  ConnectVerticesNodeBase(): super(
    name: 'ConnectVertices',
    inputs: [
      GeometryConstantInputSocket(name: 'vertices'),
    ],
    outputs: [
      GeometryConstantOutputSocket(name: 'geometry'),
    ],
  );

  late final i = (
    vertices: inputs[0] as GeometryConstantInputSocket,
  );

  late final o = (
    geometry: outputs[0] as GeometryConstantOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.geometry;
}

abstract class JoinGeometryNodeBase extends bp.Node {
  JoinGeometryNodeBase(): super(
    name: 'JoinGeometry',
    inputs: [
      GeometryListConstantInputSocket(name: 'geometry'),
    ],
    outputs: [
      GeometryConstantOutputSocket(name: 'geometry'),
    ],
  );

  late final i = (
    geometry: inputs[0] as GeometryListConstantInputSocket,
  );

  late final o = (
    geometry: outputs[0] as GeometryConstantOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.geometry;
}

abstract class GeometryOutputNodeBase extends bp.Node {
  GeometryOutputNodeBase(): super(
    name: 'GeometryOutput',
    inputs: [
      GeometryConstantInputSocket(name: 'geometry'),
    ],
    outputs: const [],
  );

  late final i = (
    geometry: inputs[0] as GeometryConstantInputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.geometry;
}

abstract class RandomVectorNodeBase extends bp.Node {
  RandomVectorNodeBase(): super(
    name: 'RandomVector',
    inputs: const [],
    outputs: [
      VectorDynamicOutputSocket(name: 'vector'),
    ],
  );

  late final o = (
    vector: outputs[0] as VectorDynamicOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.math;
}

abstract class ShiftGeometryNodeBase extends bp.Node {
  ShiftGeometryNodeBase(): super(
    name: 'ShiftGeometry',
    inputs: [
      GeometryConstantInputSocket(name: 'geometry'),
      VectorDynamicInputSocket(name: 'shift'),
    ],
    outputs: [
      GeometryConstantOutputSocket(name: 'geometry'),
    ],
  );

  late final i = (
    geometry: inputs[0] as GeometryConstantInputSocket,
    shift: inputs[1] as VectorDynamicInputSocket,
  );

  late final o = (
    geometry: outputs[0] as GeometryConstantOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.geometry;
}

abstract class InstanceOnVerticesNodeBase extends bp.Node {
  InstanceOnVerticesNodeBase(): super(
    name: 'InstanceOnVertices',
    inputs: [
      GeometryConstantInputSocket(name: 'geometry'),
      GeometryConstantInputSocket(name: 'instance'),
      RotationDynamicInputSocket(name: 'rotation'),
      ScaleDynamicInputSocket(name: 'scale'),
    ],
    outputs: [
      GeometryConstantOutputSocket(name: 'instances'),
    ],
  );

  late final i = (
    geometry: inputs[0] as GeometryConstantInputSocket,
    instance: inputs[1] as GeometryConstantInputSocket,
    rotation: inputs[2] as RotationDynamicInputSocket,
    scale: inputs[3] as ScaleDynamicInputSocket,
  );

  late final o = (
    instances: outputs[0] as GeometryConstantOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.instance;
}

abstract class InstanceOnKnotsNodeBase extends bp.Node {
  InstanceOnKnotsNodeBase(): super(
    name: 'InstanceOnKnots',
    inputs: [
      GeometryConstantInputSocket(name: 'geometry'),
      GeometryConstantInputSocket(name: 'instance'),
      RotationDynamicInputSocket(name: 'rotation'),
      ScaleDynamicInputSocket(name: 'scale'),
    ],
    outputs: [
      GeometryConstantOutputSocket(name: 'instances'),
    ],
  );

  late final i = (
    geometry: inputs[0] as GeometryConstantInputSocket,
    instance: inputs[1] as GeometryConstantInputSocket,
    rotation: inputs[2] as RotationDynamicInputSocket,
    scale: inputs[3] as ScaleDynamicInputSocket,
  );

  late final o = (
    instances: outputs[0] as GeometryConstantOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.instance;
}

abstract class SymbolNodeBase extends bp.Node {
  SymbolNodeBase(): super(
    name: 'Symbol',
    inputs: [
      SymbolIdConstantInputSocket(name: 'symbolId'),
    ],
    outputs: [
      GeometryConstantOutputSocket(name: 'geometry'),
    ],
  );

  late final i = (
    symbolId: inputs[0] as SymbolIdConstantInputSocket,
  );

  late final o = (
    geometry: outputs[0] as GeometryConstantOutputSocket,
  );
}

abstract class GeometryInputNodeBase extends bp.Node {
  GeometryInputNodeBase(): super(
    name: 'GeometryInput',
    inputs: const [],
    outputs: [
      GeometryConstantOutputSocket(name: 'geometry'),
    ],
  );

  late final o = (
    geometry: outputs[0] as GeometryConstantOutputSocket,
  );

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.node.geometry;
}

abstract class VectorSocket extends bp.Socket<Vector2> {
  VectorSocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.vector;
}

abstract class VectorInputSocket extends VectorSocket with bp.InputSocket<Vector2> {
  VectorInputSocket({required super.name});

  @override
  Vector2 get defaultValue => Vector2.zero();
}

abstract class VectorOutputSocket extends VectorSocket with bp.OutputSocket<Vector2> {
  VectorOutputSocket({required super.name});
}

class VectorConstantInputSocket extends VectorInputSocket with bp.ConstantSocket<Vector2> {
  VectorConstantInputSocket({required super.name});
}

class VectorConstantOutputSocket extends VectorOutputSocket with bp.ConstantSocket<Vector2> {
  VectorConstantOutputSocket({required super.name});
}

class VectorDynamicInputSocket extends VectorInputSocket with bp.DynamicSocket<Vector2> {
  VectorDynamicInputSocket({required super.name});
}

class VectorDynamicOutputSocket extends VectorOutputSocket with bp.DynamicSocket<Vector2> {
  VectorDynamicOutputSocket({required super.name});
}

abstract class IntegerSocket extends bp.Socket<int> {
  IntegerSocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.int;
}

abstract class IntegerInputSocket extends IntegerSocket with bp.InputSocket<int> {
  IntegerInputSocket({required super.name});

  @override
  int get defaultValue => 0;
}

abstract class IntegerOutputSocket extends IntegerSocket with bp.OutputSocket<int> {
  IntegerOutputSocket({required super.name});
}

class IntegerConstantInputSocket extends IntegerInputSocket with bp.ConstantSocket<int> {
  IntegerConstantInputSocket({required super.name});
}

class IntegerConstantOutputSocket extends IntegerOutputSocket with bp.ConstantSocket<int> {
  IntegerConstantOutputSocket({required super.name});
}

class IntegerDynamicInputSocket extends IntegerInputSocket with bp.DynamicSocket<int> {
  IntegerDynamicInputSocket({required super.name});
}

class IntegerDynamicOutputSocket extends IntegerOutputSocket with bp.DynamicSocket<int> {
  IntegerDynamicOutputSocket({required super.name});
}

abstract class FloatSocket extends bp.Socket<double> {
  FloatSocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.float;
}

abstract class FloatInputSocket extends FloatSocket with bp.InputSocket<double> {
  FloatInputSocket({required super.name});

  @override
  double get defaultValue => 0.0;
}

abstract class FloatOutputSocket extends FloatSocket with bp.OutputSocket<double> {
  FloatOutputSocket({required super.name});
}

class FloatConstantInputSocket extends FloatInputSocket with bp.ConstantSocket<double> {
  FloatConstantInputSocket({required super.name});
}

class FloatConstantOutputSocket extends FloatOutputSocket with bp.ConstantSocket<double> {
  FloatConstantOutputSocket({required super.name});
}

class FloatDynamicInputSocket extends FloatInputSocket with bp.DynamicSocket<double> {
  FloatDynamicInputSocket({required super.name});
}

class FloatDynamicOutputSocket extends FloatOutputSocket with bp.DynamicSocket<double> {
  FloatDynamicOutputSocket({required super.name});
}

abstract class GeometrySocket extends bp.Socket<PrimitiveBundle> {
  GeometrySocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.geometry;
}

abstract class GeometryInputSocket extends GeometrySocket with bp.InputSocket<PrimitiveBundle> {
  GeometryInputSocket({required super.name});

  @override
  PrimitiveBundle get defaultValue => PrimitiveBundle.empty();
}

abstract class GeometryOutputSocket extends GeometrySocket with bp.OutputSocket<PrimitiveBundle> {
  GeometryOutputSocket({required super.name});
}

class GeometryConstantInputSocket extends GeometryInputSocket with bp.ConstantSocket<PrimitiveBundle> {
  GeometryConstantInputSocket({required super.name});
}

class GeometryConstantOutputSocket extends GeometryOutputSocket with bp.ConstantSocket<PrimitiveBundle> {
  GeometryConstantOutputSocket({required super.name});
}

class GeometryDynamicInputSocket extends GeometryInputSocket with bp.DynamicSocket<PrimitiveBundle> {
  GeometryDynamicInputSocket({required super.name});
}

class GeometryDynamicOutputSocket extends GeometryOutputSocket with bp.DynamicSocket<PrimitiveBundle> {
  GeometryDynamicOutputSocket({required super.name});
}

abstract class GeometryListSocket extends bp.Socket<List<PrimitiveBundle>> {
  GeometryListSocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.geometry;
}

abstract class GeometryListInputSocket extends GeometryListSocket with bp.InputSocket<List<PrimitiveBundle>>, bp.ListInputSocket<PrimitiveBundle, List<PrimitiveBundle>> {
  GeometryListInputSocket({required super.name});
}

class GeometryListConstantInputSocket extends GeometryListInputSocket with bp.ConstantSocket<List<PrimitiveBundle>> {
  GeometryListConstantInputSocket({required super.name});
}

class GeometryListDynamicInputSocket extends GeometryListInputSocket with bp.DynamicSocket<List<PrimitiveBundle>> {
  GeometryListDynamicInputSocket({required super.name});
}


abstract class RotationSocket extends bp.Socket<Angle2> {
  RotationSocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.float;
}

abstract class RotationInputSocket extends RotationSocket with bp.InputSocket<Angle2> {
  RotationInputSocket({required super.name});

  @override
  Angle2 get defaultValue => Angle2.zero;
}

abstract class RotationOutputSocket extends RotationSocket with bp.OutputSocket<Angle2> {
  RotationOutputSocket({required super.name});
}

class RotationConstantInputSocket extends RotationInputSocket with bp.ConstantSocket<Angle2> {
  RotationConstantInputSocket({required super.name});
}

class RotationConstantOutputSocket extends RotationOutputSocket with bp.ConstantSocket<Angle2> {
  RotationConstantOutputSocket({required super.name});
}

class RotationDynamicInputSocket extends RotationInputSocket with bp.DynamicSocket<Angle2> {
  RotationDynamicInputSocket({required super.name});
}

class RotationDynamicOutputSocket extends RotationOutputSocket with bp.DynamicSocket<Angle2> {
  RotationDynamicOutputSocket({required super.name});
}

abstract class ScaleSocket extends bp.Socket<Vector2> {
  ScaleSocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.vector;
}

abstract class ScaleInputSocket extends ScaleSocket with bp.InputSocket<Vector2> {
  ScaleInputSocket({required super.name});

  @override
  Vector2 get defaultValue => .new(1.0, 1.0);
}

abstract class ScaleOutputSocket extends ScaleSocket with bp.OutputSocket<Vector2> {
  ScaleOutputSocket({required super.name});
}

class ScaleConstantInputSocket extends ScaleInputSocket with bp.ConstantSocket<Vector2> {
  ScaleConstantInputSocket({required super.name});
}

class ScaleConstantOutputSocket extends ScaleOutputSocket with bp.ConstantSocket<Vector2> {
  ScaleConstantOutputSocket({required super.name});
}

class ScaleDynamicInputSocket extends ScaleInputSocket with bp.DynamicSocket<Vector2> {
  ScaleDynamicInputSocket({required super.name});
}

class ScaleDynamicOutputSocket extends ScaleOutputSocket with bp.DynamicSocket<Vector2> {
  ScaleDynamicOutputSocket({required super.name});
}

abstract class SymbolIdSocket extends bp.Socket<SymbolId?> {
  SymbolIdSocket({required super.name});

  @override
  Color? resolveColor(BuildContext context) => context.colors.blueprint.data.symbol;
}

abstract class SymbolIdInputSocket extends SymbolIdSocket with bp.InputSocket<SymbolId?> {
  SymbolIdInputSocket({required super.name});

  @override
  SymbolId? get defaultValue => null;
}

abstract class SymbolIdOutputSocket extends SymbolIdSocket with bp.OutputSocket<SymbolId?> {
  SymbolIdOutputSocket({required super.name});
}

class SymbolIdConstantInputSocket extends SymbolIdInputSocket with bp.ConstantSocket<SymbolId?> {
  SymbolIdConstantInputSocket({required super.name});
}

class SymbolIdConstantOutputSocket extends SymbolIdOutputSocket with bp.ConstantSocket<SymbolId?> {
  SymbolIdConstantOutputSocket({required super.name});
}

class SymbolIdDynamicInputSocket extends SymbolIdInputSocket with bp.DynamicSocket<SymbolId?> {
  SymbolIdDynamicInputSocket({required super.name});
}

class SymbolIdDynamicOutputSocket extends SymbolIdOutputSocket with bp.DynamicSocket<SymbolId?> {
  SymbolIdDynamicOutputSocket({required super.name});
}

// dart format on
