name: design
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  canvas:
  commander:
  css:
  color:
  shared:
  text:
  tool:
  tree:
  ui:

  stack_mouse_cursor:
  stack_ffi:
  vector_math: ^2.2.0