// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by blueprint/generator.dart

// ignore_for_file: unused_import

import 'package:blueprint/core.dart' as bp;
import 'package:geometry/geometry.dart';
import 'package:program/program.dart';
import 'package:color/color_data.dart';

// dart format off

abstract class GeneratorInputNodeBase extends bp.Node {
  GeneratorInputNodeBase({
    required super.id,
  }) : super(
    name: 'GeneratorInput',
    category: #geometry,
    inputs: const [],
    outputs: [
      ProgramSliceConstantOutputSocket(name: 'slice'),
    ],
  );

  late final o = (
    slice: outputs[0] as ProgramSliceConstantOutputSocket,
  );

  @override
  GeneratorInputNode copyWith({
    bp.NodeId? id,
  }) => .new(
    id: id ?? this.id,
  );

  @override
  GeneratorInputNode copyWithInline(int index, Object? value) => switch(index) {
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class GeneratorOutputNodeBase extends bp.Node {
  GeneratorOutputNodeBase({
    required super.id,
  }) : super(
    name: 'GeneratorOutput',
    category: #geometry,
    inputs: [
      ProgramSliceListConstantInputSocket(name: 'slices'),
    ],
    outputs: const [],
  );

  late final i = (
    slices: inputs[0] as ProgramSliceListConstantInputSocket,
  );

  @override
  GeneratorOutputNode copyWith({
    bp.NodeId? id,
  }) => .new(
    id: id ?? this.id,
  );

  @override
  GeneratorOutputNode copyWithInline(int index, Object? value) => switch(index) {
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class ArrayNodeBase extends bp.Node {
  ArrayNodeBase({
    required super.id,
    ProgramSlice? slice,
    Vec2? count,
    Vec2? offset,
  }) : super(
    name: 'Array',
    category: #geometry,
    inputs: [
      ProgramSliceConstantInputSocket(name: 'slice', inlineValue: slice),
      VectorConstantInputSocket(name: 'count', inlineValue: count),
      VectorConstantInputSocket(name: 'offset', inlineValue: offset),
    ],
    outputs: [
      ProgramSliceConstantOutputSocket(name: 'slice'),
    ],
  );

  late final i = (
    slice: inputs[0] as ProgramSliceConstantInputSocket,
    count: inputs[1] as VectorConstantInputSocket,
    offset: inputs[2] as VectorConstantInputSocket,
  );

  late final o = (
    slice: outputs[0] as ProgramSliceConstantOutputSocket,
  );

  @override
  ArrayNode copyWith({
    bp.NodeId? id,
    ProgramSlice? slice,
    Vec2? count,
    Vec2? offset,
  }) => .new(
    id: id ?? this.id,
    slice: slice ?? i.slice.inlineValue,
    count: count ?? i.count.inlineValue,
    offset: offset ?? i.offset.inlineValue,
  );

  @override
  ArrayNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(slice: value as ProgramSlice),
    1 => copyWith(count: value as Vec2),
    2 => copyWith(offset: value as Vec2),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class FilletNodeBase extends bp.Node {
  FilletNodeBase({
    required super.id,
    ProgramSlice? slice,
    Vec2? radius,
  }) : super(
    name: 'Fillet',
    category: #geometry,
    inputs: [
      ProgramSliceConstantInputSocket(name: 'slice', inlineValue: slice),
      VectorDynamicInputSocket(name: 'radius', inlineValue: radius),
    ],
    outputs: [
      ProgramSliceConstantOutputSocket(name: 'slice'),
    ],
  );

  late final i = (
    slice: inputs[0] as ProgramSliceConstantInputSocket,
    radius: inputs[1] as VectorDynamicInputSocket,
  );

  late final o = (
    slice: outputs[0] as ProgramSliceConstantOutputSocket,
  );

  @override
  FilletNode copyWith({
    bp.NodeId? id,
    ProgramSlice? slice,
    Vec2? radius,
  }) => .new(
    id: id ?? this.id,
    slice: slice ?? i.slice.inlineValue,
    radius: radius ?? i.radius.inlineValue,
  );

  @override
  FilletNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(slice: value as ProgramSlice),
    1 => copyWith(radius: value as Vec2),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class NumberNodeBase extends bp.Node {
  NumberNodeBase({
    required super.id,
    double? value,
  }) : super(
    name: 'Number',
    category: #value,
    inputs: [
      FloatConstantInputSocket(name: 'value', inlineValue: value),
    ],
    outputs: [
      FloatConstantOutputSocket(name: 'value'),
    ],
  );

  late final i = (
    value: inputs[0] as FloatConstantInputSocket,
  );

  late final o = (
    value: outputs[0] as FloatConstantOutputSocket,
  );

  @override
  NumberNode copyWith({
    bp.NodeId? id,
    double? value,
  }) => .new(
    id: id ?? this.id,
    value: value ?? i.value.inlineValue,
  );

  @override
  NumberNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(value: value as double),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class VectorNodeBase extends bp.Node {
  VectorNodeBase({
    required super.id,
    Vec2? value,
  }) : super(
    name: 'Vector',
    category: #value,
    inputs: [
      VectorConstantInputSocket(name: 'value', inlineValue: value),
    ],
    outputs: [
      VectorConstantOutputSocket(name: 'value'),
    ],
  );

  late final i = (
    value: inputs[0] as VectorConstantInputSocket,
  );

  late final o = (
    value: outputs[0] as VectorConstantOutputSocket,
  );

  @override
  VectorNode copyWith({
    bp.NodeId? id,
    Vec2? value,
  }) => .new(
    id: id ?? this.id,
    value: value ?? i.value.inlineValue,
  );

  @override
  VectorNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(value: value as Vec2),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class VerticesNodeBase extends bp.Node {
  VerticesNodeBase({
    required super.id,
    int? count,
    Vec2? position,
  }) : super(
    name: 'Vertices',
    category: #primitive,
    inputs: [
      IntegerConstantInputSocket(name: 'count', inlineValue: count),
      VectorDynamicInputSocket(name: 'position', inlineValue: position),
    ],
    outputs: [
      ProgramSliceConstantOutputSocket(name: 'slice'),
    ],
  );

  late final i = (
    count: inputs[0] as IntegerConstantInputSocket,
    position: inputs[1] as VectorDynamicInputSocket,
  );

  late final o = (
    slice: outputs[0] as ProgramSliceConstantOutputSocket,
  );

  @override
  VerticesNode copyWith({
    bp.NodeId? id,
    int? count,
    Vec2? position,
  }) => .new(
    id: id ?? this.id,
    count: count ?? i.count.inlineValue,
    position: position ?? i.position.inlineValue,
  );

  @override
  VerticesNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(count: value as int),
    1 => copyWith(position: value as Vec2),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class RandomVectorNodeBase extends bp.Node {
  RandomVectorNodeBase({
    required super.id,
    int? seed,
    Vec2? min,
    Vec2? max,
  }) : super(
    name: 'RandomVector',
    category: #value,
    inputs: [
      IntegerConstantInputSocket(name: 'seed', inlineValue: seed),
      VectorDynamicInputSocket(name: 'min', inlineValue: min),
      VectorDynamicInputSocket(name: 'max', inlineValue: max),
    ],
    outputs: [
      VectorDynamicOutputSocket(name: 'value'),
    ],
  );

  late final i = (
    seed: inputs[0] as IntegerConstantInputSocket,
    min: inputs[1] as VectorDynamicInputSocket,
    max: inputs[2] as VectorDynamicInputSocket,
  );

  late final o = (
    value: outputs[0] as VectorDynamicOutputSocket,
  );

  @override
  RandomVectorNode copyWith({
    bp.NodeId? id,
    int? seed,
    Vec2? min,
    Vec2? max,
  }) => .new(
    id: id ?? this.id,
    seed: seed ?? i.seed.inlineValue,
    min: min ?? i.min.inlineValue,
    max: max ?? i.max.inlineValue,
  );

  @override
  RandomVectorNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(seed: value as int),
    1 => copyWith(min: value as Vec2),
    2 => copyWith(max: value as Vec2),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class IndexNodeBase extends bp.Node {
  IndexNodeBase({
    required super.id,
  }) : super(
    name: 'Index',
    category: #value,
    inputs: const [],
    outputs: [
      IntegerDynamicOutputSocket(name: 'value'),
    ],
  );

  late final o = (
    value: outputs[0] as IntegerDynamicOutputSocket,
  );

  @override
  IndexNode copyWith({
    bp.NodeId? id,
  }) => .new(
    id: id ?? this.id,
  );

  @override
  IndexNode copyWithInline(int index, Object? value) => switch(index) {
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class ScaleVectorNodeBase extends bp.Node {
  ScaleVectorNodeBase({
    required super.id,
    Vec2? vector,
    double? factor,
  }) : super(
    name: 'ScaleVector',
    category: #value,
    inputs: [
      VectorDynamicInputSocket(name: 'vector', inlineValue: vector),
      FloatDynamicInputSocket(name: 'factor', inlineValue: factor),
    ],
    outputs: [
      VectorDynamicOutputSocket(name: 'value'),
    ],
  );

  late final i = (
    vector: inputs[0] as VectorDynamicInputSocket,
    factor: inputs[1] as FloatDynamicInputSocket,
  );

  late final o = (
    value: outputs[0] as VectorDynamicOutputSocket,
  );

  @override
  ScaleVectorNode copyWith({
    bp.NodeId? id,
    Vec2? vector,
    double? factor,
  }) => .new(
    id: id ?? this.id,
    vector: vector ?? i.vector.inlineValue,
    factor: factor ?? i.factor.inlineValue,
  );

  @override
  ScaleVectorNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(vector: value as Vec2),
    1 => copyWith(factor: value as double),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class ConnectVerticesNodeBase extends bp.Node {
  ConnectVerticesNodeBase({
    required super.id,
    ProgramSlice? slice,
    bool? closed,
  }) : super(
    name: 'ConnectVertices',
    category: #geometry,
    inputs: [
      ProgramSliceConstantInputSocket(name: 'slice', inlineValue: slice),
      BooleanConstantInputSocket(name: 'closed', inlineValue: closed),
    ],
    outputs: [
      ProgramSliceConstantOutputSocket(name: 'slice'),
    ],
  );

  late final i = (
    slice: inputs[0] as ProgramSliceConstantInputSocket,
    closed: inputs[1] as BooleanConstantInputSocket,
  );

  late final o = (
    slice: outputs[0] as ProgramSliceConstantOutputSocket,
  );

  @override
  ConnectVerticesNode copyWith({
    bp.NodeId? id,
    ProgramSlice? slice,
    bool? closed,
  }) => .new(
    id: id ?? this.id,
    slice: slice ?? i.slice.inlineValue,
    closed: closed ?? i.closed.inlineValue,
  );

  @override
  ConnectVerticesNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(slice: value as ProgramSlice),
    1 => copyWith(closed: value as bool),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class FaceNodeBase extends bp.Node {
  FaceNodeBase({
    required super.id,
    ProgramSlice? slice,
  }) : super(
    name: 'Face',
    category: #geometry,
    inputs: [
      ProgramSliceConstantInputSocket(name: 'slice', inlineValue: slice),
    ],
    outputs: [
      ProgramSliceConstantOutputSocket(name: 'slice'),
    ],
  );

  late final i = (
    slice: inputs[0] as ProgramSliceConstantInputSocket,
  );

  late final o = (
    slice: outputs[0] as ProgramSliceConstantOutputSocket,
  );

  @override
  FaceNode copyWith({
    bp.NodeId? id,
    ProgramSlice? slice,
  }) => .new(
    id: id ?? this.id,
    slice: slice ?? i.slice.inlineValue,
  );

  @override
  FaceNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(slice: value as ProgramSlice),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class PolarNodeBase extends bp.Node {
  PolarNodeBase({
    required super.id,
    double? radius,
    double? angle,
  }) : super(
    name: 'Polar',
    category: #math,
    inputs: [
      FloatDynamicInputSocket(name: 'radius', inlineValue: radius),
      FloatDynamicInputSocket(name: 'angle', inlineValue: angle),
    ],
    outputs: [
      VectorDynamicOutputSocket(name: 'value'),
    ],
  );

  late final i = (
    radius: inputs[0] as FloatDynamicInputSocket,
    angle: inputs[1] as FloatDynamicInputSocket,
  );

  late final o = (
    value: outputs[0] as VectorDynamicOutputSocket,
  );

  @override
  PolarNode copyWith({
    bp.NodeId? id,
    double? radius,
    double? angle,
  }) => .new(
    id: id ?? this.id,
    radius: radius ?? i.radius.inlineValue,
    angle: angle ?? i.angle.inlineValue,
  );

  @override
  PolarNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(radius: value as double),
    1 => copyWith(angle: value as double),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class PiNodeBase extends bp.Node {
  PiNodeBase({
    required super.id,
  }) : super(
    name: 'Pi',
    category: #math,
    inputs: const [],
    outputs: [
      FloatConstantOutputSocket(name: 'value'),
    ],
  );

  late final o = (
    value: outputs[0] as FloatConstantOutputSocket,
  );

  @override
  PiNode copyWith({
    bp.NodeId? id,
  }) => .new(
    id: id ?? this.id,
  );

  @override
  PiNode copyWithInline(int index, Object? value) => switch(index) {
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class DivideNodeBase extends bp.Node {
  DivideNodeBase({
    required super.id,
    double? numerator,
    double? denominator,
  }) : super(
    name: 'Divide',
    category: #math,
    inputs: [
      FloatDynamicInputSocket(name: 'numerator', inlineValue: numerator),
      FloatDynamicInputSocket(name: 'denominator', inlineValue: denominator),
    ],
    outputs: [
      FloatDynamicOutputSocket(name: 'value'),
    ],
  );

  late final i = (
    numerator: inputs[0] as FloatDynamicInputSocket,
    denominator: inputs[1] as FloatDynamicInputSocket,
  );

  late final o = (
    value: outputs[0] as FloatDynamicOutputSocket,
  );

  @override
  DivideNode copyWith({
    bp.NodeId? id,
    double? numerator,
    double? denominator,
  }) => .new(
    id: id ?? this.id,
    numerator: numerator ?? i.numerator.inlineValue,
    denominator: denominator ?? i.denominator.inlineValue,
  );

  @override
  DivideNode copyWithInline(int index, Object? value) => switch(index) {
    0 => copyWith(numerator: value as double),
    1 => copyWith(denominator: value as double),
    _ => throw RangeError.index(index, inputs),
  };
}

abstract class VectorSocket extends bp.Socket<Vec2> {
  VectorSocket({required super.name});

  @override
  Symbol get category => #vector;
}

abstract class VectorInputSocket extends VectorSocket with bp.InputSocket<Vec2> {
  VectorInputSocket({required super.name, Vec2? inlineValue}) {
    this.inlineValue = inlineValue ?? defaultValue;
  }

  @override
  Vec2 get defaultValue => .zero();
}

abstract class VectorOutputSocket extends VectorSocket with bp.OutputSocket<Vec2> {
  VectorOutputSocket({required super.name});
}

class VectorConstantInputSocket extends VectorInputSocket with bp.ConstantSocket<Vec2> {
  VectorConstantInputSocket({required super.name, super.inlineValue});
}

class VectorConstantOutputSocket extends VectorOutputSocket with bp.ConstantSocket<Vec2> {
  VectorConstantOutputSocket({required super.name});
}

class VectorDynamicInputSocket extends VectorInputSocket with bp.DynamicSocket<Vec2> {
  VectorDynamicInputSocket({required super.name, super.inlineValue});
}

class VectorDynamicOutputSocket extends VectorOutputSocket with bp.DynamicSocket<Vec2> {
  VectorDynamicOutputSocket({required super.name});
}

abstract class IntegerSocket extends bp.Socket<int> {
  IntegerSocket({required super.name});

  @override
  Symbol get category => #int;
}

abstract class IntegerInputSocket extends IntegerSocket with bp.InputSocket<int> {
  IntegerInputSocket({required super.name, int? inlineValue}) {
    this.inlineValue = inlineValue ?? defaultValue;
  }

  @override
  int get defaultValue => 0;
}

abstract class IntegerOutputSocket extends IntegerSocket with bp.OutputSocket<int> {
  IntegerOutputSocket({required super.name});
}

class IntegerConstantInputSocket extends IntegerInputSocket with bp.ConstantSocket<int> {
  IntegerConstantInputSocket({required super.name, super.inlineValue});
}

class IntegerConstantOutputSocket extends IntegerOutputSocket with bp.ConstantSocket<int> {
  IntegerConstantOutputSocket({required super.name});
}

class IntegerDynamicInputSocket extends IntegerInputSocket with bp.DynamicSocket<int> {
  IntegerDynamicInputSocket({required super.name, super.inlineValue});
}

class IntegerDynamicOutputSocket extends IntegerOutputSocket with bp.DynamicSocket<int> {
  IntegerDynamicOutputSocket({required super.name});
}

abstract class FloatSocket extends bp.Socket<double> {
  FloatSocket({required super.name});

  @override
  Symbol get category => #float;
}

abstract class FloatInputSocket extends FloatSocket with bp.InputSocket<double> {
  FloatInputSocket({required super.name, double? inlineValue}) {
    this.inlineValue = inlineValue ?? defaultValue;
  }

  @override
  double get defaultValue => 0.0;
}

abstract class FloatOutputSocket extends FloatSocket with bp.OutputSocket<double> {
  FloatOutputSocket({required super.name});
}

class FloatConstantInputSocket extends FloatInputSocket with bp.ConstantSocket<double> {
  FloatConstantInputSocket({required super.name, super.inlineValue});
}

class FloatConstantOutputSocket extends FloatOutputSocket with bp.ConstantSocket<double> {
  FloatConstantOutputSocket({required super.name});
}

class FloatDynamicInputSocket extends FloatInputSocket with bp.DynamicSocket<double> {
  FloatDynamicInputSocket({required super.name, super.inlineValue});
}

class FloatDynamicOutputSocket extends FloatOutputSocket with bp.DynamicSocket<double> {
  FloatDynamicOutputSocket({required super.name});
}

abstract class ProgramSliceSocket extends bp.Socket<ProgramSlice> {
  ProgramSliceSocket({required super.name});

  @override
  Symbol get category => #geometry;
}

abstract class ProgramSliceInputSocket extends ProgramSliceSocket with bp.InputSocket<ProgramSlice> {
  ProgramSliceInputSocket({required super.name, ProgramSlice? inlineValue}) {
    this.inlineValue = inlineValue ?? defaultValue;
  }

  @override
  ProgramSlice get defaultValue => .empty();
}

abstract class ProgramSliceOutputSocket extends ProgramSliceSocket with bp.OutputSocket<ProgramSlice> {
  ProgramSliceOutputSocket({required super.name});
}

class ProgramSliceConstantInputSocket extends ProgramSliceInputSocket with bp.ConstantSocket<ProgramSlice> {
  ProgramSliceConstantInputSocket({required super.name, super.inlineValue});
}

class ProgramSliceConstantOutputSocket extends ProgramSliceOutputSocket with bp.ConstantSocket<ProgramSlice> {
  ProgramSliceConstantOutputSocket({required super.name});
}

class ProgramSliceDynamicInputSocket extends ProgramSliceInputSocket with bp.DynamicSocket<ProgramSlice> {
  ProgramSliceDynamicInputSocket({required super.name, super.inlineValue});
}

class ProgramSliceDynamicOutputSocket extends ProgramSliceOutputSocket with bp.DynamicSocket<ProgramSlice> {
  ProgramSliceDynamicOutputSocket({required super.name});
}

abstract class BooleanSocket extends bp.Socket<bool> {
  BooleanSocket({required super.name});

  @override
  Symbol get category => #boolean;
}

abstract class BooleanInputSocket extends BooleanSocket with bp.InputSocket<bool> {
  BooleanInputSocket({required super.name, bool? inlineValue}) {
    this.inlineValue = inlineValue ?? defaultValue;
  }

  @override
  bool get defaultValue => false;
}

abstract class BooleanOutputSocket extends BooleanSocket with bp.OutputSocket<bool> {
  BooleanOutputSocket({required super.name});
}

class BooleanConstantInputSocket extends BooleanInputSocket with bp.ConstantSocket<bool> {
  BooleanConstantInputSocket({required super.name, super.inlineValue});
}

class BooleanConstantOutputSocket extends BooleanOutputSocket with bp.ConstantSocket<bool> {
  BooleanConstantOutputSocket({required super.name});
}

class BooleanDynamicInputSocket extends BooleanInputSocket with bp.DynamicSocket<bool> {
  BooleanDynamicInputSocket({required super.name, super.inlineValue});
}

class BooleanDynamicOutputSocket extends BooleanOutputSocket with bp.DynamicSocket<bool> {
  BooleanDynamicOutputSocket({required super.name});
}

abstract class ColorSocket extends bp.Socket<ColorData> {
  ColorSocket({required super.name});

  @override
  Symbol get category => #color;
}

abstract class ColorInputSocket extends ColorSocket with bp.InputSocket<ColorData> {
  ColorInputSocket({required super.name, ColorData? inlineValue}) {
    this.inlineValue = inlineValue ?? defaultValue;
  }

  @override
  ColorData get defaultValue => .white;
}

abstract class ColorOutputSocket extends ColorSocket with bp.OutputSocket<ColorData> {
  ColorOutputSocket({required super.name});
}

class ColorConstantInputSocket extends ColorInputSocket with bp.ConstantSocket<ColorData> {
  ColorConstantInputSocket({required super.name, super.inlineValue});
}

class ColorConstantOutputSocket extends ColorOutputSocket with bp.ConstantSocket<ColorData> {
  ColorConstantOutputSocket({required super.name});
}

class ColorDynamicInputSocket extends ColorInputSocket with bp.DynamicSocket<ColorData> {
  ColorDynamicInputSocket({required super.name, super.inlineValue});
}

class ColorDynamicOutputSocket extends ColorOutputSocket with bp.DynamicSocket<ColorData> {
  ColorDynamicOutputSocket({required super.name});
}

abstract class BoundsSocket extends bp.Socket<Aabb2> {
  BoundsSocket({required super.name});

  @override
  Symbol get category => #geometry;
}

abstract class BoundsInputSocket extends BoundsSocket with bp.InputSocket<Aabb2> {
  BoundsInputSocket({required super.name, Aabb2? inlineValue}) {
    this.inlineValue = inlineValue ?? defaultValue;
  }

  @override
  Aabb2 get defaultValue => .invertedInfinity();
}

abstract class BoundsOutputSocket extends BoundsSocket with bp.OutputSocket<Aabb2> {
  BoundsOutputSocket({required super.name});
}

class BoundsConstantInputSocket extends BoundsInputSocket with bp.ConstantSocket<Aabb2> {
  BoundsConstantInputSocket({required super.name, super.inlineValue});
}

class BoundsConstantOutputSocket extends BoundsOutputSocket with bp.ConstantSocket<Aabb2> {
  BoundsConstantOutputSocket({required super.name});
}

class BoundsDynamicInputSocket extends BoundsInputSocket with bp.DynamicSocket<Aabb2> {
  BoundsDynamicInputSocket({required super.name, super.inlineValue});
}

class BoundsDynamicOutputSocket extends BoundsOutputSocket with bp.DynamicSocket<Aabb2> {
  BoundsDynamicOutputSocket({required super.name});
}

abstract class ProgramSliceListSocket extends bp.Socket<List<ProgramSlice>> {
  ProgramSliceListSocket({required super.name});

  @override
  Symbol get category => #geometry;
}

abstract class ProgramSliceListInputSocket extends ProgramSliceListSocket with bp.InputSocket<List<ProgramSlice>>, bp.ListInputSocket<ProgramSlice, List<ProgramSlice>> {
  ProgramSliceListInputSocket({required super.name}) {
    this.inlineValue = defaultValue;
  }
}

class ProgramSliceListConstantInputSocket extends ProgramSliceListInputSocket with bp.ConstantSocket<List<ProgramSlice>> {
  ProgramSliceListConstantInputSocket({required super.name});
}

class ProgramSliceListDynamicInputSocket extends ProgramSliceListInputSocket with bp.DynamicSocket<List<ProgramSlice>> {
  ProgramSliceListDynamicInputSocket({required super.name});
}


// dart format on
