name: vc
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  blueprint:
  color:
  geometry:
  node:
  stack:
  ui:

dev_dependencies:
  flutter_test: 
    sdk: flutter
