// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by tool/webgpu_gen.py
// Spec source: build/webgpu.yml
//
// ignore_for_file: unused_element, unused_field, constant_identifier_names, prefer_function_declarations_over_variables, non_constant_identifier_names

import 'dart:async';
import 'dart:ffi' as ffi;
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'bindings.g.dart' as bindings;
import '../utils/chained_struct.dart';

// dart format off
// ignore_for_file: invalid_use_of_protected_member, unreachable_switch_case, unused_import

import '../webgpu/webgpu.g.dart';
part 'wgpu_native_extensions.dart';

GlobalReport _generateReport(Instance instance) => using((allocator) {
  final outPtr = allocator<bindings.WGPUGlobalReport>();
  final _instance = internalInstanceGetPtr(instance).cast();
  bindings.wgpuGenerateReport(_instance.cast(), outPtr);
  return GlobalReport.fromNative(outPtr.ref);
});

List<Adapter> _instanceEnumerateAdapters(Instance instance, InstanceEnumerateAdapterOptions? options) => using((allocator) {
  final outPtr = allocator<bindings.WGPUAdapter>();
  final _instance = internalInstanceGetPtr(instance).cast();
  final _options = options?.toNative(allocator) ?? ffi.nullptr;
  final length = bindings.wgpuInstanceEnumerateAdapters(_instance.cast(), _options, outPtr);
  final result = <Adapter>[];
  for (var i = 0; i < length; i++) {
    result.add(internalAdapterFromBorrowedPtr(outPtr[i].cast()));
  }
  return result;
});

int _queueSubmitForIndex(Queue queue, List<CommandBuffer> commands) => using((allocator) {
  final _queue = internalQueueGetPtr(queue).cast();
  late final int _commandCount;
  late final ffi.Pointer<bindings.WGPUCommandBuffer> _commands;
  if (commands.isNotEmpty) {
    final arrayPtr = allocator<bindings.WGPUCommandBuffer>(commands.length);
    for (var i = 0; i < commands.length; i++) {
      arrayPtr[i] = internalCommandBufferGetPtr(commands[i]).cast();
    }
    _commands = arrayPtr;
    _commandCount = commands.length;
  }
  else {
    _commands = ffi.nullptr;
    _commandCount = 0;
  }
  final result = bindings.wgpuQueueSubmitForIndex(_queue.cast(), _commandCount, _commands);
  return result;
});

double _queueGetTimestampPeriod(Queue queue) => using((allocator) {
  final _queue = internalQueueGetPtr(queue).cast();
  final result = bindings.wgpuQueueGetTimestampPeriod(_queue.cast());
  return result;
});

void _devicePoll(Device device, bool wait, Uint64List? submissionIndex) => using((allocator) {
  final _device = internalDeviceGetPtr(device).cast();
  final _wait = wait ? 1 : 0;
  late final ffi.Pointer<ffi.Uint64> _submissionIndex;
  if (submissionIndex != null) {
    final _ptr = allocator<ffi.Uint64>(submissionIndex.length);
    _ptr.asTypedList(submissionIndex.length).setAll(0, submissionIndex);
    _submissionIndex = _ptr;
  }
  else {
    _submissionIndex = ffi.nullptr;
  }
  bindings.wgpuDevicePoll(_device.cast(), _wait, _submissionIndex);
});

ShaderModule _deviceCreateShaderModuleSpirV(Device device, ShaderModuleDescriptorSpirV descriptor) => using((allocator) {
  final _device = internalDeviceGetPtr(device).cast();
  final _descriptor = descriptor.toNative(allocator);
  final result = bindings.wgpuDeviceCreateShaderModuleSpirV(_device.cast(), _descriptor);
  return internalShaderModuleFromPtr(result.cast());
});

void _setLogLevel(LogLevel level) => using((allocator) {
  final _level = level.toNative();
  bindings.wgpuSetLogLevel(_level);
});

int _getVersion() => using((allocator) {
  final result = bindings.wgpuGetVersion();
  return result;
});

ffi.Pointer<ffi.Void> _deviceGetNativeMetalDevice(Device device) => using((allocator) {
  final _device = internalDeviceGetPtr(device).cast();
  final result = bindings.wgpuDeviceGetNativeMetalDevice(_device.cast());
  return result;
});

ffi.Pointer<ffi.Void> _queueGetNativeMetalCommandQueue(Queue queue) => using((allocator) {
  final _queue = internalQueueGetPtr(queue).cast();
  final result = bindings.wgpuQueueGetNativeMetalCommandQueue(_queue.cast());
  return result;
});

ffi.Pointer<ffi.Void> _textureGetNativeMetalTexture(Texture texture) => using((allocator) {
  final _texture = internalTextureGetPtr(texture).cast();
  final result = bindings.wgpuTextureGetNativeMetalTexture(_texture.cast());
  return result;
});

void _renderPassEncoderSetImmediates(RenderPassEncoder encoder, int offset, int sizeBytes, ffi.Pointer<ffi.Void> data) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  final _offset = offset;
  final _sizeBytes = sizeBytes;
  final _data = data;
  bindings.wgpuRenderPassEncoderSetImmediates(_encoder.cast(), _offset, _sizeBytes, _data);
});

void _computePassEncoderSetImmediates(ComputePassEncoder encoder, int offset, int sizeBytes, ffi.Pointer<ffi.Void> data) => using((allocator) {
  final _encoder = internalComputePassEncoderGetPtr(encoder).cast();
  final _offset = offset;
  final _sizeBytes = sizeBytes;
  final _data = data;
  bindings.wgpuComputePassEncoderSetImmediates(_encoder.cast(), _offset, _sizeBytes, _data);
});

void _renderBundleEncoderSetImmediates(RenderBundleEncoder encoder, int offset, int sizeBytes, ffi.Pointer<ffi.Void> data) => using((allocator) {
  final _encoder = internalRenderBundleEncoderGetPtr(encoder).cast();
  final _offset = offset;
  final _sizeBytes = sizeBytes;
  final _data = data;
  bindings.wgpuRenderBundleEncoderSetImmediates(_encoder.cast(), _offset, _sizeBytes, _data);
});

void _renderPassEncoderMultiDrawIndirect(RenderPassEncoder encoder, Buffer buffer, int offset, int count) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  final _buffer = internalBufferGetPtr(buffer).cast();
  final _offset = offset;
  final _count = count;
  bindings.wgpuRenderPassEncoderMultiDrawIndirect(_encoder.cast(), _buffer.cast(), _offset, _count);
});

void _renderPassEncoderMultiDrawIndexedIndirect(RenderPassEncoder encoder, Buffer buffer, int offset, int count) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  final _buffer = internalBufferGetPtr(buffer).cast();
  final _offset = offset;
  final _count = count;
  bindings.wgpuRenderPassEncoderMultiDrawIndexedIndirect(_encoder.cast(), _buffer.cast(), _offset, _count);
});

void _renderPassEncoderMultiDrawIndirectCount(RenderPassEncoder encoder, Buffer buffer, int offset, Buffer countBuffer, int countBufferOffset, int maxCount) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  final _buffer = internalBufferGetPtr(buffer).cast();
  final _offset = offset;
  final _countBuffer = internalBufferGetPtr(countBuffer).cast();
  final _countBufferOffset = countBufferOffset;
  final _maxCount = maxCount;
  bindings.wgpuRenderPassEncoderMultiDrawIndirectCount(_encoder.cast(), _buffer.cast(), _offset, _countBuffer.cast(), _countBufferOffset, _maxCount);
});

void _renderPassEncoderMultiDrawIndexedIndirectCount(RenderPassEncoder encoder, Buffer buffer, int offset, Buffer countBuffer, int countBufferOffset, int maxCount) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  final _buffer = internalBufferGetPtr(buffer).cast();
  final _offset = offset;
  final _countBuffer = internalBufferGetPtr(countBuffer).cast();
  final _countBufferOffset = countBufferOffset;
  final _maxCount = maxCount;
  bindings.wgpuRenderPassEncoderMultiDrawIndexedIndirectCount(_encoder.cast(), _buffer.cast(), _offset, _countBuffer.cast(), _countBufferOffset, _maxCount);
});

void _computePassEncoderBeginPipelineStatisticsQuery(ComputePassEncoder encoder, QuerySet querySet, int queryIndex) => using((allocator) {
  final _encoder = internalComputePassEncoderGetPtr(encoder).cast();
  final _querySet = internalQuerySetGetPtr(querySet).cast();
  final _queryIndex = queryIndex;
  bindings.wgpuComputePassEncoderBeginPipelineStatisticsQuery(_encoder.cast(), _querySet.cast(), _queryIndex);
});

void _computePassEncoderEndPipelineStatisticsQuery(ComputePassEncoder encoder) => using((allocator) {
  final _encoder = internalComputePassEncoderGetPtr(encoder).cast();
  bindings.wgpuComputePassEncoderEndPipelineStatisticsQuery(_encoder.cast());
});

void _renderPassEncoderBeginPipelineStatisticsQuery(RenderPassEncoder encoder, QuerySet querySet, int queryIndex) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  final _querySet = internalQuerySetGetPtr(querySet).cast();
  final _queryIndex = queryIndex;
  bindings.wgpuRenderPassEncoderBeginPipelineStatisticsQuery(_encoder.cast(), _querySet.cast(), _queryIndex);
});

void _renderPassEncoderEndPipelineStatisticsQuery(RenderPassEncoder encoder) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  bindings.wgpuRenderPassEncoderEndPipelineStatisticsQuery(_encoder.cast());
});

void _computePassEncoderWriteTimestamp(ComputePassEncoder encoder, QuerySet querySet, int queryIndex) => using((allocator) {
  final _encoder = internalComputePassEncoderGetPtr(encoder).cast();
  final _querySet = internalQuerySetGetPtr(querySet).cast();
  final _queryIndex = queryIndex;
  bindings.wgpuComputePassEncoderWriteTimestamp(_encoder.cast(), _querySet.cast(), _queryIndex);
});

void _renderPassEncoderWriteTimestamp(RenderPassEncoder encoder, QuerySet querySet, int queryIndex) => using((allocator) {
  final _encoder = internalRenderPassEncoderGetPtr(encoder).cast();
  final _querySet = internalQuerySetGetPtr(querySet).cast();
  final _queryIndex = queryIndex;
  bindings.wgpuRenderPassEncoderWriteTimestamp(_encoder.cast(), _querySet.cast(), _queryIndex);
});

bool _deviceStartGraphicsDebuggerCapture(Device device) => using((allocator) {
  final _device = internalDeviceGetPtr(device).cast();
  final result = bindings.wgpuDeviceStartGraphicsDebuggerCapture(_device.cast());
  return result == 1;
});

void _deviceStopGraphicsDebuggerCapture(Device device) => using((allocator) {
  final _device = internalDeviceGetPtr(device).cast();
  bindings.wgpuDeviceStopGraphicsDebuggerCapture(_device.cast());
});

extension type const _SType._(int value) {
  static const deviceExtras = _SType._(196609);
  static const nativeLimits = _SType._(196610);
  static const pipelineLayoutExtras = _SType._(196611);
  static const shaderSourceGLSL = _SType._(196612);
  static const instanceExtras = _SType._(196614);
  static const bindGroupEntryExtras = _SType._(196615);
  static const bindGroupLayoutEntryExtras = _SType._(196616);
  static const querySetDescriptorExtras = _SType._(196617);
  static const surfaceConfigurationExtras = _SType._(196618);
  static const surfaceSourceSwapChainPanel = _SType._(196619);
  static const primitiveStateExtras = _SType._(196620);

  bindings.WGPUNativeSType toNative() => switch (this) {
    .deviceExtras => bindings.WGPUNativeSType.WGPUSType_DeviceExtras,
    .nativeLimits => bindings.WGPUNativeSType.WGPUSType_NativeLimits,
    .pipelineLayoutExtras => bindings.WGPUNativeSType.WGPUSType_PipelineLayoutExtras,
    .shaderSourceGLSL => bindings.WGPUNativeSType.WGPUSType_ShaderSourceGLSL,
    .instanceExtras => bindings.WGPUNativeSType.WGPUSType_InstanceExtras,
    .bindGroupEntryExtras => bindings.WGPUNativeSType.WGPUSType_BindGroupEntryExtras,
    .bindGroupLayoutEntryExtras => bindings.WGPUNativeSType.WGPUSType_BindGroupLayoutEntryExtras,
    .querySetDescriptorExtras => bindings.WGPUNativeSType.WGPUSType_QuerySetDescriptorExtras,
    .surfaceConfigurationExtras => bindings.WGPUNativeSType.WGPUSType_SurfaceConfigurationExtras,
    .surfaceSourceSwapChainPanel => bindings.WGPUNativeSType.WGPUSType_SurfaceSourceSwapChainPanel,
    .primitiveStateExtras => bindings.WGPUNativeSType.WGPUSType_PrimitiveStateExtras,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for _SType'),
  };

  String get name => switch (this) {
    .deviceExtras => 'device_extras',
    .nativeLimits => 'native_limits',
    .pipelineLayoutExtras => 'pipeline_layout_extras',
    .shaderSourceGLSL => 'shader_source_GLSL',
    .instanceExtras => 'instance_extras',
    .bindGroupEntryExtras => 'bind_group_entry_extras',
    .bindGroupLayoutEntryExtras => 'bind_group_layout_entry_extras',
    .querySetDescriptorExtras => 'query_set_descriptor_extras',
    .surfaceConfigurationExtras => 'surface_configuration_extras',
    .surfaceSourceSwapChainPanel => 'surface_source_swap_chain_panel',
    .primitiveStateExtras => 'primitive_state_extras',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for _SType'),
  };

  static _SType fromNative(bindings.WGPUNativeSType value) => switch (value) {
    bindings.WGPUNativeSType.WGPUSType_DeviceExtras => _SType.deviceExtras,
    bindings.WGPUNativeSType.WGPUSType_NativeLimits => _SType.nativeLimits,
    bindings.WGPUNativeSType.WGPUSType_PipelineLayoutExtras => _SType.pipelineLayoutExtras,
    bindings.WGPUNativeSType.WGPUSType_ShaderSourceGLSL => _SType.shaderSourceGLSL,
    bindings.WGPUNativeSType.WGPUSType_InstanceExtras => _SType.instanceExtras,
    bindings.WGPUNativeSType.WGPUSType_BindGroupEntryExtras => _SType.bindGroupEntryExtras,
    bindings.WGPUNativeSType.WGPUSType_BindGroupLayoutEntryExtras => _SType.bindGroupLayoutEntryExtras,
    bindings.WGPUNativeSType.WGPUSType_QuerySetDescriptorExtras => _SType.querySetDescriptorExtras,
    bindings.WGPUNativeSType.WGPUSType_SurfaceConfigurationExtras => _SType.surfaceConfigurationExtras,
    bindings.WGPUNativeSType.WGPUSType_SurfaceSourceSwapChainPanel => _SType.surfaceSourceSwapChainPanel,
    bindings.WGPUNativeSType.WGPUSType_PrimitiveStateExtras => _SType.primitiveStateExtras,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for _SType'),
  };

  static _SType fromValue(int value) => switch (value) {
    196609 => .deviceExtras,
    196610 => .nativeLimits,
    196611 => .pipelineLayoutExtras,
    196612 => .shaderSourceGLSL,
    196614 => .instanceExtras,
    196615 => .bindGroupEntryExtras,
    196616 => .bindGroupLayoutEntryExtras,
    196617 => .querySetDescriptorExtras,
    196618 => .surfaceConfigurationExtras,
    196619 => .surfaceSourceSwapChainPanel,
    196620 => .primitiveStateExtras,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for _SType'),
  };
}

extension type const NativeFeature._(int value) implements FeatureName {
  static const immediates = NativeFeature._(196609);
  static const textureAdapterSpecificFormatFeatures = NativeFeature._(196610);
  static const multiDrawIndirectCount = NativeFeature._(196612);
  static const vertexWritableStorage = NativeFeature._(196613);
  static const textureBindingArray = NativeFeature._(196614);
  static const sampledTextureAndStorageBufferArrayNonUniformIndexing = NativeFeature._(196615);
  static const pipelineStatisticsQuery = NativeFeature._(196616);
  static const storageResourceBindingArray = NativeFeature._(196617);
  static const partiallyBoundBindingArray = NativeFeature._(196618);
  static const textureFormat16bitNorm = NativeFeature._(196619);
  static const textureCompressionAstcHdr = NativeFeature._(196620);
  static const mappablePrimaryBuffers = NativeFeature._(196622);
  static const bufferBindingArray = NativeFeature._(196623);
  static const uniformBufferAndStorageTextureArrayNonUniformIndexing = NativeFeature._(196624);
  static const polygonModeLine = NativeFeature._(196627);
  static const polygonModePoint = NativeFeature._(196628);
  static const conservativeRasterization = NativeFeature._(196629);
  static const spirvShaderPassthrough = NativeFeature._(196630);
  static const vertexAttribute64bit = NativeFeature._(196633);
  static const textureFormatNv12 = NativeFeature._(196634);
  static const rayQuery = NativeFeature._(196636);
  static const shaderF64 = NativeFeature._(196637);
  static const shaderI16 = NativeFeature._(196638);
  static const shaderEarlyDepthTest = NativeFeature._(196640);
  static const subgroup = NativeFeature._(196641);
  static const subgroupVertex = NativeFeature._(196642);
  static const subgroupBarrier = NativeFeature._(196643);
  static const timestampQueryInsideEncoders = NativeFeature._(196644);
  static const timestampQueryInsidePasses = NativeFeature._(196645);
  static const shaderInt64 = NativeFeature._(196646);

  bindings.WGPUNativeFeature toNative() => switch (this) {
    .immediates => bindings.WGPUNativeFeature.WGPUNativeFeature_Immediates,
    .textureAdapterSpecificFormatFeatures => bindings.WGPUNativeFeature.WGPUNativeFeature_TextureAdapterSpecificFormatFeatures,
    .multiDrawIndirectCount => bindings.WGPUNativeFeature.WGPUNativeFeature_MultiDrawIndirectCount,
    .vertexWritableStorage => bindings.WGPUNativeFeature.WGPUNativeFeature_VertexWritableStorage,
    .textureBindingArray => bindings.WGPUNativeFeature.WGPUNativeFeature_TextureBindingArray,
    .sampledTextureAndStorageBufferArrayNonUniformIndexing => bindings.WGPUNativeFeature.WGPUNativeFeature_SampledTextureAndStorageBufferArrayNonUniformIndexing,
    .pipelineStatisticsQuery => bindings.WGPUNativeFeature.WGPUNativeFeature_PipelineStatisticsQuery,
    .storageResourceBindingArray => bindings.WGPUNativeFeature.WGPUNativeFeature_StorageResourceBindingArray,
    .partiallyBoundBindingArray => bindings.WGPUNativeFeature.WGPUNativeFeature_PartiallyBoundBindingArray,
    .textureFormat16bitNorm => bindings.WGPUNativeFeature.WGPUNativeFeature_TextureFormat16bitNorm,
    .textureCompressionAstcHdr => bindings.WGPUNativeFeature.WGPUNativeFeature_TextureCompressionAstcHdr,
    .mappablePrimaryBuffers => bindings.WGPUNativeFeature.WGPUNativeFeature_MappablePrimaryBuffers,
    .bufferBindingArray => bindings.WGPUNativeFeature.WGPUNativeFeature_BufferBindingArray,
    .uniformBufferAndStorageTextureArrayNonUniformIndexing => bindings.WGPUNativeFeature.WGPUNativeFeature_UniformBufferAndStorageTextureArrayNonUniformIndexing,
    .polygonModeLine => bindings.WGPUNativeFeature.WGPUNativeFeature_PolygonModeLine,
    .polygonModePoint => bindings.WGPUNativeFeature.WGPUNativeFeature_PolygonModePoint,
    .conservativeRasterization => bindings.WGPUNativeFeature.WGPUNativeFeature_ConservativeRasterization,
    .spirvShaderPassthrough => bindings.WGPUNativeFeature.WGPUNativeFeature_SpirvShaderPassthrough,
    .vertexAttribute64bit => bindings.WGPUNativeFeature.WGPUNativeFeature_VertexAttribute64bit,
    .textureFormatNv12 => bindings.WGPUNativeFeature.WGPUNativeFeature_TextureFormatNv12,
    .rayQuery => bindings.WGPUNativeFeature.WGPUNativeFeature_RayQuery,
    .shaderF64 => bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderF64,
    .shaderI16 => bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderI16,
    .shaderEarlyDepthTest => bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderEarlyDepthTest,
    .subgroup => bindings.WGPUNativeFeature.WGPUNativeFeature_Subgroup,
    .subgroupVertex => bindings.WGPUNativeFeature.WGPUNativeFeature_SubgroupVertex,
    .subgroupBarrier => bindings.WGPUNativeFeature.WGPUNativeFeature_SubgroupBarrier,
    .timestampQueryInsideEncoders => bindings.WGPUNativeFeature.WGPUNativeFeature_TimestampQueryInsideEncoders,
    .timestampQueryInsidePasses => bindings.WGPUNativeFeature.WGPUNativeFeature_TimestampQueryInsidePasses,
    .shaderInt64 => bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderInt64,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeFeature'),
  };

  String get name => switch (this) {
    .immediates => 'immediates',
    .textureAdapterSpecificFormatFeatures => 'texture_adapter_specific_format_features',
    .multiDrawIndirectCount => 'multi_draw_indirect_count',
    .vertexWritableStorage => 'vertex_writable_storage',
    .textureBindingArray => 'texture_binding_array',
    .sampledTextureAndStorageBufferArrayNonUniformIndexing => 'sampled_texture_and_storage_buffer_array_non_uniform_indexing',
    .pipelineStatisticsQuery => 'pipeline_statistics_query',
    .storageResourceBindingArray => 'storage_resource_binding_array',
    .partiallyBoundBindingArray => 'partially_bound_binding_array',
    .textureFormat16bitNorm => 'texture_format_16bit_norm',
    .textureCompressionAstcHdr => 'texture_compression_astc_hdr',
    .mappablePrimaryBuffers => 'mappable_primary_buffers',
    .bufferBindingArray => 'buffer_binding_array',
    .uniformBufferAndStorageTextureArrayNonUniformIndexing => 'uniform_buffer_and_storage_texture_array_non_uniform_indexing',
    .polygonModeLine => 'polygon_mode_line',
    .polygonModePoint => 'polygon_mode_point',
    .conservativeRasterization => 'conservative_rasterization',
    .spirvShaderPassthrough => 'spirv_shader_passthrough',
    .vertexAttribute64bit => 'vertex_attribute_64bit',
    .textureFormatNv12 => 'texture_format_nv12',
    .rayQuery => 'ray_query',
    .shaderF64 => 'shader_f64',
    .shaderI16 => 'shader_i16',
    .shaderEarlyDepthTest => 'shader_early_depth_test',
    .subgroup => 'subgroup',
    .subgroupVertex => 'subgroup_vertex',
    .subgroupBarrier => 'subgroup_barrier',
    .timestampQueryInsideEncoders => 'timestamp_query_inside_encoders',
    .timestampQueryInsidePasses => 'timestamp_query_inside_passes',
    .shaderInt64 => 'shader_int64',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeFeature'),
  };

  static NativeFeature fromNative(bindings.WGPUNativeFeature value) => switch (value) {
    bindings.WGPUNativeFeature.WGPUNativeFeature_Immediates => NativeFeature.immediates,
    bindings.WGPUNativeFeature.WGPUNativeFeature_TextureAdapterSpecificFormatFeatures => NativeFeature.textureAdapterSpecificFormatFeatures,
    bindings.WGPUNativeFeature.WGPUNativeFeature_MultiDrawIndirectCount => NativeFeature.multiDrawIndirectCount,
    bindings.WGPUNativeFeature.WGPUNativeFeature_VertexWritableStorage => NativeFeature.vertexWritableStorage,
    bindings.WGPUNativeFeature.WGPUNativeFeature_TextureBindingArray => NativeFeature.textureBindingArray,
    bindings.WGPUNativeFeature.WGPUNativeFeature_SampledTextureAndStorageBufferArrayNonUniformIndexing => NativeFeature.sampledTextureAndStorageBufferArrayNonUniformIndexing,
    bindings.WGPUNativeFeature.WGPUNativeFeature_PipelineStatisticsQuery => NativeFeature.pipelineStatisticsQuery,
    bindings.WGPUNativeFeature.WGPUNativeFeature_StorageResourceBindingArray => NativeFeature.storageResourceBindingArray,
    bindings.WGPUNativeFeature.WGPUNativeFeature_PartiallyBoundBindingArray => NativeFeature.partiallyBoundBindingArray,
    bindings.WGPUNativeFeature.WGPUNativeFeature_TextureFormat16bitNorm => NativeFeature.textureFormat16bitNorm,
    bindings.WGPUNativeFeature.WGPUNativeFeature_TextureCompressionAstcHdr => NativeFeature.textureCompressionAstcHdr,
    bindings.WGPUNativeFeature.WGPUNativeFeature_MappablePrimaryBuffers => NativeFeature.mappablePrimaryBuffers,
    bindings.WGPUNativeFeature.WGPUNativeFeature_BufferBindingArray => NativeFeature.bufferBindingArray,
    bindings.WGPUNativeFeature.WGPUNativeFeature_UniformBufferAndStorageTextureArrayNonUniformIndexing => NativeFeature.uniformBufferAndStorageTextureArrayNonUniformIndexing,
    bindings.WGPUNativeFeature.WGPUNativeFeature_PolygonModeLine => NativeFeature.polygonModeLine,
    bindings.WGPUNativeFeature.WGPUNativeFeature_PolygonModePoint => NativeFeature.polygonModePoint,
    bindings.WGPUNativeFeature.WGPUNativeFeature_ConservativeRasterization => NativeFeature.conservativeRasterization,
    bindings.WGPUNativeFeature.WGPUNativeFeature_SpirvShaderPassthrough => NativeFeature.spirvShaderPassthrough,
    bindings.WGPUNativeFeature.WGPUNativeFeature_VertexAttribute64bit => NativeFeature.vertexAttribute64bit,
    bindings.WGPUNativeFeature.WGPUNativeFeature_TextureFormatNv12 => NativeFeature.textureFormatNv12,
    bindings.WGPUNativeFeature.WGPUNativeFeature_RayQuery => NativeFeature.rayQuery,
    bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderF64 => NativeFeature.shaderF64,
    bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderI16 => NativeFeature.shaderI16,
    bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderEarlyDepthTest => NativeFeature.shaderEarlyDepthTest,
    bindings.WGPUNativeFeature.WGPUNativeFeature_Subgroup => NativeFeature.subgroup,
    bindings.WGPUNativeFeature.WGPUNativeFeature_SubgroupVertex => NativeFeature.subgroupVertex,
    bindings.WGPUNativeFeature.WGPUNativeFeature_SubgroupBarrier => NativeFeature.subgroupBarrier,
    bindings.WGPUNativeFeature.WGPUNativeFeature_TimestampQueryInsideEncoders => NativeFeature.timestampQueryInsideEncoders,
    bindings.WGPUNativeFeature.WGPUNativeFeature_TimestampQueryInsidePasses => NativeFeature.timestampQueryInsidePasses,
    bindings.WGPUNativeFeature.WGPUNativeFeature_ShaderInt64 => NativeFeature.shaderInt64,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeFeature'),
  };

  static NativeFeature fromValue(int value) => switch (value) {
    196609 => .immediates,
    196610 => .textureAdapterSpecificFormatFeatures,
    196612 => .multiDrawIndirectCount,
    196613 => .vertexWritableStorage,
    196614 => .textureBindingArray,
    196615 => .sampledTextureAndStorageBufferArrayNonUniformIndexing,
    196616 => .pipelineStatisticsQuery,
    196617 => .storageResourceBindingArray,
    196618 => .partiallyBoundBindingArray,
    196619 => .textureFormat16bitNorm,
    196620 => .textureCompressionAstcHdr,
    196622 => .mappablePrimaryBuffers,
    196623 => .bufferBindingArray,
    196624 => .uniformBufferAndStorageTextureArrayNonUniformIndexing,
    196627 => .polygonModeLine,
    196628 => .polygonModePoint,
    196629 => .conservativeRasterization,
    196630 => .spirvShaderPassthrough,
    196633 => .vertexAttribute64bit,
    196634 => .textureFormatNv12,
    196636 => .rayQuery,
    196637 => .shaderF64,
    196638 => .shaderI16,
    196640 => .shaderEarlyDepthTest,
    196641 => .subgroup,
    196642 => .subgroupVertex,
    196643 => .subgroupBarrier,
    196644 => .timestampQueryInsideEncoders,
    196645 => .timestampQueryInsidePasses,
    196646 => .shaderInt64,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeFeature'),
  };
}

extension type const LogLevel._(int value) {
  static const off = LogLevel._(0);
  static const error = LogLevel._(1);
  static const warn = LogLevel._(2);
  static const info = LogLevel._(3);
  static const debug = LogLevel._(4);
  static const trace = LogLevel._(5);

  bindings.WGPULogLevel toNative() => switch (this) {
    .off => bindings.WGPULogLevel.WGPULogLevel_Off,
    .error => bindings.WGPULogLevel.WGPULogLevel_Error,
    .warn => bindings.WGPULogLevel.WGPULogLevel_Warn,
    .info => bindings.WGPULogLevel.WGPULogLevel_Info,
    .debug => bindings.WGPULogLevel.WGPULogLevel_Debug,
    .trace => bindings.WGPULogLevel.WGPULogLevel_Trace,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for LogLevel'),
  };

  String get name => switch (this) {
    .off => 'off',
    .error => 'error',
    .warn => 'warn',
    .info => 'info',
    .debug => 'debug',
    .trace => 'trace',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for LogLevel'),
  };

  static LogLevel fromNative(bindings.WGPULogLevel value) => switch (value) {
    bindings.WGPULogLevel.WGPULogLevel_Off => LogLevel.off,
    bindings.WGPULogLevel.WGPULogLevel_Error => LogLevel.error,
    bindings.WGPULogLevel.WGPULogLevel_Warn => LogLevel.warn,
    bindings.WGPULogLevel.WGPULogLevel_Info => LogLevel.info,
    bindings.WGPULogLevel.WGPULogLevel_Debug => LogLevel.debug,
    bindings.WGPULogLevel.WGPULogLevel_Trace => LogLevel.trace,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for LogLevel'),
  };

  static LogLevel fromValue(int value) => switch (value) {
    0 => .off,
    1 => .error,
    2 => .warn,
    3 => .info,
    4 => .debug,
    5 => .trace,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for LogLevel'),
  };
}

extension type const Dx12Compiler._(int value) {
  static const undefined = Dx12Compiler._(0);
  static const fxc = Dx12Compiler._(1);
  static const dxc = Dx12Compiler._(2);

  bindings.WGPUDx12Compiler toNative() => switch (this) {
    .undefined => bindings.WGPUDx12Compiler.WGPUDx12Compiler_Undefined,
    .fxc => bindings.WGPUDx12Compiler.WGPUDx12Compiler_Fxc,
    .dxc => bindings.WGPUDx12Compiler.WGPUDx12Compiler_Dxc,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for Dx12Compiler'),
  };

  String get name => switch (this) {
    .undefined => 'undefined',
    .fxc => 'fxc',
    .dxc => 'dxc',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for Dx12Compiler'),
  };

  static Dx12Compiler fromNative(bindings.WGPUDx12Compiler value) => switch (value) {
    bindings.WGPUDx12Compiler.WGPUDx12Compiler_Undefined => Dx12Compiler.undefined,
    bindings.WGPUDx12Compiler.WGPUDx12Compiler_Fxc => Dx12Compiler.fxc,
    bindings.WGPUDx12Compiler.WGPUDx12Compiler_Dxc => Dx12Compiler.dxc,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for Dx12Compiler'),
  };

  static Dx12Compiler fromValue(int value) => switch (value) {
    0 => .undefined,
    1 => .fxc,
    2 => .dxc,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for Dx12Compiler'),
  };
}

extension type const Gles3MinorVersion._(int value) {
  static const automatic = Gles3MinorVersion._(0);
  static const version0 = Gles3MinorVersion._(1);
  static const version1 = Gles3MinorVersion._(2);
  static const version2 = Gles3MinorVersion._(3);

  bindings.WGPUGles3MinorVersion toNative() => switch (this) {
    .automatic => bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Automatic,
    .version0 => bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Version0,
    .version1 => bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Version1,
    .version2 => bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Version2,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for Gles3MinorVersion'),
  };

  String get name => switch (this) {
    .automatic => 'automatic',
    .version0 => 'version0',
    .version1 => 'version1',
    .version2 => 'version2',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for Gles3MinorVersion'),
  };

  static Gles3MinorVersion fromNative(bindings.WGPUGles3MinorVersion value) => switch (value) {
    bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Automatic => Gles3MinorVersion.automatic,
    bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Version0 => Gles3MinorVersion.version0,
    bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Version1 => Gles3MinorVersion.version1,
    bindings.WGPUGles3MinorVersion.WGPUGles3MinorVersion_Version2 => Gles3MinorVersion.version2,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for Gles3MinorVersion'),
  };

  static Gles3MinorVersion fromValue(int value) => switch (value) {
    0 => .automatic,
    1 => .version0,
    2 => .version1,
    3 => .version2,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for Gles3MinorVersion'),
  };
}

extension type const PipelineStatisticName._(int value) {
  static const vertexShaderInvocations = PipelineStatisticName._(0);
  static const clipperInvocations = PipelineStatisticName._(1);
  static const clipperPrimitivesOut = PipelineStatisticName._(2);
  static const fragmentShaderInvocations = PipelineStatisticName._(3);
  static const computeShaderInvocations = PipelineStatisticName._(4);

  bindings.WGPUPipelineStatisticName toNative() => switch (this) {
    .vertexShaderInvocations => bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_VertexShaderInvocations,
    .clipperInvocations => bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_ClipperInvocations,
    .clipperPrimitivesOut => bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_ClipperPrimitivesOut,
    .fragmentShaderInvocations => bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_FragmentShaderInvocations,
    .computeShaderInvocations => bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_ComputeShaderInvocations,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for PipelineStatisticName'),
  };

  String get name => switch (this) {
    .vertexShaderInvocations => 'vertex_shader_invocations',
    .clipperInvocations => 'clipper_invocations',
    .clipperPrimitivesOut => 'clipper_primitives_out',
    .fragmentShaderInvocations => 'fragment_shader_invocations',
    .computeShaderInvocations => 'compute_shader_invocations',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for PipelineStatisticName'),
  };

  static PipelineStatisticName fromNative(bindings.WGPUPipelineStatisticName value) => switch (value) {
    bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_VertexShaderInvocations => PipelineStatisticName.vertexShaderInvocations,
    bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_ClipperInvocations => PipelineStatisticName.clipperInvocations,
    bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_ClipperPrimitivesOut => PipelineStatisticName.clipperPrimitivesOut,
    bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_FragmentShaderInvocations => PipelineStatisticName.fragmentShaderInvocations,
    bindings.WGPUPipelineStatisticName.WGPUPipelineStatisticName_ComputeShaderInvocations => PipelineStatisticName.computeShaderInvocations,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for PipelineStatisticName'),
  };

  static PipelineStatisticName fromValue(int value) => switch (value) {
    0 => .vertexShaderInvocations,
    1 => .clipperInvocations,
    2 => .clipperPrimitivesOut,
    3 => .fragmentShaderInvocations,
    4 => .computeShaderInvocations,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for PipelineStatisticName'),
  };
}

extension type const NativeQueryType._(int value) implements QueryType {
  static const pipelineStatistics = NativeQueryType._(12288);

  bindings.WGPUNativeQueryType toNative() => switch (this) {
    .pipelineStatistics => bindings.WGPUNativeQueryType.WGPUNativeQueryType_PipelineStatistics,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeQueryType'),
  };

  String get name => switch (this) {
    .pipelineStatistics => 'pipeline_statistics',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeQueryType'),
  };

  static NativeQueryType fromNative(bindings.WGPUNativeQueryType value) => switch (value) {
    bindings.WGPUNativeQueryType.WGPUNativeQueryType_PipelineStatistics => NativeQueryType.pipelineStatistics,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeQueryType'),
  };

  static NativeQueryType fromValue(int value) => switch (value) {
    12288 => .pipelineStatistics,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeQueryType'),
  };
}

extension type const DxcMaxShaderModel._(int value) {
  static const v6_0 = DxcMaxShaderModel._(0);
  static const v6_1 = DxcMaxShaderModel._(1);
  static const v6_2 = DxcMaxShaderModel._(2);
  static const v6_3 = DxcMaxShaderModel._(3);
  static const v6_4 = DxcMaxShaderModel._(4);
  static const v6_5 = DxcMaxShaderModel._(5);
  static const v6_6 = DxcMaxShaderModel._(6);
  static const v6_7 = DxcMaxShaderModel._(7);

  bindings.WGPUDxcMaxShaderModel toNative() => switch (this) {
    .v6_0 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_0,
    .v6_1 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_1,
    .v6_2 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_2,
    .v6_3 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_3,
    .v6_4 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_4,
    .v6_5 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_5,
    .v6_6 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_6,
    .v6_7 => bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_7,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for DxcMaxShaderModel'),
  };

  String get name => switch (this) {
    .v6_0 => 'v6__0',
    .v6_1 => 'v6__1',
    .v6_2 => 'v6__2',
    .v6_3 => 'v6__3',
    .v6_4 => 'v6__4',
    .v6_5 => 'v6__5',
    .v6_6 => 'v6__6',
    .v6_7 => 'v6__7',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for DxcMaxShaderModel'),
  };

  static DxcMaxShaderModel fromNative(bindings.WGPUDxcMaxShaderModel value) => switch (value) {
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_0 => DxcMaxShaderModel.v6_0,
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_1 => DxcMaxShaderModel.v6_1,
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_2 => DxcMaxShaderModel.v6_2,
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_3 => DxcMaxShaderModel.v6_3,
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_4 => DxcMaxShaderModel.v6_4,
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_5 => DxcMaxShaderModel.v6_5,
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_6 => DxcMaxShaderModel.v6_6,
    bindings.WGPUDxcMaxShaderModel.WGPUDxcMaxShaderModel_V6_7 => DxcMaxShaderModel.v6_7,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for DxcMaxShaderModel'),
  };

  static DxcMaxShaderModel fromValue(int value) => switch (value) {
    0 => .v6_0,
    1 => .v6_1,
    2 => .v6_2,
    3 => .v6_3,
    4 => .v6_4,
    5 => .v6_5,
    6 => .v6_6,
    7 => .v6_7,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for DxcMaxShaderModel'),
  };
}

extension type const GLFenceBehaviour._(int value) {
  static const normal = GLFenceBehaviour._(0);
  static const autoFinish = GLFenceBehaviour._(1);

  bindings.WGPUGLFenceBehaviour toNative() => switch (this) {
    .normal => bindings.WGPUGLFenceBehaviour.WGPUGLFenceBehaviour_Normal,
    .autoFinish => bindings.WGPUGLFenceBehaviour.WGPUGLFenceBehaviour_AutoFinish,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for GLFenceBehaviour'),
  };

  String get name => switch (this) {
    .normal => 'normal',
    .autoFinish => 'auto_finish',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for GLFenceBehaviour'),
  };

  static GLFenceBehaviour fromNative(bindings.WGPUGLFenceBehaviour value) => switch (value) {
    bindings.WGPUGLFenceBehaviour.WGPUGLFenceBehaviour_Normal => GLFenceBehaviour.normal,
    bindings.WGPUGLFenceBehaviour.WGPUGLFenceBehaviour_AutoFinish => GLFenceBehaviour.autoFinish,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for GLFenceBehaviour'),
  };

  static GLFenceBehaviour fromValue(int value) => switch (value) {
    0 => .normal,
    1 => .autoFinish,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for GLFenceBehaviour'),
  };
}

extension type const Dx12SwapchainKind._(int value) {
  static const undefined = Dx12SwapchainKind._(0);
  static const dxgiFromHwnd = Dx12SwapchainKind._(1);
  static const dxgiFromVisual = Dx12SwapchainKind._(2);

  bindings.WGPUDx12SwapchainKind toNative() => switch (this) {
    .undefined => bindings.WGPUDx12SwapchainKind.WGPUDx12SwapchainKind_Undefined,
    .dxgiFromHwnd => bindings.WGPUDx12SwapchainKind.WGPUDx12SwapchainKind_DxgiFromHwnd,
    .dxgiFromVisual => bindings.WGPUDx12SwapchainKind.WGPUDx12SwapchainKind_DxgiFromVisual,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for Dx12SwapchainKind'),
  };

  String get name => switch (this) {
    .undefined => 'undefined',
    .dxgiFromHwnd => 'dxgi_from_hwnd',
    .dxgiFromVisual => 'dxgi_from_visual',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for Dx12SwapchainKind'),
  };

  static Dx12SwapchainKind fromNative(bindings.WGPUDx12SwapchainKind value) => switch (value) {
    bindings.WGPUDx12SwapchainKind.WGPUDx12SwapchainKind_Undefined => Dx12SwapchainKind.undefined,
    bindings.WGPUDx12SwapchainKind.WGPUDx12SwapchainKind_DxgiFromHwnd => Dx12SwapchainKind.dxgiFromHwnd,
    bindings.WGPUDx12SwapchainKind.WGPUDx12SwapchainKind_DxgiFromVisual => Dx12SwapchainKind.dxgiFromVisual,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for Dx12SwapchainKind'),
  };

  static Dx12SwapchainKind fromValue(int value) => switch (value) {
    0 => .undefined,
    1 => .dxgiFromHwnd,
    2 => .dxgiFromVisual,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for Dx12SwapchainKind'),
  };
}

extension type const NativeDisplayHandleType._(int value) {
  static const none = NativeDisplayHandleType._(0);
  static const xlib = NativeDisplayHandleType._(1);
  static const xcb = NativeDisplayHandleType._(2);
  static const wayland = NativeDisplayHandleType._(3);

  bindings.WGPUNativeDisplayHandleType toNative() => switch (this) {
    .none => bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_None,
    .xlib => bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_Xlib,
    .xcb => bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_Xcb,
    .wayland => bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_Wayland,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeDisplayHandleType'),
  };

  String get name => switch (this) {
    .none => 'none',
    .xlib => 'xlib',
    .xcb => 'xcb',
    .wayland => 'wayland',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeDisplayHandleType'),
  };

  static NativeDisplayHandleType fromNative(bindings.WGPUNativeDisplayHandleType value) => switch (value) {
    bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_None => NativeDisplayHandleType.none,
    bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_Xlib => NativeDisplayHandleType.xlib,
    bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_Xcb => NativeDisplayHandleType.xcb,
    bindings.WGPUNativeDisplayHandleType.WGPUNativeDisplayHandleType_Wayland => NativeDisplayHandleType.wayland,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeDisplayHandleType'),
  };

  static NativeDisplayHandleType fromValue(int value) => switch (value) {
    0 => .none,
    1 => .xlib,
    2 => .xcb,
    3 => .wayland,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeDisplayHandleType'),
  };
}

extension type const PolygonMode._(int value) {
  static const fill = PolygonMode._(0);
  static const line = PolygonMode._(1);
  static const point = PolygonMode._(2);

  bindings.WGPUPolygonMode toNative() => switch (this) {
    .fill => bindings.WGPUPolygonMode.WGPUPolygonMode_Fill,
    .line => bindings.WGPUPolygonMode.WGPUPolygonMode_Line,
    .point => bindings.WGPUPolygonMode.WGPUPolygonMode_Point,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for PolygonMode'),
  };

  String get name => switch (this) {
    .fill => 'fill',
    .line => 'line',
    .point => 'point',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for PolygonMode'),
  };

  static PolygonMode fromNative(bindings.WGPUPolygonMode value) => switch (value) {
    bindings.WGPUPolygonMode.WGPUPolygonMode_Fill => PolygonMode.fill,
    bindings.WGPUPolygonMode.WGPUPolygonMode_Line => PolygonMode.line,
    bindings.WGPUPolygonMode.WGPUPolygonMode_Point => PolygonMode.point,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for PolygonMode'),
  };

  static PolygonMode fromValue(int value) => switch (value) {
    0 => .fill,
    1 => .line,
    2 => .point,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for PolygonMode'),
  };
}

extension type const NativeTextureFormat._(int value) implements TextureFormat {
  static const r16Unorm = NativeTextureFormat._(196609);
  static const r16Snorm = NativeTextureFormat._(196610);
  static const rg16Unorm = NativeTextureFormat._(196611);
  static const rg16Snorm = NativeTextureFormat._(196612);
  static const rgba16Unorm = NativeTextureFormat._(196613);
  static const rgba16Snorm = NativeTextureFormat._(196614);
  static const NV12 = NativeTextureFormat._(196615);
  static const p010 = NativeTextureFormat._(196616);

  bindings.WGPUNativeTextureFormat toNative() => switch (this) {
    .r16Unorm => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_R16Unorm,
    .r16Snorm => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_R16Snorm,
    .rg16Unorm => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rg16Unorm,
    .rg16Snorm => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rg16Snorm,
    .rgba16Unorm => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rgba16Unorm,
    .rgba16Snorm => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rgba16Snorm,
    .NV12 => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_NV12,
    .p010 => bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_P010,
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeTextureFormat'),
  };

  String get name => switch (this) {
    .r16Unorm => 'r16_unorm',
    .r16Snorm => 'r16_snorm',
    .rg16Unorm => 'rg16_unorm',
    .rg16Snorm => 'rg16_snorm',
    .rgba16Unorm => 'rgba16_unorm',
    .rgba16Snorm => 'rgba16_snorm',
    .NV12 => 'NV12',
    .p010 => 'p010',
    _ => throw ArgumentError.value(this, 'this', 'unknown enum entry for NativeTextureFormat'),
  };

  static NativeTextureFormat fromNative(bindings.WGPUNativeTextureFormat value) => switch (value) {
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_R16Unorm => NativeTextureFormat.r16Unorm,
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_R16Snorm => NativeTextureFormat.r16Snorm,
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rg16Unorm => NativeTextureFormat.rg16Unorm,
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rg16Snorm => NativeTextureFormat.rg16Snorm,
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rgba16Unorm => NativeTextureFormat.rgba16Unorm,
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_Rgba16Snorm => NativeTextureFormat.rgba16Snorm,
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_NV12 => NativeTextureFormat.NV12,
    bindings.WGPUNativeTextureFormat.WGPUNativeTextureFormat_P010 => NativeTextureFormat.p010,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeTextureFormat'),
  };

  static NativeTextureFormat fromValue(int value) => switch (value) {
    196609 => .r16Unorm,
    196610 => .r16Snorm,
    196611 => .rg16Unorm,
    196612 => .rg16Snorm,
    196613 => .rgba16Unorm,
    196614 => .rgba16Snorm,
    196615 => .NV12,
    196616 => .p010,
    _ => throw ArgumentError.value(value, 'value', 'unknown value for NativeTextureFormat'),
  };
}

extension type const InstanceBackend(int value) {
  static const all = InstanceBackend(0);
  static const vulkan = InstanceBackend(1);
  static const GL = InstanceBackend(2);
  static const metal = InstanceBackend(4);
  static const DX12 = InstanceBackend(8);
  static const browserWebgpu = InstanceBackend(32);
  static const primary = InstanceBackend(45);
  static const secondary = InstanceBackend(2);

  static InstanceBackend of(List<InstanceBackend> flags) => InstanceBackend(flags.fold(0, (v, f) => v | f.value));

  bool contains(InstanceBackend flag) => (value & flag.value) == flag.value;
  bool get hasAll => contains(.all);
  bool get hasVulkan => contains(.vulkan);
  bool get hasGL => contains(.GL);
  bool get hasMetal => contains(.metal);
  bool get hasDX12 => contains(.DX12);
  bool get hasBrowserWebgpu => contains(.browserWebgpu);
  bool get hasPrimary => contains(.primary);
  bool get hasSecondary => contains(.secondary);

  InstanceBackend operator |(InstanceBackend other) => InstanceBackend(value | other.value);
  InstanceBackend operator &(InstanceBackend other) => InstanceBackend(value & other.value);
  InstanceBackend operator ^(InstanceBackend other) => InstanceBackend(value ^ other.value);
  InstanceBackend operator ~() => InstanceBackend(~value);
}

extension type const InstanceFlag(int value) {
  static const empty = InstanceFlag(0);
  static const debug = InstanceFlag(1);
  static const validation = InstanceFlag(2);
  static const discardHalLabels = InstanceFlag(4);
  static const allowUnderlyingNoncompliantAdapters = InstanceFlag(8);
  static const gpuBasedValidation = InstanceFlag(16);
  static const validationIndirectCalls = InstanceFlag(32);
  static const automaticTimestampNormalization = InstanceFlag(64);
  static const default_ = InstanceFlag(16777216);
  static const debugging = InstanceFlag(33554432);
  static const advancedDebugging = InstanceFlag(67108864);
  static const withEnv = InstanceFlag(134217728);

  static const all = InstanceFlag(0 | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 16777216 | 33554432 | 67108864 | 134217728);

  static InstanceFlag of(List<InstanceFlag> flags) => InstanceFlag(flags.fold(0, (v, f) => v | f.value));

  bool contains(InstanceFlag flag) => (value & flag.value) == flag.value;
  bool get hasEmpty => contains(.empty);
  bool get hasDebug => contains(.debug);
  bool get hasValidation => contains(.validation);
  bool get hasDiscardHalLabels => contains(.discardHalLabels);
  bool get hasAllowUnderlyingNoncompliantAdapters => contains(.allowUnderlyingNoncompliantAdapters);
  bool get hasGpuBasedValidation => contains(.gpuBasedValidation);
  bool get hasValidationIndirectCalls => contains(.validationIndirectCalls);
  bool get hasAutomaticTimestampNormalization => contains(.automaticTimestampNormalization);
  bool get hasDefault_ => contains(.default_);
  bool get hasDebugging => contains(.debugging);
  bool get hasAdvancedDebugging => contains(.advancedDebugging);
  bool get hasWithEnv => contains(.withEnv);

  InstanceFlag operator |(InstanceFlag other) => InstanceFlag(value | other.value);
  InstanceFlag operator &(InstanceFlag other) => InstanceFlag(value & other.value);
  InstanceFlag operator ^(InstanceFlag other) => InstanceFlag(value ^ other.value);
  InstanceFlag operator ~() => InstanceFlag(~value);
}

class XlibDisplayHandle {
  const XlibDisplayHandle({
    required this.display,
    required this.screen,
  });

  const XlibDisplayHandle._({
    required this.display,
    required this.screen,
  });

  static const XlibDisplayHandle _zero = ._(
    display: null,
    screen: 0,
  );

  final ffi.Pointer<ffi.Void>? display;
  final int screen;

  ffi.Pointer<bindings.WGPUXlibDisplayHandle> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUXlibDisplayHandle>();
    if (display != null) ptr.ref.display = display!;
    ptr.ref.screen = screen;
    return ptr;
  }

  factory XlibDisplayHandle.fromNative(bindings.WGPUXlibDisplayHandle str) {
    final display = str.display;
    final screen = str.screen;
    return XlibDisplayHandle._(
      display: display,
      screen: screen,
    );
  }
}

class XcbDisplayHandle {
  const XcbDisplayHandle({
    required this.connection,
    required this.screen,
  });

  const XcbDisplayHandle._({
    required this.connection,
    required this.screen,
  });

  static const XcbDisplayHandle _zero = ._(
    connection: null,
    screen: 0,
  );

  final ffi.Pointer<ffi.Void>? connection;
  final int screen;

  ffi.Pointer<bindings.WGPUXcbDisplayHandle> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUXcbDisplayHandle>();
    if (connection != null) ptr.ref.connection = connection!;
    ptr.ref.screen = screen;
    return ptr;
  }

  factory XcbDisplayHandle.fromNative(bindings.WGPUXcbDisplayHandle str) {
    final connection = str.connection;
    final screen = str.screen;
    return XcbDisplayHandle._(
      connection: connection,
      screen: screen,
    );
  }
}

class WaylandDisplayHandle {
  const WaylandDisplayHandle({
    required this.display,
  });

  const WaylandDisplayHandle._({
    required this.display,
  });

  static const WaylandDisplayHandle _zero = ._(
    display: null,
  );

  final ffi.Pointer<ffi.Void>? display;

  ffi.Pointer<bindings.WGPUWaylandDisplayHandle> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUWaylandDisplayHandle>();
    if (display != null) ptr.ref.display = display!;
    return ptr;
  }

  factory WaylandDisplayHandle.fromNative(bindings.WGPUWaylandDisplayHandle str) {
    final display = str.display;
    return WaylandDisplayHandle._(
      display: display,
    );
  }
}

class NativeDisplayHandle {
  const NativeDisplayHandle({
    this.type = .none,
  });

  const NativeDisplayHandle._({
    required this.type,
  });

  static const NativeDisplayHandle _zero = ._(
    type: .none,
  );

  final NativeDisplayHandleType type;

  ffi.Pointer<bindings.WGPUNativeDisplayHandle> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUNativeDisplayHandle>();
    ptr.ref.typeAsInt = type.value;
    return ptr;
  }

  factory NativeDisplayHandle.fromNative(bindings.WGPUNativeDisplayHandle str) {
    final type = NativeDisplayHandleType.fromNative(str.type);
    return NativeDisplayHandle._(
      type: type,
    );
  }
}

class InstanceExtras extends ChainedStruct {
  const InstanceExtras({
    this.flags = .empty,
    this.dx12ShaderCompiler = .undefined,
    this.gles3MinorVersion = .automatic,
    this.glFenceBehaviour = .normal,
    required this.dxcPath,
    this.dxcMaxShaderModel = .v6_0,
    this.dx12PresentationSystem = .undefined,
    this.displayHandle = const NativeDisplayHandle(),
    super.next,
  });

  const InstanceExtras._({
    required this.flags,
    required this.dx12ShaderCompiler,
    required this.gles3MinorVersion,
    required this.glFenceBehaviour,
    required this.dxcPath,
    required this.dxcMaxShaderModel,
    required this.dx12PresentationSystem,
    required this.displayHandle,
    super.next,
  });

  static const InstanceExtras _zero = ._(
    flags: .new(0),
    dx12ShaderCompiler: .undefined,
    gles3MinorVersion: .automatic,
    glFenceBehaviour: .normal,
    dxcPath: '',
    dxcMaxShaderModel: .v6_0,
    dx12PresentationSystem: .undefined,
    displayHandle: ._zero,
    next: null,
  );

  final InstanceFlag flags;
  final Dx12Compiler dx12ShaderCompiler;
  final Gles3MinorVersion gles3MinorVersion;
  final GLFenceBehaviour glFenceBehaviour;
  final String dxcPath;
  final DxcMaxShaderModel dxcMaxShaderModel;
  final Dx12SwapchainKind dx12PresentationSystem;
  final NativeDisplayHandle displayHandle;

  @override
  int get sType => _SType.instanceExtras.value;

  @override
  ffi.Pointer<bindings.WGPUInstanceExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUInstanceExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.flags = flags.value;
    ptr.ref.dx12ShaderCompilerAsInt = dx12ShaderCompiler.value;
    ptr.ref.gles3MinorVersionAsInt = gles3MinorVersion.value;
    ptr.ref.glFenceBehaviourAsInt = glFenceBehaviour.value;
    ptr.ref.dxcPath = dxcPath.toStringView(allocator);
    ptr.ref.dxcMaxShaderModelAsInt = dxcMaxShaderModel.value;
    ptr.ref.dx12PresentationSystemAsInt = dx12PresentationSystem.value;
    ptr.ref.displayHandle = displayHandle.toNative(allocator).ref;
    return ptr;
  }

  factory InstanceExtras.fromNative(bindings.WGPUInstanceExtras str) {
    final flags = InstanceFlag(str.flags);
    final dx12ShaderCompiler = Dx12Compiler.fromNative(str.dx12ShaderCompiler);
    final gles3MinorVersion = Gles3MinorVersion.fromNative(str.gles3MinorVersion);
    final glFenceBehaviour = GLFenceBehaviour.fromNative(str.glFenceBehaviour);
    final dxcPath = str.dxcPath.toDartString();
    final dxcMaxShaderModel = DxcMaxShaderModel.fromNative(str.dxcMaxShaderModel);
    final dx12PresentationSystem = Dx12SwapchainKind.fromNative(str.dx12PresentationSystem);
    final displayHandle = NativeDisplayHandle.fromNative(str.displayHandle);
    return InstanceExtras._(
      flags: flags,
      dx12ShaderCompiler: dx12ShaderCompiler,
      gles3MinorVersion: gles3MinorVersion,
      glFenceBehaviour: glFenceBehaviour,
      dxcPath: dxcPath,
      dxcMaxShaderModel: dxcMaxShaderModel,
      dx12PresentationSystem: dx12PresentationSystem,
      displayHandle: displayHandle,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class DeviceExtras extends ChainedStruct {
  const DeviceExtras({
    required this.tracePath,
    super.next,
  });

  const DeviceExtras._({
    required this.tracePath,
    super.next,
  });

  static const DeviceExtras _zero = ._(
    tracePath: '',
    next: null,
  );

  final String tracePath;

  @override
  int get sType => _SType.deviceExtras.value;

  @override
  ffi.Pointer<bindings.WGPUDeviceExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUDeviceExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.tracePath = tracePath.toStringView(allocator);
    return ptr;
  }

  factory DeviceExtras.fromNative(bindings.WGPUDeviceExtras str) {
    final tracePath = str.tracePath.toDartString();
    return DeviceExtras._(
      tracePath: tracePath,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class NativeLimits extends ChainedStruct {
  const NativeLimits({
    required this.maxImmediateSize,
    required this.maxNonSamplerBindings,
    required this.maxBindingArrayElementsPerShaderStage,
    super.next,
  });

  const NativeLimits._({
    required this.maxImmediateSize,
    required this.maxNonSamplerBindings,
    required this.maxBindingArrayElementsPerShaderStage,
    super.next,
  });

  static const NativeLimits _zero = ._(
    maxImmediateSize: 0,
    maxNonSamplerBindings: 0,
    maxBindingArrayElementsPerShaderStage: 0,
    next: null,
  );

  final int maxImmediateSize;
  final int maxNonSamplerBindings;
  final int maxBindingArrayElementsPerShaderStage;

  @override
  int get sType => _SType.nativeLimits.value;

  @override
  ffi.Pointer<bindings.WGPUNativeLimits> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUNativeLimits>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.maxImmediateSize = maxImmediateSize;
    ptr.ref.maxNonSamplerBindings = maxNonSamplerBindings;
    ptr.ref.maxBindingArrayElementsPerShaderStage = maxBindingArrayElementsPerShaderStage;
    return ptr;
  }

  factory NativeLimits.fromNative(bindings.WGPUNativeLimits str) {
    final maxImmediateSize = str.maxImmediateSize;
    final maxNonSamplerBindings = str.maxNonSamplerBindings;
    final maxBindingArrayElementsPerShaderStage = str.maxBindingArrayElementsPerShaderStage;
    return NativeLimits._(
      maxImmediateSize: maxImmediateSize,
      maxNonSamplerBindings: maxNonSamplerBindings,
      maxBindingArrayElementsPerShaderStage: maxBindingArrayElementsPerShaderStage,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class PipelineLayoutExtras extends ChainedStruct {
  const PipelineLayoutExtras({
    required this.immediateDataSize,
    super.next,
  });

  const PipelineLayoutExtras._({
    required this.immediateDataSize,
    super.next,
  });

  static const PipelineLayoutExtras _zero = ._(
    immediateDataSize: 0,
    next: null,
  );

  final int immediateDataSize;

  @override
  int get sType => _SType.pipelineLayoutExtras.value;

  @override
  ffi.Pointer<bindings.WGPUPipelineLayoutExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUPipelineLayoutExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.immediateDataSize = immediateDataSize;
    return ptr;
  }

  factory PipelineLayoutExtras.fromNative(bindings.WGPUPipelineLayoutExtras str) {
    final immediateDataSize = str.immediateDataSize;
    return PipelineLayoutExtras._(
      immediateDataSize: immediateDataSize,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class ShaderDefine {
  const ShaderDefine({
    this.name = '',
    this.value = '',
  });

  const ShaderDefine._({
    required this.name,
    required this.value,
  });

  static const ShaderDefine _zero = ._(
    name: '',
    value: '',
  );

  final String name;
  final String value;

  ffi.Pointer<bindings.WGPUShaderDefine> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUShaderDefine>();
    ptr.ref.name = name.toStringView(allocator);
    ptr.ref.value = value.toStringView(allocator);
    return ptr;
  }

  factory ShaderDefine.fromNative(bindings.WGPUShaderDefine str) {
    final name = str.name.toDartString();
    final value = str.value.toDartString();
    return ShaderDefine._(
      name: name,
      value: value,
    );
  }
}

class ShaderSourceGLSL extends ChainedStruct {
  const ShaderSourceGLSL({
    this.stage = .none,
    this.code = '',
    this.defines = const [],
    super.next,
  });

  const ShaderSourceGLSL._({
    required this.stage,
    required this.code,
    required this.defines,
    super.next,
  });

  static const ShaderSourceGLSL _zero = ._(
    stage: .new(0),
    code: '',
    defines: [],
    next: null,
  );

  final ShaderStage stage;
  final String code;
  final List<ShaderDefine> defines;

  @override
  int get sType => _SType.shaderSourceGLSL.value;

  @override
  ffi.Pointer<bindings.WGPUShaderSourceGLSL> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUShaderSourceGLSL>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.stage = stage.value;
    ptr.ref.code = code.toStringView(allocator);
    if (defines.isNotEmpty) {
      final arrayPtr = allocator<bindings.WGPUShaderDefine>(defines.length);
      for (var i = 0; i < defines.length; i++) {
        arrayPtr[i] = defines[i].toNative(allocator).ref;
      }
      ptr.ref.defines = arrayPtr;
      ptr.ref.defineCount = defines.length;
    }
    else {
      ptr.ref.defines = ffi.nullptr;
      ptr.ref.defineCount = 0;
    }
    return ptr;
  }

  factory ShaderSourceGLSL.fromNative(bindings.WGPUShaderSourceGLSL str) {
    final stage = ShaderStage(str.stage);
    final code = str.code.toDartString();
    final defines = <ShaderDefine>[];
    if (str.defines != ffi.nullptr && str.defineCount > 0) {
      for (var i = 0; i < str.defineCount; i++) {
        defines.add(ShaderDefine.fromNative(str.defines[i]));
      }
    }
    return ShaderSourceGLSL._(
      stage: stage,
      code: code,
      defines: defines,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class ShaderModuleDescriptorSpirV {
  const ShaderModuleDescriptorSpirV({
    this.label = '',
    required this.sourceSize,
    required this.source,
  });

  const ShaderModuleDescriptorSpirV._({
    required this.label,
    required this.sourceSize,
    required this.source,
  });

  static const ShaderModuleDescriptorSpirV _zero = ._(
    label: '',
    sourceSize: 0,
    source: null,
  );

  final String label;
  final int sourceSize;
  final Uint32List? source;

  ffi.Pointer<bindings.WGPUShaderModuleDescriptorSpirV> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUShaderModuleDescriptorSpirV>();
    ptr.ref.label = label.toStringView(allocator);
    ptr.ref.sourceSize = sourceSize;
    if (source != null) {
      final _ptr = allocator<ffi.Uint32>(source!.length);
      _ptr.asTypedList(source!.length).setAll(0, source!);
      ptr.ref.source = _ptr;
    }
    else {
      ptr.ref.source = ffi.nullptr;
    }
    return ptr;
  }

  factory ShaderModuleDescriptorSpirV.fromNative(bindings.WGPUShaderModuleDescriptorSpirV str) {
    final label = str.label.toDartString();
    final sourceSize = str.sourceSize;
    final source = str.source != ffi.nullptr ? Uint32List.fromList(str.source.asTypedList(str.sourceSize)) : null;
    return ShaderModuleDescriptorSpirV._(
      label: label,
      sourceSize: sourceSize,
      source: source,
    );
  }
}

class RegistryReport {
  const RegistryReport({
    required this.numAllocated,
    required this.numKeptFromUser,
    required this.numReleasedFromUser,
    required this.elementSize,
  });

  const RegistryReport._({
    required this.numAllocated,
    required this.numKeptFromUser,
    required this.numReleasedFromUser,
    required this.elementSize,
  });

  static const RegistryReport _zero = ._(
    numAllocated: 0,
    numKeptFromUser: 0,
    numReleasedFromUser: 0,
    elementSize: 0,
  );

  final int numAllocated;
  final int numKeptFromUser;
  final int numReleasedFromUser;
  final int elementSize;

  ffi.Pointer<bindings.WGPURegistryReport> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPURegistryReport>();
    ptr.ref.numAllocated = numAllocated;
    ptr.ref.numKeptFromUser = numKeptFromUser;
    ptr.ref.numReleasedFromUser = numReleasedFromUser;
    ptr.ref.elementSize = elementSize;
    return ptr;
  }

  factory RegistryReport.fromNative(bindings.WGPURegistryReport str) {
    final numAllocated = str.numAllocated;
    final numKeptFromUser = str.numKeptFromUser;
    final numReleasedFromUser = str.numReleasedFromUser;
    final elementSize = str.elementSize;
    return RegistryReport._(
      numAllocated: numAllocated,
      numKeptFromUser: numKeptFromUser,
      numReleasedFromUser: numReleasedFromUser,
      elementSize: elementSize,
    );
  }
}

class HubReport {
  const HubReport({
    required this.adapters,
    required this.devices,
    required this.queues,
    required this.pipelineLayouts,
    required this.shaderModules,
    required this.bindGroupLayouts,
    required this.bindGroups,
    required this.commandBuffers,
    required this.renderBundles,
    required this.renderPipelines,
    required this.computePipelines,
    required this.querySets,
    required this.buffers,
    required this.textures,
    required this.textureViews,
    required this.samplers,
  });

  const HubReport._({
    required this.adapters,
    required this.devices,
    required this.queues,
    required this.pipelineLayouts,
    required this.shaderModules,
    required this.bindGroupLayouts,
    required this.bindGroups,
    required this.commandBuffers,
    required this.renderBundles,
    required this.renderPipelines,
    required this.computePipelines,
    required this.querySets,
    required this.buffers,
    required this.textures,
    required this.textureViews,
    required this.samplers,
  });

  static const HubReport _zero = ._(
    adapters: ._zero,
    devices: ._zero,
    queues: ._zero,
    pipelineLayouts: ._zero,
    shaderModules: ._zero,
    bindGroupLayouts: ._zero,
    bindGroups: ._zero,
    commandBuffers: ._zero,
    renderBundles: ._zero,
    renderPipelines: ._zero,
    computePipelines: ._zero,
    querySets: ._zero,
    buffers: ._zero,
    textures: ._zero,
    textureViews: ._zero,
    samplers: ._zero,
  );

  final RegistryReport adapters;
  final RegistryReport devices;
  final RegistryReport queues;
  final RegistryReport pipelineLayouts;
  final RegistryReport shaderModules;
  final RegistryReport bindGroupLayouts;
  final RegistryReport bindGroups;
  final RegistryReport commandBuffers;
  final RegistryReport renderBundles;
  final RegistryReport renderPipelines;
  final RegistryReport computePipelines;
  final RegistryReport querySets;
  final RegistryReport buffers;
  final RegistryReport textures;
  final RegistryReport textureViews;
  final RegistryReport samplers;

  ffi.Pointer<bindings.WGPUHubReport> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUHubReport>();
    ptr.ref.adapters = adapters.toNative(allocator).ref;
    ptr.ref.devices = devices.toNative(allocator).ref;
    ptr.ref.queues = queues.toNative(allocator).ref;
    ptr.ref.pipelineLayouts = pipelineLayouts.toNative(allocator).ref;
    ptr.ref.shaderModules = shaderModules.toNative(allocator).ref;
    ptr.ref.bindGroupLayouts = bindGroupLayouts.toNative(allocator).ref;
    ptr.ref.bindGroups = bindGroups.toNative(allocator).ref;
    ptr.ref.commandBuffers = commandBuffers.toNative(allocator).ref;
    ptr.ref.renderBundles = renderBundles.toNative(allocator).ref;
    ptr.ref.renderPipelines = renderPipelines.toNative(allocator).ref;
    ptr.ref.computePipelines = computePipelines.toNative(allocator).ref;
    ptr.ref.querySets = querySets.toNative(allocator).ref;
    ptr.ref.buffers = buffers.toNative(allocator).ref;
    ptr.ref.textures = textures.toNative(allocator).ref;
    ptr.ref.textureViews = textureViews.toNative(allocator).ref;
    ptr.ref.samplers = samplers.toNative(allocator).ref;
    return ptr;
  }

  factory HubReport.fromNative(bindings.WGPUHubReport str) {
    final adapters = RegistryReport.fromNative(str.adapters);
    final devices = RegistryReport.fromNative(str.devices);
    final queues = RegistryReport.fromNative(str.queues);
    final pipelineLayouts = RegistryReport.fromNative(str.pipelineLayouts);
    final shaderModules = RegistryReport.fromNative(str.shaderModules);
    final bindGroupLayouts = RegistryReport.fromNative(str.bindGroupLayouts);
    final bindGroups = RegistryReport.fromNative(str.bindGroups);
    final commandBuffers = RegistryReport.fromNative(str.commandBuffers);
    final renderBundles = RegistryReport.fromNative(str.renderBundles);
    final renderPipelines = RegistryReport.fromNative(str.renderPipelines);
    final computePipelines = RegistryReport.fromNative(str.computePipelines);
    final querySets = RegistryReport.fromNative(str.querySets);
    final buffers = RegistryReport.fromNative(str.buffers);
    final textures = RegistryReport.fromNative(str.textures);
    final textureViews = RegistryReport.fromNative(str.textureViews);
    final samplers = RegistryReport.fromNative(str.samplers);
    return HubReport._(
      adapters: adapters,
      devices: devices,
      queues: queues,
      pipelineLayouts: pipelineLayouts,
      shaderModules: shaderModules,
      bindGroupLayouts: bindGroupLayouts,
      bindGroups: bindGroups,
      commandBuffers: commandBuffers,
      renderBundles: renderBundles,
      renderPipelines: renderPipelines,
      computePipelines: computePipelines,
      querySets: querySets,
      buffers: buffers,
      textures: textures,
      textureViews: textureViews,
      samplers: samplers,
    );
  }
}

class GlobalReport {
  const GlobalReport({
    required this.surfaces,
    required this.hub,
  });

  const GlobalReport._({
    required this.surfaces,
    required this.hub,
  });

  static const GlobalReport _zero = ._(
    surfaces: ._zero,
    hub: ._zero,
  );

  final RegistryReport surfaces;
  final HubReport hub;

  ffi.Pointer<bindings.WGPUGlobalReport> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUGlobalReport>();
    ptr.ref.surfaces = surfaces.toNative(allocator).ref;
    ptr.ref.hub = hub.toNative(allocator).ref;
    return ptr;
  }

  factory GlobalReport.fromNative(bindings.WGPUGlobalReport str) {
    final surfaces = RegistryReport.fromNative(str.surfaces);
    final hub = HubReport.fromNative(str.hub);
    return GlobalReport._(
      surfaces: surfaces,
      hub: hub,
    );
  }
}

class InstanceEnumerateAdapterOptions {
  const InstanceEnumerateAdapterOptions({
    this.backends = .all,
    this.next,
  });

  const InstanceEnumerateAdapterOptions._({
    required this.backends,
    this.next,
  });

  static const InstanceEnumerateAdapterOptions _zero = ._(
    backends: .new(0),
    next: null,
  );

  final InstanceBackend backends;
  final ChainedStruct? next;

  ffi.Pointer<bindings.WGPUInstanceEnumerateAdapterOptions> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUInstanceEnumerateAdapterOptions>();
    ptr.ref.nextInChain = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.backends = backends.value;
    return ptr;
  }

  factory InstanceEnumerateAdapterOptions.fromNative(bindings.WGPUInstanceEnumerateAdapterOptions str) {
    final backends = InstanceBackend(str.backends);
    return InstanceEnumerateAdapterOptions._(
      backends: backends,
      next: ChainedStruct.fromNative(str.nextInChain),
    );
  }
}

class BindGroupEntryExtras extends ChainedStruct {
  const BindGroupEntryExtras({
    this.buffers = const [],
    this.samplers = const [],
    this.textureViews = const [],
    super.next,
  });

  const BindGroupEntryExtras._({
    required this.buffers,
    required this.samplers,
    required this.textureViews,
    super.next,
  });

  static const BindGroupEntryExtras _zero = ._(
    buffers: [],
    samplers: [],
    textureViews: [],
    next: null,
  );

  final List<Buffer> buffers;
  final List<Sampler> samplers;
  final List<TextureView> textureViews;

  @override
  int get sType => _SType.bindGroupEntryExtras.value;

  @override
  ffi.Pointer<bindings.WGPUBindGroupEntryExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUBindGroupEntryExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    if (buffers.isNotEmpty) {
      final arrayPtr = allocator<bindings.WGPUBuffer>(buffers.length);
      for (var i = 0; i < buffers.length; i++) {
        arrayPtr[i] = internalBufferGetPtr(buffers[i]).cast();
      }
      ptr.ref.buffers = arrayPtr;
      ptr.ref.bufferCount = buffers.length;
    }
    else {
      ptr.ref.buffers = ffi.nullptr;
      ptr.ref.bufferCount = 0;
    }
    if (samplers.isNotEmpty) {
      final arrayPtr = allocator<bindings.WGPUSampler>(samplers.length);
      for (var i = 0; i < samplers.length; i++) {
        arrayPtr[i] = internalSamplerGetPtr(samplers[i]).cast();
      }
      ptr.ref.samplers = arrayPtr;
      ptr.ref.samplerCount = samplers.length;
    }
    else {
      ptr.ref.samplers = ffi.nullptr;
      ptr.ref.samplerCount = 0;
    }
    if (textureViews.isNotEmpty) {
      final arrayPtr = allocator<bindings.WGPUTextureView>(textureViews.length);
      for (var i = 0; i < textureViews.length; i++) {
        arrayPtr[i] = internalTextureViewGetPtr(textureViews[i]).cast();
      }
      ptr.ref.textureViews = arrayPtr;
      ptr.ref.textureViewCount = textureViews.length;
    }
    else {
      ptr.ref.textureViews = ffi.nullptr;
      ptr.ref.textureViewCount = 0;
    }
    return ptr;
  }

  factory BindGroupEntryExtras.fromNative(bindings.WGPUBindGroupEntryExtras str) {
    final buffers = <Buffer>[];
    if (str.buffers != ffi.nullptr && str.bufferCount > 0) {
      for (var i = 0; i < str.bufferCount; i++) {
        buffers.add(internalBufferFromPtr(str.buffers[i].cast()));
      }
    }
    final samplers = <Sampler>[];
    if (str.samplers != ffi.nullptr && str.samplerCount > 0) {
      for (var i = 0; i < str.samplerCount; i++) {
        samplers.add(internalSamplerFromPtr(str.samplers[i].cast()));
      }
    }
    final textureViews = <TextureView>[];
    if (str.textureViews != ffi.nullptr && str.textureViewCount > 0) {
      for (var i = 0; i < str.textureViewCount; i++) {
        textureViews.add(internalTextureViewFromPtr(str.textureViews[i].cast()));
      }
    }
    return BindGroupEntryExtras._(
      buffers: buffers,
      samplers: samplers,
      textureViews: textureViews,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class BindGroupLayoutEntryExtras extends ChainedStruct {
  const BindGroupLayoutEntryExtras({
    required this.count,
    super.next,
  });

  const BindGroupLayoutEntryExtras._({
    required this.count,
    super.next,
  });

  static const BindGroupLayoutEntryExtras _zero = ._(
    count: 0,
    next: null,
  );

  final int count;

  @override
  int get sType => _SType.bindGroupLayoutEntryExtras.value;

  @override
  ffi.Pointer<bindings.WGPUBindGroupLayoutEntryExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUBindGroupLayoutEntryExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.count = count;
    return ptr;
  }

  factory BindGroupLayoutEntryExtras.fromNative(bindings.WGPUBindGroupLayoutEntryExtras str) {
    final count = str.count;
    return BindGroupLayoutEntryExtras._(
      count: count,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class QuerySetDescriptorExtras extends ChainedStruct {
  const QuerySetDescriptorExtras({
    this.pipelineStatistics = const [],
    super.next,
  });

  const QuerySetDescriptorExtras._({
    required this.pipelineStatistics,
    super.next,
  });

  static const QuerySetDescriptorExtras _zero = ._(
    pipelineStatistics: [],
    next: null,
  );

  final List<PipelineStatisticName> pipelineStatistics;

  @override
  int get sType => _SType.querySetDescriptorExtras.value;

  @override
  ffi.Pointer<bindings.WGPUQuerySetDescriptorExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUQuerySetDescriptorExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    if (pipelineStatistics.isNotEmpty) {
      final arrayPtr = allocator<ffi.UnsignedInt>(pipelineStatistics.length);
      for (var i = 0; i < pipelineStatistics.length; i++) {
        arrayPtr[i] = pipelineStatistics[i].value;
      }
      ptr.ref.pipelineStatistics = arrayPtr;
      ptr.ref.pipelineStatisticCount = pipelineStatistics.length;
    }
    else {
      ptr.ref.pipelineStatistics = ffi.nullptr;
      ptr.ref.pipelineStatisticCount = 0;
    }
    return ptr;
  }

  factory QuerySetDescriptorExtras.fromNative(bindings.WGPUQuerySetDescriptorExtras str) {
    final pipelineStatistics = <PipelineStatisticName>[];
    if (str.pipelineStatistics != ffi.nullptr && str.pipelineStatisticCount > 0) {
      for (var i = 0; i < str.pipelineStatisticCount; i++) {
        pipelineStatistics.add(PipelineStatisticName.fromValue(str.pipelineStatistics[i]));
      }
    }
    return QuerySetDescriptorExtras._(
      pipelineStatistics: pipelineStatistics,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class SurfaceConfigurationExtras extends ChainedStruct {
  const SurfaceConfigurationExtras({
    required this.desiredMaximumFrameLatency,
    super.next,
  });

  const SurfaceConfigurationExtras._({
    required this.desiredMaximumFrameLatency,
    super.next,
  });

  static const SurfaceConfigurationExtras _zero = ._(
    desiredMaximumFrameLatency: 0,
    next: null,
  );

  final int desiredMaximumFrameLatency;

  @override
  int get sType => _SType.surfaceConfigurationExtras.value;

  @override
  ffi.Pointer<bindings.WGPUSurfaceConfigurationExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUSurfaceConfigurationExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.desiredMaximumFrameLatency = desiredMaximumFrameLatency;
    return ptr;
  }

  factory SurfaceConfigurationExtras.fromNative(bindings.WGPUSurfaceConfigurationExtras str) {
    final desiredMaximumFrameLatency = str.desiredMaximumFrameLatency;
    return SurfaceConfigurationExtras._(
      desiredMaximumFrameLatency: desiredMaximumFrameLatency,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class SurfaceSourceSwapChainPanel extends ChainedStruct {
  const SurfaceSourceSwapChainPanel({
    required this.panelNative,
    super.next,
  });

  const SurfaceSourceSwapChainPanel._({
    required this.panelNative,
    super.next,
  });

  static const SurfaceSourceSwapChainPanel _zero = ._(
    panelNative: null,
    next: null,
  );

  final ffi.Pointer<ffi.Void>? panelNative;

  @override
  int get sType => _SType.surfaceSourceSwapChainPanel.value;

  @override
  ffi.Pointer<bindings.WGPUSurfaceSourceSwapChainPanel> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUSurfaceSourceSwapChainPanel>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    if (panelNative != null) ptr.ref.panelNative = panelNative!;
    return ptr;
  }

  factory SurfaceSourceSwapChainPanel.fromNative(bindings.WGPUSurfaceSourceSwapChainPanel str) {
    final panelNative = str.panelNative;
    return SurfaceSourceSwapChainPanel._(
      panelNative: panelNative,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

class PrimitiveStateExtras extends ChainedStruct {
  const PrimitiveStateExtras({
    this.polygonMode = .fill,
    required this.conservative,
    super.next,
  });

  const PrimitiveStateExtras._({
    required this.polygonMode,
    required this.conservative,
    super.next,
  });

  static const PrimitiveStateExtras _zero = ._(
    polygonMode: .fill,
    conservative: false,
    next: null,
  );

  final PolygonMode polygonMode;
  final bool conservative;

  @override
  int get sType => _SType.primitiveStateExtras.value;

  @override
  ffi.Pointer<bindings.WGPUPrimitiveStateExtras> toNative(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUPrimitiveStateExtras>();
    ptr.ref.chain.sTypeAsInt = sType;
    ptr.ref.chain.next = next?.toNative(allocator).cast() ?? ffi.nullptr;

    ptr.ref.polygonModeAsInt = polygonMode.value;
    ptr.ref.conservative = conservative ? 1 : 0;
    return ptr;
  }

  factory PrimitiveStateExtras.fromNative(bindings.WGPUPrimitiveStateExtras str) {
    final polygonMode = PolygonMode.fromNative(str.polygonMode);
    final conservative = str.conservative == 1;
    return PrimitiveStateExtras._(
      polygonMode: polygonMode,
      conservative: conservative,
      next: ChainedStruct.fromNative(str.chain.next),
    );
  }
}

typedef LogCallback = void Function(LogLevel level, String message);
void _logCallbackTrampoline(int _level, bindings.WGPUStringView _message, ffi.Pointer<ffi.Void> userdata1) {
  final handler = _LogCallbackRegistry.instance.lookup(userdata1);
  if (handler == null) return;
  final level = LogLevel.fromValue(_level);
  final message = _message.toDartString();
  handler(level, message);
}

class _LogCallbackRegistry extends _CallbackRegistry<LogCallback, ffi.NativeFunction<bindings.WGPULogCallbackFunction>> {
  static final instance = _LogCallbackRegistry();

  @override
  ffi.Pointer<ffi.NativeFunction<bindings.WGPULogCallbackFunction>> get nativeFunction => _callable.nativeFunction;
  final ffi.NativeCallable<bindings.WGPULogCallbackFunction> _callable = .isolateLocal(_logCallbackTrampoline);
}

class LogListener extends _CallbackListener<LogCallback, ffi.NativeFunction<bindings.WGPULogCallbackFunction>> {
  LogListener(LogCallback handler): super(handler, _LogCallbackRegistry.instance);
}

ChainedStruct? WGPUNative_ChainedStructFromNative(ffi.Pointer<bindings.WGPUChainedStruct> ptr) {
  if (ptr == ffi.nullptr) return null;
  final stype = ptr.ref.sTypeAsInt;
  return switch (stype) {
    196609 => DeviceExtras.fromNative(ptr.cast<bindings.WGPUDeviceExtras>().ref),
    196610 => NativeLimits.fromNative(ptr.cast<bindings.WGPUNativeLimits>().ref),
    196611 => PipelineLayoutExtras.fromNative(ptr.cast<bindings.WGPUPipelineLayoutExtras>().ref),
    196612 => ShaderSourceGLSL.fromNative(ptr.cast<bindings.WGPUShaderSourceGLSL>().ref),
    196614 => InstanceExtras.fromNative(ptr.cast<bindings.WGPUInstanceExtras>().ref),
    196615 => BindGroupEntryExtras.fromNative(ptr.cast<bindings.WGPUBindGroupEntryExtras>().ref),
    196616 => BindGroupLayoutEntryExtras.fromNative(ptr.cast<bindings.WGPUBindGroupLayoutEntryExtras>().ref),
    196617 => QuerySetDescriptorExtras.fromNative(ptr.cast<bindings.WGPUQuerySetDescriptorExtras>().ref),
    196618 => SurfaceConfigurationExtras.fromNative(ptr.cast<bindings.WGPUSurfaceConfigurationExtras>().ref),
    196619 => SurfaceSourceSwapChainPanel.fromNative(ptr.cast<bindings.WGPUSurfaceSourceSwapChainPanel>().ref),
    196620 => PrimitiveStateExtras.fromNative(ptr.cast<bindings.WGPUPrimitiveStateExtras>().ref),
    _ => throw ArgumentError('Unknown chained struct type: $stype'),
  };
}


// {NULL, WGPU_STRLEN}: the null value.
// {non_null_pointer, WGPU_STRLEN}: a null-terminated string view.
// {any, 0}: the empty string.
// {NULL, non_zero_length}: not allowed (null dereference).
// {non_null_pointer, non_zero_length}: an explictly-sized string view with
// size non_zero_length (in bytes).
extension _StringViewExt on bindings.WGPUStringView {
  String toDartString() {
    if (data == ffi.nullptr) return '';
    if (length == STRLEN) return data.cast<Utf8>().toDartString();
    if (length == 0) return '';
    return data.cast<Utf8>().toDartString(length: length);
  }
}

extension _StringExt on String {
  bindings.WGPUStringView toStringView(ffi.Allocator allocator) {
    final ptr = allocator<bindings.WGPUStringView>();
    final data = toNativeUtf8(allocator: allocator);

    ptr.ref.data = data.cast();
    ptr.ref.length = length;

    return ptr.ref;
  }
}

abstract class _CallbackRegistry<T extends Function, TN extends ffi.NativeFunction> {
  int _nextId = 1;
  final Map<int, T> _futures = {};
  final Map<int, T> _repeating = {};

  CallbackMode get callbackMode => .waitAnyOnly;

  ffi.Pointer<ffi.Void> register(T handler) {
    final id = _nextId++;
    _futures[id] = handler;
    return ffi.Pointer<ffi.Void>.fromAddress(id);
  }

  void unregister(ffi.Pointer<ffi.Void> handle) {
    final id = handle.address;
    _futures.remove(id);
    _repeating.remove(id);
  }

  T? lookup(ffi.Pointer<ffi.Void> handle) {
    final id = handle.address;
    final future = _futures.remove(id);
    if (future != null) return future;
    return _repeating[id];
  }

  ffi.Pointer<TN> get nativeFunction;
}

abstract class _CallbackListener<T extends Function, TN extends ffi.NativeFunction> {
  _CallbackListener(T handler, this._registry) : _id = _registry.register(handler).address;

  final int _id;
  final _CallbackRegistry<T, TN> _registry;
  bool _cancelled = false;

  ffi.Pointer<TN> get nativeFunction => _registry.nativeFunction;
  ffi.Pointer<ffi.Void> get userdata => .fromAddress(_id);

  CallbackMode get callbackMode => .waitAnyOnly;

  void cancel() {
    if (_cancelled) return;
    _cancelled = true;
  }
}

abstract class _Opaque<T extends ffi.NativeType> implements ffi.Finalizable {
  _Opaque._(this.__ptr) { _finalizer.attach(this, __ptr.cast(), detach: this); }
  _Opaque._borrowed(this.__ptr);

  ffi.Pointer<T> __ptr;

  ffi.Pointer<T> get _ptr {
    if (__ptr.address == 0) throw StateError('pointer is null');
    return __ptr;
  }

  ffi.NativeFinalizer get _finalizer;

  void _dispose(void Function(ffi.Pointer<T>) deleter) {
    if (__ptr.address != 0) {
      _finalizer.detach(this);
      deleter(__ptr);
      __ptr = ffi.nullptr;
    }
  }

  void dispose();
}

class _AsyncResult<T> {
  _AsyncResult();

  T? result;
  (Object, StackTrace)? err;
  var done = false;

  void complete(T value) {
    result = value;
    done = true;
  }

  void completeError(Object error, StackTrace stackTrace) {
    err = (error, stackTrace);
    done = true;
  }

  Future<T> waitUntilDone(void Function() poll) async {
    await Future<void>.delayed(.zero);
    while (!done) {
      poll();
      await Future<void>.delayed(.zero);
    }
    if (err != null) Error.throwWithStackTrace(err!.$1, err!.$2);
    return result as dynamic;
  }
}

class _SyncResult<T> {
  _SyncResult();

  T? result;
  (Object, StackTrace)? err;
  var done = false;

  void complete(T value) {
    result = value;
    done = true;
  }

  void completeError(Object error, StackTrace stackTrace) {
    err = (error, stackTrace);
    done = true;
  }

  T waitUntilDone(void Function() poll) {
    while (!done) poll();
    if (err != null) Error.throwWithStackTrace(err!.$1, err!.$2);
    return result as dynamic;
  }
}

// dart format on