// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by wgslgen

import 'dart:typed_data';
import 'package:wgpu/wgpu.dart' as wgpu;
import 'package:wgpu/wgsl.dart' as wgsl;
import 'package:wgpu/wgsl_meta.dart' as meta;

@meta.Overrides()
extension type const Overrides._(() _) {
  const Overrides(): this._(());

  List<wgpu.ConstantEntry> get entries => const [];
}

typedef F32Array6 = (double, double, double, double, double, double);
typedef F32Array6Internal = (wgsl.F32, wgsl.F32, wgsl.F32, wgsl.F32, wgsl.F32, wgsl.F32);

typedef Cubic2Array3 = ((wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3));
typedef Cubic2Array3Internal = ((wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3));

typedef F32Array3 = (double, double, double);
typedef F32Array3Internal = (wgsl.F32, wgsl.F32, wgsl.F32);

typedef Cubic2 = (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3);
typedef Cubic2Internal = (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3);

extension Cubic2Ext on Cubic2 {
  wgsl.Vec2f get p0 => this.$1;
  wgsl.Vec2f get p1 => this.$2;
  wgsl.Vec2f get p2 => this.$3;
  wgsl.Vec2f get p3 => this.$4;

  @pragma('vm:prefer-inline')
  Cubic2Internal get asInternal => (
    p0,
    p1,
    p2,
    p3,
  );
}

extension Cubic2InternalExt on Cubic2Internal {
  wgsl.Vec2f get p0 => this.$1;
  wgsl.Vec2f get p1 => this.$2;
  wgsl.Vec2f get p2 => this.$3;
  wgsl.Vec2f get p3 => this.$4;

  @pragma('vm:prefer-inline')
  Cubic2 get asDart => (
    this.$1,
    this.$2,
    this.$3,
    this.$4,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    this.$1.write(data, offset + 0);
    this.$2.write(data, offset + 8);
    this.$3.write(data, offset + 16);
    this.$4.write(data, offset + 24);
  }
}

extension Cubic2Struct on Cubic2 {
  @pragma('vm:prefer-inline')
  static Cubic2Internal read(ByteData data, int offset) => (
    wgsl.Vec2f.read(data, offset + 0),
    wgsl.Vec2f.read(data, offset + 8),
    wgsl.Vec2f.read(data, offset + 16),
    wgsl.Vec2f.read(data, offset + 24),
  );

}

typedef Cubic2InflectionsResult = (int count, wgsl.Vec2f t);
typedef Cubic2InflectionsResultInternal = (wgsl.U32 count, wgsl.Vec2f t);

extension Cubic2InflectionsResultExt on Cubic2InflectionsResult {
  int get count => this.$1;
  wgsl.Vec2f get t => this.$2;

  @pragma('vm:prefer-inline')
  Cubic2InflectionsResultInternal get asInternal => (
    .new(count),
    t,
  );
}

extension Cubic2InflectionsResultInternalExt on Cubic2InflectionsResultInternal {
  wgsl.U32 get count => this.$1;
  wgsl.Vec2f get t => this.$2;

  @pragma('vm:prefer-inline')
  Cubic2InflectionsResult get asDart => (
    this.$1,
    this.$2,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.U32(this.$1).write(data, offset + 0);
    this.$2.write(data, offset + 8);
  }
}

extension Cubic2InflectionsResultStruct on Cubic2InflectionsResult {
  @pragma('vm:prefer-inline')
  static Cubic2InflectionsResultInternal read(ByteData data, int offset) => (
    wgsl.U32.read(data, offset + 0),
    wgsl.Vec2f.read(data, offset + 8),
  );

}

typedef Extrema1D = (int count, wgsl.Vec2f t);
typedef Extrema1DInternal = (wgsl.U32 count, wgsl.Vec2f t);

extension Extrema1DExt on Extrema1D {
  int get count => this.$1;
  wgsl.Vec2f get t => this.$2;

  @pragma('vm:prefer-inline')
  Extrema1DInternal get asInternal => (
    .new(count),
    t,
  );
}

extension Extrema1DInternalExt on Extrema1DInternal {
  wgsl.U32 get count => this.$1;
  wgsl.Vec2f get t => this.$2;

  @pragma('vm:prefer-inline')
  Extrema1D get asDart => (
    this.$1,
    this.$2,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.U32(this.$1).write(data, offset + 0);
    this.$2.write(data, offset + 8);
  }
}

extension Extrema1DStruct on Extrema1D {
  @pragma('vm:prefer-inline')
  static Extrema1DInternal read(ByteData data, int offset) => (
    wgsl.U32.read(data, offset + 0),
    wgsl.Vec2f.read(data, offset + 8),
  );

}

typedef Extrema2D = (int count, wgsl.Vec4f t);
typedef Extrema2DInternal = (wgsl.U32 count, wgsl.Vec4f t);

extension Extrema2DExt on Extrema2D {
  int get count => this.$1;
  wgsl.Vec4f get t => this.$2;

  @pragma('vm:prefer-inline')
  Extrema2DInternal get asInternal => (
    .new(count),
    t,
  );
}

extension Extrema2DInternalExt on Extrema2DInternal {
  wgsl.U32 get count => this.$1;
  wgsl.Vec4f get t => this.$2;

  @pragma('vm:prefer-inline')
  Extrema2D get asDart => (
    this.$1,
    this.$2,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.U32(this.$1).write(data, offset + 0);
    this.$2.write(data, offset + 16);
  }
}

extension Extrema2DStruct on Extrema2D {
  @pragma('vm:prefer-inline')
  static Extrema2DInternal read(ByteData data, int offset) => (
    wgsl.U32.read(data, offset + 0),
    wgsl.Vec4f.read(data, offset + 16),
  );

}

typedef Cubic2KeyPointsResult = (F32Array6 t, int count);
typedef Cubic2KeyPointsResultInternal = (F32Array6Internal t, wgsl.U32 count);

extension Cubic2KeyPointsResultExt on Cubic2KeyPointsResult {
  (double, double, double, double, double, double) get t => this.$1;
  int get count => this.$2;

  @pragma('vm:prefer-inline')
  Cubic2KeyPointsResultInternal get asInternal => (
    (.new(t.$1), .new(t.$2), .new(t.$3), .new(t.$4), .new(t.$5), .new(t.$6)),
    .new(count),
  );
}

extension Cubic2KeyPointsResultInternalExt on Cubic2KeyPointsResultInternal {
  (wgsl.F32, wgsl.F32, wgsl.F32, wgsl.F32, wgsl.F32, wgsl.F32) get t => this.$1;
  wgsl.U32 get count => this.$2;

  @pragma('vm:prefer-inline')
  Cubic2KeyPointsResult get asDart => (
    (this.$1.$1, this.$1.$2, this.$1.$3, this.$1.$4, this.$1.$5, this.$1.$6),
    this.$2,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.F32(this.$1.$1).write(data, offset + 0 + 0 * 4);
    wgsl.F32(this.$1.$2).write(data, offset + 0 + 1 * 4);
    wgsl.F32(this.$1.$3).write(data, offset + 0 + 2 * 4);
    wgsl.F32(this.$1.$4).write(data, offset + 0 + 3 * 4);
    wgsl.F32(this.$1.$5).write(data, offset + 0 + 4 * 4);
    wgsl.F32(this.$1.$6).write(data, offset + 0 + 5 * 4);
    wgsl.U32(this.$2).write(data, offset + 24);
  }
}

extension Cubic2KeyPointsResultStruct on Cubic2KeyPointsResult {
  @pragma('vm:prefer-inline')
  static Cubic2KeyPointsResultInternal read(ByteData data, int offset) => (
    (
      wgsl.F32.read(data, offset + 0 + 0 * 4),
      wgsl.F32.read(data, offset + 0 + 1 * 4),
      wgsl.F32.read(data, offset + 0 + 2 * 4),
      wgsl.F32.read(data, offset + 0 + 3 * 4),
      wgsl.F32.read(data, offset + 0 + 4 * 4),
      wgsl.F32.read(data, offset + 0 + 5 * 4),
    ),
    wgsl.U32.read(data, offset + 24),
  );

}

typedef Cubic2ChopAtInflectionsResult = (Cubic2Array3 cubics, F32Array3 t0, F32Array3 t1, int count);
typedef Cubic2ChopAtInflectionsResultInternal = (Cubic2Array3Internal cubics, F32Array3Internal t0, F32Array3Internal t1, wgsl.U32 count);

extension Cubic2ChopAtInflectionsResultExt on Cubic2ChopAtInflectionsResult {
  ((wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3)) get cubics => this.$1;
  (double, double, double) get t0 => this.$2;
  (double, double, double) get t1 => this.$3;
  int get count => this.$4;

  @pragma('vm:prefer-inline')
  Cubic2ChopAtInflectionsResultInternal get asInternal => (
    cubics,
    (.new(t0.$1), .new(t0.$2), .new(t0.$3)),
    (.new(t1.$1), .new(t1.$2), .new(t1.$3)),
    .new(count),
  );
}

extension Cubic2ChopAtInflectionsResultInternalExt on Cubic2ChopAtInflectionsResultInternal {
  ((wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3), (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3)) get cubics => this.$1;
  (wgsl.F32, wgsl.F32, wgsl.F32) get t0 => this.$2;
  (wgsl.F32, wgsl.F32, wgsl.F32) get t1 => this.$3;
  wgsl.U32 get count => this.$4;

  @pragma('vm:prefer-inline')
  Cubic2ChopAtInflectionsResult get asDart => (
    this.$1,
    (this.$2.$1, this.$2.$2, this.$2.$3),
    (this.$3.$1, this.$3.$2, this.$3.$3),
    this.$4,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    this.$1.$1.asInternal.write(data, offset + 0 + 0 * 32);
    this.$1.$2.asInternal.write(data, offset + 0 + 1 * 32);
    this.$1.$3.asInternal.write(data, offset + 0 + 2 * 32);
    wgsl.F32(this.$2.$1).write(data, offset + 96 + 0 * 4);
    wgsl.F32(this.$2.$2).write(data, offset + 96 + 1 * 4);
    wgsl.F32(this.$2.$3).write(data, offset + 96 + 2 * 4);
    wgsl.F32(this.$3.$1).write(data, offset + 108 + 0 * 4);
    wgsl.F32(this.$3.$2).write(data, offset + 108 + 1 * 4);
    wgsl.F32(this.$3.$3).write(data, offset + 108 + 2 * 4);
    wgsl.U32(this.$4).write(data, offset + 120);
  }
}

extension Cubic2ChopAtInflectionsResultStruct on Cubic2ChopAtInflectionsResult {
  @pragma('vm:prefer-inline')
  static Cubic2ChopAtInflectionsResultInternal read(ByteData data, int offset) => (
    (
      Cubic2Struct.read(data, offset + 0 + 0 * 32),
      Cubic2Struct.read(data, offset + 0 + 1 * 32),
      Cubic2Struct.read(data, offset + 0 + 2 * 32),
    ),
    (
      wgsl.F32.read(data, offset + 96 + 0 * 4),
      wgsl.F32.read(data, offset + 96 + 1 * 4),
      wgsl.F32.read(data, offset + 96 + 2 * 4),
    ),
    (
      wgsl.F32.read(data, offset + 108 + 0 * 4),
      wgsl.F32.read(data, offset + 108 + 1 * 4),
      wgsl.F32.read(data, offset + 108 + 2 * 4),
    ),
    wgsl.U32.read(data, offset + 120),
  );

}

typedef Uniforms = (int cubicCount, int weightAnchorCount, double tolerance, wgsl.Vec2f screenSize, wgsl.Mat4x4f transform);
typedef UniformsInternal = (wgsl.U32 cubicCount, wgsl.U32 weightAnchorCount, wgsl.F32 tolerance, wgsl.Vec2f screenSize, wgsl.Mat4x4f transform);

extension UniformsExt on Uniforms {
  int get cubicCount => this.$1;
  int get weightAnchorCount => this.$2;
  double get tolerance => this.$3;
  wgsl.Vec2f get screenSize => this.$4;
  wgsl.Mat4x4f get transform => this.$5;

  @pragma('vm:prefer-inline')
  UniformsInternal get asInternal => (
    .new(cubicCount),
    .new(weightAnchorCount),
    .new(tolerance),
    screenSize,
    transform,
  );
}

extension UniformsInternalExt on UniformsInternal {
  wgsl.U32 get cubicCount => this.$1;
  wgsl.U32 get weightAnchorCount => this.$2;
  wgsl.F32 get tolerance => this.$3;
  wgsl.Vec2f get screenSize => this.$4;
  wgsl.Mat4x4f get transform => this.$5;

  @pragma('vm:prefer-inline')
  Uniforms get asDart => (
    this.$1,
    this.$2,
    this.$3,
    this.$4,
    this.$5,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.U32(this.$1).write(data, offset + 0);
    wgsl.U32(this.$2).write(data, offset + 4);
    wgsl.F32(this.$3).write(data, offset + 8);
    this.$4.write(data, offset + 16);
    this.$5.write(data, offset + 32);
  }
}

extension UniformsStruct on Uniforms {
  @pragma('vm:prefer-inline')
  static UniformsInternal read(ByteData data, int offset) => (
    wgsl.U32.read(data, offset + 0),
    wgsl.U32.read(data, offset + 4),
    wgsl.F32.read(data, offset + 8),
    wgsl.Vec2f.read(data, offset + 16),
    wgsl.Mat4x4f.read(data, offset + 32),
  );

}

typedef VertexData = (wgsl.Vec2f pos, wgsl.Vec2u incidentEdgesSpan);
typedef VertexDataInternal = (wgsl.Vec2f pos, wgsl.Vec2u incidentEdgesSpan);

extension VertexDataExt on VertexData {
  wgsl.Vec2f get pos => this.$1;
  wgsl.Vec2u get incidentEdgesSpan => this.$2;

  @pragma('vm:prefer-inline')
  VertexDataInternal get asInternal => (
    pos,
    incidentEdgesSpan,
  );
}

extension VertexDataInternalExt on VertexDataInternal {
  wgsl.Vec2f get pos => this.$1;
  wgsl.Vec2u get incidentEdgesSpan => this.$2;

  @pragma('vm:prefer-inline')
  VertexData get asDart => (
    this.$1,
    this.$2,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    this.$1.write(data, offset + 0);
    this.$2.write(data, offset + 8);
  }
}

extension VertexDataStruct on VertexData {
  @pragma('vm:prefer-inline')
  static VertexDataInternal read(ByteData data, int offset) => (
    wgsl.Vec2f.read(data, offset + 0),
    wgsl.Vec2u.read(data, offset + 8),
  );

}

typedef EdgeData = (int startVertexIdx, int endVertexIdx, wgsl.Vec2u cubicsSpan, wgsl.Vec2u weightSpan, double width, double arcLength, wgsl.Vec4f color);
typedef EdgeDataInternal = (wgsl.U32 startVertexIdx, wgsl.U32 endVertexIdx, wgsl.Vec2u cubicsSpan, wgsl.Vec2u weightSpan, wgsl.F32 width, wgsl.F32 arcLength, wgsl.Vec4f color);

extension EdgeDataExt on EdgeData {
  int get startVertexIdx => this.$1;
  int get endVertexIdx => this.$2;
  wgsl.Vec2u get cubicsSpan => this.$3;
  wgsl.Vec2u get weightSpan => this.$4;
  double get width => this.$5;
  double get arcLength => this.$6;
  wgsl.Vec4f get color => this.$7;

  @pragma('vm:prefer-inline')
  EdgeDataInternal get asInternal => (
    .new(startVertexIdx),
    .new(endVertexIdx),
    cubicsSpan,
    weightSpan,
    .new(width),
    .new(arcLength),
    color,
  );
}

extension EdgeDataInternalExt on EdgeDataInternal {
  wgsl.U32 get startVertexIdx => this.$1;
  wgsl.U32 get endVertexIdx => this.$2;
  wgsl.Vec2u get cubicsSpan => this.$3;
  wgsl.Vec2u get weightSpan => this.$4;
  wgsl.F32 get width => this.$5;
  wgsl.F32 get arcLength => this.$6;
  wgsl.Vec4f get color => this.$7;

  @pragma('vm:prefer-inline')
  EdgeData get asDart => (
    this.$1,
    this.$2,
    this.$3,
    this.$4,
    this.$5,
    this.$6,
    this.$7,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.U32(this.$1).write(data, offset + 0);
    wgsl.U32(this.$2).write(data, offset + 4);
    this.$3.write(data, offset + 8);
    this.$4.write(data, offset + 16);
    wgsl.F32(this.$5).write(data, offset + 24);
    wgsl.F32(this.$6).write(data, offset + 28);
    this.$7.write(data, offset + 32);
  }
}

extension EdgeDataStruct on EdgeData {
  @pragma('vm:prefer-inline')
  static EdgeDataInternal read(ByteData data, int offset) => (
    wgsl.U32.read(data, offset + 0),
    wgsl.U32.read(data, offset + 4),
    wgsl.Vec2u.read(data, offset + 8),
    wgsl.Vec2u.read(data, offset + 16),
    wgsl.F32.read(data, offset + 24),
    wgsl.F32.read(data, offset + 28),
    wgsl.Vec4f.read(data, offset + 32),
  );

}

typedef CubicData = (Cubic2 cubic, int edgeIdx, int edgeSegmentIdx, int edgeSegmentCount, double edgeStartArcLength, double opacity);
typedef CubicDataInternal = (Cubic2Internal cubic, wgsl.U32 edgeIdx, wgsl.U32 edgeSegmentIdx, wgsl.U32 edgeSegmentCount, wgsl.F32 edgeStartArcLength, wgsl.F32 opacity);

extension CubicDataExt on CubicData {
  (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3) get cubic => this.$1;
  int get edgeIdx => this.$2;
  int get edgeSegmentIdx => this.$3;
  int get edgeSegmentCount => this.$4;
  double get edgeStartArcLength => this.$5;
  double get opacity => this.$6;

  @pragma('vm:prefer-inline')
  CubicDataInternal get asInternal => (
    cubic,
    .new(edgeIdx),
    .new(edgeSegmentIdx),
    .new(edgeSegmentCount),
    .new(edgeStartArcLength),
    .new(opacity),
  );
}

extension CubicDataInternalExt on CubicDataInternal {
  (wgsl.Vec2f p0, wgsl.Vec2f p1, wgsl.Vec2f p2, wgsl.Vec2f p3) get cubic => this.$1;
  wgsl.U32 get edgeIdx => this.$2;
  wgsl.U32 get edgeSegmentIdx => this.$3;
  wgsl.U32 get edgeSegmentCount => this.$4;
  wgsl.F32 get edgeStartArcLength => this.$5;
  wgsl.F32 get opacity => this.$6;

  @pragma('vm:prefer-inline')
  CubicData get asDart => (
    this.$1,
    this.$2,
    this.$3,
    this.$4,
    this.$5,
    this.$6,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    this.$1.asInternal.write(data, offset + 0);
    wgsl.U32(this.$2).write(data, offset + 32);
    wgsl.U32(this.$3).write(data, offset + 36);
    wgsl.U32(this.$4).write(data, offset + 40);
    wgsl.F32(this.$5).write(data, offset + 44);
    wgsl.F32(this.$6).write(data, offset + 48);
  }
}

extension CubicDataStruct on CubicData {
  @pragma('vm:prefer-inline')
  static CubicDataInternal read(ByteData data, int offset) => (
    Cubic2Struct.read(data, offset + 0),
    wgsl.U32.read(data, offset + 32),
    wgsl.U32.read(data, offset + 36),
    wgsl.U32.read(data, offset + 40),
    wgsl.F32.read(data, offset + 44),
    wgsl.F32.read(data, offset + 48),
  );

}

typedef RenderGeometry = (wgsl.Vec2f v0, wgsl.Vec2f v1, wgsl.Vec2f v2, wgsl.Vec2f v3, wgsl.Vec4f color, int zIndex, int kind);
typedef RenderGeometryInternal = (wgsl.Vec2f v0, wgsl.Vec2f v1, wgsl.Vec2f v2, wgsl.Vec2f v3, wgsl.Vec4f color, wgsl.U32 zIndex, wgsl.U32 kind);

extension RenderGeometryExt on RenderGeometry {
  wgsl.Vec2f get v0 => this.$1;
  wgsl.Vec2f get v1 => this.$2;
  wgsl.Vec2f get v2 => this.$3;
  wgsl.Vec2f get v3 => this.$4;
  wgsl.Vec4f get color => this.$5;
  int get zIndex => this.$6;
  int get kind => this.$7;

  @pragma('vm:prefer-inline')
  RenderGeometryInternal get asInternal => (
    v0,
    v1,
    v2,
    v3,
    color,
    .new(zIndex),
    .new(kind),
  );
}

extension RenderGeometryInternalExt on RenderGeometryInternal {
  wgsl.Vec2f get v0 => this.$1;
  wgsl.Vec2f get v1 => this.$2;
  wgsl.Vec2f get v2 => this.$3;
  wgsl.Vec2f get v3 => this.$4;
  wgsl.Vec4f get color => this.$5;
  wgsl.U32 get zIndex => this.$6;
  wgsl.U32 get kind => this.$7;

  @pragma('vm:prefer-inline')
  RenderGeometry get asDart => (
    this.$1,
    this.$2,
    this.$3,
    this.$4,
    this.$5,
    this.$6,
    this.$7,
  );

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    this.$1.write(data, offset + 0);
    this.$2.write(data, offset + 8);
    this.$3.write(data, offset + 16);
    this.$4.write(data, offset + 24);
    this.$5.write(data, offset + 32);
    wgsl.U32(this.$6).write(data, offset + 48);
    wgsl.U32(this.$7).write(data, offset + 52);
  }
}

extension RenderGeometryStruct on RenderGeometry {
  @pragma('vm:prefer-inline')
  static RenderGeometryInternal read(ByteData data, int offset) => (
    wgsl.Vec2f.read(data, offset + 0),
    wgsl.Vec2f.read(data, offset + 8),
    wgsl.Vec2f.read(data, offset + 16),
    wgsl.Vec2f.read(data, offset + 24),
    wgsl.Vec4f.read(data, offset + 32),
    wgsl.U32.read(data, offset + 48),
    wgsl.U32.read(data, offset + 52),
  );

}

@meta.ShaderSource('flatten_old.wgsl')
const String _shaderSource = r'''
// import "shared/cubic2.wgsl"
// A cubic bezier curve.
struct Cubic2 {
  p0: vec2f,
  p1: vec2f,
  p2: vec2f,
  p3: vec2f,
}

fn cubic2_transform(c: Cubic2, m: mat4x4f) -> Cubic2 {
  return Cubic2(
    (m * vec4f(c.p0, 0.0, 1.0)).xy,
    (m * vec4f(c.p1, 0.0, 1.0)).xy,
    (m * vec4f(c.p2, 0.0, 1.0)).xy,
    (m * vec4f(c.p3, 0.0, 1.0)).xy
  );
}

// #region Evaluation

// Evaluates the cubic bezier at parameter [t].
fn cubic2_pos(c: Cubic2, t: f32) -> vec2f {
  let mt = 1.0 - t;
  let mt2 = mt * mt;
  let t2 = t * t;

  return c.p0 * (mt2 * mt) + c.p1 * (3.0 * mt2 * t) + c.p2 * (3.0 * mt * t2) + c.p3 * (t2 * t);
}

// Evaluates the tangent of the cubic bezier at parameter [t].
fn cubic2_tan(c: Cubic2, t: f32) -> vec2f {
  let mt = 1.0 - t;
  let mt2 = mt * mt;
  let t2 = t * t;

  return (c.p1 - c.p0) * (3.0 * mt2) + (c.p2 - c.p1) * (6.0 * mt * t) + (c.p3 - c.p2) * (3.0 * t2);
}

// Evaluates the acceleration of the cubic bezier at parameter [t].
fn cubic2_acc(c: Cubic2, t: f32) -> vec2f {
  let mt = 1.0 - t;
  return (c.p2 - 2.0 * c.p1 + c.p0) * (6.0 * mt) + (c.p3 - 2.0 * c.p2 + c.p1) * (6.0 * t);
}

// Evaluates the position and the tangent of the cubic bezier at parameter [t] as (pos.x, pos.y, tan.x, tan.y).
fn cubic2_pos_tan(c: Cubic2, t: f32) -> vec4f {
  let mt = 1.0 - t;
  let mt2 = mt * mt;
  let t2 = t * t;

  let pos = c.p0 * (mt2 * mt) + c.p1 * (3.0 * mt2 * t) + c.p2 * (3.0 * mt * t2) + c.p3 * (t2 * t);
  let tan = (c.p1 - c.p0) * (3.0 * mt2) + (c.p2 - c.p1) * (6.0 * mt * t) + (c.p3 - c.p2) * (3.0 * t2);

  return vec4f(pos, tan);
}

// Evalutes the signed curvature of the cubic at parameter [t].
fn cubic2_signed_curvature(c: Cubic2, t: f32) -> f32 {
  let tan = cubic2_tan(c, t);
  let acc = cubic2_acc(c, t);
  let cross = tan.x * acc.y - tan.y * acc.x;
  let speed = length(tan);
  let speed3 = speed * speed * speed;
  if (speed3 < 1.0e-9) { return 0.0; }
  return cross / speed3;
}

// Evaluates the center of curvature of the cubic at parameter [t].
fn cubic2_curvature_center(c: Cubic2, t: f32) -> vec2f {
  let pos_tan = cubic2_pos_tan(c, t);
  let pos = pos_tan.xy;
  let tan = normalize(pos_tan.zw);
  let normal = vec2f(-tan.y, tan.x);

  let k = cubic2_signed_curvature(c, t);
  if (abs(k) < 1.0e-5) { return pos + normal * (1.0e6 * sign(k)); }

  let radius = 1.0 / k;
  return pos + normal * radius;
}

// #endregion

// #region Key metrics

struct Cubic2InflectionsResult {
  count: u32,
  t: vec2f,
}

// Returns the number of inflection points and their parameter values.
fn cubic2_inflections(c: Cubic2) -> Cubic2InflectionsResult {
  const T_EPS = 1.0e-4;

  let A = c.p1 - c.p0;
  let B = c.p2 - 2.0 * c.p1 + c.p0;
  let C = c.p3 - 3.0 * c.p2 + 3.0 * c.p1 - c.p0;

  let a = B.x * C.y - B.y * C.x;
  let b = A.x * C.y - A.y * C.x;
  let c_ = A.x * B.y - A.y * B.x;

  var root_count = 0u;
  var roots = vec2f(-1.0);

  if (abs(a) < 1.0e-5) {
    if (abs(b) > 1.0e-5) {
      let t = -c_ / b;
      if (t > T_EPS && t < 1.0 - T_EPS) {
        roots[0] = t;
        root_count = 1u;
      }
    }
  }
  else {
    let disc = b * b - 4.0 * a * c_;
    if (disc >= 0.0) {
      let sqrt_disc = sqrt(disc);
      let t1 = (-b + sqrt_disc) / (2.0 * a);
      let t2 = (-b - sqrt_disc) / (2.0 * a);
      
      if (t1 > T_EPS && t1 < 1.0 - T_EPS) {
        roots[root_count] = t1;
        root_count++;
      }
      if (disc > 1.0e-6 && t2 > T_EPS && t2 < 1.0 - T_EPS) {
        roots[root_count] = t2;
        root_count++;
      }
    }
  }

  if (root_count == 2u && roots[0] > roots[1]) {
    let temp = roots[0];
    roots[0] = roots[1];
    roots[1] = temp;
  }

  return Cubic2InflectionsResult(root_count, roots);
}


struct Extrema1D { count: u32, t: vec2f }
struct Extrema2D { count: u32, t: vec4f }

fn _find_unit_quad_roots(a: f32, b: f32, c: f32) -> Extrema1D {
  var out = Extrema1D(0u, vec2f(0.0));

  if (a == 0.0) {
    if (b != 0.0) {
      let t = -c / b;
      if (t > 0.0 && t < 1.0) {
        out.t[0] = t;
        out.count = 1u;
      }
    }

    return out;
  }

  let dr_sq = b * b - 4.0 * a * c;
  if (dr_sq < 0.0) { return out; }

  let r = sqrt(dr_sq);
  let q = select(-(b + r) * 0.5, -(b - r) * 0.5, b < 0.0);

  if (a != 0.0) {
    let t1 = q / a;
    if (t1 > 0.0 && t1 < 1.0) {
      out.t[out.count] = t1;
      out.count += 1u;
    }
  }

  if (q != 0.0) {
    let t2 = c / q;
    if (t2 > 0.0 && t2 < 1.0) {
      out.t[out.count] = t2;
      out.count += 1u;
    }
  }

  if (out.count == 2u) {
    if (out.t.x > out.t.y) { out.t = out.t.yx; }
    else if (out.t.x == out.t.y) { out.count = 1u; }
  }

  return out;
}


fn _cubic_extrema_1d(a: f32, b: f32, c: f32, d: f32) -> Extrema1D {
  return _find_unit_quad_roots(
    d - a + 3.0 * (b - c),
    2.0 * (a - 2.0 * b + c),
    b - a,
  );
}


// Returns the number of extrema in x and y and their parameter values.
fn cubic2_extrema(c: Cubic2) -> Extrema2D {
  var out = Extrema2D(0u, vec4f(0.0));

  let x_extrema = _cubic_extrema_1d(c.p0.x, c.p1.x, c.p2.x, c.p3.x);
  for (var i = 0u; i < x_extrema.count; i++) {
    out.t[out.count] = x_extrema.t[i];
    out.count++;
  }

  let y_extrema = _cubic_extrema_1d(c.p0.y, c.p1.y, c.p2.y, c.p3.y);
  for (var i = 0u; i < y_extrema.count; i++) {
    out.t[out.count] = y_extrema.t[i];
    out.count++;
  }

  if (out.count > 1u) {
    for (var i = 0u; i < out.count - 1u; i++) {
      for (var j = 0u; j < out.count - i - 1u; j++) {
        if (out.t[j] > out.t[j + 1u]) {
          let temp = out.t[j];
          out.t[j] = out.t[j + 1u];
          out.t[j + 1u] = temp;
        }
      }
    }
  }

  return out;
}

struct Cubic2KeyPointsResult {
  t: array<f32, 6>,
  count: u32,
}

// Returns the sorted parameter values of the inflection points and extrema of the cubic.
fn cubic2_key_points(c: Cubic2) -> Cubic2KeyPointsResult {
  var out: Cubic2KeyPointsResult;
  out.count = 0u;

  let v0 = c.p1 - c.p0;
  let v1 = c.p2 - c.p1;
  let v2 = c.p3 - c.p2;

  let A = v2 - 2.0 * v1 + v0;
  let B = 2.0 * (v1 - v0);
  let C = v0;

  let x_extrema = _find_unit_quad_roots(A.x, B.x, C.x);
  for (var i = 0u; i < x_extrema.count; i++) {
    out.t[out.count] = x_extrema.t[i];
    out.count++;
  }

  let y_extrema = _find_unit_quad_roots(A.y, B.y, C.y);
  for (var i = 0u; i < y_extrema.count; i++) {
    out.t[out.count] = y_extrema.t[i];
    out.count++;
  }

  let inf_a = B.x * A.y - B.y * A.x;
  let inf_b = 2.0 * (C.x * A.y - C.y * A.x);
  let inf_c = C.x * B.y - C.y * B.x;

  let inflections = _find_unit_quad_roots(inf_a, inf_b, inf_c);
  for (var i = 0u; i < inflections.count; i++) {
    out.t[out.count] = inflections.t[i];
    out.count++;
  }

  if (out.count > 1u) {
    for (var i = 0u; i < out.count - 1u; i++) {
      for (var j = 0u; j < out.count - i - 1u; j++) {
        if (out.t[j] > out.t[j + 1u]) {
          let temp = out.t[j];
          out.t[j] = out.t[j + 1u];
          out.t[j + 1u] = temp;
        }
      }
    }
  }

  return out;
}

// #endregion

// #region Geometry

// Returns the rough bounding box of the cubic bezier.
fn cubic2_bbox(c: Cubic2) -> vec4f {
  let min_pt = min(c.p0, min(c.p1, min(c.p2, c.p3)));
  let max_pt = max(c.p0, max(c.p1, max(c.p2, c.p3)));
  return vec4f(min_pt, max_pt);
}

// Returns the tight bounding box of the cubic bezier.
fn cubic2_bbox_tight(c: Cubic2) -> vec4f {
  var min_pt = min(c.p0, c.p3);
  var max_pt = max(c.p0, c.p3);

  let extrema = cubic2_extrema(c);
  for (var i = 0u; i < extrema.count; i++) {
    let t = extrema.t[i];
    let pt = cubic2_pos(c, t);
    min_pt = min(min_pt, pt);
    max_pt = max(max_pt, pt);
  }

  return vec4f(min_pt, max_pt);
}

fn _cubic2_arc_len_vel(v0: vec2f, v1: vec2f, v2: vec2f, t: f32) -> f32 {
  let mt = 1.0 - t;
  let vel = v0 * (mt * mt) + v1 * (2.0 * mt * t) + v2 * (t * t);
  return length(vel);
}

fn _cubic2_arc_len_quadrature(c: Cubic2) -> f32 {
  let v0 = 3.0 * (c.p1 - c.p0);
  let v1 = 3.0 * (c.p2 - c.p1);
  let v2 = 3.0 * (c.p3 - c.p2);

  var arc_len = 0.0;

  arc_len += 0.28444444 * _cubic2_arc_len_vel(v0, v1, v2, 0.5);
  
  arc_len += 0.23931434 * _cubic2_arc_len_vel(v0, v1, v2, 0.23076535);
  arc_len += 0.23931434 * _cubic2_arc_len_vel(v0, v1, v2, 0.76923465);
  
  arc_len += 0.11846344 * _cubic2_arc_len_vel(v0, v1, v2, 0.04691008);
  arc_len += 0.11846344 * _cubic2_arc_len_vel(v0, v1, v2, 0.95308992);

  return arc_len;
}

// Returns the approximate arc length of the cubic bezier.
fn cubic2_arc_length_approximate(c: Cubic2) -> f32 {
  return _cubic2_arc_len_quadrature(c);
}

// Returns a more refined arc length estimation of the cubic bezier.
fn cubic2_arc_length(c: Cubic2) -> f32 {
  let key_points = cubic2_key_points(c);

  var total = 0.0;
  var t0 = 0.0;
  for (var i = 0u; i < key_points.count; i++) {
    let t1 = key_points.t[i];
    if (t1 - t0 > 1.0e-4) {
      let piece = cubic2_piece_at(c, t0, t1);
      total += cubic2_arc_length_approximate(piece);
      t0 = t1;
    }
  }

  if (1.0 - t0 > 1.0e-4) {
    let piece = cubic2_piece_at(c, t0, 1.0);
    total += cubic2_arc_length_approximate(piece);
  }

  return total;
}

// Returns the parameter t at arc length.
fn cubic2_distance_to_t(c: Cubic2, dist: f32) -> f32 {
  var t_min = 0.0; var t_max = 1.0; var local_t = 0.5;

  for (var iter = 0u; iter < 12u; iter++) {
    local_t = (t_min + t_max) * 0.5;
    let sub_curve = cubic2_piece_at(c, 0.0, local_t);
    let dist_at_t = cubic2_arc_length(sub_curve);

    if (dist_at_t < dist) { t_min = local_t; }
    else { t_max = local_t; }
  }

  return local_t;
}

// Returns the arc distance at parameter t.
fn cubic2_distance_at_t(c: Cubic2, t: f32) -> f32 {
  let sub = cubic2_piece_at(c, 0.0, t);
  return cubic2_arc_length(sub);
}

// Returns the number of line segments needed to approximate the cubic bezier within the given tolerance.
fn cubic2_wang(c: Cubic2, tolerance: f32) -> f32 {
  let v1 = c.p2 - 2.0 * c.p1 + c.p0;
  let v2 = c.p3 - 2.0 * c.p2 + c.p1;
  let m = max(dot(v1, v1), dot(v2, v2));
  if (m < 1.0e-6) { return 1.0; }
  return sqrt(sqrt(m) * 3.0 / (4.0 * tolerance));
}

// #endregion

// #region Subdivision

// Splits the cubic bezier at [t].
fn cubic2_chop_at(c: Cubic2, t: f32) -> array<Cubic2, 2> {
  let p01 = mix(c.p0, c.p1, t);
  let p12 = mix(c.p1, c.p2, t);
  let p23 = mix(c.p2, c.p3, t);

  let p012 = mix(p01, p12, t);
  let p123 = mix(p12, p23, t);

  let p0123 = mix(p012, p123, t);

  return array<Cubic2, 2>(
    Cubic2(c.p0, p01, p012, p0123),
    Cubic2(p0123, p123, p23, c.p3)
  );
}

// Splits the cubic bezier at [t=0.5].
fn cubic2_chop_at_half(c: Cubic2) -> array<Cubic2, 2> {
  return cubic2_chop_at(c, 0.5);
}

// Returns the cubic bezier piece between [t0] and [t1].
fn cubic2_piece_at(c: Cubic2, t0: f32, t1: f32) -> Cubic2 {
  let pos_tan_t0 = cubic2_pos_tan(c, t0);
  let pos_tan_t1 = cubic2_pos_tan(c, t1);
  let dt = (t1 - t0) / 3.0;

  return Cubic2(
    pos_tan_t0.xy,
    pos_tan_t0.xy + pos_tan_t0.zw * dt,
    pos_tan_t1.xy - pos_tan_t1.zw * dt,
    pos_tan_t1.xy
  );
}


struct Cubic2ChopAtInflectionsResult {
  cubics: array<Cubic2, 3>,
  t0: array<f32, 3>,
  t1: array<f32, 3>,
  count: u32,
}


// Splits the cubic bezier at its inflection points.
fn cubic2_chop_at_inflections(c: Cubic2) -> Cubic2ChopAtInflectionsResult {
  var out: Cubic2ChopAtInflectionsResult;
  let inflections = cubic2_inflections(c);

  if (inflections.count == 0u) {
    out.cubics[0] = c;
    out.t0[0] = 0.0;
    out.t1[0] = 1.0;
    out.count = 1u;
  }
  else if (inflections.count == 1u) {
    let t1 = inflections.t[0];
    let pieces = cubic2_chop_at(c, t1);
  
    out.cubics[0] = pieces[0];
    out.t0[0] = 0.0;
    out.t1[0] = t1;

    out.cubics[1] = pieces[1];
    out.t0[1] = t1;
    out.t1[1] = 1.0;

    out.count = 2u;
  }
  else if (inflections.count == 2u) {
    let t1 = inflections.t[0];
    let t2 = inflections.t[1];
    
    let pieces1 = cubic2_chop_at(c, t1);
    out.cubics[0] = pieces1[0];
    out.t0[0] = 0.0;
    out.t1[0] = t1;

    let pieces2 = cubic2_chop_at(pieces1[1], (t2 - t1) / (1.0 - t1));
    out.cubics[1] = pieces2[0];
    out.t0[1] = t1;
    out.t1[1] = t2;

    out.cubics[2] = pieces2[1];
    out.t0[2] = t2;
    out.t1[2] = 1.0;

    out.count = 3u;
  }

  return out;
}

// #endregion
// end import "shared/cubic2.wgsl"

// import "shared/hermite.wgsl"
// Interpolate between two values using the hermite basis functions.
//
// Input points are of form (x, y, dy/dx), return value is (y, dy/dx).
fn hermite_interpolate(p0: vec3f, p1: vec3f, t: f32) -> vec2f {
  let h = p1.x - p0.x;
  if (h < 1.0e-6) { return vec2f(p0.yz); }

  let u = (t - p0.x) / h;
  let u2 = u * u;
  let one_minus_u = 1.0 - u;
  let one_minus_u2 = one_minus_u * one_minus_u;

  let h00 = (1.0 + 2.0 * u) * one_minus_u2;
  let h10 = u * one_minus_u2;
  let h01 = u2 * (3.0 - 2.0 * u);
  let h11 = u2 * (u - 1.0);
  
  let v = h00 * p0.y + h10 * h * p0.z + h01 * p1.y + h11 * h * p1.z;

  let dh00 = 6.0 * u * (u - 1.0);
  let dh10 = (1.0 - u) * (1.0 - 3.0 * u);
  let dh01 = -dh00;
  let dh11 = u * (3.0 * u - 2.0);

  let dv_du = dh00 * p0.y + dh10 * h * p0.z + dh01 * p1.y + dh11 * h * p1.z;
  let dv_dt = dv_du / h;

  return vec2f(v, dv_dt);
}
// end import "shared/hermite.wgsl"

// import "shared/utils.wgsl"
// Pads the bounding box by [pad] pixels in all directions.
fn bbox_pad(bbox: vec4f, pad: f32) -> vec4f {
  return vec4f(bbox.xy - vec2f(pad), bbox.zw + vec2f(pad));
}

// Returns true if the two bounding boxes intersect.
fn bbox_intersects(b1: vec4f, b2: vec4f) -> bool {
  return b1.x <= b2.z && b1.z >= b2.x && b1.y <= b2.w && b1.w >= b2.y;
}

// Returns true if the point [p] is inside the bounding box [bbox].
fn bbox_contains(bbox: vec4f, p: vec2f) -> bool {
  return p.x >= bbox.x && p.x <= bbox.z && p.y >= bbox.y && p.y <= bbox.w;
}

const PI = 3.14159265358979323;
const TWO_PI = 6.28318530717958646;

fn vec2_transform(v: vec2f, m: mat4x4f) -> vec2f {
  let res = m * vec4f(v, 0.0, 1.0);
  return res.xy;
}
// end import "shared/utils.wgsl"

// import "structs.wgsl"
struct Uniforms {
  cubic_count: u32,
  weight_anchor_count: u32,
  tolerance: f32,
  screen_size: vec2f,
  transform: mat4x4f,
}

struct VertexData {
  pos: vec2f,
  incident_edges_span: vec2u,
}

struct EdgeData {
  start_vertex_idx: u32,
  end_vertex_idx: u32,
  cubics_span: vec2u,
  weight_span: vec2u,
  width: f32,
  arc_length: f32,
  color: vec4f,
}

struct CubicData {
  cubic: Cubic2,
  edge_idx: u32,
  edge_segment_idx: u32,
  edge_segment_count: u32,
  edge_start_arc_length: f32,
  opacity: f32,
}
// end import "structs.wgsl"

// import "geometry.wgsl"
// A quad.
// - v0-v3: four vertices
const RENDER_GEOMETRY_KIND_QUAD = 0u;

// // An ellipse.
// // - v0: center
// // - v1: radii
// const RENDER_GEOMETRY_KIND_ELLIPSE = 1u;

struct RenderGeometry {
  v0: vec2f,
  v1: vec2f,
  v2: vec2f,
  v3: vec2f,
  color: vec4f,
  z_index: u32,
  kind: u32,
}

fn render_geometry_create_quad(v0: vec2f, v1: vec2f, v2: vec2f, v3: vec2f, color: vec4f, z_index: u32) -> RenderGeometry {
  return RenderGeometry(v0, v1, v2, v3, color, z_index, RENDER_GEOMETRY_KIND_QUAD);
}

// fn render_geometry_create_ellipse(c: vec2f, r: vec2f, color: vec4f, z_index: u32) -> RenderGeometry {
//   return RenderGeometry(c, r, vec2f(0.0), vec2f(0.0), color, z_index, RENDER_GEOMETRY_KIND_ELLIPSE);
// }

// fn render_geometry_create_circle(c: vec2f, r: f32, color: vec4f, z_index: u32) -> RenderGeometry {
//   return render_geometry_create_ellipse(c, vec2f(r), color, z_index);
// }
// end import "geometry.wgsl"


// const MAX_SPLITS: u32 = 32u;

// struct DrawIndirectArgs {
//   vertex_count: u32,
//   instance_count: atomic<u32>,
//   first_vertex: u32,
//   first_instance: u32,
// };

// @group(0) @binding(0) var<uniform> u: Uniforms;
// @group(0) @binding(1) var<storage, read> in_edge_data: array<EdgeData>;
// @group(0) @binding(2) var<storage, read> in_cubic_data: array<CubicData>;
// @group(0) @binding(3) var<storage, read> in_edge_weight_samples: array<vec3f>;
// @group(0) @binding(5) var<storage, read_write> out_draw_args: DrawIndirectArgs;
// @group(0) @binding(6) var<storage, read_write> out_render_geometry: array<RenderGeometry>;

// // Evaluates the stroke weight at parameter [t] in the given weight span [span].
// fn edge_weight_eval(span: vec2u, t: f32) -> vec2f {
//   let offset = span.x; 
//   let count = span.y;

//   if (count == 0u) { return vec2f(1.0, 0.0); }
//   if (count == 1u) { return vec2f(in_edge_weight_samples[offset].y, 0.0); }

//   let first_sample = in_edge_weight_samples[offset];
//   if (t <= first_sample.x) { return vec2f(first_sample.y, 0.0); }

//   let last_sample = in_edge_weight_samples[offset + count - 1u];
//   if (t >= last_sample.x) { return vec2f(last_sample.y, 0.0); }

//   var l = 0u;
//   var r = count - 1u;
//   while (l < r) {
//     let m = (l + r) / 2u;
//     let sample = in_edge_weight_samples[offset + m];
//     if (t < sample.x) { r = m; }
//     else { l = m + 1u; }
//   }

//   let s0 = in_edge_weight_samples[offset + l - 1u];
//   let s1 = in_edge_weight_samples[offset + l];
//   return hermite_interpolate(s0, s1, t);
// }

// fn emit_quad(v0: vec2f, v1: vec2f, v2: vec2f, v3: vec2f, edge_idx: u32, color: vec4f) {
//   let line_id = atomicAdd(&out_draw_args.instance_count, 1u);
//   if (line_id >= arrayLength(&out_lines)) { return; }

//   out_lines[line_id] = Line(v0, v1, v2, v3, color, edge_idx);
// }

// fn emit_join(pos: vec2f, r: f32, edge_idx: u32, color: vec4f) {
//   let pivot_pos = vec2_transform(pos, u.transform);
  
//   // Dynamically calculate the number of steps based on the physical screen size 
//   // of the radius, so small circles don't waste vertices.
//   let scale = length(u.transform[0].xy);
//   let screen_r = r * scale;
//   let steps = max(16u, u32(ceil(screen_r * 0.5))); // Adjust multiplier for smoothness
  
//   let da = 6.283185307 / f32(steps);
  
//   // Start the fan at angle 0
//   var prev_tf_outer = vec2_transform(pos + vec2f(r, 0.0), u.transform);

//   for (var i = 1u; i <= steps; i++) {
//     let angle = f32(i) * da;
    
//     let outer_pt = pos + vec2f(cos(angle), sin(angle)) * r;
//     let tf_outer = vec2_transform(outer_pt, u.transform);

//     // Emit a degenerate quad (a triangle) with the inner vertices pinned to the center pivot
//     emit_line(prev_tf_outer, tf_outer, pivot_pos, pivot_pos, edge_idx, color);
    
//     prev_tf_outer = tf_outer;
//   }
// }

// var<private> cubic: Cubic2;
// var<private> cubic_start_dist: f32;
// var<private> cubic_end_dist: f32;
// var<private> cubic_start_tan: vec2f;
// var<private> cubic_end_tan: vec2f;
// var<private> edge_weight_span: vec2u;
// var<private> edge_width: f32;
// var<private> edge_idx: u32;
// var<private> 

// fn compute_point_radii(segment: Cubic2, global_t: f32, t: f32, arc_dist: f32) -> array<vec2f, 4> {
//   let pos_tan = cubic2_eval_pos_tan(segment, t);
//   let pos = pos_tan.xy;
//   let base_tan = normalize(pos_tan.zw);

//   let weight_sample = edge_weight_eval(edge_weight_span, arc_dist);
//   let target_r = weight_sample.x * edge_width;
//   let k = cubic2_eval_signed_curvature(segment, t);
//   let inner_side = sign(k);

//   let max_safe_r = 1.0 / max(abs(k), 1.0e-5);
//   let safe_r = min(target_r, max_safe_r);

//   let r_left = select(target_r, safe_r, inner_side > 0.0);
//   let r_right = select(target_r, safe_r, inner_side < 0.0);

//   let normal = vec2f(-base_tan.y, base_tan.x);

//   let v_left = pos + r_left * normal;
//   let v_right = pos - r_right * normal;

//   return array<vec2f, 4>(pos, v_left, v_right, vec2f(0.0));
// }

// @compute @workgroup_size(64)
// fn main(@builtin(global_invocation_id) global_idx: vec3u) {
//   let idx = global_idx.x;
//   if (idx >= u.cubic_count) { return; }

//   let scale = length(u.transform[0].xy);

//   let cubic_data = in_cubic_data[idx];
//   cubic = cubic_data.cubic;
//   cubic_start_dist = cubic_data.edge_start_arc_length;
//   cubic_end_dist = cubic_start_dist + cubic2_arc_len(cubic);
//   cubic_start_tan = cubic2_eval_tan(cubic, 0.0);
//   cubic_end_tan = cubic2_eval_tan(cubic, 1.0);

//   let edge_data = in_edge_data[cubic_data.edge_idx];
//   edge_width = edge_data.width / 2.0;
//   edge_weight_span = edge_data.weight_span;

//   // // Cull off-screen cubics
//   let cubic_bbox = cubic2_bbox(cubic);
//   let cubic_padded_bbox = bbox_pad(cubic_bbox, edge_width * 2.0);
//   let screen_bbox = vec4f(0.0, 0.0, f32(u.screen_size.x), f32(u.screen_size.y));
//   if (!bbox_intersects(cubic_padded_bbox, screen_bbox)) { return; }

//   var splits: array<f32, MAX_SPLITS>;
//   var n_splits = 0u;
//   splits[0] = 0.0; n_splits = 1u;

//   // First, split at inflection points
//   var inflection_ts: vec2f;
//   let inflection_count = cubic2_find_inflections(cubic, &inflection_ts);
//   for (var i = 0u; i < inflection_count; i++) {
//     splits[n_splits] = inflection_ts[i];
//     n_splits += 1u;
//   }

//   let ext = cubic2_find_extrema(cubic);
//   for (var i = 0u; i < ext.count && n_splits < MAX_SPLITS - 1u; i++) {
//     splits[n_splits] = ext.t[i];
//     n_splits += 1u;
//   }

//   {
//     const N_SAMPLES = 32u;
    
//     let k0 = cubic2_eval_signed_curvature(cubic, 0.0);
//     let a0 = cubic_data.edge_start_arc_length;
//     let r0 = edge_weight_eval(edge_weight_span, a0).x * edge_width;
//     var prev_excess = r0 * abs(k0) - 1.0;
//     var cusp_start_t: f32;

//     const CUSP_THRESHOLD = 0.66;
    
//     for (var i = 1u; i <= N_SAMPLES; i++) {
//       let t = f32(i) / f32(N_SAMPLES);
//       let k1 = cubic2_eval_signed_curvature(cubic, t);
//       let a1 = cubic_data.edge_start_arc_length + cubic2_distance_at_t(cubic, t);
//       let r1 = edge_weight_eval(edge_weight_span, a1).x * edge_width;
//       let excess = r1 * abs(k1) - CUSP_THRESHOLD;
      
//       // If the sign flipped, we crossed a swallowtail boundary
//       if (prev_excess * excess <= 0.0 && prev_excess != excess) {
//         var t_left = t - (1.0 / f32(N_SAMPLES));
//         var t_right = t;
//         var root_t = t_left;
        
//         // 6 steps of binary search to nail the float precision
//         for (var search = 0u; search < 6u; search++) {
//            let t_mid = (t_left + t_right) * 0.5;
//            let k_mid = cubic2_eval_signed_curvature(cubic, t_mid);
//            let a_mid = cubic_data.edge_start_arc_length + cubic2_distance_at_t(cubic, t_mid);
//            let r_mid = edge_weight_eval(edge_weight_span, a_mid).x * edge_width;
//            let e_mid = r_mid * abs(k_mid) - CUSP_THRESHOLD;
           
//            if (prev_excess * e_mid <= 0.0) { t_right = t_mid; } 
//            else { t_left = t_mid; }
//            root_t = t_mid;
//         }

//         // ==========================================
//         // EXACT SWALLOWTAIL BOUNDARY EXTRACTION
//         // ==========================================
//         let exact_t = root_t;
//         let exact_arc = cubic_data.edge_start_arc_length + cubic2_distance_at_t(cubic, exact_t);
//         let exact_r = edge_weight_eval(edge_weight_span, exact_arc).x * edge_width;
//         let exact_pos = cubic2_eval_pos(cubic, exact_t);

//         if (excess > 0.0) {
//           cusp_start_t = exact_t;
          
//         } else {
//           let color = vec4f(0.0, 1.0, 1.0, 0.5);
//           let cusp_end_t = exact_t;
//           let start_arc = cubic_data.edge_start_arc_length + cubic2_distance_at_t(cubic, cusp_start_t);
//           let end_arc = cubic_data.edge_start_arc_length + cubic2_distance_at_t(cubic, cusp_end_t);
          
//           let _r0 = edge_weight_eval(edge_weight_span, start_arc).x * edge_width;
//           let _r1 = edge_weight_eval(edge_weight_span, end_arc).x * edge_width;

//           let a0 = start_arc - _r0;
//           let a1 = end_arc + _r1;

//           let t0 = cubic2_distance_to_t(cubic, a0);
//           let t1 = cubic2_distance_to_t(cubic, a1);
//           let dt = t1 - t0;

//           let p0 = cubic2_eval_pos(cubic, t0);
//           let p1 = cubic2_eval_pos(cubic, t1);

//           let raw_tan0 = cubic2_eval_tan(cubic, t0);
//           let raw_tan1 = cubic2_eval_tan(cubic, t1);

//           let speed0 = length(raw_tan0);
//           let speed1 = length(raw_tan1);
          
//           let tan0 = normalize(raw_tan0);
//           let tan1 = normalize(raw_tan1);
          
//           let n0 = vec2f(-tan0.y, tan0.x);
//           let n1 = vec2f(-tan1.y, tan1.x);
          
//           let k0 = cubic2_eval_signed_curvature(cubic, t0);
//           let k1 = cubic2_eval_signed_curvature(cubic, t1);

//           let w0 = edge_weight_eval(edge_weight_span, a0);
//           let w1 = edge_weight_eval(edge_weight_span, a1);

//           let r0 = w0.x * edge_width;
//           let r1 = w1.x * edge_width;

//           let dr_dt0 = w0.y * edge_width * speed0;
//           let dr_dt1 = w1.y * edge_width * speed1;

//           let side = sign(k0);
//           let inner_n0 = n0 * side;
//           let inner_n1 = n1 * side;

//           let env_vel0 = speed0 * (1.0 - r0 * abs(k0)) * tan0 + dr_dt0 * inner_n0;
//           let env_vel1 = speed1 * (1.0 - r1 * abs(k1)) * tan1 + dr_dt1 * inner_n1;

//           let inner_v0 = p0 + inner_n0 * r0;
//           let inner_v3 = p1 + inner_n1 * r1;

//           let dist = dt / 3.0;
//           let h0 = env_vel0 * dist;
//           let h1 = env_vel1 * dist;

//           let gap_dist = length(inner_v3 - inner_v0);
//           let max_handle = gap_dist / 3.0;

//           let h0_len = length(h0);
//           let h1_len = length(h1);

//           let scale0 = min(1.0, max_handle / max(h0_len, 1.0e-5));
//           let scale1 = min(1.0, max_handle / max(h1_len, 1.0e-5));

//           let inner_v1 = inner_v0 + h0 * scale0;
//           let inner_v2 = inner_v3 - h1 * scale1;

//           let inner_bridge = Cubic2(inner_v0, inner_v1, inner_v2, inner_v3);

//           // emit_join(inner_v0, 2.0, cubic_data.edge_idx, vec4f(0.0, 1.0, 0.0, 1.0));
//           // emit_join(inner_v1, 2.0, cubic_data.edge_idx, vec4f(0.0, 1.0, 1.0, 1.0));
//           // emit_join(inner_v2, 2.0, cubic_data.edge_idx, vec4f(0.0, 1.0, 1.0, 1.0));
//           // emit_join(inner_v3, 2.0, cubic_data.edge_idx, vec4f(1.0, 1.0, 0.0, 1.0));

//           // emit a "bowtie" quad across the cusp region, to visualize the singularity
//           // {
//           //   let p0 = cubic2_eval_pos(cubic, t0);
//           //   let p1 = cubic2_eval_pos(cubic, t1);
//           //   let v0 = vec2_transform(p0, u.transform);
//           //   let v1 = vec2_transform(p0 + vec2f(-tan0.y, tan0.x) * r0, u.transform);
//           //   let v2 = vec2_transform(p1 + vec2f(-tan1.y, tan1.x) * r1, u.transform);
//           //   let v3 = vec2_transform(p1, u.transform);
//           //   emit_line(v0, v1, v2, v3, cubic_data.edge_idx, vec4f(0.0, 1.0, 1.0, 0.5));
//           // }

//           const iterations = 32u;

//           var prev_p: vec2f;
//           var prev_inner_v: vec2f;

//           for (var j = 0u; j <= iterations; j++) {
//             let f = f32(j) / f32(iterations);
            
//             let t = mix(t0, t1, f);
//             let p = cubic2_eval_pos(cubic, t);
            
//             let inner_v = cubic2_eval_pos(inner_bridge, f);

//             if (j > 0u) {
//               let v0 = vec2_transform(prev_p, u.transform);
//               let v1 = vec2_transform(prev_inner_v, u.transform);
//               let v2 = vec2_transform(inner_v, u.transform);
//               let v3 = vec2_transform(p, u.transform);

//               emit_line(v0, v1, v2, v3, cubic_data.edge_idx, color);
//             }

//             prev_p = p;
//             prev_inner_v = inner_v;
//           }
//         }
//       }
//       prev_excess = excess;
//     }
//   }

//   // Add splits at weight anchors
//   var max_weight = max(
//     edge_weight_eval(edge_weight_span, cubic_start_dist).x,
//     edge_weight_eval(edge_weight_span, cubic_end_dist).x
//   );

//   let edge_weight_offset = edge_weight_span.x;
//   let edge_weight_count = edge_weight_span.y;

//   for (var i = 0u; i < edge_weight_count && n_splits < MAX_SPLITS - 1u; i++) {
//     let sample = in_edge_weight_samples[edge_weight_offset + i];
//     let sample_dist = sample.x;

//     if (sample_dist > cubic_start_dist + 1.0e-4 && sample_dist < cubic_end_dist - 1.0e-4) {
//       max_weight = max(max_weight, sample.y);

//       let local_t = cubic2_distance_to_t(cubic, sample_dist - cubic_start_dist);
//       if (local_t > 1.0e-4 && local_t < 1.0 - 1.0e-4) {
//         splits[n_splits] = local_t;
//         n_splits += 1u;
//       }
//     }
//   }

//   splits[n_splits] = 1.0; n_splits += 1u;

//   // Sort splits
//   for (var i = 1u; i < n_splits; i++) {
//     let k = splits[i];
//     var j = i;
//     while (j > 0u && splits[j - 1u] > k) {
//       splits[j] = splits[j - 1u];
//       j -= 1u;
//     }
//     splits[j] = k;
//   }

//   let dynamic_tolerance = u.tolerance / clamp(max(1.0, max_weight * edge_width * 0.05), 1.0, 3.0);

//   // Take splits, emit flattened lines
//   for (var s = 0u; s < n_splits - 1u; s++) {
//     let t0 = splits[s];
//     let t1 = splits[s + 1u];
//     if (t1 - t0 < 1.0e-5) { continue; }

//     let segment = cubic2_piece_at(cubic, t0, t1);
//     let arc_len_start = cubic2_distance_at_t(cubic, t0) + cubic_data.edge_start_arc_length;

//     let first_res = compute_point_radii(segment, t0, 0.0, arc_len_start);

//     var prev_pos = first_res[0];
//     var prev_v_left = first_res[1];
//     var prev_v_right = first_res[2];

//     var stack: array<vec2f, 32>;
//     var stack_cursor: u32 = 0u;

//     stack[stack_cursor] = vec2f(0.0, 1.0);
//     stack_cursor += 1u;

//     while (stack_cursor > 0u) {
//       stack_cursor -= 1u;
//       let t_span = stack[stack_cursor];
//       let t_start = t_span.x;
//       let t_end = t_span.y;
//       let t_mid = (t_start + t_end) * 0.5;

//       let sub_segment = cubic2_piece_at(segment, t_start, t_end);
//       let transformed_sub_segment = cubic2_transform(sub_segment, u.transform);
//       let is_flat = cubic2_wang(transformed_sub_segment, dynamic_tolerance) <= 1.0;

//       if (is_flat || stack_cursor >= 30u) {
//         let arc_dist = arc_len_start + cubic2_distance_at_t(segment, t_end);
//         let t_global = t0 + t_end * (t1 - t0);
//         let res = compute_point_radii(
//           segment, t_global, t_end, arc_dist
//         );

//         let v_left = res[1];
//         let v_right = res[2];
//         let tightness = res[3].x;

//         var v0 = vec2_transform(prev_v_left, u.transform);
//         var v1 = vec2_transform(v_left, u.transform);
//         var v2 = vec2_transform(v_right, u.transform);
//         var v3 = vec2_transform(prev_v_right, u.transform);

//         let color = vec4f(f32(s) / f32(n_splits), tightness, f32(cubic_data.edge_segment_idx) / f32(cubic_data.edge_segment_count), 0.25);

//         emit_line(v0, v1, v2, v3, cubic_data.edge_idx, color);
//         prev_pos = res[0];
//         prev_v_left = v_left;
//         prev_v_right = v_right;
//       }
//       else {
//         let t_mid = (t_start + t_end) * 0.5;
//         stack[stack_cursor] = vec2f(t_mid, t_end);
//         stack_cursor += 1u;
//         stack[stack_cursor] = vec2f(t_start, t_mid);
//         stack_cursor += 1u;
//       }
//     }
//   }

//   if (cubic_data.edge_segment_idx + 1u < cubic_data.edge_segment_count) {
//     let next_cubic = in_cubic_data[idx + 1u].cubic;
    
//     let pos = cubic.p3;
//     let tan_in = normalize(cubic2_eval_tan(cubic, 1.0));
//     let tan_out = normalize(cubic2_eval_tan(next_cubic, 0.0));
    
//     // Evaluate the stroke radius at the end of this cubic
//     let r = edge_weight_eval(edge_weight_span, cubic_end_dist).x * edge_width;

//     if (dot(tan_in, tan_out) < 0.999) {
//       emit_join(pos, r, cubic_data.edge_idx, edge_data.color);
//     }
//   }
// }

''';

@meta.ShaderModule('flatten_old.wgsl')
wgpu.ShaderModule createShaderModule(wgpu.Device device) => device.createShaderModule(.new(
  label: '(flatten_old.wgsl) module',
  next: const wgpu.ShaderSourceWGSL(code: _shaderSource),
));