name: schema
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  protobuf: ^6.0.0
  fixnum: ^1.1.1

  shared:
  color:
  geometry:
  kernel:
  program:

dev_dependencies:
  protoc_plugin: ^25.1.0