message Scene {
  required Program program = 1;
}

message Program {
  repeated Statement statements = 1;
}

message Statement {
  oneof statement {
    FrameStatement frame = 1;
    VertexStatement vertex = 2;
    EdgeStatement edge = 3;
    FaceStatement face = 4;
    CutEdgeStatement cutEdge = 5;
    GlueVerticesStatement glueVertices = 6;
    RectangleStatement rectangle = 7;
    ContainerStatement container = 8;
  }
}

message StatementId {
  required string value = 1;
}

message Vec2 {
  required double x = 1;
  required double y = 2;
}

message Mat4 {
  repeated double values = 1;
}

message Ref {
  required StatementId id = 1;
  required string product = 2;
}

message FrameStatement {
  required StatementId id = 1;
  optional Ref parent = 2;
  required Mat4 transform = 3;
}

message VertexStatement {
  required StatementId id = 1;
  optional Ref parent = 2;
  required Vec2 position = 3;
}

message EdgeStatement {
  required StatementId id = 1;
  optional Ref parent = 2;
  required Ref start = 3;
  required Ref end = 4;
  optional Vec2 startTangent = 5;
  optional Vec2 endTangent = 6;
}

message FaceStatement {
  message Cycle {
    repeated Ref edges = 1;
  }
  
  required StatementId id = 1;
  optional Ref parent = 2;
  required Cycle outer = 3;
  repeated Cycle holes = 4;
}

message CutEdgeStatement {
  required StatementId id = 1;
  required Ref target = 2;
  required double t = 3;
}

message GlueVerticesStatement {
  enum Position {
    GLUE_VERTICES_STATEMENT_POSITION_CENTROID = 0;
    GLUE_VERTICES_STATEMENT_POSITION_FIRST = 1;
  }

  required StatementId id = 1;
  repeated Ref targets = 2;
  required Position position = 3;
}

message LayoutRange {
  required double min = 1;
  required double max = 2;
}

enum LayoutDimensionType {
  LAYOUT_DIMENSION_TYPE_FIXED = 0;
  LAYOUT_DIMENSION_TYPE_EXPAND = 1;
  LAYOUT_DIMENSION_TYPE_CONTAIN = 2;
}

message LayoutDimension {
  optional double value = 1;
  required LayoutDimensionType type = 2;
  required LayoutRange range = 3;
}

message LayoutSize {
  required LayoutDimension width = 1;
  required LayoutDimension height = 2;
}

message CornerRadius {
  required double x = 1;
  required double y = 2;
}

message RectangleObjectShape {
  required CornerRadius top_left_radius = 1;
  required CornerRadius top_right_radius = 2;
  required CornerRadius bottom_right_radius = 3;
  required CornerRadius bottom_left_radius = 4;
}

message RectangleStatement {
  required StatementId id = 1;
  optional Ref parent = 2;
  required Mat4 transform = 3;
  required LayoutSize size = 4;
  required RectangleObjectShape shape = 5;
}

enum LayoutAlign {
  LAYOUT_ALIGN_START = 0;
  LAYOUT_ALIGN_CENTER = 1;
  LAYOUT_ALIGN_END = 2;
}

enum LayoutJustify {
  LAYOUT_JUSTIFY_START = 0;
  LAYOUT_JUSTIFY_CENTER = 1;
  LAYOUT_JUSTIFY_END = 2;
  LAYOUT_JUSTIFY_SPACE_BETWEEN = 3;
}

enum FlexDirection {
  FLEX_DIRECTION_ROW = 0;
  FLEX_DIRECTION_COLUMN = 1;
}

message LayoutInsets {
  required double left = 1;
  required double top = 2;
  required double right = 3;
  required double bottom = 4;
}

message ChildLayout {
  oneof layout {
    StackChildLayout stack = 1;
    FlexChildLayout flex = 2;
  }
}

message StackChildLayout {
  optional LayoutAlign alignHorizontal = 1;
  optional LayoutAlign alignVertical = 2;
  required LayoutInsets padding = 3;
}

message FlexChildLayout {
  required FlexDirection direction = 1;
  required LayoutJustify justify = 2;
  required LayoutAlign crossAlign = 3;
  required double gap = 4;
  required LayoutInsets padding = 5;
}

message ContainerStatement {
  required StatementId id = 1;
  optional Ref parent = 2;
  required Mat4 transform = 3;
  required LayoutSize size = 4;
  required RectangleObjectShape shape = 5;
  required ChildLayout childLayout = 6;
}