syntax = "proto3";

message Scene {
  Program program = 1;
}

message Program {
  repeated Statement statements = 1;
}

// ---------------------------------------------------------------------------------------------------------------------
// Statements
// ---------------------------------------------------------------------------------------------------------------------

message Statement {
  oneof statement {
    FrameStatement        frame        = 1;
    VertexStatement       vertex       = 2;
    EdgeStatement         edge         = 3;
    FaceStatement         face         = 4;
    CutEdgeStatement      cutEdge      = 5;
    GlueVerticesStatement glueVertices = 6;
    CircleStatement       circle       = 7;
    RectangleStatement    rectangle    = 8;
    TriangleStatement     triangle     = 9;
    ContainerStatement    container    = 10;
  }
}

message FrameStatement {
  StatementId  id        = 1;
  optional Ref parent    = 2;
  Mat4         transform = 3;
}

message VertexStatement {
  StatementId  id       = 1;
  optional Ref parent   = 2;
  Vec2         position = 3;
}

message EdgeStatement {
  StatementId   id           = 1;
  optional Ref  parent       = 2;
  Ref           start        = 3;
  Ref           end          = 4;
  optional Vec2 startTangent = 5;
  optional Vec2 endTangent   = 6;
  EdgeStyle     style        = 7;
}

message FaceStatement {
  message Cycle {
    repeated Ref edges = 1;
  }

  StatementId    id     = 1;
  optional Ref   parent = 2;
  Cycle          outer  = 3;
  repeated Cycle holes  = 4;
  FaceStyle      style  = 5;
}

message CutEdgeStatement {
  StatementId id     = 1;
  Ref         target = 2;
  double      t      = 3;
}

message GlueVerticesStatement {
  enum Position {
    GLUE_VERTICES_STATEMENT_POSITION_CENTROID = 0;
    GLUE_VERTICES_STATEMENT_POSITION_FIRST    = 1;
  }

  StatementId  id       = 1;
  repeated Ref targets  = 2;
  Position     position = 3;
}

message CircleStatement {
  StatementId       id        = 1;
  optional Ref      parent    = 2;
  Mat4              transform = 3;
  LayoutSize        size      = 4;
  CircleObjectShape shape     = 5;
  EdgeStyle         edgeStyle = 6;
  FaceStyle         faceStyle = 7;
}

message RectangleStatement {
  StatementId          id        = 1;
  optional Ref         parent    = 2;
  Mat4                 transform = 3;
  LayoutSize           size      = 4;
  RectangleObjectShape shape     = 5;
  EdgeStyle            edgeStyle = 6;
  FaceStyle            faceStyle = 7;
}

message TriangleStatement {
  StatementId         id        = 1;
  optional Ref        parent    = 2;
  Mat4                transform = 3;
  LayoutSize          size      = 4;
  TriangleObjectShape shape     = 5;
  EdgeStyle           edgeStyle = 6;
  FaceStyle           faceStyle = 7;
}

message ContainerStatement {
  StatementId  id          = 1;
  optional Ref parent      = 2;
  Mat4         transform   = 3;
  LayoutSize   size        = 4;
  ObjectShape  shape       = 5;
  ChildLayout  childLayout = 6;
  EdgeStyle    edgeStyle   = 7;
  FaceStyle    faceStyle   = 8;
}

// ---------------------------------------------------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------------------------------------------------

message StatementId {
  string value = 1;
}

message Vec2 {
  double x = 1;
  double y = 2;
}

message Mat4 {
  repeated double values = 1;
}

message Ref {
  enum Kind {
    REF_KIND_FRAME  = 0;
    REF_KIND_VERTEX = 1;
    REF_KIND_EDGE   = 2;
    REF_KIND_FACE   = 3;
  }

  StatementId id      = 1;
  string      product = 2;
  Kind        kind    = 3;
}

message LayoutRange {
  double min = 1;
  double max = 2;
}

message LayoutDimension {
  enum Type {
    LAYOUT_DIMENSION_TYPE_FIXED   = 0;
    LAYOUT_DIMENSION_TYPE_EXPAND  = 1;
    LAYOUT_DIMENSION_TYPE_CONTAIN = 2;
  };

  optional double value = 1;
  Type            type  = 2;
  LayoutRange     range = 3;
}

message LayoutSize {
  LayoutDimension width  = 1;
  LayoutDimension height = 2;
}

message CornerRadius {
  double x = 1;
  double y = 2;
}

message CircleObjectShape {}

message RectangleObjectShape {
  CornerRadius top_left_radius     = 1;
  CornerRadius top_right_radius    = 2;
  CornerRadius bottom_right_radius = 3;
  CornerRadius bottom_left_radius  = 4;
}

message TriangleObjectShape {}

message ObjectShape {
  oneof shape {
    CircleObjectShape    circle    = 1;
    RectangleObjectShape rectangle = 2;
    TriangleObjectShape  triangle  = 3;
  }
}

message ColorData {
  enum Type {
    COLOR_DATA_TYPE_HSV = 0;
  }

  Type   type  = 1;
  double v1    = 2;
  double v2    = 3;
  double v3    = 4;
  double alpha = 5;
}

message EdgeStyle {
  double    width = 1;
  ColorData color = 2;
}

message FaceStyle {
  ColorData color = 1;
}

enum LayoutAlign {
  LAYOUT_ALIGN_START  = 0;
  LAYOUT_ALIGN_CENTER = 1;
  LAYOUT_ALIGN_END    = 2;
}

enum LayoutJustify {
  LAYOUT_JUSTIFY_START         = 0;
  LAYOUT_JUSTIFY_CENTER        = 1;
  LAYOUT_JUSTIFY_END           = 2;
  LAYOUT_JUSTIFY_SPACE_BETWEEN = 3;
}

enum FlexDirection {
  FLEX_DIRECTION_ROW    = 0;
  FLEX_DIRECTION_COLUMN = 1;
}

message LayoutInsets {
  double left   = 1;
  double top    = 2;
  double right  = 3;
  double bottom = 4;
}

message ChildLayout {
  oneof layout {
    StackChildLayout stack = 1;
    FlexChildLayout  flex  = 2;
  }
}

message StackChildLayout {
  optional LayoutAlign alignHorizontal = 1;
  optional LayoutAlign alignVertical   = 2;
  LayoutInsets         padding         = 3;
}

message FlexChildLayout {
  FlexDirection direction  = 1;
  LayoutJustify justify    = 2;
  LayoutAlign   crossAlign = 3;
  double        gap        = 4;
  LayoutInsets  padding    = 5;
}
