// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by wgslgen

import 'dart:typed_data';
import 'package:wgpu/wgpu.dart' as wgpu;
import 'package:wgpu/wgsl.dart' as wgsl;

@wgsl.Overrides()
extension type const Overrides._((int? workgroupSizeX, bool? useShadows, double? globalBias) _) {
  const Overrides({int? workgroupSizeX, bool? useShadows, double? globalBias}): this._((workgroupSizeX, useShadows, globalBias));

  int? get workgroupSizeX => _.$1;
  bool? get useShadows => _.$2;
  double? get globalBias => _.$3;

  List<wgpu.ConstantEntry> get entries => [
    if (workgroupSizeX != null) .new(
      key: 'workgroup_size_x',
      value: workgroupSizeX!.toDouble(),
    ),
    if (useShadows != null) .new(
      key: 'use_shadows',
      value: useShadows! ? 1.0 : 0.0,
    ),
    if (globalBias != null) .new(
      key: 'global_bias',
      value: globalBias!.toDouble(),
    ),
  ];
}

@wgsl.Struct('GlobalConfig')
extension type const GlobalConfig._((double time, double deltaTime, int frameCount, (wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u) resolutions) _) {
  static const GlobalConfig zero = GlobalConfig._((
    0.0,
    0.0,
    0,
    (.zero, .zero, .zero, .zero),
  ));

  double get time => _.$1;
  double get deltaTime => _.$2;
  int get frameCount => _.$3;
  (wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u) get resolutions => _.$4;

  @pragma('vm:prefer-inline')
  GlobalConfig({double time = 0.0, double deltaTime = 0.0, int frameCount = 0, (wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u) resolutions = (.zero, .zero, .zero, .zero)}): this._((
    time,
    deltaTime,
    frameCount,
    resolutions,
  ));

  @pragma('vm:prefer-inline')
  GlobalConfig.read(ByteData data, int offset): this._((
    wgsl.F32.read(data, offset + 0),
    wgsl.F32.read(data, offset + 4),
    wgsl.U32.read(data, offset + 8),
    (
      wgsl.Vec4u.read(data, offset + 16 + 0 * 16),
      wgsl.Vec4u.read(data, offset + 16 + 1 * 16),
      wgsl.Vec4u.read(data, offset + 16 + 2 * 16),
      wgsl.Vec4u.read(data, offset + 16 + 3 * 16),
    ),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.F32(_.$1).write(data, offset + 0);
    wgsl.F32(_.$2).write(data, offset + 4);
    wgsl.U32(_.$3).write(data, offset + 8);
    _.$4.$1.write(data, offset + 16 + 0 * 16);
    _.$4.$2.write(data, offset + 16 + 1 * 16);
    _.$4.$3.write(data, offset + 16 + 2 * 16);
    _.$4.$4.write(data, offset + 16 + 3 * 16);
  }
}

@wgsl.Struct('TransformData')
extension type const TransformData._((wgsl.Mat4x4f model, wgsl.Mat4x4f view, wgsl.Mat3x3f normalMat) _) {
  static const TransformData zero = TransformData._((
    .identity,
    .identity,
    .identity,
  ));

  wgsl.Mat4x4f get model => _.$1;
  wgsl.Mat4x4f get view => _.$2;
  wgsl.Mat3x3f get normalMat => _.$3;

  @pragma('vm:prefer-inline')
  TransformData({wgsl.Mat4x4f model = .identity, wgsl.Mat4x4f view = .identity, wgsl.Mat3x3f normalMat = .identity}): this._((
    model,
    view,
    normalMat,
  ));

  @pragma('vm:prefer-inline')
  TransformData.read(ByteData data, int offset): this._((
    wgsl.Mat4x4f.read(data, offset + 0),
    wgsl.Mat4x4f.read(data, offset + 64),
    wgsl.Mat3x3f.read(data, offset + 128),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    _.$2.write(data, offset + 64);
    _.$3.write(data, offset + 128);
  }
}

@wgsl.Struct('Material')
extension type const Material._((wgsl.Vec4f albedo, double roughness, double metallic, wgsl.Vec3h emission) _) {
  static const Material zero = Material._((
    .zero,
    0.0,
    0.0,
    .zero,
  ));

  wgsl.Vec4f get albedo => _.$1;
  double get roughness => _.$2;
  double get metallic => _.$3;
  wgsl.Vec3h get emission => _.$4;

  @pragma('vm:prefer-inline')
  Material({wgsl.Vec4f albedo = .zero, double roughness = 0.0, double metallic = 0.0, wgsl.Vec3h emission = .zero}): this._((
    albedo,
    roughness,
    metallic,
    emission,
  ));

  @pragma('vm:prefer-inline')
  Material.read(ByteData data, int offset): this._((
    wgsl.Vec4f.read(data, offset + 0),
    wgsl.F32.read(data, offset + 16),
    wgsl.F32.read(data, offset + 20),
    wgsl.Vec3h.read(data, offset + 24),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    wgsl.F32(_.$2).write(data, offset + 16);
    wgsl.F32(_.$3).write(data, offset + 20);
    _.$4.write(data, offset + 24);
  }
}

@wgsl.Struct('Particle')
extension type const Particle._((wgsl.Vec3f pos, wgsl.Vec3f vel, double age) _) {
  static const Particle zero = Particle._((
    .zero,
    .zero,
    0.0,
  ));

  wgsl.Vec3f get pos => _.$1;
  wgsl.Vec3f get vel => _.$2;
  double get age => _.$3;

  @pragma('vm:prefer-inline')
  Particle({wgsl.Vec3f pos = .zero, wgsl.Vec3f vel = .zero, double age = 0.0}): this._((
    pos,
    vel,
    age,
  ));

  @pragma('vm:prefer-inline')
  Particle.read(ByteData data, int offset): this._((
    wgsl.Vec3f.read(data, offset + 0),
    wgsl.Vec3f.read(data, offset + 16),
    wgsl.F32.read(data, offset + 28),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    _.$1.write(data, offset + 0);
    _.$2.write(data, offset + 16);
    wgsl.F32(_.$3).write(data, offset + 28);
  }
}

@wgsl.Struct('Counters')
extension type const Counters._((int aliveCount, int deadCount) _) {
  static const Counters zero = Counters._((
    0,
    0,
  ));

  int get aliveCount => _.$1;
  int get deadCount => _.$2;

  @pragma('vm:prefer-inline')
  Counters({int aliveCount = 0, int deadCount = 0}): this._((
    aliveCount,
    deadCount,
  ));

  @pragma('vm:prefer-inline')
  Counters.read(ByteData data, int offset): this._((
    wgsl.U32.read(data, offset + 0),
    wgsl.I32.read(data, offset + 4),
  ));

  @pragma('vm:prefer-inline')
  void write(ByteData data, int offset) {
    wgsl.U32(_.$1).write(data, offset + 0);
    wgsl.I32(_.$2).write(data, offset + 4);
  }
}

@wgsl.UniformBufferView('u_config')
extension type GlobalConfigBufferView(ByteData data) {
  static const int sizeInBytes = 80;

  GlobalConfigBufferView.create(): this(ByteData(sizeInBytes));

  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static wgpu.BufferDescriptor descriptor({
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(test.wgsl) globalconfig buffer',
    size: sizeInBytes,
    usage: usage ?? .of([.uniform, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(wgpu.Device device, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void write(GlobalConfig value) {
    value.write(data, 0);
  }

  GlobalConfig read() {
    return GlobalConfig.read(data, 0);
  }

  double get time {
    return wgsl.F32.read(data, 0);
  }

  set time(double value) {
    wgsl.F32(value).write(data, 0);
  }

  double get deltaTime {
    return wgsl.F32.read(data, 4);
  }

  set deltaTime(double value) {
    wgsl.F32(value).write(data, 4);
  }

  int get frameCount {
    return wgsl.U32.read(data, 8);
  }

  set frameCount(int value) {
    wgsl.U32(value).write(data, 8);
  }

  (wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u) get resolutions {
    return (
      wgsl.Vec4u.read(data, 16 + 0 * 16),
      wgsl.Vec4u.read(data, 16 + 1 * 16),
      wgsl.Vec4u.read(data, 16 + 2 * 16),
      wgsl.Vec4u.read(data, 16 + 3 * 16),
    );
  }

  set resolutions((wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u) value) {
    value.$1.write(data, 16 + 0 * 16);
    value.$2.write(data, 16 + 1 * 16);
    value.$3.write(data, 16 + 2 * 16);
    value.$4.write(data, 16 + 3 * 16);
  }


  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.UniformBuffer('u_config')
class GlobalConfigBuffer {
  GlobalConfigBuffer(wgpu.Device device, {String? label, wgpu.BufferUsage? usage}):
    buffer = GlobalConfigBufferView.createBuffer(device, label: label, usage: usage),
    _view = GlobalConfigBufferView(ByteData(GlobalConfigBufferView.sizeInBytes));

  final wgpu.Buffer buffer;
  final GlobalConfigBufferView _view;

  static const int sizeInBytes = GlobalConfigBufferView.sizeInBytes;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  double get time => _view.time;
  set time(double value) => _view.time = value;
  double get deltaTime => _view.deltaTime;
  set deltaTime(double value) => _view.deltaTime = value;
  int get frameCount => _view.frameCount;
  set frameCount(int value) => _view.frameCount = value;
  (wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u) get resolutions => _view.resolutions;
  set resolutions((wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u, wgsl.Vec4u) value) => _view.resolutions = value;
  void clear() => _view.clear();
}

@wgsl.UniformBufferView('u_transform')
extension type TransformDataBufferView(ByteData data) {
  static const int sizeInBytes = 176;

  TransformDataBufferView.create(): this(ByteData(sizeInBytes));

  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static wgpu.BufferDescriptor descriptor({
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(test.wgsl) transformdata buffer',
    size: sizeInBytes,
    usage: usage ?? .of([.uniform, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(wgpu.Device device, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void write(TransformData value) {
    value.write(data, 0);
  }

  TransformData read() {
    return TransformData.read(data, 0);
  }

  wgsl.Mat4x4f get model {
    return wgsl.Mat4x4f.read(data, 0);
  }

  set model(wgsl.Mat4x4f value) {
    value.write(data, 0);
  }

  wgsl.Mat4x4f get view {
    return wgsl.Mat4x4f.read(data, 64);
  }

  set view(wgsl.Mat4x4f value) {
    value.write(data, 64);
  }

  wgsl.Mat3x3f get normalMat {
    return wgsl.Mat3x3f.read(data, 128);
  }

  set normalMat(wgsl.Mat3x3f value) {
    value.write(data, 128);
  }


  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.UniformBuffer('u_transform')
class TransformDataBuffer {
  TransformDataBuffer(wgpu.Device device, {String? label, wgpu.BufferUsage? usage}):
    buffer = TransformDataBufferView.createBuffer(device, label: label, usage: usage),
    _view = TransformDataBufferView(ByteData(TransformDataBufferView.sizeInBytes));

  final wgpu.Buffer buffer;
  final TransformDataBufferView _view;

  static const int sizeInBytes = TransformDataBufferView.sizeInBytes;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  wgsl.Mat4x4f get model => _view.model;
  set model(wgsl.Mat4x4f value) => _view.model = value;
  wgsl.Mat4x4f get view => _view.view;
  set view(wgsl.Mat4x4f value) => _view.view = value;
  wgsl.Mat3x3f get normalMat => _view.normalMat;
  set normalMat(wgsl.Mat3x3f value) => _view.normalMat = value;
  void clear() => _view.clear();
}

@wgsl.StorageBufferView('b_materials')
extension type MaterialArrayBufferView(ByteData data) {
  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static const int stride = 32;
  int get length => data.lengthInBytes ~/ stride;

  MaterialArrayBufferView.create(int length): this(ByteData(length * stride));

  static wgpu.BufferDescriptor descriptor(
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(test.wgsl) bmaterials buffer',
    size: length * stride,
    usage: usage ?? .of([.storage, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(
    wgpu.Device device,
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(length, label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void operator []=(int index, Material value) {
    value.write(data, index * stride);
  }

  Material operator [](int index) {
    return Material.read(data, index * stride);
  }

  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.StorageBuffer('b_materials')
class MaterialArrayBuffer {
  MaterialArrayBuffer(wgpu.Device device, this.length, {String? label, wgpu.BufferUsage? usage}):
    buffer = MaterialArrayBufferView.createBuffer(device, length, label: label, usage: usage),
    _view = MaterialArrayBufferView(ByteData(length * MaterialArrayBufferView.stride));

  final int length;
  final wgpu.Buffer buffer;
  final MaterialArrayBufferView _view;

  static const int stride = MaterialArrayBufferView.stride;
  int get sizeInBytes => length * stride;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void operator []=(int index, Material value) => _view[index] = value;
  Material operator [](int index) => _view[index];
  void clear() => _view.clear();
}

@wgsl.StorageBufferView('b_particles')
extension type ParticleArrayBufferView(ByteData data) {
  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static const int stride = 32;
  int get length => data.lengthInBytes ~/ stride;

  ParticleArrayBufferView.create(int length): this(ByteData(length * stride));

  static wgpu.BufferDescriptor descriptor(
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(test.wgsl) bparticles buffer',
    size: length * stride,
    usage: usage ?? .of([.storage, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(
    wgpu.Device device,
    int length, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(length, label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void operator []=(int index, Particle value) {
    value.write(data, index * stride);
  }

  Particle operator [](int index) {
    return Particle.read(data, index * stride);
  }

  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.StorageBuffer('b_particles')
class ParticleArrayBuffer {
  ParticleArrayBuffer(wgpu.Device device, this.length, {String? label, wgpu.BufferUsage? usage}):
    buffer = ParticleArrayBufferView.createBuffer(device, length, label: label, usage: usage),
    _view = ParticleArrayBufferView(ByteData(length * ParticleArrayBufferView.stride));

  final int length;
  final wgpu.Buffer buffer;
  final ParticleArrayBufferView _view;

  static const int stride = ParticleArrayBufferView.stride;
  int get sizeInBytes => length * stride;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void operator []=(int index, Particle value) => _view[index] = value;
  Particle operator [](int index) => _view[index];
  void clear() => _view.clear();
}

@wgsl.StorageBufferView('b_counters')
extension type CountersBufferView(ByteData data) {
  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static const int sizeInBytes = 8;

  CountersBufferView.create(): this(ByteData(sizeInBytes));

  static wgpu.BufferDescriptor descriptor({
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(test.wgsl) bcounters buffer',
    size: sizeInBytes,
    usage: usage ?? .of([.storage, .copyDst]),
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(wgpu.Device device, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void write(Counters value) {
    value.write(data, 0);
  }

  Counters read() {
    return Counters.read(data, 0);
  }

  void clear() {
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes).fillRange(0, data.lengthInBytes, 0);
  }
}

@wgsl.StorageBuffer('b_counters')
class CountersBuffer {
  CountersBuffer(wgpu.Device device, {String? label, wgpu.BufferUsage? usage}):
    buffer = CountersBufferView.createBuffer(device, label: label, usage: usage),
    _view = CountersBufferView(ByteData(CountersBufferView.sizeInBytes));

  final wgpu.Buffer buffer;
  final CountersBufferView _view;

  static const int sizeInBytes = CountersBufferView.sizeInBytes;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void write(Counters value) => _view.write(value);
  Counters read() => _view.read();
  void clear() => _view.clear();
}

@wgsl.BindGroupLayoutDescriptor(0)
wgpu.BindGroupLayoutDescriptor get bindGroup0Layout => .new(
  label: '(test.wgsl) bind group 0 layout',
  entries: [
    .new(
      binding: 0,
      visibility: .compute,
      buffer: .new(
        type: .uniform,
        minBindingSize: 80,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 1,
      visibility: .none,
      texture: .new(
        sampleType: .float,
        multisampled: false,
        viewDimension: .cube,
      ),
    ),
    .new(
      binding: 2,
      visibility: .fragment,
      sampler: .new(type: .filtering),
    ),
    .new(
      binding: 3,
      visibility: .fragment,
      texture: .new(
        sampleType: .depth,
        multisampled: false,
        viewDimension: .twoD,
      ),
    ),
    .new(
      binding: 4,
      visibility: .fragment,
      sampler: .new(type: .comparison),
    ),
    .new(
      binding: 5,
      visibility: .none,
      texture: .new(
        sampleType: .float,
        multisampled: true,
        viewDimension: .twoD,
      ),
    ),
  ],
);

@wgsl.BindGroupLayout(0)
wgpu.BindGroupLayout createBindGroup0Layout(wgpu.Device device) => device.createBindGroupLayout(bindGroup0Layout);

@wgsl.BindGroup(0)
wgpu.BindGroup createBindGroup0Raw(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required wgpu.BufferView uConfig,
  required wgpu.TextureView tEnvMap,
  required wgpu.Sampler sLinear,
  required wgpu.TextureView tShadowMap,
  required wgpu.Sampler sShadowCmp,
  required wgpu.TextureView tMultisampled,
  String? label,
}) => device.createBindGroup(.new(
  label: label ?? '(test.wgsl) bind group 0',
  layout: layout,
  entries: [
    .new(
      binding: 0,
      buffer: uConfig.buffer,
      offset: uConfig.offset,
      size: uConfig.size,
    ),
    .new(
      binding: 1,
      textureView: tEnvMap,
    ),
    .new(
      binding: 2,
      sampler: sLinear,
    ),
    .new(
      binding: 3,
      textureView: tShadowMap,
    ),
    .new(
      binding: 4,
      sampler: sShadowCmp,
    ),
    .new(
      binding: 5,
      textureView: tMultisampled,
    ),
  ],
));

@wgsl.BindGroup(0)
wgpu.BindGroup createBindGroup0(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required GlobalConfigBuffer uConfig,
  required wgpu.TextureView tEnvMap,
  required wgpu.Sampler sLinear,
  required wgpu.TextureView tShadowMap,
  required wgpu.Sampler sShadowCmp,
  required wgpu.TextureView tMultisampled,
}) => createBindGroup0Raw(
  device,
  layout,
  uConfig: uConfig.bufferView,
  tEnvMap: tEnvMap,
  sLinear: sLinear,
  tShadowMap: tShadowMap,
  sShadowCmp: sShadowCmp,
  tMultisampled: tMultisampled,
);

@wgsl.BindGroupLayoutDescriptor(1)
wgpu.BindGroupLayoutDescriptor get bindGroup1Layout => .new(
  label: '(test.wgsl) bind group 1 layout',
  entries: [
    .new(
      binding: 0,
      visibility: .vertex,
      buffer: .new(
        type: .uniform,
        minBindingSize: 176,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 1,
      visibility: .none,
      buffer: .new(
        type: .readOnlyStorage,
        minBindingSize: 32,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 2,
      visibility: .fragment,
      texture: .new(
        sampleType: .float,
        multisampled: false,
        viewDimension: .twoD,
      ),
    ),
    .new(
      binding: 4,
      visibility: .none,
      texture: .new(
        sampleType: .uint,
        multisampled: false,
        viewDimension: .oneD,
      ),
    ),
  ],
);

@wgsl.BindGroupLayout(1)
wgpu.BindGroupLayout createBindGroup1Layout(wgpu.Device device) => device.createBindGroupLayout(bindGroup1Layout);

@wgsl.BindGroup(1)
wgpu.BindGroup createBindGroup1Raw(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required wgpu.BufferView uTransform,
  required wgpu.BufferView bMaterials,
  required wgpu.TextureView tAlbedo,
  required wgpu.TextureView tData1d,
  String? label,
}) => device.createBindGroup(.new(
  label: label ?? '(test.wgsl) bind group 1',
  layout: layout,
  entries: [
    .new(
      binding: 0,
      buffer: uTransform.buffer,
      offset: uTransform.offset,
      size: uTransform.size,
    ),
    .new(
      binding: 1,
      buffer: bMaterials.buffer,
      offset: bMaterials.offset,
      size: bMaterials.size,
    ),
    .new(
      binding: 2,
      textureView: tAlbedo,
    ),
    .new(
      binding: 4,
      textureView: tData1d,
    ),
  ],
));

@wgsl.BindGroup(1)
wgpu.BindGroup createBindGroup1(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required TransformDataBuffer uTransform,
  required MaterialArrayBuffer bMaterials,
  required wgpu.TextureView tAlbedo,
  required wgpu.TextureView tData1d,
}) => createBindGroup1Raw(
  device,
  layout,
  uTransform: uTransform.bufferView,
  bMaterials: bMaterials.bufferView,
  tAlbedo: tAlbedo,
  tData1d: tData1d,
);

@wgsl.BindGroupLayoutDescriptor(2)
wgpu.BindGroupLayoutDescriptor get bindGroup2Layout => .new(
  label: '(test.wgsl) bind group 2 layout',
  entries: [
    .new(
      binding: 0,
      visibility: .compute,
      buffer: .new(
        type: .storage,
        minBindingSize: 32,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 1,
      visibility: .compute,
      buffer: .new(
        type: .storage,
        minBindingSize: 8,
        hasDynamicOffset: false,
      ),
    ),
    .new(
      binding: 2,
      visibility: .none,
      storageTexture: .new(
        access: .writeOnly,
        format: .RGBA8Unorm,
        viewDimension: .threeD,
      ),
    ),
    .new(
      binding: 3,
      visibility: .compute,
      storageTexture: .new(
        access: .writeOnly,
        format: .RGBA16Float,
        viewDimension: .twoD,
      ),
    ),
  ],
);

@wgsl.BindGroupLayout(2)
wgpu.BindGroupLayout createBindGroup2Layout(wgpu.Device device) => device.createBindGroupLayout(bindGroup2Layout);

@wgsl.BindGroup(2)
wgpu.BindGroup createBindGroup2Raw(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required wgpu.BufferView bParticles,
  required wgpu.BufferView bCounters,
  required wgpu.TextureView tVoxelGrid,
  required wgpu.TextureView tOutputImage,
  String? label,
}) => device.createBindGroup(.new(
  label: label ?? '(test.wgsl) bind group 2',
  layout: layout,
  entries: [
    .new(
      binding: 0,
      buffer: bParticles.buffer,
      offset: bParticles.offset,
      size: bParticles.size,
    ),
    .new(
      binding: 1,
      buffer: bCounters.buffer,
      offset: bCounters.offset,
      size: bCounters.size,
    ),
    .new(
      binding: 2,
      textureView: tVoxelGrid,
    ),
    .new(
      binding: 3,
      textureView: tOutputImage,
    ),
  ],
));

@wgsl.BindGroup(2)
wgpu.BindGroup createBindGroup2(
  wgpu.Device device,
  wgpu.BindGroupLayout layout, {
  required ParticleArrayBuffer bParticles,
  required CountersBuffer bCounters,
  required wgpu.TextureView tVoxelGrid,
  required wgpu.TextureView tOutputImage,
}) => createBindGroup2Raw(
  device,
  layout,
  bParticles: bParticles.bufferView,
  bCounters: bCounters.bufferView,
  tVoxelGrid: tVoxelGrid,
  tOutputImage: tOutputImage,
);

@wgsl.PipelineLayout('test.wgsl')
wgpu.PipelineLayout createPipelineLayout(
 wgpu.Device device, {
  wgpu.BindGroupLayout? group0,
  wgpu.BindGroupLayout? group1,
  wgpu.BindGroupLayout? group2,
}) => device.createPipelineLayout(.new(
  label: '(test.wgsl) pipeline layout',
  bindGroupLayouts: [
    group0 ?? device.createBindGroupLayout(bindGroup0Layout),
    group1 ?? device.createBindGroupLayout(bindGroup1Layout),
    group2 ?? device.createBindGroupLayout(bindGroup2Layout),
  ],
));

@wgsl.VertexBufferLayout('vs_main')
wgpu.VertexBufferLayout createVsMainVertexBufferLayout({wgpu.VertexStepMode stepMode = .vertex}) => .new(
  arrayStride: 48,
  stepMode: stepMode,
  attributes: [
    .new(
      format: wgpu.VertexFormat.float32x3,
      offset: 0,
      shaderLocation: 0,
    ),
    .new(
      format: wgpu.VertexFormat.float32x2,
      offset: 12,
      shaderLocation: 1,
    ),
    .new(
      format: wgpu.VertexFormat.float32x3,
      offset: 20,
      shaderLocation: 2,
    ),
    .new(
      format: wgpu.VertexFormat.sint32x4,
      offset: 32,
      shaderLocation: 3,
    ),
  ],
);

@wgsl.VertexBufferView('vs_main')
extension type VsMainVertexView(ByteData data) {
  static const stride = 48;
  int get vertexCount => data.lengthInBytes ~/ stride;

  VsMainVertexView.create(int vertexCount): this(ByteData(vertexCount * stride));

  void writeToQueue(wgpu.Queue queue, wgpu.Buffer buffer, {int offset = 0}) {
    queue.writeBuffer(buffer, offset, data);
  }

  static wgpu.BufferDescriptor descriptor(
    int vertexCount, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => .new(
    label: label ?? '(test.wgsl) vs_main buffer',
    size: vertexCount * stride,
    usage: usage ?? .copyDst,
    mappedAtCreation: mappedAtCreation,
  );
  
  static wgpu.Buffer createBuffer(
    wgpu.Device device,
    int vertexCount, {
    String? label,
    wgpu.BufferUsage? usage,
    bool mappedAtCreation = false,
  }) => device.createBuffer(descriptor(vertexCount, label: label, usage: usage, mappedAtCreation: mappedAtCreation));

  void set(int index, {required wgsl.Vec3f position, required wgsl.Vec2f uv, required wgsl.Vec3f normal, required wgsl.Vec4i customData}) {
    position.write(data, index * stride + 0);
    uv.write(data, index * stride + 12);
    normal.write(data, index * stride + 20);
    customData.write(data, index * stride + 32);
  }
}

@wgsl.VertexBuffer('vs_main')
class VsMainVertexBuffer {
  VsMainVertexBuffer(wgpu.Device device, this.vertexCount, {String? label, wgpu.BufferUsage? usage}):
    buffer = VsMainVertexView.createBuffer(device, vertexCount, label: label, usage: usage),
    _view = VsMainVertexView(ByteData(vertexCount * VsMainVertexView.stride));

  final int vertexCount;
  final wgpu.Buffer buffer;
  final VsMainVertexView _view;

  static const int stride = VsMainVertexView.stride;
  int get sizeInBytes => vertexCount * stride;

  wgpu.BufferView get bufferView => .new(buffer);
  void writeToQueue(wgpu.Queue queue) => _view.writeToQueue(queue, buffer);

  void readBack(wgpu.Device device) {
    final staging = device.createBuffer(.new(size: sizeInBytes, usage: .of([.copyDst, .mapRead])));
  
    final encoder = device.createCommandEncoder();
    encoder.copyBufferToBuffer(buffer, 0, staging, 0, sizeInBytes);
    final commands = encoder.finish();
    device.queue.submit([commands]);
  
    staging.mapSync(offset: 0, size: sizeInBytes, mode: .read);
    final mapped = staging.getMappedRange(0, sizeInBytes, readOnly: true);
    _view.data.buffer.asUint8List(_view.data.offsetInBytes, _view.data.lengthInBytes).setAll(0, mapped);
    staging.unmap();
    staging.destroy();
  }

  void set(int index, {required wgsl.Vec3f position, required wgsl.Vec2f uv, required wgsl.Vec3f normal, required wgsl.Vec4i customData}) => _view.set(index, position: position, uv: uv, normal: normal, customData: customData);
}

@wgsl.ComputeState('cs_main')
wgpu.ComputeState createCsMainComputeState(
  wgpu.ShaderModule module, {
  Overrides? overrides,
}) => wgpu.ComputeState(
  module: module,
  entryPoint: 'cs_main',
  constants: overrides?.entries ?? const [],
);

@wgsl.VertexState('vs_main')
wgpu.VertexState createVsMainVertexState(
  wgpu.ShaderModule module, {
  Overrides? overrides,
  List<wgpu.VertexBufferLayout>? vertexBuffers,
}) => wgpu.VertexState(
  module: module,
  entryPoint: 'vs_main',
  constants: overrides?.entries ?? const [],
  buffers: vertexBuffers ?? [createVsMainVertexBufferLayout()],
);

@wgsl.FragmentState('fs_main')
wgpu.FragmentState createFsMainFragmentState(
  wgpu.ShaderModule module,
  List<wgpu.ColorTargetState> targets, {
  Overrides? overrides,
}) => wgpu.FragmentState(
  module: module,
  entryPoint: 'fs_main',
  constants: overrides?.entries ?? const [],
  targets: targets,
);

@wgsl.ComputePipeline('cs_main')
wgpu.ComputePipeline createCsMainPipeline(
  wgpu.Device device,
  wgpu.ShaderModule module,
  wgpu.PipelineLayout layout, {
  Overrides? overrides,
}) => device.createComputePipeline(.new(
  label: '(test.wgsl) cs_main compute pipeline',
  layout: layout,
  compute: createCsMainComputeState(module, overrides: overrides),
));

@wgsl.RenderPipeline('vs_main', 'fs_main')
wgpu.RenderPipeline createVsMainFsMainRenderPipeline(
  wgpu.Device device,
  wgpu.ShaderModule module,
  wgpu.PipelineLayout layout,
  List<wgpu.ColorTargetState> targets, {
  Overrides? overrides,
  wgpu.PrimitiveState primitive = const wgpu.PrimitiveState(),
  wgpu.MultisampleState multisample = const wgpu.MultisampleState(),
  wgpu.DepthStencilState? depthStencil,
  List<wgpu.VertexBufferLayout>? vertexBuffers,
}) => device.createRenderPipeline(.new(
  label: '(test.wgsl) vs_main-fs_main render pipeline',
  layout: layout,
  vertex: createVsMainVertexState(module, overrides: overrides, vertexBuffers: vertexBuffers),
  fragment: createFsMainFragmentState(module, targets, overrides: overrides),
  primitive: primitive,
  multisample: multisample,
  depthStencil: depthStencil,
));

@wgsl.ShaderSource('test.wgsl')
const String _shaderSource = r'''
// 1. EXTENSIONS
enable f16; // Forces your generator to handle half-precision types!

// 2. PIPELINE OVERRIDES (Constants)
@id(0) override workgroup_size_x: u32 = 64;
@id(1) override use_shadows: bool = true;
override global_bias: f32 = 0.0015;

// 3. STRUCTS WITH ALIGNMENT TRAPS
struct GlobalConfig {
    time: f32,
    delta_time: f32,
    frame_count: u32,
    // Trap 1: Arrays in uniforms MUST have 16-byte stride. vec4u satisfies this.
    resolutions: array<vec4u, 4>, 
}

struct TransformData {
    model: mat4x4f,
    view: mat4x4f,
    // Trap 2: mat3x3f takes 48 bytes (three 16-byte columns), NOT 36 bytes!
    normal_mat: mat3x3f, 
}

struct Material {
    albedo: vec4f,
    roughness: f32,
    metallic: f32,
    // Trap 3: Half-precision vectors in storage buffers
    emission: vec3<f16>, 
}

struct Particle {
    pos: vec3f, // 12 bytes, but aligns to 16!
    vel: vec3f,
    age: f32,
}

struct Counters {
    // Trap 4: Atomics
    alive_count: atomic<u32>,
    dead_count: atomic<i32>,
}

// ==========================================
// GROUP 0: GLOBAL FRAME DATA (Mixed Textures)
// ==========================================
@group(0) @binding(0) var<uniform> u_config: GlobalConfig;
@group(0) @binding(1) var t_env_map: texture_cube<f32>;
@group(0) @binding(2) var s_linear: sampler;
@group(0) @binding(3) var t_shadow_map: texture_depth_2d;
@group(0) @binding(4) var s_shadow_cmp: sampler_comparison; // Comparison sampler!
@group(0) @binding(5) var t_multisampled: texture_multisampled_2d<f32>;

// ==========================================
// GROUP 1: OBJECT DATA (Skipped bindings)
// ==========================================
@group(1) @binding(0) var<uniform> u_transform: TransformData;
@group(1) @binding(1) var<storage, read> b_materials: array<Material>;
@group(1) @binding(2) var t_albedo: texture_2d<f32>;
// Notice we skipped binding 3! Your groups map should handle sparse indices.
@group(1) @binding(4) var t_data_1d: texture_1d<u32>; // Uint texture!

// ==========================================
// GROUP 2: COMPUTE & STORAGE TEXTURES
// ==========================================
@group(2) @binding(0) var<storage, read_write> b_particles: array<Particle>;
@group(2) @binding(1) var<storage, read_write> b_counters: Counters;
// Trap 5: Storage textures with explicit formats
@group(2) @binding(2) var t_voxel_grid: texture_storage_3d<rgba8unorm, write>;
@group(2) @binding(3) var t_output_image: texture_storage_2d<rgba16float, write>;


// ==========================================
// ENTRY 1: VERTEX SHADER
// ==========================================
struct VertexInput {
    @location(0) position: vec3f,
    @location(1) uv: vec2f,
    @location(2) normal: vec3f,
    @location(3) custom_data: vec4i,
}

struct VertexOutput {
    @builtin(position) clip_pos: vec4f,
    @location(0) uv: vec2f,
    @location(1) world_normal: vec3f,
}

@vertex
fn vs_main(in: VertexInput) -> VertexOutput {
    var out: VertexOutput;
    out.clip_pos = u_transform.model * vec4f(in.position, 1.0);
    out.uv = in.uv;
    out.world_normal = u_transform.normal_mat * in.normal;
    return out;
}

// ==========================================
// ENTRY 2: FRAGMENT SHADER
// ==========================================
@fragment
fn fs_main(in: VertexOutput) -> @location(0) vec4f {
    let base_color = textureSample(t_albedo, s_linear, in.uv);
    let shadow = textureSampleCompare(t_shadow_map, s_shadow_cmp, in.uv, 0.5);
    
    if (use_shadows) {
        return base_color * shadow;
    }
    return base_color + global_bias;
}

// ==========================================
// ENTRY 3: COMPUTE SHADER
// ==========================================
@compute @workgroup_size(workgroup_size_x, 1, 1)
fn cs_main(@builtin(global_invocation_id) id: vec3u) {
    let index = id.x;
    
    // Read/Write storage array
    var p = b_particles[index];
    p.age += u_config.delta_time;
    b_particles[index] = p;

    // Atomic usage
    if (p.age > 10.0) {
        atomicAdd(&b_counters.dead_count, 1);
    } else {
        atomicAdd(&b_counters.alive_count, 1u);
    }

    // Write to storage texture
    let write_coord = vec2i(i32(id.x), i32(id.y));
    textureStore(t_output_image, write_coord, vec4f(1.0, 0.0, 0.0, 1.0));
}
''';

@wgsl.ShaderModule('test.wgsl')
wgpu.ShaderModule createShaderModule(wgpu.Device device) => device.createShaderModule(.new(
  label: '(test.wgsl) module',
  next: const wgpu.ShaderSourceWGSL(code: _shaderSource),
));