// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by stack_assets

import 'package:flutter/widgets.dart';
import 'package:vector_graphics/vector_graphics.dart';
import 'package:material_symbols_icons/material_symbols_icons.dart';

// ignore_for_file: non_constant_identifier_names, unused_import, unused_element, unused_element_parameter

import 'package:ui/ui.dart';

class Assets {
  const Assets();

  static const icons = iconsAssets;
  static const cursors = cursorsAssets;
}

const assets = (
  icons: Assets.icons,
  cursors: Assets.cursors,
);

class IconsAssets {
  const IconsAssets();

  static const wFill = AssetBytesLoader('assets/gen/icons/w-fill.vec', packageName: 'ui');
  static const hFill = AssetBytesLoader('assets/gen/icons/h-fill.vec', packageName: 'ui');
  static const layoutColumn = AssetBytesLoader('assets/gen/icons/layout-column.vec', packageName: 'ui');
  static const x = AssetBytesLoader('assets/gen/icons/x.vec', packageName: 'ui');
  static const y = AssetBytesLoader('assets/gen/icons/y.vec', packageName: 'ui');
  static const cursorFill = AssetBytesLoader('assets/gen/icons/cursor-fill.vec', packageName: 'ui');
  static const angle = AssetBytesLoader('assets/gen/icons/angle.vec', packageName: 'ui');
  static const layoutRow = AssetBytesLoader('assets/gen/icons/layout-row.vec', packageName: 'ui');
  static const h = AssetBytesLoader('assets/gen/icons/h.vec', packageName: 'ui');
  static const cursor = AssetBytesLoader('assets/gen/icons/cursor.vec', packageName: 'ui');
  static const w = AssetBytesLoader('assets/gen/icons/w.vec', packageName: 'ui');
  static const layoutStackFill = AssetBytesLoader('assets/gen/icons/layout-stack-fill.vec', packageName: 'ui');
  static const layoutRowFill = AssetBytesLoader('assets/gen/icons/layout-row-fill.vec', packageName: 'ui');
  static const layoutStack = AssetBytesLoader('assets/gen/icons/layout-stack.vec', packageName: 'ui');
  static const yFill = AssetBytesLoader('assets/gen/icons/y-fill.vec', packageName: 'ui');
  static const xFill = AssetBytesLoader('assets/gen/icons/x-fill.vec', packageName: 'ui');
  static const layoutColumnFill = AssetBytesLoader('assets/gen/icons/layout-column-fill.vec', packageName: 'ui');
  static const angleFill = AssetBytesLoader('assets/gen/icons/angle-fill.vec', packageName: 'ui');
}

const iconsAssets = (
  wFill: IconsAssets.wFill,
  hFill: IconsAssets.hFill,
  layoutColumn: IconsAssets.layoutColumn,
  x: IconsAssets.x,
  y: IconsAssets.y,
  cursorFill: IconsAssets.cursorFill,
  angle: IconsAssets.angle,
  layoutRow: IconsAssets.layoutRow,
  h: IconsAssets.h,
  cursor: IconsAssets.cursor,
  w: IconsAssets.w,
  layoutStackFill: IconsAssets.layoutStackFill,
  layoutRowFill: IconsAssets.layoutRowFill,
  layoutStack: IconsAssets.layoutStack,
  yFill: IconsAssets.yFill,
  xFill: IconsAssets.xFill,
  layoutColumnFill: IconsAssets.layoutColumnFill,
  angleFill: IconsAssets.angleFill,
);

class CursorsAssets {
  const CursorsAssets();

  static const rotate = AssetBytesLoader('assets/gen/cursors/rotate.vec', packageName: 'ui');
  static const toolTriangle = AssetBytesLoader('assets/gen/cursors/tool-triangle.vec', packageName: 'ui');
  static const toolCursor = AssetBytesLoader('assets/gen/cursors/tool-cursor.vec', packageName: 'ui');
  static const toolMove = AssetBytesLoader('assets/gen/cursors/tool-move.vec', packageName: 'ui');
  static const toolEllipse = AssetBytesLoader('assets/gen/cursors/tool-ellipse.vec', packageName: 'ui');
  static const toolRectangle = AssetBytesLoader('assets/gen/cursors/tool-rectangle.vec', packageName: 'ui');
  static const resize = AssetBytesLoader('assets/gen/cursors/resize.vec', packageName: 'ui');
  static const toolContainer = AssetBytesLoader('assets/gen/cursors/tool-container.vec', packageName: 'ui');
  static const toolMarquee = AssetBytesLoader('assets/gen/cursors/tool-marquee.vec', packageName: 'ui');
}

const cursorsAssets = (
  rotate: CursorsAssets.rotate,
  toolTriangle: CursorsAssets.toolTriangle,
  toolCursor: CursorsAssets.toolCursor,
  toolMove: CursorsAssets.toolMove,
  toolEllipse: CursorsAssets.toolEllipse,
  toolRectangle: CursorsAssets.toolRectangle,
  resize: CursorsAssets.resize,
  toolContainer: CursorsAssets.toolContainer,
  toolMarquee: CursorsAssets.toolMarquee,
);

enum _BaseIconMode {
  vg,
  iconData,
}

class _BaseIcon extends StatelessWidget {
  const _BaseIcon.vgSelector({
    super.key,
    required BytesLoader Function(BuildContext) loader,
    BytesLoader Function(BuildContext)? filledLoader,
    this.size,
    this.color,
    this.autocolor = true,
  }) : mode = .vg,
       icon = null,
       loader = null,
       filledLoader = null,
       loaderFn = loader,
       filledLoaderFn = filledLoader,
       isSelectorBased = true;

  const _BaseIcon.vgBasic({
    super.key,
    required this.loader,
    this.filledLoader,
    this.size,
    this.color,
    this.autocolor = true,
  }) : mode = .vg,
       icon = null,
       loaderFn = null,
       filledLoaderFn = null,
       isSelectorBased = false;

  const _BaseIcon.iconData({
    super.key,
    required IconData this.icon,
    this.size,
    this.color,
  }) : mode = .iconData,
       loader = null,
       loaderFn = null,
       filledLoader = null,
       filledLoaderFn = null,
       isSelectorBased = false,
       autocolor = true;

  final _BaseIconMode mode;
  final IconData? icon;
  final BytesLoader Function(BuildContext)? loaderFn;
  final BytesLoader Function(BuildContext)? filledLoaderFn;
  final BytesLoader? loader;
  final BytesLoader? filledLoader;
  final bool isSelectorBased;
  final double? size;
  final Color? color;
  final bool autocolor;

  Widget _buildVgIcon(BuildContext context) {
    final iconTheme = IconTheme.of(context);

    final color = this.color ?? iconTheme.color ?? Surface.maybeColorOf(context)?.foreground;
    final size = this.size ?? iconTheme.size ?? 24.0;
    final fill = iconTheme.fill ?? 0.0;

    Widget _buildIcon(BytesLoader loader, [double? opacity]) {
      return VectorGraphic(
        key: ValueKey((loader, opacity)),
        loader: loader,
        colorFilter: color != null && autocolor ? ColorFilter.mode(color, BlendMode.srcIn) : null,
        width: size,
        height: size,
        opacity: opacity != null ? AlwaysStoppedAnimation(opacity) : null,
      );
    }

    final loader = isSelectorBased ? loaderFn!(context) : this.loader!;
    final filledLoader = isSelectorBased ? filledLoaderFn?.call(context) : this.filledLoader;

    if (filledLoader != null) {
      return Stack(
        children: [
          _buildIcon(loader, 1.0 - fill),
          _buildIcon(filledLoader, fill),
        ],
      );
    } else {
      return _buildIcon(loader);
    }
  }

  Widget _buildIconDataIcon(BuildContext context) {
    return Icon(icon, size: size, color: color);
  }

  @override
  Widget build(BuildContext context) {
    return switch (mode) {
      .vg => _buildVgIcon(context),
      .iconData => _buildIconDataIcon(context),
    };
  }
}

class Icons extends _BaseIcon {
  const Icons.wFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.wFill, filledLoader: null, autocolor: true);
  const Icons.hFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.hFill, filledLoader: null, autocolor: true);
  const Icons.layoutColumn({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.layoutColumn, filledLoader: IconsAssets.layoutColumnFill, autocolor: true);
  const Icons.x({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.x, filledLoader: IconsAssets.xFill, autocolor: true);
  const Icons.y({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.y, filledLoader: IconsAssets.yFill, autocolor: true);
  const Icons.cursorFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.cursorFill, filledLoader: null, autocolor: true);
  const Icons.angle({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.angle, filledLoader: IconsAssets.angleFill, autocolor: true);
  const Icons.layoutRow({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.layoutRow, filledLoader: IconsAssets.layoutRowFill, autocolor: true);
  const Icons.h({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.h, filledLoader: IconsAssets.hFill, autocolor: true);
  const Icons.cursor({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.cursor, filledLoader: IconsAssets.cursorFill, autocolor: true);
  const Icons.w({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.w, filledLoader: IconsAssets.wFill, autocolor: true);
  const Icons.layoutStackFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.layoutStackFill, filledLoader: null, autocolor: true);
  const Icons.layoutRowFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.layoutRowFill, filledLoader: null, autocolor: true);
  const Icons.layoutStack({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.layoutStack, filledLoader: IconsAssets.layoutStackFill, autocolor: true);
  const Icons.yFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.yFill, filledLoader: null, autocolor: true);
  const Icons.xFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.xFill, filledLoader: null, autocolor: true);
  const Icons.layoutColumnFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.layoutColumnFill, filledLoader: null, autocolor: true);
  const Icons.angleFill({super.key, super.size, super.color}) : super.vgBasic(loader: IconsAssets.angleFill, filledLoader: null, autocolor: true);
  const Icons.square({super.key, super.size, super.color}): super.iconData(icon: Symbols.square_rounded);
  const Icons.circle({super.key, super.size, super.color}): super.iconData(icon: Symbols.circle_rounded);
  const Icons.container({super.key, super.size, super.color}): super.iconData(icon: Symbols.border_all_rounded);
  const Icons.chevronLeft({super.key, super.size, super.color}): super.iconData(icon: Symbols.chevron_left_rounded);
  const Icons.chevronRight({super.key, super.size, super.color}): super.iconData(icon: Symbols.chevron_right_rounded);
  const Icons.rotateCw({super.key, super.size, super.color}): super.iconData(icon: Symbols.rotate_90_degrees_cw_rounded);
  const Icons.rotateCcw({super.key, super.size, super.color}): super.iconData(icon: Symbols.rotate_90_degrees_ccw_rounded);
  const Icons.move({super.key, super.size, super.color}): super.iconData(icon: Symbols.drag_pan_rounded);
  const Icons.marquee({super.key, super.size, super.color}): super.iconData(icon: Symbols.select_rounded);
  const Icons.close({super.key, super.size, super.color}): super.iconData(icon: Symbols.close_rounded);
  const Icons.layoutSizeFixed({super.key, super.size, super.color}): super.iconData(icon: Symbols.lock_rounded);
  const Icons.layoutSizeNonFixed({super.key, super.size, super.color}): super.iconData(icon: Symbols.lock_open_rounded);
  const Icons.layoutSizeContain({super.key, super.size, super.color}): super.iconData(icon: Symbols.compress_rounded);
  const Icons.layoutSizeExpand({super.key, super.size, super.color}): super.iconData(icon: Symbols.expand_rounded);
}

class CursorsIcons extends _BaseIcon {
  const CursorsIcons.rotate({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.rotate, filledLoader: null, autocolor: false);
  const CursorsIcons.toolTriangle({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.toolTriangle, filledLoader: null, autocolor: false);
  const CursorsIcons.toolCursor({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.toolCursor, filledLoader: null, autocolor: false);
  const CursorsIcons.toolMove({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.toolMove, filledLoader: null, autocolor: false);
  const CursorsIcons.toolEllipse({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.toolEllipse, filledLoader: null, autocolor: false);
  const CursorsIcons.toolRectangle({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.toolRectangle, filledLoader: null, autocolor: false);
  const CursorsIcons.resize({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.resize, filledLoader: null, autocolor: false);
  const CursorsIcons.toolContainer({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.toolContainer, filledLoader: null, autocolor: false);
  const CursorsIcons.toolMarquee({super.key, super.size, super.color}) : super.vgBasic(loader: CursorsAssets.toolMarquee, filledLoader: null, autocolor: false);
}
