name: ui
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  geometry:
  state:
  mouse_cursor:

  expressions: ^0.2.5+3
  material_symbols_icons: ^4.2960.0
  vector_math: ^2.2.0
  vector_graphics: ^1.2.3
  web: ^1.1.1

dev_dependencies:
  stack_assets:

flutter:
  assets:
    - assets/gen/cursors/
    - assets/gen/icons/
    - assets/fonts/RobotoMono/

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic
