name: state
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  log:

  # Core
  async: ^2.13.1
  listen: ^1.0.1

  # State management
  provider: ^6.1.5+1
  flutter_hooks: ^0.21.3+1
  signals: ^7.1.0
  signals_hooks: ^7.1.0
  signals_flutter: ^7.1.0
