name: native
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  state:
  objective_c: ^9.5.0
  ffi: ^2.2.0
  web: ^1.1.1

dev_dependencies: 
  ffigen: ^21.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: NativePluginIos
        sharedDarwinSource: true
        ffiPlugin: true
      macos:
        pluginClass: NativePluginMacos
        sharedDarwinSource: true
        ffiPlugin: true