syntax = "proto3";

package motif;

import "packages/skia_common/skia_common.proto";

message AssetManifest {
  map<string, Asset> entries = 1;
}

message Asset {
  message Font {
    string            family  = 1;
    string            license = 2;
    repeated FontFace faces   = 3;
  }

  message Image {
    int32  width     = 1;
    int32  height    = 2;
    string mime_type = 3;
  }

  string hash = 1;
  int32  size = 2;

  oneof kind {
    Font  font  = 10;
    Image image = 11;
  }
}

message FontFace {
  message Thumbnail {
    skia.Path path   = 1;
    float     width  = 2;
    float     height = 3;
  }

  string             family    = 1;
  int32              index     = 2;
  int32              weight    = 3;
  int32              width     = 4;
  int32              slant     = 5;
  optional Thumbnail thumbnail = 6;
}

message AssetLicense {
  string hash       = 1;
  string descriptor = 2;
  string kind       = 3;
  string body       = 4;
}

message LicenseBundle {
  map<string, AssetLicense> licenses = 1;
}