name: skia
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  hooks: ^1.0.3
  code_assets: ^1.0.0
  native_toolchain_c: ^0.17.4
  ffi: ^2.2.0
  ffigen: ^20.1.1
  ffigen_js: 0.0.12-pre
