name: Deploy app to GitHub Pages

on:
  push:
    tags:
      - 'app-v*'
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - id: version
        run: |
          VERSION=${GITHUB_REF_NAME#app-}
          echo "name=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: .fvmrc

      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          workingDir: app
          baseHref: /motif/
          compileToWasm: true
          customArgs: --source-maps --no-strip-wasm --dart-define="SERVER_URL=https://motif.kz" --dart-define="ENV=external" --build-name=${{ steps.version.outputs.name }} --build-number=${{ github.run_number }}