name: Deploy app to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2
        with:
          channel: master
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          workingDir: app
          baseHref: /motif/
          compileToWasm: true
          customArgs: --dart-define="SYNC_URL=wss://motif.kz" --dart-define="SYNC_ENABLED=true"